### ISSUE TITLE
RabbitMQ Archiver has no timeout

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1014]
The RabbitMQ archiver plugin doesn't appear to time out if it can't write, causing the archiver to get backed up and stop archiving.

Need to check all other archivers for this, too.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Improved the archiver's ability to handle plugin failures.
Improved the RabbitMQ archiver's robustness.

**Comment by mfeit-internet2** [comment]
The core of this, RabbitMQ not having any kind of timeout mechanism, doesn't appear to have been fixed.

**Comment by mfeit-internet2** [comment]
**Release Notes (4.4.0):**

New-from-the-ground-up RabbitMQ archiver.

Added a `timeout` parameter to govern how long the RabbitMQ archiver will wait for RabbitMQ before giving up.

**Comment by tonin** [comment]
> Added proper dependencies for RabbitMQ archiver. #1014 

I guess this needs to be added to the Deb package too, right?

**Comment by tonin** [comment]
Backported the 2 new modules in https://github.com/perfsonar/pscheduler/commit/587662753b2b86b93013268c717d1af68460bda1
