### ISSUE TITLE
latencybg test plugin misses powstream parameter: session_count

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1028]
Hi guys,

Please check this explanation: https://software.internet2.edu/owamp/powstream.man.html
seek=powstream: "powstream  can  use  large session durations to minimize control communication during execution."

I am not able to identify the corresponding parameter in the documentation: http://docs.perfsonar.net/pscheduler_ref_tests_tools.html#latency-tests

**Comment by arlake228** [comment]
This was intentionally left out when we built the plug-in. The only time it was being used when people confused it with the count parameter and provides almost no benefit to our use case. IIRC the error handling was not great in the implementation either and things would fail and not recover until the next session. I don't think we have a problem with excess control communication by OWAMP so I don’t think there would be any reason to add this option.

**Comment by igarny** [comment]
Thanks Andy,
Please tell with what defaults runs powstream then. Is it the number of packets as per the packet count?
It is safe to close the ticket.

THANKS
