### ISSUE TITLE
Add support for repeating a test at specific times

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#104]
BWCTL supported the --schedule option which allows a comma separated list of times in the form of HH:MM where HH could also be \* meaning run every minute (e.g. *:00). We have someone asking for this to be included in the MeshConfig (it was never added) but its of little use without BWCTL. We could probably hack it in meshconfig to create a task that repeats every 24 hours with a start time of the requested time, but it would probably be cleaner to support directly in pscheduler.  Not needed for RC, but if its not too difficult we should try to add support by 1.0 so we are feature complete with BWCTL in this regard.

**Comment by mfeit-internet2** [comment]
There was discussion about having a cron-like way of specifying run times in pScheduler that I'd planned for 1.1.  Leave this at 1.0 and I'll see if I can squeeze it in.  If not, early next year.

**Comment by arlake228** [comment]
Ok sounds good. If we can't get it by final, I should be able to fairly easily modify MeshConfig to emulate the same effect by creating multiple tests with the requested times as the start times.

**Comment by rodsterD** [comment]
Hi!
I requested https://github.com/perfsonar/mesh-config/issues/27. Resolving this issue can work for me too though as long as it's possible to specify multiple times. At this stage our use case will be something like _run throughput tests at 18:00,21:00,00:00,3:00,6:00_ but not during the day. I don't specifically need the * functionality but I guess the more interoperable with BWCTL the better...
Thanks!

PS note that regular-testing supports this feature and it appears to be working (see my mail "[perfsonar-user] regulartesting.conf schedule time_slot") so I didn't think it difficult to add to the mesh config (but understand the complexity now that we're moving to pScheduler).

**Comment by rodsterD** [comment]
Sorry, ignore the PS - I realise now that pScheduler is replacing BWCTL as well as regular testing...

**Comment by mfeit-internet2** [comment]
Notes:

Crontab parser/calculator:  https://github.com/josiahcarlson/parse-crontab

Starting point for validating cron specs:  https://gist.github.com/andrew-templeton/ae4126a8efe219b796a3
