### ISSUE TITLE
Improvement for the pScheduler stats

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1047]
Hi Mark,

This inquiry is about the pScheduler statistics the service reports under /pscheduler/stats
The problem with the current stats is that it is a counter for a very long period... the retention period of pscheduler. Thus it is difficult for us to keep track of, measure and have alerts on thresholds, which is the reason behind the inquiry.
What we miss actually is the ability to request these stats for a custom period of time.
IMO there is no point in having stats updates with rate less than an hour.

So my call is for the stats reporting of pScheduler to be controlled by a parameter, which would allow for more fine grained reporting of the pScheduler stats.

**Comment by mfeit-internet2** [comment]
For 4.3, all of the run statistics (everything under `/stat/runs`) can now be queried with optional `start` and `end` parameters that will limit the time range based on the start time of the runs.  The default is the beginning or end of time.  The parameter values can be an ISO8601 timestamp (e.g., `2020-09-01T12:34:56-00:00`) or a relative ISO8601 duration (e.g., `-P1D` or "+PT4H`).
