### ISSUE TITLE
pscheduler troubleshoot checking local hostname

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#1051]
The new 4.3.0-alpha feature of `pscheduler troubleshoot` checking the local hostname is a bit confusing when running on a remote host.  Is it checking the remote host DNS resolution or the local one?

Example:
```
vagrant@d9-install-ps:~$ pscheduler troubleshoot 10.0.0.102
Performing basic troubleshooting of localhost and 10.0.0.102.

localhost:

  Making sure local hostname 'd9-install-ps' resolves... OK.
  Measuring MTU... 65536+
(...)

10.0.0.102:

  Making sure local hostname 'd9-install-ps' resolves... OK.
  Measuring MTU... 1500+
```

What is the test for local hostname checking on `10.0.0.102`?  Should it test for the 10.0.0.102 local hostname resolving and not the localhost of `d9-install-ps`?  If it's doing the same test twice (i.e. resolving local hostname on the actual localhost) then I think it should be skipped when testing `10.0.0.102` because this test was already done seconds before.

Or is it testing something else or is there something I didn't get right?

**Comment by mfeit-internet2** [comment]
I'm probably going to remove that check.  It's no longer necessary.

**Comment by mfeit-internet2** [comment]
Removed.
