### ISSUE TITLE
Clean up use of 'internal invoke'

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1062]
Invocation of internal commands is currently done by running `pscheduler internal invoke ...`, which results in three execs:

 * `/usr/bin/pscheduler`
 * `/usr/libexec/pscheduler/commands/internal`
 * Program that runs the internal

This could be done better with a single Python function that understands the directory structure.

### Python Library
- [x] Function to run internal program
- [x] Limit processor's `test` limit

### API Server
- [x] Archivers
- [x] Contexts
- [x] Runs
- [x] Tasks
- [x] Tests

### Daemons
- [x] Archiver
- [x] Runner

### Database
- [x] Archiver
- [x] Context
- [x] Run
- [x] Task
- [x] Test
- [x] Tool

**Comment by mfeit-internet2** [comment]
Downstream:  The RPM spec for `python-pscheduler` passes the path of the plugin classes directory (nominally `/usr/libexec/pscheduler/classes`) to `python-pscheduler/pscheduler/Makefile` so a path can be injected into one of the module's files.

Debian will need to do the equivalent.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Internal improvements that should make a marginal improvement in performance on busy or resource-constrained systems.

**Comment by tonin** [comment]
Has been released and can be closed.
