### ISSUE TITLE
Remove BWCTL support

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#107]
We do not want to support BWCTL indefinitely, so we should remove the pscheduler-tool-bwctl\* stuff after a transition period. This will require we also remove code from the throughput, trace and rtt tests that check for pscheduler on each end. Removing the tools and the blocks of code in participants should be all we need to do.

**Comment by mfeit-internet2** [comment]
Other things to remove:

 * python-pscheduler: `api_has_bwctl()`
 * pscheduler-server: `httpd_can_network_connect` addition in RPM spec

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Removed remaining support for backward compatibility with BWCTL.  Older systems with tools supporting BWCTL installed will receive upgrades that makes them inert.
