### ISSUE TITLE
problem with --server-cpu-affinity and --client-cpu-affinity options

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#1076]
I'm getting this error:

pscheduler task throughput --client-cpu-affinity=0 --dest ps-dev-gridftp1.es.net

Diagnostics from localhost:
  numactl -N 0 /usr/bin/iperf3 -p 5201 -c ps-dev-gridftp1.es.net -t 10 --json

Error from localhost:
  iperf3 returned an error: error - the server has terminated

Diagnostics from ps-dev-gridftp1.es.net:
  Unable to use NUMA for eth0.  Disabling it.
  /usr/bin/iperf3 -s -1 --json -p 5201

----------

I'm not sure what '  Unable to use NUMA for eth0.  Disabling it." means. ??
NUMA is for CPU, not network interfaces....

**Comment by mfeit-internet2** [comment]
```
Error from localhost:
iperf3 returned an error: error - the server has terminated
```

That's iperf3 croaking without saying why.  You'll have to take that one up with Bruce.

```
Diagnostics from ps-dev-gridftp1.es.net:
Unable to use NUMA for eth0. Disabling it.
```

Interfaces on NUMA systems are usually tied to a node.  In the absence of any specific instructions on where to bind, the plugin attempts to determine which one it is and will bind iperf3 to that node.  The diagnostic from the far end says that it was unable to do it on that system so it didn't do anything with numactl.

**Comment by mfeit-internet2** [comment]
@bltierney Close this if there's no issue.

**Comment by bltierney** [comment]
closing. Problem was elsewhere.
