### ISSUE TITLE
Daemon options files for systemd services are not loaded

### ISSUE THREAD

**Issue by jthiltges** [perfsonar/pscheduler#1099]
pScheduler daemons have options files such as `/etc/pscheduler/daemons/archiver.conf` to allow additional runtime flags to be set, such as `--debug`. But, the options files are apparently not loaded due to a few issues:

- The systemd configuration looks in `/etc/pscheduler/daemons/archiver/conf` instead of `archiver.conf`
- ExecStartPre attempts to write the options to a non-existent directory (`/run/pscheduler-server/pscheduler/archiver/options` rather than `/run/pscheduler-server/archiver/options`)

After fixing those minor issues in `service-template.raw` I ran into other issues:

- The options don't get into the `$OPTIONS` environment variable
- Trying to set `EnvironmentFile=/run/pscheduler-server/archiver/options` caused systemd to fail, since the environment file doesn't exist until it's created by `ExecStartPre`

The easiest way I found to set daemon options was to create an override. For example, `systemctl edit pscheduler-archiver.service` and the following:

```
[Service]
Environment=OPTIONS=--debug
```

**Comment by mfeit-internet2** [comment]
Good catch.  You're probably the first to use those files; nobody else has complained.  I'll have that adjusted in the next bugfix release.

BTW, debug can be enabled on-the-fly using the `pscheduler debug` command.
