### ISSUE TITLE
Make pscheduler-server RPM fail when postgresql-load does

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#110]
The calls to `postgresql-load` in the `pscheduler-server` RPM spec cause the scriptlet to stop on error, but for some internal, RPM-related reason, the whole operation continues.

Discussion:
- https://bugzilla.redhat.com/show_bug.cgi?id=569930
- http://rpm5.org/community/rpm-users/0834.html

Try to find a workaround for this.

**Comment by mfeit-internet2** [comment]
Consider doing a test load of the finished SQL into a temporary database during the build instead of depending on loads failing during installation.

**Comment by mfeit-internet2** [comment]
Arranged a syntax check during build to keep silly mistakes from getting into production.

Because this requires a running PostgreSQL server, the Makefile will not do the check unless `CHECK_SYNTAX` is defined.  The RPM spec does this; the Debian packagers can set this if/when they're ready to do this.  (Since Debian is effectively a port of the CentOS version, the developers should catch most things before they reach Debian.)

**Comment by vvidic** [comment]
Sound good to make this optional. We can than try to integrate this check in the test part of the package build or in the post-build package tests.

**Comment by vvidic** [comment]
On the Debian side the package install will fail if the database does not load properly so basic testing should reveal any problems here.

**Comment by mfeit-internet2** [comment]
Checking syntax during build seems to have prevented these kinds of problems.  Closing.
