### ISSUE TITLE
Let daemons exit if they fail

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1108]
On EL6, SysV init didn't do automatic restarts, so `safe_run()` was built to catch and log uncaught exceptions and restart cleanly.  Systemd will take care of this for us and will give administrators a more-standard way to check up on failures, so the use of `safe_run()` can be discontinued.  Restart provisions are already in the systemd service templates.

We're safe to do this on CentOS.

@tonin  Please verify that all supported Debian and Ubuntu distributions are using systemd.  If they are (or aren't), please comment and put this back in the In Progress queue.

**Comment by tonin** [comment]
Yes, all 3 distributions we currently support (D9, U16, U18) are using systemd.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

pScheduler services are now more-closely managed by systemd, and failures can be found by consulting `journalctl`.
