### ISSUE TITLE
Loopback mode for throughput testing

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1118]
RNP's use case involves having the transmitter and receiver on the same host with different IPs:

![Screen Shot 2021-02-03 at 11 27 59 AM](https://user-images.githubusercontent.com/14113568/106777331-e5749780-6612-11eb-81fb-6e61c8c7b779.png)

To make this happen:

- [x] Add a `loopback` switch to the test.
- [x] Use a single participant (the `source` node) if `loopback` is set.
- [x] In loopback mode, have the tool plugin run both ends.  For iperf3, there are already two  separate functions for this, so it's just threads.
- [x] Lead participant returns its result but no second.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added loopback (destination on same host) testing to throughput tests and selected tools.

**Comment by DanielNeto** [comment]
ToDo:
- [ ] Add `loopback` option to iperf2
- [ ] Add `loopback` option to nuttcp
- [ ] Add `loopback` option to ethr

**Comment by DanielNeto** [comment]
**Release Notes:**

Added support to loopback (destination on same host) throughput tests to iperf2, nuttcp and ethr tools.
