### ISSUE TITLE
file path issues... systemd params problem

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1129]
Hi Mark

Problem are the bad file path statements in the Systemd pscheduler-scheduler config:
version is: pscheduler-server.noarch                          4.4.0-0.a1.0.el

specifically this line:
[root@r72 ~]# grep "/run/pscheduler-server/pscheduler/scheduler/options" /usr/lib/systemd/system/pscheduler-scheduler.service
```
ExecStartPre=-/bin/sh -c "if [ -r /etc/pscheduler/daemons/scheduler/conf ]; then opts=$(sed -e 's/#.*$//' /etc/pscheduler/daemons/scheduler/conf); echo OPTIONS=$opts > /run/pscheduler-server/pscheduler/scheduler/options; chown pscheduler:pscheduler /run/pscheduler-server/scheduler/options; fi"
```
The folder for the options file doesn't exist:
[root@r72 ~]# ll /etc/pscheduler/daemons/
total 16
-rw-------. 1 pscheduler pscheduler 160 Nov 10 21:08 archiver.conf
-rw-------. 1 pscheduler pscheduler 158 Nov 10 21:08 runner.conf
-rw-------. 1 pscheduler pscheduler 208 Mar 15 14:54 **scheduler.conf**
-rw-------. 1 pscheduler pscheduler 158 Nov 10 21:08 ticker.conf

the file scheduler.conf is not referenced

on top there is a file which is referenced by systemd config (see above), but is not present, therefore leads to errors in service start.
```
Mar 15 15:31:24 r72 systemd: Starting pScheduler server - scheduler...
Mar 15 15:31:24 r72 sh: /bin/sh: /run/pscheduler-server/pscheduler/scheduler/options: No such file or directory
Mar 15 15:31:24 r72 sh: chown: cannot access вЂ/run/pscheduler-server/scheduler/optionsвЂ™: No such file or directory
```

**Comment by mfeit-internet2** [comment]
#1099 corrected that and the code wasn't merged into 4.4.0 until yesterday.
