### ISSUE TITLE
Survive inability to make a thread.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1131]
The daemons that use threads crash when they aren't able to create new threads.  This should be caught and dealt with so work being done by existing threads isn't interrupted.

**Comment by igarny** [comment]
Is this related to the file descriptors exhaustion problem?

**Comment by mfeit-internet2** [comment]
@igarny Similar class of problem but different.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Improved ability of services to continue working when unable to start new threads.
