### ISSUE TITLE
archiver and runner fail to start after upgrading to v4.3.4

### ISSUE THREAD

**Issue by pdelong42** [perfsonar/pscheduler#1138]
After updating from pscheduler-server-4.2.4-1.el7.noarch to pscheduler-server-4.3.4-1.el7.noarch, both archiver and runner processes are failing to start, and they do it repeatedly in a tight loop (thanks to systemd).

I've included what appears to be a relevant snippet of my /var/log/messages:

[var_log_messages.txt](https://github.com/perfsonar/pscheduler/files/6307309/var_log_messages.txt)

After disabling both services in systemd (and doing a daemon-reexec), I tried running both manually, with --verbose and --debug, without --daemon, and as the pscheduler user and group.  Unfortunately, it became less verbose with its error reporting.

I haven't come across anything in any other logs to get me any closer to a root-cause of the issue.  But point me in the direction of any other logs, and I'll upload them to this issue as soon as possible.

The rest of the perfSONAR stack has been updated to v4.3.4 as well, but nothing else appears to be broken so-far.

This is on centos-release-7-9.2009.1.el7.centos.x86_64

**Comment by pdelong42** [comment]
Much as I'd like to locally revert the changes introduced by commit 7912effc579c48eab68ebaa45e3465086322b16a (a.k.a, "Be smarter about archiver queries to maximize throughput.  #1126"), I think I'd be playing with fire.

For starters, I wouldn't even dream of modifying the stored proc - that ship has sailed.  And I can't simply drop the second parameter when calling archiving_next(), much as I might like to.  What should an empty list look like in this context?  I'd pass that in, but I don't know what PostgreSQL-style stored-procs expect that to look like (it definitely didn't like Python's idea of an empty list).

**Comment by mfeit-internet2** [comment]
What's happening looks like the fallout from a failed upgrade rather than a problem in the code.

There is a problem with the way RPM works that precludes a solid rollback when a package-provided scriptlet fails during an install or upgrade.  Issue #110 has links to discussion about why that is and why it's not going to change.  The short answer is that It's not something we can work around, and I've spent quite a bit of time thinking about clever ways to do it.  The best we've been able to is send those errors to syslog (see #1055), but that only helps if you know to look for it.

In the case of `pscheduler-server`, the package involved here, a failure to upgrade the database would leave the last version of the database in place but would still install code that depends on the current version.

To get your system working again, run `pscheduler internal db-update` as root.  If that fails, report any errors and we'll go from there.

I am, as I write this, doing some work on one system that archives a quarter-million measurements daily using the current code.  That system's user would have raised a red flag almost instantly if it stopped archiving measurements.

**Comment by pdelong42** [comment]
Wow, I think that did the trick.  Thanks!

I ran the db-update, as you directed, and it appeared to succeed without much fanfare.

Just in case it's too good to be true (because I'm always worried when I don't see much output - my issue, not yours), I'm still checking things thoroughly.  But the services in systemd immediately recovered, and all of my scheduled tests immediately fired back up again.  Also, the graphs are rendering data within the latest hour.  All good signs.

Here's the output, just for verification:
```
$ env LANG=C script -c 'sudo pscheduler internal db-update' $(date +%F_%T).log
Script started, file is 2021-04-14_10:47:12.log
[sudo] password for username:
Loading database:
    Administrative... Done.
    User pscheduler... Done.
Script done, file is 2021-04-14_10:47:12.log
```

I just have a handful of questions:

- How much of this could have been a function of the distance I was jumping between versions?  That is, was I trying to jump too many versions by going from v4.2.4 to v4.3.4?  Would I be less likely to run across this problem if I were to update more frequently, with smaller distance between version updates?
- Is this a common failure mode?  That is, would it be prudent for me to keep this fix in my back pocket, for future updates?  Or is it just a corner case?  Is this a fix I might have known to consider, If I were better-versed with the overall documentation and the interrelations between all of the moving bits?

I didn't have this issue on some of my other perfSONAR servers, which were narrower gaps between versions.  But those servers are also not configured with as many tests as the one that broke.  Then again, it could have nothing to do with either of those differences, and I'm just wildly speculating here.

**Comment by pdelong42** [comment]
Another possible cause: I updated the RPMs piecemeal (in related batches, that is - I'm not _completely_ insane), because I'm uneasy with doing them all in one fell swoop.  I updated ```postgresql-init``` close to the end, right before some of the more standalone utilities.

**Comment by mfeit-internet2** [comment]
> How much of this could have been a function of the distance I was jumping between versions?

The code that maintains the database takes care of doing all of the incremental changes between where it was and where it should be.  The net result should be no different than having upgraded to each release individually.

 > Is this a common failure mode?

I've seen failed database upgrades before, but not more than I could count on one hand and most were the result of some other problem.

 > I didn't have this issue on some of my other perfSONAR servers, which were narrower gaps between versions. But those servers are also not configured with as many tests as the one that broke.

Those should be unconnected.

 > Another possible cause: I updated the RPMs piecemeal (in related batches, that is - I'm not completely insane), because I'm uneasy with doing them all in one fell swoop. I updated postgresql-init close to the end, right before some of the more standalone utilities.

Please don't do that.  The dependencies between the packages are structured so the package managers will upgrade the right things in the right order.  There are thousands of systems in the field that auto-update without incident, and we can't support attempts to do it by hand.

If you have a need to updates that lag behind our release schedule, grab a snapshot of the repository containing the version you want to field, point your systems at that and update the snapshot when we release a version you want.

**Comment by pdelong42** [comment]
> Please don't do that.

Understood.  I'll stop doing that. :-)

> If you have a need to updates that lag behind our release schedule, grab a snapshot of the repository containing the version you want to field, point your systems at that and update the snapshot when we release a version you want.

We're presently working towards exactly that (it's just taking us some time to get there).

Thanks again for all your help and patience.
