### ISSUE TITLE
Single-ended, reverse nuttcp test is failing due to missing "-r" option on client host

### ISSUE THREAD

**Issue by guhl1956** [perfsonar/pscheduler#1148]
I realize this is one of those rare use cases but I have a situation where I need to run a single-ended nuttcp test and reverse the direction of the test flow.  It works fine when I run nuttcp standalone but when I tried it with pscheduler it fails because pscheduler doesn’t set the “-r” nuttcp receiver flag on the client host receiving the reverse test flow. In order to get nuttcp reverse test flows to work both the “-r” and “-F” CLI options are required.  FWIW, it works fine when transmitting tests.

----- pscheduler nuttcp with reverse test flow fails:
> pscheduler task --tool nuttcp throughput --dest xxx.xxx.xxx.xxx --single-ended  --single-ended-port=5000 --reverse
 
The nuttcp command that pscheduler generates (from pscheduler.log) leaves out the “-r” receiver option which causes the failure
/usr/bin/nuttcp -p 5101 -P 5000 -T 10 -F xxx.xxx.xxx.xxx
 
 
----- running the same pscheduler nuttcp command as above via the CLI but with the receiver flag  (-r) set is successful:
> /usr/bin/nuttcp -p 5101 -P 5000 -T 10 -r -F xxx.xxx.xxx.xxx
   51.3111 MB /  10.16 sec =   42.3535 Mbps 0 %TX 3 %RX 0 retrans 9.81 msRTT

**Comment by mfeit-internet2** [comment]
If this is done for all tests where `single-ended` and `reverse` are in effect, it will break another common use case, which is a reverse test from behind NAT where the connection has to be opened forward.

The addition of a `full-reverse` switch might solve this problem.  It would force as many connections as  possible to go in the destination-to-host direction.  (Obviously, the control connection would have to be forward in single-ended mode.

**Comment by guhl1956** [comment]
Hi Mark,

Is there anything that I need to do for this ?

-George

From: Mark Feit ***@***.***>
Reply-To: perfsonar/pscheduler ***@***.***>
Date: Wednesday, May 5, 2021 at 4:04 PM
To: perfsonar/pscheduler ***@***.***>
Cc: "George.D.Uhl" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [perfsonar/pscheduler] Single-ended, reverse nuttcp test is failing due to missing "-r" option on client host (#1148)


If this is done for all tests where single-ended and reverse are in effect, it will break another common use case, which is a reverse test from behind NAT where the connection has to be opened forward.

The addition of a full-reverse switch might solve this problem. It would force as many connections as possible to go in the destination-to-host direction. (Obviously, the control connection would have to be forward in single-ended mode.

**Comment by mfeit-internet2** [comment]
Just use the switch.

**Comment by guhl1956** [comment]
Unfortunately,



# pscheduler task --tool nuttcp throughput --dest xxx.xxx.xxx.xxx --single-ended --single-ended-port=5000 --full-reverse

localhost: no such option: --full-reverse

Is there a patch for nuttcp tool/throughput test to support this? I keep my software up to date with daily yum-crons.

From: Mark Feit ***@***.***>
Reply-To: perfsonar/pscheduler ***@***.***>
Date: Wednesday, May 12, 2021 at 2:20 PM
To: perfsonar/pscheduler ***@***.***>
Cc: "George.D.Uhl" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [perfsonar/pscheduler] Single-ended, reverse nuttcp test is failing due to missing "-r" option on client host (#1148)


Just use the switch.

**Comment by mfeit-internet2** [comment]
You might find it helpful to wait until the code that adds the switch has actually been released.

**Comment by guhl1956** [comment]
Ah, I thought maybe it had been released already.  I’ll keep an eye out for it.

Thanks for your help!
-George

From: Mark Feit ***@***.***>
Reply-To: perfsonar/pscheduler ***@***.***>
Date: Wednesday, May 12, 2021 at 2:31 PM
To: perfsonar/pscheduler ***@***.***>
Cc: "George.D.Uhl" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [perfsonar/pscheduler] Single-ended, reverse nuttcp test is failing due to missing "-r" option on client host (#1148)


You might find it helpful to wait until the code that adds the switch has actually been released.

**Comment by mfeit-internet2** [comment]
I neglected to add this comment:

A`--reverse-connections` switch has been added to the throughput test.   Only `nuttcp` will offer itself to run when it's present.


```
$ pscheduler task throughput --dest 10.0.2.15 --single-ended --single-ended-port=5000 --reverse --reverse-connections
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/9d5ca797-aa5f-4c0c-b166-7a27e4894d38
Running with tool 'nuttcp'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/9d5ca797-aa5f-4c0c-b166-7a27e4894d38/runs/e28f2fbb-f96e-4a02-8a6b-66bb466fe200
Starts 2021-05-12T17:52:46Z (~3 seconds)
Ends   2021-05-12T17:53:02Z (~15 seconds)
Waiting for result...

Summary
Interval       Throughput     Retransmits
0.0 - 10.0     45.26 Gbps     11

No further runs scheduled.
```

**Comment by mfeit-internet2** [comment]
@guhl1956 If you're running the 4.4 beta someplace, could you check to see that this works to your satisfaction?

**Comment by guhl1956** [comment]
Hi Mark,

I installed 4.4 beta on a server running 4.3 but the single-ended reverse nuttcp test is still failing.  I tried setting the –reverse and –reverse-connection options, each separately and then together but no dice.  The nuttcp CLI “-r” option is still missing.

HTH,
-George


# yum install perfSONAR-repo-staging

[snip]

Installed:

  perfSONAR-repo-staging.noarch 0:0.10-1



Complete!





# yum install perfsonar-testpoint

Loaded plugins: fastestmirror

Loading mirror speeds from cached hostfile

 * epel: dl.fedoraproject.org

 * perfSONAR: mirror.net.cen.ct.gov

perfSONAR-staging                                                                                | 2.5 kB  00:00:00

perfSONAR-staging/x86_64/primary_db                                                              | 555 kB  00:00:00

Resolving Dependencies

--> Running transaction check

---> Package perfsonar-testpoint.noarch 0:4.3.4-1.el7 will be updated

---> Package perfsonar-testpoint.noarch 0:4.4.0-0.1.b1.el7 will be an update

[snip]



# yum update

[snip]

(65/90): pscheduler-tool-nuttcp-4.4.0-0.10.b1.el7.noarch.rpm                                                                          |  17 kB  00:00:00

[snip]


# pscheduler task --tool nuttcp --debug throughput --dest xxx.xxx.xxx.xxx --single-ended  --single-ended-port=5000 --reverse

2021-06-17T12:31:34 Debug started

2021-06-17T12:31:34 Assistance is from localhost

2021-06-17T12:31:34 Forcing default slip of PT5M

2021-06-17T12:31:34 Converting to spec via https://localhost/pscheduler/tests/throughput/spec

Submitting task...

2021-06-17T12:31:34 Fetching participant list

2021-06-17T12:31:34 Spec is: {"dest": "xxx.xxx.xxx.xxx", "single-ended": true, "single-ended-port": 5000, "reverse": true, "schema": 2}

2021-06-17T12:31:34 Params are: {'spec': '{"dest": "xxx.xxx.xxx.xxx", "single-ended": true, "single-ended-port": 5000, "reverse": true, "schema": 2}'}

2021-06-17T12:31:34 Got participants: {'participants': [None], 'null-reason': 'No source specified'}

2021-06-17T12:31:34 Lead is None

2021-06-17T12:31:34 Null reason is No source specified

2021-06-17T12:31:34 Pinging https://localhost/pscheduler/

2021-06-17T12:31:34 localhost is up

2021-06-17T12:31:34 Posting task to https://localhost/pscheduler/tasks

2021-06-17T12:31:34 Data is {'schedule': {'slip': 'PT5M'}, 'test': {'spec': {'dest': xxx.xxx.xxx.xxx', 'single-ended': True, 'single-ended-port': 5000, 'reverse': True, 'schema': 2}, 'type': 'throughput'}, 'tools': ['nuttcp']}

Task URL:

https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc

2021-06-17T12:31:39 Posted https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc

2021-06-17T12:31:39 Submission diagnostics:

2021-06-17T12:31:39   Hints:

2021-06-17T12:31:39     requester: 127.0.0.1

2021-06-17T12:31:39     server: 127.0.0.1

2021-06-17T12:31:39   Identified as everybody, local-interfaces

2021-06-17T12:31:39   Classified as default, friendlies

2021-06-17T12:31:39   Application: Hosts we trust to do everything

2021-06-17T12:31:39     Group 1: Limit 'always' passed

2021-06-17T12:31:39     Group 1: Want all, 1/1 passed, 0/1 failed: PASS

2021-06-17T12:31:39     Application PASSES

2021-06-17T12:31:39   Application: Defaults applied to non-friendly hosts

2021-06-17T12:31:39     Group 1: Limit 'innocuous-tests' failed: Passed but inverted

2021-06-17T12:31:39     Group 1: Limit 'throughput-default-time' passed

2021-06-17T12:31:39     Group 1: Limit 'throughput-default-udp' failed: UDP testing not allowed

2021-06-17T12:31:39     Group 1: Limit 'idleex-default' failed: Test is not 'idleex'

2021-06-17T12:31:39     Group 1: Want any, 1/4 passed, 3/4 failed: PASS

2021-06-17T12:31:39     Application PASSES

2021-06-17T12:31:39   Proposal meets limits

2021-06-17T12:31:39   Priority set to default of 0

Running with tool 'nuttcp'

Fetching first run...

2021-06-17T12:31:39 Fetching https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc/runs/first

2021-06-17T12:31:41 Handing off: pscheduler watch --first --debug https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc

2021-06-17T12:31:41 Debug started

2021-06-17T12:31:41 Fetching https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc

2021-06-17T12:31:42 Fetching next run from https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc/runs/first



Next scheduled run:

https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc/runs/fc8adce2-c989-45d3-ae7f-5c98c1452b55

Starts 2021-06-17T12:31:44Z (~1 seconds)

Ends   2021-06-17T12:32:00Z (~15 seconds)

Waiting for result...



2021-06-17T12:32:00 Calling ['pscheduler', 'result', '--quiet', '--format', 'text/plain', '--debug', 'https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc/runs/fc8adce2-c989-45d3-ae7f-5c98c1452b55']

Run failed.



Error:

  nuttcp returned an error: nuttcp-t: v8.1.4: Error: accept() timeout







Diagnostics:

  numactl -N 0 /usr/bin/nuttcp -p 5101 -P 5000 -T 10 -F xxx.xxx.xxx.xxx



Limit system diagnostics for this run:

  Hints:

    requester: 127.0.0.1

    server: 127.0.0.1

  Identified as everybody, local-interfaces

  Classified as default, friendlies

  Application: Hosts we trust to do everything

    Group 1: Limit 'always' passed

    Group 1: Want all, 1/1 passed, 0/1 failed: PASS

    Application PASSES

  Application: Defaults applied to non-friendly hosts

    Group 1: Limit 'innocuous-tests' failed: Passed but inverted

    Group 1: Limit 'throughput-default-time' passed

    Group 1: Limit 'throughput-default-udp' failed: UDP testing not allowed

    Group 1: Limit 'idleex-default' failed: Test is not 'idleex'

    Group 1: Want any, 1/4 passed, 3/4 failed: PASS

    Application PASSES

  Proposal meets limits

  Priority set at 0:

    Initial priority  (Set to 0)



Error from localhost:

  nuttcp returned an error: nuttcp-t: v8.1.4: Error: accept() timeout







Diagnostics from localhost:

  numactl -N 0 /usr/bin/nuttcp -p 5101 -P 5000 -T 10 -F xxx.xxx.xxx.xxx

2021-06-17T12:32:01 Fetching next run from https://localhost/pscheduler/tasks/4e713919-0f63-4e95-9568-796e76c91edc/runs/next



No further runs scheduled.



From: Mark Feit ***@***.***>
Reply-To: perfsonar/pscheduler ***@***.***>
Date: Wednesday, June 16, 2021 at 4:40 PM
To: perfsonar/pscheduler ***@***.***>
Cc: "George.D.Uhl" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [perfsonar/pscheduler] Single-ended, reverse nuttcp test is failing due to missing "-r" option on client host (#1148)


@guhl1956<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fguhl1956&data=04%7C01%7Cgeorge.d.uhl%40nasa.gov%7C30dcc66996e74901c79208d93106eddb%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637594728568764621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Qu4YFHaa3NfZVvFgEmru6J6PtmJVxWrWGX%2BYPW9CGSw%3D&reserved=0> If you're running the 4.4 beta someplace, could you check to see that this works to your satisfaction?

**Comment by mfeit-internet2** [comment]
Thanks, George, I'll have a look at that and make sure I didn't goof something up.

**Comment by mfeit-internet2** [comment]
It looks like your last example...
```
# pscheduler task --tool nuttcp --debug throughput --dest xxx.xxx.xxx.xxx --single-ended  --single-ended-port=5000 --reverse
```
... only had `--reverse` and not `--reverse-connections`, which is what adds the extra switch.

I ran a bunch of permutations on a 4.4 beta system, and it appears to function as expected:

Baseline:
```
pscheduler task --tool nuttcp throughput --dest psdev2
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 psdev2
  /usr/bin/nuttcp -S -1 --nofork -p 5101 -P 5001
```

Two-Ended:
```
pscheduler task --tool nuttcp throughput --dest psdev2 --reverse
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -F psdev2
  /usr/bin/nuttcp -S -1 --nofork -p 5101 -P 5001

pscheduler task --tool nuttcp throughput --dest psdev2 --reverse-connections
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -r psdev2
  /usr/bin/nuttcp -S -1 --nofork -p 5101 -P 5001

pscheduler task --tool nuttcp throughput --dest psdev2 --reverse --reverse-connections
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -F -r psdev2
  /usr/bin/nuttcp -S -1 --nofork -p 5101 -P 5001
```

Single-Ended:
```
pscheduler task --tool nuttcp throughput --dest psdev2 --single-ended
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 psdev2

pscheduler task --tool nuttcp throughput --dest psdev2 --reverse --single-ended
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -F psdev2

pscheduler task --tool nuttcp throughput --dest psdev2 --reverse-connections --single-ended
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -r psdev2

pscheduler task --tool nuttcp throughput --dest psdev2 --reverse --reverse-connections --single-ended
  /usr/bin/nuttcp -p 5101 -P 5001 -T 10 -F -r psdev2
```

The [change that added the switch](https://github.com/perfsonar/pscheduler/blame/4.4.0/pscheduler-tool-nuttcp/nuttcp/run#L196) has been in place since I first did this in May.

**Comment by mfeit-internet2** [comment]
Assuming no news is good news.
