### ISSUE TITLE
Unit tests relying on DNS resolution

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#1156]
I'm currently seeing the `python-pscheduler` unit test about Team Cymru bogon service failing at the `dead:beef` IPv6 reverse DNS resolution.  I'm not sure if it should be corrected or completely removed.  We've seen other DNS resolution issues on build machines in the past.

```
FAIL: Limit Processor / Identifier IP Cymru Bogon / Identifier
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/build/python-pscheduler-4.4.0~3.b1~20210526030251/tests/limitprocessor_identifier_ipcymrubogon_test.py", line 75, in test_identifier
   True)
AssertionError: False != True
```

This one is also a common failure, but I'd blame the slowness of the DNS resolver:
```
FAIL: Bulk resolve test.
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/build/python-pscheduler-4.4.0~2.b1~20210524195508/tests/psdns_test.py", line 74, in test_bulk_resolve
   self.assertEqual(ret.get('198.6.1.1'), 'cache00.ns.uu.net')
AssertionError: None != 'cache00.ns.uu.net'
```

Alternatively, is there a possibility to change the DNS request timeout or retry policy during the unit tests?

**Comment by mfeit-internet2** [comment]
Tests requiring off-host DNS resolution have been disabled.
