### ISSUE TITLE
Iperf3 plugin throws exception with loopback

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1159]
When running in loopback mode, the `iperf3` plugin throws an exception:

```
$ pscheduler task throughput --loopback --dest 127.0.0.1
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/42e6449f-69b4-4cd3-a67d-05d59fc6244d
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/42e6449f-69b4-4cd3-a67d-05d59fc6244d/runs/f39745e2-597a-47db-b7b8-5f0f0789d5b2
Starts 2021-05-28T14:45:46Z (~2 seconds)
Ends   2021-05-28T14:46:05Z (~18 seconds)
Waiting for result...

Run failed.

Diagnostics:


Limit system diagnostics for this run:
  No limits were applied

No further runs scheduled.
```

From the log:
```
May 28 14:46:56 psdev1 journal: runner INFO     13: Running https://127.0.0.1/pscheduler/tasks/1bffef10-df01-4e86-a2b3-8589bb585979/runs/9dac6449-b705-4372-b7b6-08d45c11a823
May 28 14:46:56 psdev1 journal: runner INFO     13: With iperf3: throughput --source 127.0.0.1 --dest 127.0.0.1 --loopback
May 28 14:46:56 psdev1 journal: tool-iperf3/run ERROR    Exception list index out of range
May 28 14:46:56 psdev1 journal: runner INFO     13: Run succeeded.

```

From the API:
```
curl -sk https://127.0.0.1/pscheduler/tasks/1bffef10-df01-4e86-a2b3-8589bb585979/runs/9dac6449-b705-4372-b7b6-08d45c11a823 | jq .errors
"Exception in thread Thread-1:\nTraceback (most recent call last):\n"
```

A few things need to be done:

- [x] Determine what's causing `Thread-1` to throw the exception.
- [x] Adjust the code that creates the thread to run the target method in an exception-safe way.  ([Example](https://github.com/perfsonar/pscheduler/blob/a6e9cedaa99a883a44c83ae41fd9e2c294f5398d/pscheduler-server/pscheduler-server/daemons/archiver.raw#L549))
- [x] Adjust the final catch at the bottom of the program to call `log.exception()`, which will properly format and log the exception.  The result should probably get that properly-formatted error in it as well.

**Comment by DanielNeto** [comment]
The code that creates the thread was already in a try/exception block, however the exception was not being properly logged. I changed it to use the log module.
