### ISSUE TITLE
pscheduler status API does not reflect service status

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1160]
>>yum list pscheduler-server
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: de.mirrors.clouvider.net
 * epel: ftp.fau.de
 * extras: ftp.plusline.net
 * updates: ftp.plusline.net
Installed Packages
pscheduler-server.noarch                                         4.4.0-0.4.b1.el7                                          @perfSONAR-nightly-minor

>> curl -k https://localhost/pscheduler/
"This is the pScheduler API server on localhost (r72.rrze)."

>> pscheduler validate-limits
Invalid JSON: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by igarny** [comment]
\>> sudo systemctl stop pscheduler-scheduler

\>> curl -k https://localhost/pscheduler/
"This is the pScheduler API server on localhost (r72.rrze)."


\>> ps ax | grep pscheduler

 4252 ?        Ssl    0:27 python3 /usr/libexec/pscheduler/daemons/ticker --daemon --pid-file /run/pscheduler-server/ticker/pid --dsn @/etc/pscheduler/database/database-dsn
 4307 ?        Ssl    1:13 python3 /usr/libexec/pscheduler/daemons/runner --daemon --pid-file /run/pscheduler-server/runner/pid --dsn @/etc/pscheduler/database/database-dsn
 4336 ?        Ss     0:38 python3 /usr/libexec/pscheduler/daemons/archiver --daemon --pid-file /run/pscheduler-server/archiver/pid --dsn @/etc/pscheduler/database/database-dsn
 4338 ?        Ss     0:36 postgres: pscheduler pscheduler [local] idle
 4339 ?        Ssl    5:42 postgres: pscheduler pscheduler [local] idle
 4532 ?        Ss     6:02 postgres: pscheduler pscheduler [local] idle
 4562 ?        Ss     2:22 postgres: pscheduler pscheduler [local] idle
 4565 ?        Ss     0:00 postgres: pscheduler pscheduler [local] idle
 9601 ?        Ss     0:13 postgres: pscheduler pscheduler [local] idle
18337 ?        Ss     0:07 postgres: pscheduler pscheduler [local] idle
19142 ?        R      0:00 python3 /usr/libexec/pscheduler/classes/test/latencybg/spec-is-valid
19145 pts/0    R+     0:00 grep --color=auto pscheduler
23724 ?        Sl     2:52 pscheduler-api  -DFOREGROUND
23725 ?        Sl     2:53 pscheduler-api  -DFOREGROUND
23726 ?        Sl     2:51 pscheduler-api  -DFOREGROUND
23727 ?        Sl     2:48 pscheduler-api  -DFOREGROUND
23728 ?        Sl     2:49 pscheduler-api  -DFOREGROUND
23729 ?        Sl     2:47 pscheduler-api  -DFOREGROUND
23730 ?        Sl     2:48 pscheduler-api  -DFOREGROUND
23731 ?        Sl     2:52 pscheduler-api  -DFOREGROUND
23732 ?        Sl     2:48 pscheduler-api  -DFOREGROUND
23733 ?        Sl     2:53 pscheduler-api  -DFOREGROUND
29065 ?        Ss    13:51 psconfig_pscheduler_agent

\>> curl -k https://localhost/pscheduler/
"This is the pScheduler API server on localhost (r72.rrze)."

**Comment by mfeit-internet2** [comment]
Failure to load the limit configuration doesn't cause the daemons to fail because none of them use it.

The only part of the system that uses the limit processor is the API.  If there's an invalid limit configuration in place, endpoints that require it will return HTTP status `422` (unable to complete request).

I did add a section to the output of the `status` endpoint that shows the state of the limit processor.  There's new code in the troubleshooter that checks the state of it on servers that support it.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added limit processor status to the API and troubleshooter.
