### ISSUE TITLE
Write a HTTP PUT/POST Archiver

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#117]
Title says it all.

This would be useful as a standard archiver so people running tasks on remote servers that don't have specialized archivers can have the results posted somewhere that can process them.

**Comment by mfeit-internet2** [comment]
Ed did this and the first cut is in the repository.  It just needs to have support for `retry-policy` added.

**Comment by epcjr** [comment]
I added retry-policy with commit 8371935.
