### ISSUE TITLE
Nuttcp Process took too long to run

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1171]
Hi Mark,

As promised here is the log from my machine.
Thank you for your attention

Jun 27 09:11:47 r72 journal: runner INFO     100180: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/5096297c-a69d-4413-8e86-830abd76d29a/runs/c41299e6-fd86-4c35-b26e-71a15db794f2
Jun 27 09:11:47 r72 journal: runner INFO     100180: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/5096297c-a69d-4413-8e86-830abd76d29a/runs/c41299e6-fd86-4c35-b26e-71a15db794f2
Jun 27 09:11:47 r72 journal: runner INFO     100180: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/5096297c-a69d-4413-8e86-830abd76d29a/runs/c41299e6-fd86-4c35-b26e-71a15db794f2
Jun 27 09:11:47 r72 journal: runner INFO     100180: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest ps-bionic.qalab.geant.net --duration PT20S --ip-version 4
Jun 27 09:11:47 r72 journal: runner INFO     100180: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest ps-bionic.qalab.geant.net --duration PT20S --ip-version 4
Jun 27 09:11:47 r72 journal: runner INFO     100180: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest ps-bionic.qalab.geant.net --duration PT20S --ip-version 4
Jun 27 09:12:17 r72 journal: runner INFO     100180: Run failed 2: Process took too long to run.
Jun 27 09:12:17 r72 journal: runner INFO     100180: Run failed 2: Process took too long to run.
Jun 27 09:12:17 r72 journal: runner INFO     100180: Run failed 2: Process took too long to run.
Jun 29 07:47:32 r72 journal: runner INFO     112619: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/8877eb3c-b58d-40d9-95a9-e7dc0f87f5c1/runs/9538d3e0-7669-4eaa-b401-520e04f8ac5b
Jun 29 07:47:32 r72 journal: runner INFO     112619: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/8877eb3c-b58d-40d9-95a9-e7dc0f87f5c1/runs/9538d3e0-7669-4eaa-b401-520e04f8ac5b
Jun 29 07:47:32 r72 journal: runner INFO     112619: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/8877eb3c-b58d-40d9-95a9-e7dc0f87f5c1/runs/9538d3e0-7669-4eaa-b401-520e04f8ac5b
Jun 29 07:47:32 r72 journal: runner INFO     112619: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest adhoc.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 07:47:32 r72 journal: runner INFO     112619: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest adhoc.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 07:47:32 r72 journal: runner INFO     112619: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest adhoc.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 07:48:02 r72 journal: runner INFO     112619: Run failed 2: Process took too long to run.
Jun 29 07:48:02 r72 journal: runner INFO     112619: Run failed 2: Process took too long to run.
Jun 29 07:48:02 r72 journal: runner INFO     112619: Run failed 2: Process took too long to run.
Jun 29 21:17:22 r72 journal: runner INFO     116641: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/41fd2b6c-a705-4662-b1e4-a38bc398a5b4/runs/7ca55118-a7c2-4982-9dd4-046aec0d5d22
Jun 29 21:17:22 r72 journal: runner INFO     116641: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/41fd2b6c-a705-4662-b1e4-a38bc398a5b4/runs/7ca55118-a7c2-4982-9dd4-046aec0d5d22
Jun 29 21:17:22 r72 journal: runner INFO     116641: Running https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/41fd2b6c-a705-4662-b1e4-a38bc398a5b4/runs/7ca55118-a7c2-4982-9dd4-046aec0d5d22
Jun 29 21:17:22 r72 journal: runner INFO     116641: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest tb-el7-prod.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 21:17:22 r72 journal: runner INFO     116641: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest tb-el7-prod.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 21:17:22 r72 journal: runner INFO     116641: With nuttcp: throughput --source t2-psdev.rrze.uni-erlangen.de --dest tb-el7-prod.ps.dev.internet2.edu --duration PT20S --ip-version 4
Jun 29 21:17:52 r72 journal: runner INFO     116641: Run failed 2: Process took too long to run.
Jun 29 21:17:52 r72 journal: runner INFO     116641: Run failed 2: Process took too long to run.
Jun 29 21:17:52 r72 journal: runner INFO     116641: Run failed 2: Process took too long to run.

**Comment by mfeit-internet2** [comment]
Is this still an issue?

**Comment by mfeit-internet2** [comment]
Assuming not.  Closing.
