### ISSUE TITLE
Remote troubleshoot from an IPv4 only host to an IPv6 enabled fail

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#1175]
Running `pscheduler troubleshoot ip6.enabled.host.net` from a IPv4 only host result in a failed simple stream test.

```
geantadmin@perfsonar:(~$ pscheduler troubleshoot perfsonar.eenet.ee
Performing basic troubleshooting of localhost and perfsonar.eenet.ee.

localhost:

  Measuring MTU... 65535 (Local)
  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.
  Exercising API... Archivers... Clock... Contexts... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services... Ticker... Scheduler... Runner... Archiver... OK.
  Checking limits... OK.
  Idle test.... 7 seconds.... Checking archiving... OK.

perfsonar.eenet.ee:

  Measuring MTU... 1500+
  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.
  Exercising API... Archivers... Clock... Contexts... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services... Ticker... Scheduler... Runner... Archiver... OK.
  Checking limits... OK.
  Idle test.... 6 seconds.... Checking archiving... OK.

localhost and perfsonar.eenet.ee:

  Checking IP addresses... IPv6
  Measuring MTU... 1500+
  Checking timekeeping... OK.
  Simple stream test... Failed.

Unable to post task: Error getting tools from 2001:bb8:0:132::8e: Failed to connect to 2001:bb8:0:132::8e: Network is unreachable

geantadmin@perfsonar:(~$ ifconfig -a | grep inet6
        inet6 fe80::e2d5:5eff:fe95:312  prefixlen 64  scopeid 0x20<link>
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
geantadmin@perfsonar:)~$ route -6n | grep "::/0"
::/0                           ::                         !n   -1  1 77330737 lo
::/0                           ::                         !n   -1  1 77330737 lo
geantadmin@perfsonar:)~$ hostname -f
perfsonar.cynet.ac.cy

```

**Comment by mfeit-internet2** [comment]
This is a side effect of perfsonar.eenet.ee having both A and AAAA records in DNS.

Andy wrote a function `called ip_normalize_version()` that lives in practically everything.  Given a pair of host names and an optional preference for v4 or v6, will pick out a pair of addresses with the same protocol.  If no preference is given, it's wired to select IPv6 first, which is what happens here.  There's no way for it to know ahead of time that IPv6 will be unroutable and I'm not sure there's much that can be done about it.

```
$ pscheduler troubleshoot --ip-version 4 --skip-single perfsonar.eenet.ee
Performing basic troubleshooting of localhost and perfsonar.eenet.ee.

localhost:

  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.

perfsonar.eenet.ee:

  Looking for pScheduler... OK.
  Fetching API level... 5
  Checking clock... OK.

localhost and perfsonar.eenet.ee:

  Checking IP addresses... IPv4
  Measuring MTU... 1500+
  Checking timekeeping... OK.
  Simple stream test.... 11 seconds.... OK.

pScheduler on both hosts appears to be functioning normally.

```

The practice I've seen recommended for dual-stack environments is to differentiate IPv4 and IPv6 hosts by name (e.g., `foo` and `foo6`) or have the server vary the answers so IPv4 clients can see `A` records and IPv6 clients see `AAAA` records.

**Comment by tonin** [comment]
I'd agree with that if the node from which the troubleshoot command is launched is IPv6 misconfigured or there is indeed a routing issue, but not if IPv6 is just not configured (but not disabled though) and so the node has a link-local address (which is the default network setup with CentOS, Debian or Ubuntu).  I think pscheduler should have a behaviour similar to that of `curl` that uses IPv6 by default but don't use it when the IPv6 addresses configured on the machine have a local scope.

Example from an IPv4 only host:
```
geantadmin^2@lola01:)~$ ifconfig -a | grep inet
        inet 193.206.127.163  netmask 255.255.255.240  broadcast 193.206.127.175
        inet6 fe80::e2d5:5eff:fe95:347  prefixlen 64  scopeid 0x20<link>
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
geantadmin^2@lola01:(~$ route -6n | grep "::/0"
::/0                           ::                         !n   -1  1 148553 lo
::/0                           ::                         !n   -1  1 148553 lo
geantadmin^2@lola01:)~$ curl -#kI https://perfsonar.eenet.ee/toolkit/ | head -1

HTTP/1.1 200 OK
geantadmin^2@lola01:)~$ curl -#kI4 https://perfsonar.eenet.ee/toolkit/ | head -1

HTTP/1.1 200 OK
geantadmin^2@lola01:)~$ curl -#kI6 https://perfsonar.eenet.ee/toolkit/ | head -1

curl: (7) Failed to connect to 2001:bb8:0:132::8e: Network is unreachable
```

Example from a dual stack host:
```
geantadmin^2@ps02:(~$ ifconfig -a | grep inet
        inet 193.170.114.250  netmask 255.255.255.248  broadcast 193.170.114.255
        inet6 2001:628:200b::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::e2d5:5eff:fe95:318  prefixlen 64  scopeid 0x20<link>
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
geantadmin^2@ps02:)~$ route -6n | grep "::/0"
::/0                           2001:628:200b::1           UG   1   4 1214290690 enp3s0
::/0                           ::                         !n   -1  1 1214560795 lo
::/0                           ::                         !n   -1  1 1214560795 lo
geantadmin^2@ps02:)~$ curl -#kI https://perfsonar.eenet.ee/toolkit/ | head -1

HTTP/1.1 200 OK
geantadmin^2@ps02:)~$ curl -#kI4 https://perfsonar.eenet.ee/toolkit/ | head -1

HTTP/1.1 200 OK
geantadmin^2@ps02:)~$ curl -#kI6 https://perfsonar.eenet.ee/toolkit/ | head -1

HTTP/1.1 200 OK
```

And, to confirm that `curl` is still defaulting to IPv6, the corresponding `httpd` log on `perfsonar.eenet.ee` for the 6 attempted HTTP requests is:
```
193.206.127.163 - - [09/Aug/2021:12:49:06 +0300] "HEAD /toolkit/ HTTP/1.1" 200 -
193.206.127.163 - - [09/Aug/2021:12:49:13 +0300] "HEAD /toolkit/ HTTP/1.1" 200 -
2001:628:200b::2 - - [09/Aug/2021:12:53:04 +0300] "HEAD /toolkit/ HTTP/1.1" 200 -
193.170.114.250 - - [09/Aug/2021:12:53:11 +0300] "HEAD /toolkit/ HTTP/1.1" 200 -
2001:628:200b::2 - - [09/Aug/2021:12:53:19 +0300] "HEAD /toolkit/ HTTP/1.1" 200 -
```

`curl` doesn't need to be given the `-4` flag on the IPv4 only host, even if the remote host has both an A and an AAAA record.  That's what I understand is the wanted behaviour as described in [RFC-6724](https://datatracker.ietf.org/doc/html/rfc6724).  This doesn't need to check if there is indeed IPv6 connectivity, but only to check the scope of the IPv6 source address.  Probably `ip_normalize_version()` can be amended to take care of that?

**Comment by mfeit-internet2** [comment]
This proved interesting:

The existing code does the equivalent of `pscheduler task simplestream --dest NORMALIZED-DEST-IP`.  This comes up with perfsonar.eenet.ee's IPv6 address because the normalizer can resolve `localhost` into IPv6 and prefers IPv6.  (Many Linux distributions have both IPv4 and IPv6 addresses assigned in `/etc/hosts` whether or not there's an IPv6 interface that can take traffic off-host.)  This causes the normalizer to say IPv6 is okay when it isn't and the task given to pScheduler has the IPv6 address in it.

The right thing to do is what all of the other things the troubleshooter do: use the provided parameters when talking to other hosts or giving them things to do, e.g., `pscheduler task simplestream --source-node PROVIDED-SOURCE --dest PROVIDED-DEST`.  That throws all of the work over to the host actually doing the test and it will fail if there's an actual connectivity problem.  I've tested that out with a bunch of scenarios and it works as expected.

I may remove or modify the `Checking IP addresses` section of the test because what comes out of it could be misleading.
