### ISSUE TITLE
Runner waits for children but does not send signal to them on shutdown

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#125]
The best way to recreate this is to create a long-running powstream test. Once it's started, send a SIGTERM to the runner process (this used to be all that the init script did until I implemented a workaround that sends a SIGKILL after a few seconds):
`kill $(cat /var/run/pscheduler-runner.pid)`

Notice that the runner, run and powstream commands are all still running. Also notice the pid file is unlocked so new runners can start. This can lead to an explosion in processes if you have lots of long-running tests. Doing a few straces, the runner is blocking on some mysterious futex. It looks like maybe something is hijacking the atexit in the runner, because as far as I can tell, run_program should be set-up to send all the signals needed. 

I have worked-around this for now by adding the SIGKILL to the inits and some extra checks to powstream, but we should eventually figure out what is going on and get this right.

**Comment by mfeit-internet2** [comment]
The program runner (`program.py`) is supposed to terminate running processes with `atexit`.  Need to see if that's not working.

**Comment by mfeit-internet2** [comment]
Andy's temporary fix works fine for the time being.  Kicking to 1.0 for later investigation.  Should consider rewriting the runner so it doesn't do so much forking.

**Comment by arlake228** [comment]
Not worth fixing further, really a EL6 problem. Closing

**Comment by mfeit-internet2** [comment]
Re-opening.  We're not doing brute force on EL7, and some of the daemons take awhile to shut down.
