### ISSUE TITLE
IPv4 address rather than IPv6 is used with paris-traceroute 

### ISSUE THREAD

**Issue by duncanrand** [perfsonar/pscheduler#1260]
When running a trace with the paris-traceroute tool requesting IPv6 it appears that the IPv4 address is used:

$ pscheduler task --tool paris-traceroute trace --ip-version 6 --source ps-slough-10g.ja.net --dest picperfsonar-bandwidth.pic.es
...

Error from ps-slough-10g.ja.net:

  E: Invalid destination address 193.109.172.250

Diagnostics from ps-slough-10g.ja.net:

  sudo paris-traceroute -q 1 -6 -n 193.109.172.250

**Comment by mfeit-internet2** [comment]
This is resolved and will be in the next bugfix release.
