### ISSUE TITLE
tracepath test in v4.4.6

### ISSUE THREAD

**Issue by muali14** [perfsonar/pscheduler#1315]
Running a simple tracepath test sometimes fails in v4.4.6. Here is an example:

```
$ pscheduler task --tool tracepath trace --dest uct2-net1.mwt2.org
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/a47edf88-2f97-4e6d-8626-87ac710270ca
Running with tool 'tracepath'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/a47edf88-2f97-4e6d-8626-87ac710270ca/runs/4264c641-84a0-47cd-8be0-977c3b57ee5f
Starts 2023-01-19T17:38:33-05 (~2 seconds)
Ends   2023-01-19T17:40:14-05 (~100 seconds)
Waiting for result...

Problem fetching results: Failed to format result: At /paths/0/4/hostname: 'chic-cr6--uchicago_se-204.es.net' is not a 'ipv4'

```

The same command runs fine without any errors in v4.3.4. Additionally, the above error seems to be related to the hostname lookup and\or the default output format. So the below commands run without any errors in v4.4.6.

`pscheduler task --tool tracepath trace --dest uct2-net1.mwt2.org --no-hostnames`

`pscheduler task --format json --tool tracepath trace --dest uct2-net1.mwt2.org`

Please let me know if you have any suggestions, or need further info. Thanks.

**Comment by mfeit-internet2** [comment]
We've run into this before.  The DNS hostname `chic-cr6--uchicago_se-204.es.net` contains an underscore, which makes it invalid under RFC 1034.  That, in turn, torpedoes the validity of the entire result, which is checked before the result formatter will operate on it.

Some inside baseball:  pScheduler has a dictionary of standard things that it uses for validating JSON.  Part of the result spec for the `trace` test includes use of the [`Host`](https://github.com/perfsonar/pscheduler/blob/aa02596df366e3391bdd2e609766fa7729d16333/python-pscheduler/pscheduler/pscheduler/jsonval.py#L141) element, which refers to the `Hostname` element a few lines down.  That uses a standard JSONSchema validator, which is compliant with the RFC.

Outside of altering the invalid result to be valid (which I can't bring myself to do), there are a couple of options:

 * Disobey Postel's law and make a more-tolerant version of the validator for what we get back from DNS.  But then I won't have produced something valid and something downstream based on that data will blow up and I'll have to field the same question in a different context.
 * Validate results when they're returned by the tool and treat the entire measurement as having failed.

The plugins don't generate bad JSON the the current compromise of storing it and letting the formatter choke on it seems to be the right thing.  DNS misconfigurations like this aren't very common; I've seen maybe two in the last ten years.

BTW, I've notified ESnet of the problem in their DNS.
