### ISSUE TITLE
Upgrade PostgreSQL

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1316]
Per the [PostgreSQL Versioning Policy](https://www.postgresql.org/support/versioning/), version 10 reached the end of support in November 2022.

# Current state of Pg in the distributions we support

| Distro | Default | End of Life | Notes |
|--------|---------|-------------|-------|
| CentOS 7 | 9 | | We currently build 10. |
| Alma/Rocky 8 | 11 | 2023-11-09 | Uses DNF modules. |
| Alma/Rocky 9 | | | Not provided; depends on `download.postgresql.org` |
| Debian 10 | 11 | 2024-06-30 | Provided by the OS (LTS) |
| Debian 11 | 13 | 2026-06-30 | Provided by the OS (LTS) |
| Debian 12 | 15 | 2028-06-30 | Provided by the OS (LTS) |
| Ubuntu 18 | 10 | 2028-04-30 | Provided by the OS (LTS) |
| Ubuntu 20 | 12 | 2030-04-30 | Provided by the OS (LTS) |
| Ubuntu 22 | 14 | 2032-04-30 | Provided by the OS (LTS) |

Based on this information, all code should be targeted at 10 and builds for CentOS 7 and Alma/Rocky 9 should be 11.

## Changes by version that may affect us

[Pg 11](https://www.postgresql.org/docs/11/release-11.html):
 * None

[Pg 12](https://www.postgresql.org/docs/12/release-12.html):
 * None

[Pg 13](https://www.postgresql.org/docs/13/release-13.html):
 *  Prevent display of auxiliary processes in pg_stat_ssl and pg_stat_gssapi system views (Euler Taveira).  Queries that join these views to pg_stat_activity and wish to see auxiliary processes will need to use left joins.
 * Remove support for defining foreign key constraints using pre-PostgreSQL 7.3 syntax (Daniel Gustafsson)

[Pg 14](https://www.postgresql.org/docs/14/release-14.html):
 * Default server password encryption has changed.  Will need to do a password reset after the upgrade.

[Pg 15](https://www.postgresql.org/docs/15/release-15.html):
 * None

## Also of Note

Pg14 has added multiranges to its range types.  This might be used to eliminate the hand-rolled code used to propose run times.

**Comment by tonin** [comment]
PostgreSQL support in Debian and Ubuntu are the following:
- Ubuntu 18: PSQL 10
- Debian 10: PSQL 11
- Ubuntu 20: PSQL 12
- Debian 11: PSQL 13
- Ubuntu 22: PSQL 14

The way we distribute pScheduler now on these OS is that we rely on the default version they provide and their security fixes.

**Comment by mfeit-internet2** [comment]
Dropping support for EL7 and EL8 makes this OBE since Alma and Rocky supply a good version by default.
