### ISSUE TITLE
How to customize a test?

### ISSUE THREAD

**Issue by jianan1104** [perfsonar/pscheduler#1319]
Hey developers, I have a question for you guys.

It is very convenient for pScheduler to have rtt test, but my current situation is quite special, and I don’t know how to implement it. The situation is as follows

The tool flow I need is something like:

1. restart [hostB]
2. wait for hostB to be available to ping...
3. [hostA] ping [hostB]

Then repeat this process 10-100 times. I need to remotely control hostB through commands in the first step, but I don't know how to add it to the existing test, or should I customize a test?

**Comment by mfeit-internet2** [comment]
pScheduler isn't the right tool for this job.  You'd need to write custom test and tool plugins to do this, which is a labor-intensive process for relatively-little gain.

If you want to take advantage of pScheduler's ability to archive measurements that happen in step 3, I'd recommend writing a short shell script:

- Restart host B
- Repeat step 2 until host B appears up
- Call [pScheduler's batch processor](https://docs.perfsonar.net/pscheduler_batch.html) to do the `rtt` measurement and send it to an archive.
