### ISSUE TITLE
fwmtu tool should default to IPv6

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#1345]
The fwmtu currently defaults to IPv4 when given a hostname. It should default to IPv6 to be consistent with other tools and long-standing perfSONAR practice. It should likely also have an "ip-version" field to control whether something uses IPv4 vs IPv6. This issue will be particularly relevant when #1344 is fixed and can use `pscheduler.ip_normalize_version` to select the proper address family and set of addresses.

**Comment by mfeit-internet2** [comment]
**Release Notes:**  (This covers #1344, too.)

Improved IPv6 handling and source binding in MTU measurement tool.
