### ISSUE TITLE
pscheduler not handing iperf2 output 'error = Failed to format result'

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#1356]
pscheduler version:        5.0.4-1

I'm getting this error everywhere I run tests to:

pscheduler task --tool iperf2 throughput  --ip-version 4 --parallel 8 --duration PT10S --dest kans-ps-tp.es.net
Submitting task...
Task URL:
https://chic-ps.es.net/pscheduler/tasks/8022c198-9f9d-473f-a581-2d294c85911b
Running with tool 'iperf2'
Fetching first run...

Next scheduled run:
https://chic-ps.es.net/pscheduler/tasks/8022c198-9f9d-473f-a581-2d294c85911b/runs/d8240841-9a45-4532-bd72-23563c04bc05
Starts 2023-09-18T14:28:15+00:00 (~22 seconds)
Ends   2023-09-18T14:28:31+00:00 (~15 seconds)
Waiting for result...

Problem fetching results: Failed to format result: At /summary: [{'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '9', 'throughput-bits': 15700000000.0, 'throughput-bytes': 18300000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '6', 'throughput-bits': 15700000000.0, 'throughput-bytes': 18300000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '3', 'throughput-bits': 11100000000.0, 'throughput-bytes': 12900000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '5', 'throughput-bits': 15700000000.0, 'throughput-bytes': 18300000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '4', 'throughput-bits': 7880000000.0, 'throughput-bytes': 9170000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '7', 'throughput-bits': 9820000000.0, 'throughput-bytes': 11400000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '10', 'throughput-bits': 14400000000.0, 'throughput-bytes': 16800000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': '8', 'throughput-bits': 7890000000.0, 'throughput-bytes': 9210000000.0}, {'end': 10.0, 'lost': None, 'sent': None, 'start': 0.0, 'jitter': None, 'stream-id': 'SUM', 'throughput-bits': 98000000000.0, 'throughput-bytes': 114000000000.0}] is not of type 'object'

To some hosts I just get "Run Failed". Eg:

>pscheduler task --tool iperf2 throughput --ip-version 4 --parallel 8 --duration PT10S --dest ps-london-bw.perf.ja.net
>curl -k "https://chic-ps.es.net/pscheduler/tasks/806c2369-97e4-49a9-8260-bb6ee9ec5c4c/runs/bd0b3fff-9fc0-48d2-8ed0-2f0621e14531?pretty"
{
    "added": "2023-09-18T14:36:09+00:00",
    "clock-survey": [
        {
            "offset": 2.002716064453125e-05,
            "reference": "secondary reference (2) from 234.244.223.110",
            "source": "ntp",
            "synchronized": true,
            "time": "2023-09-18T14:36:33.661700+00:00"
        },
        {
            "offset": 4.315376281738281e-05,
            "reference": "secondary reference (2) from 157.44.176.4",
            "source": "ntp",
            "synchronized": true,
            "time": "2023-09-18T15:36:34.048866+01:00"
        }
    ],
    "duration": "PT11S",
    "end-time": "2023-09-18T14:36:28+00:00",
    "errors": null,
    "href": "https://chic-ps.es.net/pscheduler/tasks/806c2369-97e4-49a9-8260-bb6ee9ec5c4c/runs/bd0b3fff-9fc0-48d2-8ed0-2f0621e14531",
    "limit-diags": "Hints:\n  requester: 127.0.0.1\n  server: 127.0.1.1\nIdentified as everybody, local-interfaces\nClassified as default, root\nApplication: Check if using correct throughput interface for all classifiers\n  Group 1: Limit 'no-throughput-on-latency' passed\n  Group 1: Want all, 1/1 passed, 0/1 failed: PASS\n  Application PASSES\nPassed one application.  Stopping.\nProposal meets limits\nPriority set to default of 0",
    "participant": 0,
    "participant-data": {},
    "participant-data-full": [
        {},
        {
            "server_port": 5001
        }
    ],
    "participants": [
        "chic-ps.es.net",
        "ps-london-bw.perf.ja.net"
    ],
    "priority": null,
    "result": {},
    "result-full": [
        {},
        {
            "succeeded": true
        }
    ],
    "result-href": "https://chic-ps.es.net/pscheduler/tasks/806c2369-97e4-49a9-8260-bb6ee9ec5c4c/runs/bd0b3fff-9fc0-48d2-8ed0-2f0621e14531/result",
    "result-merged": {},
    "start-time": "2023-09-18T14:36:17+00:00",
    "state": "failed",
    "state-display": "Failed",
    "task-href": "https://chic-ps.es.net/pscheduler/tasks/806c2369-97e4-49a9-8260-bb6ee9ec5c4c"

**Comment by mfeit-internet2** [comment]
Fixed.  The iperf2 plugin wasn't correctly generating the summary data.
