### ISSUE TITLE
Scheduler throws all non-starters after a long run.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#1363]
CERN is seeing a situation after about a week where the `error` variable is getting set with global scope and the `schedule_task()` function is picking it up, assuming there is actually an error and posting explanation-free non-starters.

A two-part fix is required:

First is to force `error` into local scope by initializing it withing the function:

```
diff scheduler-orig scheduler-patched
748a749,750
>     error = None
>
```

Second is to figure out where `error` is being assigned with global scope.  (Edit: Looks like this is the only place where this variable is used, so initializing it should be a good fix.)

System showing the error is `pse01-gva.cern.ch`.

**Comment by arlake228** [comment]
Closing this since we included fix above in 5.0.6.
