### ISSUE TITLE
pscheduler service management

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#138]
Hi Mark, guys,

Please do consider implementing the "status" option in the init scripts of pscheduler. See below:

Regards,
Ivan

[root@psps-test2-mgmt ~]# service pscheduler-runner status
Usage: /etc/init.d/pscheduler-runner {start|stop|restart}
[root@psps-test2-mgmt ~]# service pscheduler-scheduler status
Usage: /etc/init.d/pscheduler-scheduler {start|stop|restart}
[root@psps-test2-mgmt ~]# service pscheduler-archiver status
Usage: /etc/init.d/pscheduler-archiver {start|stop|restart}
[root@psps-test2-mgmt ~]# service pscheduler-ticker status
Usage: /etc/init.d/pscheduler-ticker {start|stop|restart}
[root@psps-test2-mgmt ~]# service httpd status
**httpd (pid  22342) is running...**
[root@psps-test2-mgmt ~]# echo $?
**0**
[root@psps-test2-mgmt ~]# service httpd stop
Stopping httpd:                                            [  OK  ]
[root@psps-test2-mgmt ~]# service httpd status
**httpd is stopped**
[root@psps-test2-mgmt ~]# echo $?
**3**

**Comment by mfeit-internet2** [comment]
Done.  Enjoy.
