### ISSUE TITLE
Incorrect pscheduler.log permissions

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#1447]
I can see that 5.0.8 and 5.1 (Ubuntu 20) has different (unusual?) pscheduler.log permissions:
$ ls -la
total 3012
drwxr-xr-x  2 syslog root      4096 Jun 23 00:00 .
drwxrwxr-x 20 root   syslog    4096 Jun 24 00:00 ..
-rw-r-----  1 syslog adm     205581 Jun 24 08:35 pscheduler.log
-rw-r-----  1 syslog adm    1169860 Jun 22 23:39 pscheduler.log.1
-rw-r-----  1 syslog adm      96349 Jun 15 23:56 pscheduler.log.2.gz
-rw-r-----  1 syslog adm      56110 Jun  8 23:55 pscheduler.log.3.gz
-rw-r-----  1 syslog adm    1530985 Jun  1 23:11 pscheduler.log.4.gz
$ tail pscheduler.log
tail: cannot open 'pscheduler.log' for reading: Permission denied

Comparing to another host that runs 4.4.6 (CentOS):
$ ls -la
total 1916
drwxr-xr-x.  2 root root    152 Jun 23 07:04 .
drwxr-xr-x. 17 root root   4096 Jun 23 07:04 ..
-rw-r--r--   1 root root  97101 Jun 24 17:39 pscheduler.log
-rw-r--r--   1 root root 454202 Jun  2 04:52 pscheduler.log-20240602
-rw-r--r--   1 root root 468353 Jun  9 07:52 pscheduler.log-20240609
-rw-r--r--   1 root root 454774 Jun 16 04:22 pscheduler.log-20240616
-rw-r--r--   1 root root 466969 Jun 23 06:55 pscheduler.log-20240623
geantadmin@perfSonar:)/var/log/pscheduler$ $ tail pscheduler.log
Jun 24 17:18:03 perfSonar journal: runner INFO     27679159: Run succeeded.
Jun 24 17:29:01 perfSonar journal: runner INFO     27679160: Running https://193.40.132.142/pscheduler/tasks/6bfebbfc-07d5-414e-a994-690e51be1b36/runs/292cc429-ef7d-4c2f-99cb-98b1af7b5465

**Comment by mfeit-internet2** [comment]
Permissions on the log files are _mostly_ a function of how `rsyslog` is configured by default on each distribution.  The service doesn't provide granular-enough configuration to change ownership and permissions on single log files and not have it affect anything downstream in the configuration.

This was covered in #577, which added a `pscheduler log` command that would become root using `sudo` if the current user isn't.  That's about the best solution there is to the problem for the moment.

**Comment by laeti-tia** [comment]
I'll double check, I thought I had solved that as part of https://github.com/perfsonar/toolkit/issues/457

**Comment by laeti-tia** [comment]
Ok, so I'm a bit puzzled by your report @szymontrocha  What I see on a fresh U20 install is the following.

Right after installation:
```
ls -la /var/log/pscheduler/
total 4.0K
-rw-r--r-- 1 syslog adm 1.3K Jul 10 15:46 pscheduler.log
```
And after forcing a logrotate:
```
# logrotate --force /etc/logrotate.conf 
# ls -la /var/log/pscheduler/
-rw-r--r-- 1 syslog adm  795 Jul 10 16:04 pscheduler.log
-rw-r--r-- 1 syslog adm 1.3K Jul 10 15:46 pscheduler.log.1
```

Is this an upgraded system maybe?  What is the content of `/etc/logrotate.d/pscheduler-server` and `/etc/rsyslog.d/pscheduler-server.conf` ?

**Comment by laeti-tia** [comment]
I see our logrotate setup doesn't specify log mode, maybe we can force it to overwrite a default that would be different.  That's my best bet so far.

**Comment by laeti-tia** [comment]
@szymontrocha can you add a line with:
```
    create 0644
```
in `/etc/logrotate.d/pscheduler-server` and then run `logrotate --force /etc/logrotate.conf` to see if it solves your setup?

**Comment by szymontrocha** [comment]
For 5.0.8 this was an upgraded system for 5.1 it was a RC install I think.
Anyway I did the change (in 5.0.8 host):
# ls -la
total 17152
drwxr-xr-x  2 syslog root       4096 Jul  7 02:00 .
drwxrwxr-x 20 root   syslog     4096 Jul 11 00:00 ..
-rw-r-----  1 syslog adm    16222972 Jul 11 06:04 pscheduler.log
-rw-r-----  1 syslog adm     1033987 Jul  7 01:59 pscheduler.log.1
-rw-r-----  1 syslog adm       85298 Jun 30 01:59 pscheduler.log.2.gz
-rw-r-----  1 syslog adm      100265 Jun 23 01:39 pscheduler.log.3.gz
-rw-r-----  1 syslog adm       96349 Jun 16 01:56 pscheduler.log.4.gz
# vi /etc/logrotate.d/pscheduler-server 
# logrotate --force /etc/logrotate.conf
# ls -la
total 16128
drwxr-xr-x  2 syslog root       4096 Jul 11 06:54 .
drwxrwxr-x 20 root   syslog     4096 Jul 11 06:54 ..
-rw-r--r--  1 syslog adm           0 Jul 11 06:54 pscheduler.log
-rw-r-----  1 syslog adm    16222972 Jul 11 06:04 pscheduler.log.1
-rw-r-----  1 syslog adm       86746 Jul  7 01:59 pscheduler.log.2.gz
-rw-r-----  1 syslog adm       85298 Jun 30 01:59 pscheduler.log.3.gz
-rw-r-----  1 syslog adm      100265 Jun 23 01:39 pscheduler.log.4.gz

**Comment by laeti-tia** [comment]
Thanks, that's the expected behavior.  dcd1088 should solve that.
