### ISSUE TITLE
pscheduler & psconfig services failing because of python error

### ISSUE THREAD

**Issue by Rezi1999** [perfsonar/pscheduler#1478]
I am using Ubuntu 22 Ipv6 only host , checked the Host Info in grafana and these services have been failing for two weeks, the same error is recorded everywhere in the logs.

services that fail: 
![python](https://github.com/user-attachments/assets/516a57cf-7e84-4db4-9ae9-58cb21841480)

python error:
![python_import error](https://github.com/user-attachments/assets/e4b3167e-3231-4c8d-9315-0460907440bd)

**Comment by laeti-tia** [comment]
@Rezi1999 Which version of packages you have installed, which repository are you using?

**Comment by Rezi1999** [comment]
> @Rezi1999 Which version of packages you have installed, which repository are you using?

I am using 5.2 snapshot repository

**Comment by laeti-tia** [comment]
@Rezi1999 can you upgrade all the packages to their latest versions (snapshot repo receives newly built packages every night) and then list the versions of the following packages:
- jq
- pyjq or python3-pyjq or python3-pyjq-u22
- perfsonar-psconfig-pscheduler

**Comment by laeti-tia** [comment]
We have a conflict between the `python3-pyjq-u22` provided by the `perfsonar-release` and the `perfsonar-5.2-snapshot` repositories.  The latest should have precedence, but the versions numbers don't make it so.  Can you force install the one coming from the `perfsonar-5.2-snapshot` repo?

**Comment by laeti-tia** [comment]
I cannot reproduce the bug when installing using only the `perfsonar-5.2-snapshot` repository and nothing else.

**Comment by Rezi1999** [comment]
@laeti-tia 
force install from the` perfsonar-5.2-snapshot` did the trick.

thank you
