### ISSUE TITLE
--fq-rate not passed to iperf3

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#1483]
I'm running this:
pscheduler task throughput --dest hostname --duration 30 --parallel 8 --fq-rate 12.5g

But I see this iperf3 client started:
/usr/bin/iperf3 -p 5201 -c newy32aoa-ps-tp.es.net -t 30 --json -P 8 --rsa-public-key-path /var/pscheduler-server/runner/tmp/tmpipep100_/tmperwjg965/public-key --username McphfbPUwjZFhL1CGLeP

no "--fq-rate" 

Also, per-stream tput varied from 10-15 to 15G; thats how I knew to too look for a problem.

**Comment by mfeit-internet2** [comment]
Looks like the modification to the plugin was incomplete.  I'll get that fixed in the next release.
