### ISSUE TITLE
ability to set auto set pacing for iperf3

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#160]
pScheduler could query the LS to get the remote host NIC speed, and then call iperf3 using the '--bandwidth' flag with that speed. On CentOS7, this will pace the socket in the kernel.

**Comment by mfeit-internet2** [comment]
A better solution for this is for the tool on both sides to figure out what interface it's going to use, determine its rate and put it in the participant-specific data.  The sending side can compare the two values and throttle itself to whichever is smaller.

The hitch is that in some environments, the information that comes back isn't accurate.  For example, the VIFs provided to Docker containers enumerate as being 10Gb/s when they're really tied to some other physical interface.

**Comment by mfeit-internet2** [comment]
Brian says Dan did this.
