### ISSUE TITLE
feature: ability to (automatically) attempt test initiation from destination

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#167]
Hi Mark,

In the case where pscheduler initiation of a task is triggered from a third party, please consider:
1) give the ability to specify which pscheduler service the user prefers to setup the measurement
2)  a fault backup procedure with pscheduler, where the manager re-attempts to setup a measurement task by contacting the destination server in the test pair, when communication with source fails. I am excluding here the case, where the source pscheduler has denied the test establishment.
It would be very much helpful to receive also a notification of the failure...but only if possible.

Some relevance to this case as well: https://github.com/perfsonar/pscheduler/issues/33#issuecomment-251151588

P.S.: I am not sure, if I am stating the obvious here, but just to be on the safe side.

**Comment by mfeit-internet2** [comment]
Duplicates #33 and #148.
