### ISSUE TITLE
One-Step Backup for pScheduler

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#170]
Implement something that will back up the entire state of pScheduler into a tarball and restore it.

Should contain:

 * Contents of /etc/pscheduler
 * Dump of pscheduler database

Notify @daldoyle for inclusion in the toolkit.

**Comment by mfeit-internet2** [comment]
@vvidic The build changes here will need to be brought into Debian.  Please pass on to @daldoyle when finished for integration into the toolkit.

Quick summary for Dan:

`pscheduler backup > /path/to/backup/file`
`pscheduler restore /path/to/backup/file`

Neither produces output when in a non-interactive environment and `restore` doesn't ask for input.

**Comment by vvidic** [comment]
Debian packages updated to include the backup/restore command.

**Comment by mfeit-internet2** [comment]
Passed on to the toolkit in https://github.com/perfsonar/toolkit/issues/264.
