### ISSUE TITLE
better error handling for bad hostname

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#171]
Here is what I get if I use a bad hostname:

psc task throughput --dest llnl-pt1

Submitting task...

Task URL:

https://nettest.lbl.gov/pscheduler/tasks/c7579e46-8ce0-4a0b-92e8-bcaebe284e3d

Fetching first run...

Run on server was never populated.

-----------

The error should be: **host not found**, and checked before submitting the test.

**Comment by mfeit-internet2** [comment]
That's probably the slip problem we discussed.

I did do some testing on a system where there were no interfering runs on the schedule and identified a problem with the test code.  See #173.

**Comment by bltierney** [comment]
This host does not exist, so I dont think its related to the slip problem.

**Comment by mfeit-internet2** [comment]
Can't test whether or not the host resolves until the run actually happens.  It would be perfectly valid to add a test for a host that doesn't exist now but you know will in the future.

My suggestion for good practice on repeating tasks would be to run it one-shot by hand a couple of times to make sure it's right before submitting the "real" version.

Here's how it's currently handled if you're running from the command line:

```
% psc task rtt --dest badhost
Submitting task...
Task URL:
https://dev7/pscheduler/tasks/99dd11a8-9b72-4398-a1b1-5ebedb3e924b
Fetching first run...

Next run:
https://dev7/pscheduler/tasks/99dd11a8-9b72-4398-a1b1-5ebedb3e924b/runs/a0d5eb8b-dacb-41a5-8232-68607533b9ee
Starts 2016-10-19T16:58:05-04:00 (~8 seconds)
Ends   2016-10-19T16:58:16-04:00 (~10 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By dev7:
    Unable to resolve destination 'badhost'

No runs scheduled for this task.
```
