### ISSUE TITLE
Override task settings with default tool settings

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#177]
Hi Mark,

it would be nice, if admin is able to define some test parameters as obligatory / default.
Example throughput: 

For instance there are hosts, that we need to apply limitations to certain speeds. I would not be happy if some random guy, who is allowed to run tests with my host (just because is open), to be able to change these with a task request.

namely: 
- bandwidth, buffer-length with values above the defaults
- cpu-affinity

Regards,
Ivan

**Comment by mfeit-internet2** [comment]
Need to evaluate how this would work in light of:
* Two systems might alter the test parameters in different, incompatible ways.
* This violates the principle of least astonishment by causing tests to behave in ways the submitter did not specify.  (Note that we already do this with the bandwidth limit for throughput, but that fact will be documented and it will be a standard part of the test.)

If implemented, make it something that filters incoming tests.

**Comment by mfeit-internet2** [comment]
This can be accomplished with the rewriter.
