### ISSUE TITLE
Ability to apply default tool settings (pS 4.1)

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#178]
Hi Mark,

We have some hosts capable of running obtrusive tests in the network. It would be nice, if sys admin is able to define tool and task specific defaults, which are applied automatically, so that these limitations are not replicated at multiple test configurations or to be remembered by CLI test initiators, BUT applied automatically at test initiations and negotiations.

examples: 
bandwidth, duration

Regards,
Ivan

**Comment by mfeit-internet2** [comment]
Might be subsumed by #401

**Comment by arlake228** [comment]
Duplicates #177
