### ISSUE TITLE
`psc debug on` possibly not working on all scripts

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#181]
There are a handful of scripts that don't appear to have their debug environment passed in correctly from an invocation of `psc debug on`. I don't have a full list, but at least $test/`participants` seems to be affected.

Making the following change as an example:

```
--- a/pscheduler-test-throughput/throughput/participants
+++ b/pscheduler-test-throughput/throughput/participants
@@ -12,8 +12,12 @@ import sys
 logger = pscheduler.Log(prefix='test-throughput')
+logger.info("****************************INSIDE PARTICIPANTS INFO")
+logger.debug("****************************INSIDE PARTICIPANTS DEBUG")
+
```

and issuing a `psc debug on` and then starting a throughput test yields in /var/log/messages:

```
Oct 12 10:24:46 ps-test1 ticker DEBUG    Next check in 14 seconds
Oct 12 10:24:46 ps-test1 test-throughput/participants INFO     Started
Oct 12 10:24:46 ps-test1 test-throughput/participants INFO     Started
Oct 12 10:24:46 ps-test1 test-throughput/participants INFO     ****************************INSIDE PARTICIPANTS INFO
Oct 12 10:24:46 ps-test1 test-throughput/participants INFO     ****************************INSIDE PARTICIPANTS INFO
Oct 12 10:24:46 ps-test1 tool-iperf3/can-run INFO     Started
```

Note the lack of the "INSIDE PARTICIPANTS DEBUG" despite being in debug mode.

This isn't a priority for the RC since it mostly affects developers at this point, but would be good to fix up since it might afford us better field debugging opportunities in the future.

**Comment by mfeit-internet2** [comment]
Probably a side effect of #113 since `participants` is run by the API server.

**Comment by mfeit-internet2** [comment]
Verified; this is because of not all processes in the HTTP server are getting their debug state changed.

Closing as a duplicate.
