### ISSUE TITLE
Make trace and rtt background-ish tasks

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#182]
An average perfsonar host runs trace (possibly tracepath) tasks every 10 minutes. This can make the schedule look pretty busy for throughput tasks since they want nothing running except background tasks (i.e. powstream) at the moment. Throughput tests should similarly ignore trace and rtt tasks since they have little to no impact on the results. Per discussion with Mark, it probably means a new test class since the current "background" tasks have some other characteristics, but should not be too difficult to implement.

**Comment by mfeit-internet2** [comment]
See also #120, which might achieve the same thing.

**Comment by mfeit-internet2** [comment]
Not really a bug, but high-priority.

**Comment by mfeit-internet2** [comment]
Final outcome:

 * `background` scheduling class renamed `background-multi`
 * Added new `background` which runs independently but only produces one result
 * Changed `idle`, `rtt` and `trace` tests to use `background` scheduling class

Packages renamed:   (@vvidic needs to change the Debian packaging to reflect this.)
 * `pscheduler-test-idlebg` -> `pscheduler-test-idlebgm`
 * `pscheduler-tool-sleepbg` -> `pscheduler-tool-sleepbgm`
