### ISSUE TITLE
Infinite Limits

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#184]
Limits need to be able to handle the "infinite" case, such as where not specifying a parameter implies that it has some default value, such as infinity.  (This would be the use case for bandwidth during throughput tests.)

There should be an additional return from the initial limits test when the test is submitted where an infinite limit would fail but the test's processor suggests changes that would make it pass (e.g., no bandwidth specified with a `1G` limit forces it to that value).  This should not apply when the parameter is explicitly provided.

**Comment by igarny** [comment]
Please consider the feature requests in #178 and #177 

I believe #178 almost fully matches this one and #177 extends a bit further the request

**Comment by mfeit-internet2** [comment]
Still need to add the bandwidth-limiting code to the `run` method in:
* `pscheduler-tool-iperf2`
* `pscheduler-tool-nuttcp`

See if we need to do anything for the backward-compatibility code or if we're just going to leave that to `bwctl.limits`.

**Comment by mfeit-internet2** [comment]
Last bit of code has been committed.  Closing.
