### ISSUE TITLE
BUG: IPv6 address processing

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#185]
Hi Mark, 

Here I have collected some error cases with IPv6 processing: 

### Environment
my initiator host H1:
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether fa:16:3e:cb:8f:1c brd ff:ff:ff:ff:ff:ff
    inet 10.0.172.16/16 brd 10.0.255.255 scope global eth0
    **inet6 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c**/64 scope global dynamic
       valid_lft 86400sec preferred_lft 14400sec

ping to H2
 [root@pertmp01 ~]# ping6 **2001:620:5ca1:2f0:f816:3eff:fe25:b47a**                                                              PING 2001:620:5ca1:2f0:f816:3eff:fe25:b47a(2001:620:5ca1:2f0:f816:3eff:fe25:b47a) 56 data bytes
64 bytes from 2001:620:5ca1:2f0:f816:3eff:fe25:b47a: icmp_seq=1 ttl=64 time=0.972 ms
64 bytes from 2001:620:5ca1:2f0:f816:3eff:fe25:b47a: icmp_seq=2 ttl=64 time=0.393 ms

[root@pertmp01 ~]# grep pertmp01 /etc/hosts
10.0.172.16                            pertmp01    pertmp01.switch.ch
2001:620:5ca1:2f0:f816:3eff:fecb:8f1c  pertmp01    pertmp01.switch.ch

[root@pertmp01 ~]# psc debug on; psc task simplestream --timeout PT5S --source pertmp01 --dest pertmp02; psc debug off
Submitting task...
Task URL:
https://pertmp01/pscheduler/tasks/882251e7-40cc-4d21-9531-5f18b656109f
Fetching first run...

Next run:
https://pertmp01/pscheduler/tasks/882251e7-40cc-4d21-9531-5f18b656109f/runs/2fdee8ab-2f2c-43e0-beea-8bde3932bca3
Starts 2016-10-14T12:49:05Z (~7 seconds)
Ends   2016-10-14T12:49:10Z (~4 seconds)
Waiting for result...

Dawdled ......... P0D
Text Sent ....... Data sent at 2016-10-14 12:49:05.723542
Text Received ... Data sent at 2016-10-14 12:49:05.723542
Elapsed Time .... PT0.088139S

### Issues
psc task simplestream --timeout PT5S --source 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c --dest 2001:620:5ca1:2f0:f816:3eff:fe25:b47a
Submitting task...
Unable to determine the lead participant: At /dest: u'2001:620:5ca1:2f0:f816:3eff:fe25:b47a' is not a 'host-name'

[root@pertmp01 ~]# psc task simplestream --timeout PT5S --source 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c --dest 2001:620:5ca1:2f0:f816:3eff:fe25:b47a 
Submitting task...
Unable to determine the lead participant: At /dest: u'2001:620:5ca1:2f0:f816:3eff:fe25:b47a' is not a 'host-name'
[root@pertmp01 ~]# psc task **simplestream** --timeout PT5S --source 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c --dest 2001:620:5ca1:2f0:f816:3eff:fe25:b47a
Submitting task...
Unable to determine the lead participant: At /dest: u'2001:620:5ca1:2f0:f816:3eff:fe25:b47a' is not a 'host-name'

 psc task **throughput** --omit PT2S --duration PT12S --ip-version 6 --source 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c --dest 2001:620:5ca1:2f0:f816:3eff:fe25:b47a --bandwidth 1G --parallel 1
Submitting task...
Unable to post task: POST https://[2001:620:5ca1:2f0:f816:3eff:fecb:8f1c]/pscheduler/tasks returned 500: Invalid test specification: At /source: u'2001:620:5ca1:2f0:f816:3eff:fecb:8f1c' is not a 'host-name'

[root@pertmp01 ~]# psc task throughput --omit PT2S --duration PT12S --ip-version 6 --source **pertmp01** --dest 2001:620:5ca1:2f0:f816:3eff:fe25:b47a --bandwidth 1G --parallel 1
Submitting task...
Unable to post task: POST https://pertmp01/pscheduler/tasks returned 500: Invalid test specification: At /dest: u'2001:620:5ca1:2f0:f816:3eff:fe25:b47a' is not a 'host-name'

Regards,
Ivan Garnizov

**Comment by mfeit-internet2** [comment]
That should be an easy fix; it looks like a standard definition for what a host name should look like doesn't work with that case.

**Comment by mfeit-internet2** [comment]
Fixed.  Also made ping and the trace* tools smart enough to detect IP version based on what's in the --dest argument.
