### ISSUE TITLE
Request for less restrictive limits

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#186]
In a default toolkit installation with the following IP configuration:
]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:25:90:56:96:b2 brd ff:ff:ff:ff:ff:ff
    inet 150.254.160.17/28 brd 150.254.160.31 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::225:90ff:fe56:96b2/64 scope link
       valid_lft forever preferred_lft forever
3: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 00:25:90:56:96:b3 brd ff:ff:ff:ff:ff:ff
4: enp4s3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether 00:0e:0c:c4:49:1e brd ff:ff:ff:ff:ff:ff
[root@localhost log]#

a simple command of pscheduler throughput test is returning error:

psc task throughput --dest perfsonardev2.internet2.edu
Submitting task...
Unable to post task: POST https://localhost.localdomain/pscheduler/tasks returned 403: Task forbidden by limits:
Identified as everybody, bogons
Classified as everybody, default, hostiles
Application: Prevent hostiles from doing anything
    Group 1: Limit 'never' failed: Forced failure
    Group 1: Stopped on fail
    Group 1: Want all, 0/1 passed, 1/1 failed: FAIL
    Group 1: Failed; stopping here.
    Application FAILS
    Failed - Stop Forced
Proposal does not meet limits
[root@localhost log]#

due to too restrictive limits file which in a default version blocks something (IPv6 link-local address?). 
The request here is to make the default settings less restrictive so that default installation enables running default commands and do not surprise users using standard installation (in this case just IPv4 address leaving IPv6 not configured).

**Comment by szymontrocha** [comment]
I removed the pscheduler limits file but it didn' help (maybe just a bit) so the problem must be somewhere else:

[root@localhost pscheduler]# psc task throughput --dest perfsonardev2.internet2.edu
Submitting task...
Task URL:
https://localhost.localdomain/pscheduler/tasks/73730c57-0f72-436f-8ee5-676f6f00b175
Fetching first run...

Next run:
https://localhost.localdomain/pscheduler/tasks/73730c57-0f72-436f-8ee5-676f6f00b175/runs/27035a74-1621-41bc-bb3d-adb620af4698
Starts 2016-10-14T09:34:29-04:00 (~5 seconds)
Ends   2016-10-14T09:35:40-04:00 (~70 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By localhost.localdomain:
    bwctl: Unable to connect to perfsonardev2.internet2.edu

No runs scheduled for this task.
[root@localhost pscheduler]#

Let me know if you nedd more debug info

**Comment by igarny** [comment]
I believe the root of the issue reported here matches the information commented here #187.

**Comment by mfeit-internet2** [comment]
You need to restart httpd for changes in the limit file to take effect.

Auto-detection of changes is covered in #42, which I will try to get closed before we ship pS 4.0.
