### ISSUE TITLE
Change of logging behaviour to have consisteng web gui feeling

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#188]
So far pscheduler writes to /var/log/messages. However there is a link in the main toolkit page under SERVICE LOGS to pscheduler log which now opens /var/log/perfsonar which doesn't contain pscheduler log. It doesn't make much sense from consistency point of view. Now when user clicks this link he will not get the logs from pscheduler in this place similarly to other logs from web page. So we may want to change this default behaviour (either in gui or in the logs config).

**Comment by szymontrocha** [comment]
This may be related to perfsonar/toolkit#14

**Comment by mfeit-internet2** [comment]
Probably a toolkit thing that should be resolved before 1.0.

Currently, everything goes to syslog's `user` facility.  We could change that to one of the `local*` family or find a way to make it globally-configurable so syslog can be configured to snag it and put it where the toolkit likes.

I'm going to hold this open as an enhancement for 1.0 so we can revisit the default log level

**Comment by mfeit-internet2** [comment]
Log redirected in #209; logs now live in `/var/log/pscheduler/pscheduler.log`.
