### ISSUE TITLE
Scheduler's run_post not failing gracefully

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#189]
John Simpkins observed the following:

```
Oct 17 08:56:48 perfsonar4-lab-ma journal: scheduler DEBUG    Posting https://perfsonar4-lab-ma/pscheduler/tasks/c7b8e0fd-8363-4a19-b7ba-95db78aadc3a at 2016-10-17 08:56:58.289267-04:00
Oct 17 08:56:48 perfsonar4-lab-ma journal: safe_run/scheduler ERROR    Program threw an exception after 0:00:00.022652
Oct 17 08:56:48 perfsonar4-lab-ma journal: safe_run/scheduler ERROR    Program threw an exception after 0:00:00.022652
Oct 17 08:56:48 perfsonar4-lab-ma journal: safe_run/scheduler ERROR    Exception: URLException: https://perfsonar4-lab-ma/pscheduler/tasks/c7b8e0fd-8363-4a19-b7ba-95db78aadc3a: 400: Error: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 41, in safe_run
    function()
  File "/usr/libexec/pscheduler/daemons/scheduler", line 430, in <lambda>
    pscheduler.safe_run(lambda: main_program())
  File "/usr/libexec/pscheduler/daemons/scheduler", line 394, in main_program
    run_post(url, trynext, log)
  File "/usr/libexec/pscheduler/daemons/scheduler", line 96, in run_post
    status, task = pscheduler.url_get(task_url_text, params={'detail': 1})
  File "/usr/lib/python2.7/site-packages/pscheduler/psurl.py", line 57, in url_get
    + ": " + text)#012URLException: https://perfsonar4-lab-ma/pscheduler/tasks/c7b8e0fd-8363-4a19-b7ba-95db78aadc3a: 400: Error: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Oct 17 08:56:48 perfsonar4-lab-ma journal: safe_run/scheduler ERROR    Waiting 348.25 seconds before restarting
```
These should be caught and dealt with.

**Comment by szymontrocha** [comment]
It's probably related. I observe pscheduler error when one of the test hosts is not resolving (although the error message do not say which one):

Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Program threw an exception after 0:00:10.335250
Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Program threw an exception after 0:00:10.335250
Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Exception: ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 430, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 394, in main_program#012    run_post(url, trynext, log)#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 162, in run_post#012    r = requests.get(runtime_url, params=range_params, verify=False)#012  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get#012    return request('get', url, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request#012    response = session.request(method=method, url=url, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send#012    r = adapter.send(request, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#012    raise ConnectionError(err, request=request)#012ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Exception: ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 430, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 394, in main_program#012    run_post(url, trynext, log)#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 162, in run_post#012    r = requests.get(runtime_url, params=range_params, verify=False)#012  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get#012    return request('get', url, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request#012    response = session.request(method=method, url=url, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send#012    r = adapter.send(request, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#012    raise ConnectionError(err, request=request)#012ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Waiting 221.0 seconds before restarting
Oct 18 10:01:14 localhost journal: safe_run/scheduler ERROR    Waiting 221.0 seconds before restarting

The test I run are scheduled to two hosts:

This one resolves:
[root@localhost log]# host psmall-poz1.man.poznan.pl
psmall-poz1.man.poznan.pl has address 150.254.163.77
psmall-poz1.man.poznan.pl has IPv6 address 2001:808:2:3004:2::2
[root@localhost log]#

This one not:
[root@localhost log]# host perfsonardev2.internet2.edu
;; connection timed out; trying next origin
;; connection timed out; no servers could be reached
