### ISSUE TITLE
Unable to determine duration of test

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#192]
Hi,

I am getting some ugly messages for a configuration like this

<test>
    <parameters>
        tool   iperf3
        omit_interval   3
        type   bwctl
        duration   12
        force_ipv4   1
        send_only   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    target   pertmp04.switch.ch
    local_address   pertmp01.switch.ch
    description   IPv4 throughput matrix
    <schedule>
        random_start_percentage   10
        type   regular_intervals
        interval   2400
    </schedule>
</test>

I have also tried with:
        omit_interval   5

psc started cooperating just when I had this combination:
        omit_interval   5
        duration   20

but I have been using it a lot with duration 30 in the past.

Still the error message is strange, since all of these should have been valid or what am I missing?

Regards,
Ivan

Oct 19 15:01:15 pertmp01 tool-bwctl/duration INFO     Started
Oct 19 15:01:15 pertmp01 pscheduler-api ERROR    Exception: InternalError: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, participant, uuid, hints)#012        VALUES (task_package, participant, task_uuid, hints)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,integer,uuid) line 6 at SQL statement#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, participant, uuid, hints)#012        VALUES (task_package, participant, task_uuid, hints)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,integer,uuid) line 6 at SQL statement
Oct 19 15:01:15 pertmp01 pscheduler-api ERROR    Exception: InternalError: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, participant, uuid, hints)#012        VALUES (task_package, participant, task_uuid, hints)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,integer,uuid) line 6 at SQL statement#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, participant, uuid, hints)#012        VALUES (task_package, participant, task_uuid, hints)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,integer,uuid) line 6 at SQL statement
Oct 19 15:01:15 pertmp01 pscheduler-api ERROR    Response 500: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'
Oct 19 15:01:15 pertmp01 pscheduler-api ERROR    Response 500: Unable to determine duration of test: Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>#012    duration += int(json['omit'])#012ValueError: invalid literal for int() with base 10: 'PT5S'
Oct 19 15:01:16 pertmp01 archiver-esmond/archive INFO     Started
Oct 19 15:01:16 pertmp01 archiver-esmond/archive INFO     Started

**Comment by daldoyle** [comment]
It looks like the bwctliperf3 has an issue where “omit” used to be specified in seconds but was changed to ISO spec and that’s causing issues. I will take ownership of fixing this, should have something out this week.

Dan Doyle
GlobalNOC Software Developer
1-812-856-3892
daldoyle@globalnoc.iu.edu
