### ISSUE TITLE
feature: "Storing full result in" with "Tool returned failure: iperf3 requires exactly 2 participants, got 1"

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#195]
Hi Mark,

I might be missing something, but is it really necessary to store null results, when there was a test failure?

Regards,
Ivan

Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Test failed 1: iperf3 requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 participant-data INFO Started
Oct 20 12:42:23 pertmp01 participant-data INFO Started
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Stored local result
Oct 20 12:42:23 pertmp01 runner DEBUG Schedule change.
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Doing lead participant duties
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Only one participant; not waiting.
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Runs are ['https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90']
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Local run returned 1
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Tool returned failure: iperf3 requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Accumulated local result
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Full result: [null]
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Storing full result in https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90, params={"result-full": [null]}

**Comment by mfeit-internet2** [comment]
Storing the nulls is all part of the process.  Closing.
