### ISSUE TITLE
Run often takes longer than 30 seconds to schedule

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#196]
On both antg-dev.es.net and antg-staging.es.net I frequently run into cases where I run something on the command-line and it takes longer than the 30 seconds for the first run to get scheduled. This was a problem because the CLI would only wait up to 30 sec for the run to get scheduled before exiting. I recently bumped this to 60 so we'll see how that does. The hosts are both running other tests and somewhat loaded, so that may contribute. I don't usually see it on clean dev hosts, but the hosts I am seeing it on are much more representative of the type of setup we'll see in the wild.

**Comment by mfeit-internet2** [comment]
Parallelizing the scheduler as we did with the archiver will probably help this considerably.

**Comment by mfeit-internet2** [comment]
Close this when you're happy with it.

**Comment by arlake228** [comment]
Optimizations seem to have fixed this. Closing
