### ISSUE TITLE
"tool": "traceroute" Missing results....no errors reported

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#198]
Hi Mark,

Aside from the issue, I would expect to have results from the tests of {"type": "trace"} and if there aren't to have an ERROR report in the logs.
It does not become clear in below setup, with below test specification why there is missing data. There is data from previous measurements, but they seem to have stopped more than 36h ago.

pscheduler-core.noarch              1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-server.noarch            1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-idle.noarch         1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-latency.noarch      1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-latencybg.noarch    1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-rtt.noarch          1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-simplestream.noarch 1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-throughput.noarch   1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-test-trace.noarch        1.0-0.12.rc1.el6        @Internet2-staging
pscheduler-tool-bwctliperf2.noarch  1.0-0.12.rc1.el6        @Internet2-staging

[root@pertmp01 ~]# curl -k https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
{"reference": {"created-by": {"user-agent": "perfsonar-meshconfig", "uuid": "7e257677-2a6d-4b98-aa75-7335e55c98e8", "address": "10.0.172.16"}, "description": "IPv4 bw-traceroute testing"}, "schedule": {"repeat": "PT1200S", "until": "2016-10-22T09:23:41Z", "slip": "PT1200S"}, "tool": "traceroute", "archives": [{"archiver": "esmond", "data": {"url": "http://pertcs01.switch.ch/esmond/perfsonar/archive/", "retry-policy": [{"attempts": 5, "wait": "PT60S"}, {"attempts": 3, "wait": "PT5M"}, {"attempts": 24, "wait": "PT60M"}], "_auth-token": null, "measurement-agent": "pertmp01.switch.ch"}}], "test": {"type": "trace", "spec": {"dest": "pertmp02.switch.ch", "length": 40, "source": "pertmp01.switch.ch", "ip-version": 4, "hops": 64, "schema": 1}}, "tools": ["bwctltracepath", "tracepath", "bwctltraceroute", "traceroute"], "schema": 1}

[root@pertmp01 ~]# curl -k https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88
{"reference": {"created-by": {"user-agent": "perfsonar-meshconfig", "uuid": "7e257677-2a6d-4b98-aa75-7335e55c98e8", "address": "10.0.172.16"}, "description": "IPv4 bw-traceroute testing"}, "schedule": {"repeat": "PT1200S", "until": "2016-10-22T09:23:41Z", "slip": "PT1200S"}, "tool": "traceroute", "archives": [{"archiver": "esmond", "data": {"url": "http://pertcs01.switch.ch/esmond/perfsonar/archive/", "retry-policy": [{"attempts": 5, "wait": "PT60S"}, {"attempts": 3, "wait": "PT5M"}, {"attempts": 24, "wait": "PT60M"}], "_auth-token": null, "measurement-agent": "pertmp01.switch.ch"}}], "test": {"type": "trace", "spec": {"dest": "pertmp04.switch.ch", "length": 40, "source": "pertmp01.switch.ch", "ip-version": 4, "hops": 64, "schema": 1}}, "tools": ["bwctltracepath", "tracepath", "bwctltraceroute", "traceroute"], "schema": 1}

Oct 21 09:00:53 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Run posting finished
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Scheduled for 2016-10-22 08:40:51+00:00 - 2016-10-22 08:40:59+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/a0568f83-f51c-4cd5-ade2-5
6da4482534b/runs/c2362779-876c-4ec0-819e-863940f9440e
Oct 21 09:00:54 pertmp01 scheduler DEBUG    TASK e5bad79e-4cd7-42c2-ab98-25255eb8f693, 144 runs, try 2016-10-22 08:40:51+00:00
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Trying to schedule e5bad79e-4cd7-42c2-ab98-25255eb8f693 for 2016-10-22 08:40:51+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
Oct 21 09:00:54 pertmp01 scheduler DEBUG    URL is https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Posting https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693 at 2016-10-22 08:40:51+00:00
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Participant list is [u'pertmp01.switch.ch']
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Range parameters are {'start': '2016-10-22T08:40:51Z', 'end': '2016-10-22T09:00:59Z'}
Oct 21 09:00:54 pertmp01 scheduler DEBUG    1 URLs in this task
Oct 21 09:00:54 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Fetching https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693/runtimes
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Scheduled against https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Done fetching time ranges
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Time range is 2016-10-22 08:40:51+00:00 - 2016-10-22 08:43:20+00:00
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Posting lead run to https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Data {'start-time': '2016-10-22T08:40:51+00:00'}
Oct 21 09:00:54 pertmp01 runner DEBUG    Schedule change.
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Lead URL is https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693/runs/3bc23525-15ce-4712-abae-ff9c7a9f4c23
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Fetching per-participant data
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Getting part data from https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693/runs/3bc23525-15ce-4712-abae-ff9c7a9
f4c23

> Oct 21 09:00:54 pertmp01 scheduler DEBUG    Got {}

Oct 21 09:00:54 pertmp01 scheduler DEBUG    Full part data: {"part-data-full": [{}]}
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Putting full part data to https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-25255eb8f693/runs/3bc23525-15ce-4712-abae-ff9c
7a9f4c23
Oct 21 09:00:54 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 21 09:00:54 pertmp01 runner DEBUG    Nothing to do.
Oct 21 09:00:54 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 21 09:00:54 pertmp01 scheduler DEBUG    Run posting finished
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Scheduled for 2016-10-22 08:40:51+00:00 - 2016-10-22 08:40:59+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/e5bad79e-4cd7-42c2-ab98-2
5255eb8f693/runs/3bc23525-15ce-4712-abae-ff9c7a9f4c23
Oct 21 09:00:55 pertmp01 scheduler DEBUG    TASK 2b55edbb-c31f-4ce6-a47a-4efadc740a88, 144 runs, try 2016-10-22 08:40:51+00:00
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Trying to schedule 2b55edbb-c31f-4ce6-a47a-4efadc740a88 for 2016-10-22 08:40:51+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/2b55edb
b-c31f-4ce6-a47a-4efadc740a88
Oct 21 09:00:55 pertmp01 scheduler DEBUG    URL is https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Posting https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88 at 2016-10-22 08:40:51+00:00
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Participant list is [u'pertmp01.switch.ch']
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Range parameters are {'start': '2016-10-22T08:40:51Z', 'end': '2016-10-22T09:00:59Z'}
Oct 21 09:00:55 pertmp01 scheduler DEBUG    1 URLs in this task
Oct 21 09:00:55 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Fetching https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88/runtimes
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Scheduled against https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Done fetching time ranges
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Time range is 2016-10-22 08:40:51+00:00 - 2016-10-22 08:43:20+00:00
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Posting lead run to https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Data {'start-time': '2016-10-22T08:40:51+00:00'}
Oct 21 09:00:55 pertmp01 runner DEBUG    Schedule change.
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Lead URL is https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88/runs/17655d07-33ce-4cf3-ab0d-8b473ca10c02
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Fetching per-participant data
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Getting part data from https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88/runs/17655d07-33ce-4cf3-ab0d-8b473ca
10c02
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Got {}
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Full part data: {"part-data-full": [{}]}
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Putting full part data to https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88/runs/17655d07-33ce-4cf3-ab0d-8b47
3ca10c02
Oct 21 09:00:55 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 21 09:00:55 pertmp01 runner DEBUG    Nothing to do.
Oct 21 09:00:55 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Run posting finished
Oct 21 09:00:55 pertmp01 scheduler DEBUG    Scheduled for 2016-10-22 08:40:51+00:00 - 2016-10-22 08:40:59+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/2b55edbb-c31f-4ce6-a47a-4efadc740a88/runs/17655d07-33ce-4cf3-ab0d-8b473ca10c02
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Received notifications.
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Got 1 rows
Oct 21 09:00:56 pertmp01 scheduler DEBUG    TASK 76ef99fb-172d-405f-bc9b-75029d248294, 170 runs, try 2016-10-21 21:00:55+00:00
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Trying to schedule 76ef99fb-172d-405f-bc9b-75029d248294 for 2016-10-21 21:00:55+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    URL is https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Posting https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294 at 2016-10-21 21:00:55+00:00
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant list is [u'pertmp01.switch.ch', u'pertmp06.switch.ch']
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp06.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Range parameters are {'start': '2016-10-21T21:00:55Z', 'end': '2016-10-21T22:01:16Z'}
Oct 21 09:00:56 pertmp01 scheduler DEBUG    2 URLs in this task
Oct 21 09:00:56 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Fetching https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294/runtimes
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Scheduled against https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Fetching https://pertmp06.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294/runtimes
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Unable: pertmp06.switch.ch cannot schedule a time for this run
Oct 21 09:00:56 pertmp01 participant-data INFO     Started
Oct 21 09:00:56 pertmp01 participant-data INFO     Started
Oct 21 09:00:56 pertmp01 runner DEBUG    Schedule change.
Oct 21 09:00:56 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 21 09:00:56 pertmp01 runner DEBUG    Nothing to do.
Oct 21 09:00:56 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Received notifications.
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Got 1 rows
Oct 21 09:00:56 pertmp01 scheduler DEBUG    TASK 76ef99fb-172d-405f-bc9b-75029d248294, 171 runs, try 2016-10-21 21:00:56+00:00
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Trying to schedule 76ef99fb-172d-405f-bc9b-75029d248294 for 2016-10-21 21:00:56+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    URL is https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Posting https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294 at 2016-10-21 21:00:56+00:00
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant list is [u'pertmp01.switch.ch', u'pertmp06.switch.ch']
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Participant task URL is https://pertmp06.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Range parameters are {'start': '2016-10-21T21:00:56Z', 'end': '2016-10-21T22:01:17Z'}
Oct 21 09:00:56 pertmp01 scheduler DEBUG    2 URLs in this task
Oct 21 09:00:56 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:56 pertmp01 scheduler DEBUG    Fetching https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294/runtimes
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Scheduled against https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:57 pertmp01 scheduler DEBUG    TEST Fetching task
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Status = 200
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Fetching https://pertmp06.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294/runtimes
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Unable: pertmp06.switch.ch cannot schedule a time for this run
Oct 21 09:00:57 pertmp01 participant-data INFO     Started
Oct 21 09:00:57 pertmp01 participant-data INFO     Started
Oct 21 09:00:57 pertmp01 runner DEBUG    Schedule change.
Oct 21 09:00:57 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 21 09:00:57 pertmp01 runner DEBUG    Nothing to do.
Oct 21 09:00:57 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Received notifications.
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Got 1 rows
Oct 21 09:00:57 pertmp01 scheduler DEBUG    TASK 76ef99fb-172d-405f-bc9b-75029d248294, 172 runs, try 2016-10-21 21:00:57+00:00
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Trying to schedule 76ef99fb-172d-405f-bc9b-75029d248294 for 2016-10-21 21:00:57+00:00 at https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:57 pertmp01 scheduler DEBUG    URL is https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405f-bc9b-75029d248294
Oct 21 09:00:57 pertmp01 scheduler DEBUG    Posting https://pertmp01.switch.ch/pscheduler/tasks/76ef99fb-172d-405

**Comment by igarny** [comment]
Here is some old output, which seemed to be clearer IMHO.
There are strange messages with DISCARDING though

Oct 19 08:48:28 pertmp01 runner DEBUG    Schedule change.
Oct 19 08:48:28 pertmp01 runner DEBUG    106782: Testing with traceroute: {"task-uuid": "e5594904-e57f-485c-a915-ea798807fc91", "participant": 0, "schedule": {"duration": "PT8S", "start": "2016-10-19T08:48:28Z"}, "participant-data": [{}], "test": {"type": "trace", "spec": {"source": "pertmp01.switch.ch", "dest": "pertmp06.switch.ch", "ip-version": 4, "hops": 64, "length": 40, "schema": 1}}, "schema": 1}
Oct 19 08:48:28 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 19 08:48:28 pertmp01 runner DEBUG    Nothing to do.
Oct 19 08:48:28 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 19 08:48:28 pertmp01 safe_run/scheduler ERROR    Restarting
Oct 19 08:48:28 pertmp01 safe_run/scheduler ERROR    Restarting
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Debug started
Oct 19 08:48:28 pertmp01 traceroute/run INFO     Started
Oct 19 08:48:28 pertmp01 traceroute/run INFO     Started
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Running traceroute -q 1 -4 -s pertmp01.switch.ch -m 64 -N 64 -n pertmp06.switch.ch 40
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Timeout is 0:00:07
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Debug started
Oct 19 08:48:28 pertmp01 traceroute/run INFO     Started
Oct 19 08:48:28 pertmp01 traceroute/run INFO     Started
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Running traceroute -q 1 -4 -s pertmp01.switch.ch -m 64 -N 64 -n pertmp02.switch.ch 40
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Timeout is 0:00:07
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Traceroute exited 0: traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets#012 1  10.0.173.64  1.420 ms
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Discarding: traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Output Line: 1 10.0.173.64 1.420 ms
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Line elements: ['10.0.173.64', '1.420', 'ms']
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Discarding:
Oct 19 08:48:28 pertmp01 traceroute/run DEBUG    Reverse-resolving IPs: ['10.0.173.64']
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Test Succeeded: {"diags": "traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets\n 1  10.0.173.64  1.420 ms\n", "error": null, "result": {"paths": [[{"ip": "10.0.173.64", "rtt": "PT0.0014S"}]], "succeeded": true, "schema": 1}, "succeeded": true, "schema": 1}
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Stored local result
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Doing lead participant duties
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Only one participant; not waiting.
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Runs are ['https://pertmp01.switch.ch/pscheduler/tasks/575ee592-9465-450d-9424-af5776da880f/runs/0dc6632e-22de-44d8-8a55-8bade7f1591b']
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Local run returned 0
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Accumulated local result
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Full result: [{"diags": "traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets\n 1  10.0.173.64  1.420 ms\n", "error": null, "result": {"paths": [[{"ip": "10.0.173.64", "rtt": "PT0.0014S"}]], "succeeded": true, "schema": 1}, "succeeded": true, "schema": 1}]
Oct 19 08:48:28 pertmp01 runner DEBUG    106783: Storing full result in https://pertmp01.switch.ch/pscheduler/tasks/575ee592-9465-450d-9424-af5776da880f/runs/0dc6632e-22de-44d8-8a55-8bade7f1591b, params={"result-full": [{"diags": "traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets\n 1  10.0.173.64  1.420 ms\n", "error": null, "result": {"paths": [[{"ip": "10.0.173.64", "rtt": "PT0.0014S"}]], "succeeded": true, "schema": 1}, "succeeded": true, "schema": 1}]}
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    REQUEST: PUT https://pertmp01.switch.ch/pscheduler/tasks/575ee592-9465-450d-9424-af5776da880f/runs/0dc6632e-22de-44d8-8a55-8bade7f1591b
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Run PUT https://pertmp01.switch.ch/pscheduler/tasks/575ee592-9465-450d-9424-af5776da880f/runs/0dc6632e-22de-44d8-8a55-8bade7f1591b
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    QUERY: SELECT EXISTS (SELECT * FROM run WHERE uuid = %s), [u'0dc6632e-22de-44d8-8a55-8bade7f1591b']
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    QUERY returned 1 rows
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Record exists; partial PUT.
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Updating result-full from {u'result-full': [{u'diags': u'traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets\n 1  10.0.173.64  1.420 ms\n', u'error': None, u'result': {u'paths': [[{u'ip': u'10.0.173.64', u'rtt': u'PT0.0014S'}]], u'succeeded': True, u'schema': 1}, u'succeeded': True, u'schema': 1}]}
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Updating result-full: JSON [{"diags": "traceroute to pertmp02.switch.ch (10.0.173.64), 64 hops max, 40 byte packets\n 1  10.0.173.64  1.420 ms\n", "error": null, "result": {"paths": [[{"ip": "10.0.173.64", "rtt": "PT0.0014S"}]], "succeeded": true, "schema": 1}, "succeeded": true, "schema": 1}]
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Updating result-full: Run  0dc6632e-22de-44d8-8a55-8bade7f1591b
Oct 19 08:48:28 pertmp01 pscheduler-api DEBUG    Updating result-full: Task 575ee592-9465-450d-9424-af5776da880f

**Comment by mfeit-internet2** [comment]
Both tasks have a combined 140 runs, all of which show successful results.  What's the problem?

I would advise against attempting to interpret the debug output without being familiar with the code that generates it.  The discard lines mean the program is functioning correctly.

**Comment by igarny** [comment]
The problem can be observed here: http://86.119.24.92/esmond/perfsonar/archive/?format=json
There are no results collected

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
For whatever reason there is another identifier in Esmond opened for the same set of hosts. http://86.119.24.92/esmond/perfsonar/archive/e6df80a0dbfb4b0fa40145d02276b9ae/

The updates I was looking for end up there.
Thanks!

**Comment by igarny** [comment]
I am not sure what was wrong, but my browser does not refresh, so I have no notion of the number of messages apperaring in the background
