### ISSUE TITLE
pscheduler tries to intelligently use reverse DNS to identify the local host

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#208]
Hi Mark,
By chance we came across a case, where because of an error with reverse DNS the measurements from a server have stopped. 

This simple mistake leads to very interesting conclusions, which I would like to verify.
Would it be correct to state, that if the server has multiple interfaces and the default interface ( with default GW )  goes down, the measurements for all interfaces initiated locally will stop. I presume this, since I see, that the task initiation is done towards the default interface.

On your procedure: My guess is that the moment you check for the PTR record of the current default interface in order to initiate locally a task, you do not check if the FQDN really matches any of the local IPs. This becomes easily a breaking point for all the measurements, since currently (on my system) pscheduler tries to open a task with a failing service url.

Regards,
Ivan

**Comment by igarny** [comment]
As Mark pointed out: related to #190

**Comment by mfeit-internet2** [comment]
It was being done with `socket.getfqdn()`.

Pushed a change to take the IP where the request arrived into account when returning the participant list.  This should help at least part of the problem.

**Comment by mfeit-internet2** [comment]
Closing; See last comment in #190.
