### ISSUE TITLE
Adjust Flask/Jinja2/Werkzeug package names

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#215]
The above were packaged for CentOS 6 and followed Red Hat's convention that the case match the upstream author's preference.

CentOS 7 added Jinja2 as `python-jinja2`, which conflicts with ours.  Because of that and Debian's all-lowercase convention:
 * Change the names of `python-Flask`, `python-Jinja2` and `python-Werkzeug` to lowercase.
 * Disable build of Jinja2 on CentOS 7

**Comment by mfeit-internet2** [comment]
Still having problems; trying conflicts.

**Comment by mfeit-internet2** [comment]
This is the situation in the repos we use:
```
        Flask   Jinja2  Werkzeug
        -----   ------  --------
EL6
  Base  N/A     2.2.1   N/A
  EPEL  0.9.7   2.6     0.8.3
  PGDG  0.11.1  N/A     0.11.11

EL7
  Base  N/A     2.7.2   N/A
  EPEL  0.10.1  N/A     0.9.1
  PGDG  0.11.1  2.8     0.11.11
```
We should be able to safely remove all three packages from our build.

To solve the dependency on the capitalized packages, a new set will be brought into the distribution that install no files.  These will be removed prior to the GA release, and we may need to require that systems upgrading from the RCs to GA remove all of pScheduler plus selected dependencies, notably the uppercase packages.

**Comment by mfeit-internet2** [comment]
This appears to have worked.  Holding open to see if there are any other problems.

**Comment by mfeit-internet2** [comment]
Further complications:

Ivan built an EL6 3.5 system, upgraded it to the nightly and failed to get a functioning pScheduler because Python can't find Jinja2.

EL7 installs `python-jinja2` with the code in `/usr/lib/python2.7/site-packages/jinja2` and it works fine.

EL6 installs `python-jinja2-26` with the code in `/usr/lib/python2.6/site-packages/Jinja2-2.6-py2.6.egg/jinja2`.  **This does not work.**

A temporary fix is to symlink the version in the `egg` directory into `site-packages` so it can be found:  `ln -s Jinja2-2.6-py2.6.egg/jinja2 /usr/lib/python2.6/site-packages`.   Since RH is unlikely A good candidate for a not-ideal-but-solves-the-problem fix would be to put this into pscheduler-server

**Comment by mfeit-internet2** [comment]
This seems to be resolved.  Closing.

**Comment by mfeit-internet2** [comment]
EL6 correction in 2f7ea752b36720ee6b10bd05f370fadaf7915eb2 needs to handle empty directories.

**Comment by mfeit-internet2** [comment]
@arlake228 Close this once you're happy with it.

**Comment by arlake228** [comment]
Looks good, tagged and working its way into staging as we speak.
