### ISSUE TITLE
logging.handlers.SysLogHandler.LOG_FTP does not exist on CentOS 6

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#220]
pscheduler will not build on CentOS 6 because it can't find logging.handlers.SysLogHandler.LOG_FTP. Readong the python 2.6. docs it should be in there, but in fact it looks like SysLogHandlers is generated from a syslog.h file somewhere and for whatever reason the stock version that ships with CentOS 6 is missing this facility. Should be an easy fix to check these facilities with hasattr. I'll assign to myself and have a fix committed shortly.

**Comment by mfeit-internet2** [comment]
We should probably consider restricting the set of available facilities to those defined by POSIX:  http://pubs.opengroup.org/onlinepubs/000095399/basedefs/syslog.h.html

**Comment by mfeit-internet2** [comment]
I'm going to re-open this for 1.1.

What we have now is fine for the time being because nothing uses any facility other than the default.  If anything uses a facility that came up `None`, there will be problems.
