### ISSUE TITLE
latencybg runs not getting archived

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#222]
After the most recent update it appears that runs from latencybg tasks are not getting archived. Other test types seem to work correctly. As far as I can tell, the latencybg runs are not even getting in the archiving database table. You can recreate by doing something like `pscheduler task --archive {...} latencybg --dest anl-owamp.es.net -t 120`.

**Comment by mfeit-internet2** [comment]
This commit appears to fix it.  The trigger that creates the archiving entries had a reference to the background scheduling class that I missed while doing the conversion to background_multi.

Close this after verifying for yourself.

**Comment by arlake228** [comment]
Verified this works. Thanks!
