### ISSUE TITLE
Feat: pscheduler archiver: "error": "401: Invalid token."

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#223]
Hi guys,

When by mistake you have the wrong token and then later you fix it, pscheduler does not realize this for the old tasks and keeps trying with the old token.

I would suggest for the cases, where the url or the token is broken, meaning the daemon sees failers, pscheduler to check in the current DB settings (all sources) and try to match against url and token to see, if an update is present. If there is an update, then to apply it across all old pscheduler-archiver tasks.

Or shall we have some psql commands in the documentation for this use case?

Regards,
Ivan

**Comment by arlake228** [comment]
Moving to perfsonar/mesh-config#37 since this is not a pscheduler issue but a mesh-config issue.
