### ISSUE TITLE
pscheduler trying to post invalid data to Esmond

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#224]
Hi guys,

It seems to me pscheduler is pushing the result from a failed test to Esmond. Of course this fails and then the task is rescheduled again and again.

Nov 11 14:34:17 psps-test2-mgmt archiver-esmond/archive DEBUG    Archiver received: {u'last-attempt': u'2016-11-11T13:34:13+01:00', u'attempts': 21, u'data': {u'url': u'http://ps-test.ctc.grnoc.iu.edu/esmond/perfsonar/archive/', u'retry-policy': [{u'attempts': 5, u'wait': u'PT60S'}, {u'attempts': 3, u'wait': u'PT5M'}, {u'attempts': 24, u'wait': u'PT60M'}], u'summaries': [{u'summary-type': u'average', u'summary-window': 86400, u'event-type': u'throughput'}], u'measurement-agent': u'ps-test.ctc.grnoc.iu.edu'}, u'result': {u'schedule': {u'duration': u'PT26S', u'start': u'2016-11-11T03:10:48+01:00'}, u'tool': {u'version': u'1.0', u'name': u'iperf3'}, u'participants': [u'psps-test2-mgmt.rrze.uni-erlangen.de', u'ps-test.ctc.grnoc.iu.edu'], u'result': {u'succeeded': False, u'error': u'iperf3 returned an error: {\n\t"start":\t{\n\t\t"connected":\t[],\n\t\t"version":\t"iperf 3.1.3",\n\t\t"system_info":\t"Linux psps-test2-mgmt.rrze.uni-erlangen.de 2.6.32-642.6.2.el6.web100.x86_64 #1 SMP Wed Oct 26 06:23:10 PDT 2016 x86_64"\n\t},\n\t"intervals":\t[],\n\t"end":\t{\n\t},\n\t"error":\t"error - unable to connect to server: Connection refused"\n}\n\n'}, u'test': {u'type': u'throughput', u'spec': {u'dest': u'ps-test.ctc.grnoc.iu.edu', u'source': u'psps-test2-mgmt.rrze.uni-erlangen.de', u'ip-version': 4, u'duration': u'PT20S', u'parallel': 1, u'schema': 1}}, u'id': u'188ec70d-4148-424a-8679-f2df99e14ddb'}}

**Comment by arlake228** [comment]
That's what it is supposed to do and nothing about that log message you shared  looks like it failed to do so. We register failed tests. That is what creates those little red dots on the graph. You can see data like you indicate registered here: http://ps-test.ctc.grnoc.iu.edu/esmond/perfsonar/archive/320769c8622c40f6902d9ad133db15fd/failures/base?limit=5
