### ISSUE TITLE
ticker ERROR Exception: InternalError: Invalid transition between states (8 to 6)

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#229]
Hi guys,

Here is what get with pshcedulre version (see at the bottom)

Nov 15 17:51:10 psps-test2-mgmt safe_run/ticker ERROR    Exception: InternalError: Invalid transition between states (8 to 6).#012CONTEXT:  SQL statement "UPDATE run#012    SET state = ru
n_state_overdue()#012    WHERE id IN (#012        SELECT id FROM run_straggler_info#012        WHERE#012            scheduling_class <> scheduling_class_background_multi()#012
AND state = run_state_running()#012            -- TODO: This interval should probably be a tunable.#012            AND upper(times) < normalized_now() - 'PT10S'::interval#012    )"#012PL/
pgSQL function run_handle_stragglers() line 21 at SQL statement#012SQL statement "SELECT run_handle_stragglers()"#012PL/pgSQL function run_maint_fifteen() line 3 at PERFORM#012SQL stateme
nt "SELECT run_maint_fifteen()"#012PL/pgSQL function ticker_fifteen() line 4 at PERFORM#012SQL statement "SELECT ticker_fifteen()"#012PL/pgSQL function ticker() line 7 at PERFORM#012#012T
raceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/tic
ker", line 121, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/ticker", line 101, in main_program#012    cursor.execute("SELECT
ticker()")#012InternalError: Invalid transition between states (8 to 6).#012CONTEXT:  SQL statement "UPDATE run#012    SET state = run_state_overdue()#012    WHERE id IN (#012        SELE
CT id FROM run_straggler_info#012        WHERE#012            scheduling_class <> scheduling_class_background_multi()#012            AND state = run_state_running()#012            -- TODO
: This interval should probably be a tunable.#012            AND upper(times) < normalized_now() - 'PT10S'::interval#012    )"#012PL/pgSQL function run_handle_stragglers() line 21 at SQL
statement#012SQL statement "SELECT run_handle_stragglers()"#012PL/pgSQL function run_maint_fifteen() line 3 at PERFORM#012SQL statement "SELECT run_maint_fifteen()"#012PL/pgSQL function t
icker_fifteen()
Nov 15 17:51:10 psps-test2-mgmt safe_run/ticker ERROR    Waiting 60.0 seconds before restarting
Nov 15 17:51:10 psps-test2-mgmt safe_run/ticker ERROR    Program threw an exception after 0:03:23.206877
Nov 15 17:51:10 psps-test2-mgmt safe_run/ticker ERROR    Exception: InternalError: Invalid transition between states (8 to 6).#012CONTEXT:  SQL statement "UPDATE run#012    SET state = ru
n_state_overdue()#012    WHERE id IN (#012        SELECT id FROM run_straggler_info#012        WHERE#012            scheduling_class <> scheduling_class_background_multi()#012
AND state = run_state_running()#012            -- TODO: This interval should probably be a tunable.#012            AND upper(times) < normalized_now() - 'PT10S'::interval#012    )"#012PL/
pgSQL function run_handle_stragglers() line 21 at SQL statement#012SQL statement "SELECT run_handle_stragglers()"#012PL/pgSQL function run_maint_fifteen() line 3 at PERFORM#012SQL stateme
nt "SELECT run_maint_fifteen()"#012PL/pgSQL function ticker_fifteen() line 4 at PERFORM#012SQL statement "SELECT ticker_fifteen()"#012PL/pgSQL function ticker() line 7 at PERFORM#012#012T
raceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/tic
ker", line 121, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/ticker", line 101, in main_program#012    cursor.execute("SELECT
ticker()")#012InternalError: Invalid transition between states (8 to 6).#012CONTEXT:  SQL statement "UPDATE run#012    SET state = run_state_overdue()#012    WHERE id IN (#012        SELE
CT id FROM run_straggler_info#012        WHERE#012            scheduling_class <> scheduling_class_background_multi()#012            AND state = run_state_running()#012            -- TODO
: This interval should probably be a tunable.#012            AND upper(times) < normalized_now() - 'PT10S'::interval#012    )"#012PL/pgSQL function run_handle_stragglers() line 21 at SQL
statement#012SQL statement "SELECT run_handle_stragglers()"#012PL/pgSQL function run_maint_fifteen() line 3 at PERFORM#012SQL statement "SELECT run_maint_fifteen()"#012PL/pgSQL function t
icker_fifteen()
Nov 15 17:51:10 psps-test2-mgmt safe_run/ticker ERROR    Waiting 60.0 seconds before restarting

possibly leads to:
Tasks: 454 total,  25 running, 426 sleeping,   0 stopped,   3 zombie
Cpu(s): 85.9%us, 12.8%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.3%hi,  0.9%si,  0.0%st
Mem:   3924552k total,  3744188k used,   180364k free,    15572k buffers
Swap:  3670012k total,   656892k used,  3013120k free,   462436k cached

a dozen of archivers are on the "top" with 3% each

[root@psps-test2-mgmt ~]# ps ax | grep archive
6647 ?        Sl    28:37 /usr/bin/python /usr/libexec/pscheduler/daemons/archiver --daemon --pid-file /var/run/pscheduler-archiver.pid --dsn @/etc/pscheduler/database/database-dsn
13372 ?        R      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/archiver/esmond/archive
13611 ?        R      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/archiver/esmond/archive
13618 ?        R      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/archiver/esmond/archive
13619 ?        R      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/archiver/esmond/archive
13622 ?        R      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/archiver/esmond/archive

[root@psps-test2-mgmt ~]# ps ax | grep archive -c
44

pscheduler-account.noarch                                                                       1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-archiver-bitbucket.noarch                                                            1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-archiver-esmond.noarch                                                               1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-archiver-failer.noarch                                                               1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-archiver-syslog.noarch                                                               1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-bundle-full.noarch                                                                   1.0-1.15.rc2.el6                                                         @Internet2-staging
pscheduler-core.noarch                                                                          1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-rpm.noarch                                                                           1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-server.noarch                                                                        1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-idle.noarch                                                                     1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-idlebg.noarch                                                                   1.0-0.15.rc2.el6                                                         @Internet2-staging
pscheduler-test-idleex.noarch                                                                   1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-latency.noarch                                                                  1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-latencybg.noarch                                                                1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-rtt.noarch                                                                      1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-simplestream.noarch                                                             1.0-0.17.rc2.el6                                                         @Internet2-staging
pscheduler-test-throughput.noarch                                                               1.0-0.17.rc2.el6                                                         @Internet2-staging

**Comment by mfeit-internet2** [comment]
This should no longer be a problem now that the database has been optimized.
