### ISSUE TITLE
Add to what comes out of 'result'

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#232]
Add a switch to the `result` command that will dump out the diagnostics and anything else useful.

**Comment by igarny** [comment]
Just to be on the same page.
Here is a view on bwctl results: https://drive.google.com/open?id=0BwOma9C4hovwZlhweHd5LTctd2M
The info in green I am missing. The info in yellow...well is for the lazy people.

**Comment by mfeit-internet2** [comment]
Covered by f5f582fa47c3ec4308f7888b819b63c26bd0041a
