### ISSUE TITLE
JSON validator doesn't pass IPv6 IPs as valid host names.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#233]
Bill Owens observed this:
```
2016/10/06 16:21:32 (2915) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for
creation, skipping test: 400 BAD REQUEST: At /source: u'2620:f:0:914::3' is not a 'host-name'
```
Need to adjust the code in `jsonval.py` so it takes IPv6 IPs as well.

**Comment by mfeit-internet2** [comment]
This may be related to meshconfig; can't make the string not validate when sent straight to the validator.

**Comment by mfeit-internet2** [comment]
Can't reproduce with current code.  Closing.

**Comment by owens-bill** [comment]
Mark, this is the problem I mentioned at the I2 meeting this week; it appears to still be present in the release code:

2017/04/27 10:29:50 (3145) WARN> perfsonar_meshconfig_agent:430 main:: - Problem adding test, continuing with rest of config: 500 Can't connect to 2620:f:0:915::3: Can't connect to 2620:f:0:915::3

Name or service not known at /usr/share/perl5/LWP/Protocol/http.pm line 51.
