### ISSUE TITLE
better error message 

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#236]
I know that nuttcp is not supported in backwards compatibility mode, but could this maybe give a error message that indicates that? (dest host in this example is a 3.5 host)

pscheduler task --tool nuttcp throughput --omit 5 --duration PT20S --dest slac-pt1.es.net
Submitting task...
Unable to post task: POST https://antg-staging.es.net/pscheduler/tasks returned 422: Unable to complete request: Couldn't find a tool in common among the participants.

**Comment by mfeit-internet2** [comment]
Architecturally, that's a bit difficult to do.  The system shops the test spec around to the tools on each participant (all that can run the test or just those specified on the command line).  Each says whether or not it can run the test, and from that a list of those in common and their preference values are distilled down to a winner.  If there are no tools in common among the participants that can run the test, you get the `Couldn't find a tool in common...` message.

Would a wording change help?

The backward compatibility stuff was grafted onto the parts where the list of participants is determined and that parts of the tools involved to make it work.  Nobody involved thinks it's pretty, and we're all looking forward to getting it out of the code base.  Given that it has a lifespan of 12 months after the GA release, I'm not inclined to spend a huge amount of time making the backward-compatibility features user-friendly, especially if it involves doing archtecturally-kinky things.  The goal here is to allow a smooth transition while encouraging people to switch to the new tools so we can retire BWCTL for good.

**Comment by daldoyle** [comment]
Would it make sense as a temporary measure to just "hard code" some knowledge into pscheduler? Just add onto that error message something to the effect of "if type == 'throughput': error_message += "It looks like you're trying to run a throughput test. If the other side is not running pscheduler, please don't specify --tool." It's not really an architectural change, and it's a simple hack that can be removed in 12mo or whatever.

I think this could go a long ways towards helping user friendliness and a smoother transition.

Dan Doyle
GlobalNOC Software Developer
1-812-856-3892
daldoyle@globalnoc.iu.edu

**Comment by mfeit-internet2** [comment]
If we do this, see #107.

**Comment by daldoyle** [comment]
I believe this is dealt with in https://github.com/perfsonar/pscheduler/compare/2206786c9a58...94ffff4e6cc0
