### ISSUE TITLE
possible to give better error message

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#237]
While doing a typoed hostname, I got this odd error. I'm not sure if its possible to detect when something other than pscheduler is listening on port 443:

```
pscheduler task throughput  --dest slac-pt1.se.net
Submitting task...
Unable to determine the lead participant: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
```

**Comment by mfeit-internet2** [comment]
Added full detection of whether or not pScheduler is available on the participants.

In the case of your typo, it looks like se.net resolves wildcards and connections to the IP hang.  I've added safeguards so those connections don't sit too long.
