### ISSUE TITLE
stalled processes

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#238]
Hi guys,

I started with

>> service [pscheduler-archiver, pscheduler-scheduler] stop
[root@psps-test2-mgmt ~]# pscheduler internal reset

WARNING

You are about to obliterate the contents of the pScheduler database on
this host.  Please confirm this by typing today's date in YYYY-MM-DD
format at the prompt below.

Confirm (YYYY-MM-DD): 2016-11-22

Resetting database...ERROR:  database "pscheduler" is being accessed by other users
DETAIL:  There is 1 other session using the database.

**Checking processes:**
[root@psps-test2-mgmt ~]# ps ax | grep psched
 2070 ?        Ss     0:19 postgres: pscheduler pscheduler 127.0.0.1(54190) SELECT
17752 pts/0    S+     0:00 /bin/sh /usr/libexec/pscheduler/internals/reset
17810 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57788) UPDATE waiting
17874 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17884 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17886 pts/0    S+     0:00 cat /usr/share/pscheduler/database-build.sql
17915 ?        Ss     0:00 postgres: postgres pscheduler [local] DROP TRIGGER waiting
18150 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57802) idle
18151 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57804) UPDATE waiting
18711 pts/1    S+     0:00 grep psched
25271 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/test/throughput/participants

I assume pschedID: 57788 blocks the operation.

**I have tried all:**
service [pscheduler-archiver, pscheduler-runner, pscheduler-scheduler, pscheduler-ticker] stop

**There were no powstream processes. I have even owamp restarted.**

[root@psps-test2-mgmt ~]# grep 57788 /var/log/messages | grep "Nov 22"
Nov 22 02:09:04 psps-test2-mgmt owampd[7279]: FILE=sapi.c, LINE=303, Connection to ([psps-test2-mgmt.rrze.uni-erlangen.de]:861) from ([ma-dev2.bldc.grnoc.iu.edu]:57788)
Nov 22 02:09:04 psps-test2-mgmt owampd[7279]: FILE=sapi.c, LINE=303, Connection to ([psps-test2-mgmt.rrze.uni-erlangen.de]:861) from ([ma-dev2.bldc.grnoc.iu.edu]:57788)
Nov 22 02:09:04 psps-test2-mgmt owampd[7279]: FILE=sapi.c, LINE=466, ControlSession([psps-test2-mgmt.rrze.uni-erlangen.de]:861) accepted from userid(nil):([ma-dev2.bldc.grnoc.iu.edu]:57788)
Nov 22 02:09:04 psps-test2-mgmt owampd[7279]: FILE=sapi.c, LINE=466, ControlSession([psps-test2-mgmt.rrze.uni-erlangen.de]:861) accepted from userid(nil):([ma-dev2.bldc.grnoc.iu.edu]:57788)

**IMHO the process had stalled and there is nothing to clean it**

**Comment by igarny** [comment]
Hmm in fact it was another process:

[root@psps-test2-mgmt ~]# kill 17810
[root@psps-test2-mgmt ~]#
[root@psps-test2-mgmt ~]#
[root@psps-test2-mgmt ~]# ps ax | grep psch
 2070 ?        Ss     0:19 postgres: pscheduler pscheduler 127.0.0.1(54190) SELECT
17752 pts/0    S+     0:00 /bin/sh /usr/libexec/pscheduler/internals/reset
17874 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17884 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17886 pts/0    S+     0:00 cat /usr/share/pscheduler/database-build.sql
17915 ?        Ss     0:00 postgres: postgres pscheduler [local] DROP TRIGGER waiting
18150 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57802) idle
18151 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57804) UPDATE waiting
18875 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/daemons/scheduler --daemon --pid-file /var/run/pscheduler-scheduler.pid --dsn @/etc/pscheduler/database/database-dsn
18876 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(58182) SELECT waiting
19151 pts/1    S+     0:00 grep psch
25271 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/test/throughput/participants


**[root@psps-test2-mgmt ~]# kill 2070**
[root@psps-test2-mgmt ~]# ps ax | grep psch
 2070 ?        Ss     0:19 postgres: pscheduler pscheduler 127.0.0.1(54190) SELECT
17752 pts/0    S+     0:00 /bin/sh /usr/libexec/pscheduler/internals/reset
17874 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17884 pts/0    S+     0:00 /bin/sh /usr/bin/postgresql-load --role pscheduler /usr/share/pscheduler/database-build.sql
17886 pts/0    S+     0:00 cat /usr/share/pscheduler/database-build.sql
17915 ?        Ss     0:00 postgres: postgres pscheduler [local] DROP TRIGGER waiting
18150 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57802) idle
18151 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(57804) UPDATE waiting
18875 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/daemons/scheduler --daemon --pid-file /var/run/pscheduler-scheduler.pid --dsn @/etc/pscheduler/database/database-dsn
18876 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(58182) SELECT waiting
19184 pts/1    S+     0:00 grep psch
25271 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/test/throughput/participants
**[root@psps-test2-mgmt ~]# kill -9 2070**
[root@psps-test2-mgmt ~]# ps ax | grep psch
18875 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/daemons/scheduler --daemon --pid-file /var/run/pscheduler-scheduler.pid --dsn @/etc/pscheduler/database/database-dsn
19390 ?        Ss     0:00 postgres: pscheduler pscheduler 127.0.0.1(58474) idle
19401 pts/1    S+     0:00 grep psch
25271 ?        S      0:00 /usr/bin/python /usr/libexec/pscheduler/commands/../classes/test/throughput/participants

**Comment by mfeit-internet2** [comment]
I can't duplicate this.  Also, no need to stop the services when performing a reset.

Closing.
