### ISSUE TITLE
iperf3 test fails because participant-data is None

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#241]
Running a throughput test between antg-staging and ma-dev2.bldc results in a run with the following error (see https://antg-staging.es.net/pscheduler/tasks/24b3a2f6-d7db-4efd-aff3-0dfcfd54cb92/runs/27d97429-f7a7-40ad-bb3c-ec804501c338):
`
{"result-href": "https://antg-staging.es.net/pscheduler/tasks/24b3a2f6-d7db-4efd-aff3-0dfcfd54cb92/runs/27d97429-f7a7-40ad-bb3c-ec804501c338/result", "end-time": "2016-12-02T07:17:39-08:00", "participant": 0, "errors": "Traceback (most recent call last):\n  File \"/usr/libexec/pscheduler/commands/../classes/tool/iperf3/run\", line 42, in <module>\n    if len(participant_data) != 2:\nTypeError: object of type 'NoneType' has no len()\n", "participant-data": {}, "result-merged": null, "participant-data-full": [{}, {"server_port": 5201}], "state": "failed", "state-display": "Failed", "result-full": [null, null], "participants": ["antg-staging.es.net", "ma-dev2.bldc.grnoc.iu.edu"], "href": "https://antg-staging.es.net/pscheduler/tasks/24b3a2f6-d7db-4efd-aff3-0dfcfd54cb92/runs/27d97429-f7a7-40ad-bb3c-ec804501c338", "result": null, "task-href": "https://antg-staging.es.net/pscheduler/tasks/24b3a2f6-d7db-4efd-aff3-0dfcfd54cb92", "duration": "PT16S", "start-time": "2016-12-02T07:17:23-08:00", "clock-survey": [{"source": "ntp", "offset": -0.009156942367553711, "synchronized": true, "reference": "secondary reference (2) from 198.129.254.218", "time": "2016-12-02T07:18:11.332524-08:00"}, {"source": "ntp", "offset": 6.437301635742188e-05, "synchronized": true, "reference": "secondary reference (2) from 140.182.45.75", "time": "2016-12-02T15:18:11.700778+00:00"}]}`
`

The error looks like some more type checking is maybe needed, but its also strange that participant-data is None.

**Comment by mfeit-internet2** [comment]
I've bumped into that once or twice but haven't been able to replicate it reliably.  The `run` methods should probably fail more gracefully if they don't get the input they expect.

**Comment by arlake228** [comment]
I was getting this pretty consistently prior to the ESnet hosts getting bumped to 4 cores, then it went away. Makes me wonder if it is some type of race condition that is more likely to rear its head on a loaded machine. For example, if the runner is picking up a task before the local pscheduler has had a chance to merge the participant data from the remote side.

**Comment by mfeit-internet2** [comment]
This is probably a case of one of the scheduler being unable to fetch one of the participants' data before run time.  Should probably have the runner fail on runs with incomplete participant data.

**Comment by daldoyle** [comment]
I can't really reproduce this, but looking through the code I cannot see how this could possibly be the tool's fault. The `participant-data` for iperf3 will always exit with some data, even if it's an empty object, unless one of the participants is flagged as > 1 (which also shouldn't be possible). Talked with Mark and he's going to look into this upstream.

**Comment by arlake228** [comment]
Can't reproduce, closing.
