### ISSUE TITLE
`pscheduler internal reset` fails on Debian

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#244]
`pscheduler internal reset` fails on Debian because it cannot find the `postgresql-load` command. This is installed by the postgresql-load package Mark built for pScheduler. I believe it was never ported to Debian because it is doing its own DB setup. We should either port it or find a way to make `pscheduler internal reset` work without it.

**Comment by vvidic** [comment]
Ack, we need to rewrite this for Debian.

**Comment by mfeit-internet2** [comment]
You'll probably want to package `postgresql-load` for Debian anyway since I'm in the middle of writing what I described in #110, and it will use that.

You can still load the database at install time by whatever means you like.

**Comment by vvidic** [comment]
``reset`` should be patched now, I will test more after the postgres rebuild is finished...

**Comment by vvidic** [comment]
The ``reset`` command is functional with the ``pscheduler-server`` package from snapshot repo, so closing here.
