### ISSUE TITLE
daemon file descriptor leak

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#245]
I noticed today on ma-dev2.bldc the following in /var/log/messages

> Dec 12 15:34:09 ma-dev2.bldc.grnoc.iu.edu safe_run/ticker ERROR    Exception: IOError: [Errno 24] Too many open files: '/etc/pscheduler/database/database-dsn'#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/l
> ibexec/pscheduler/daemons/ticker", line 100, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/ticker", line 69, in main_program#012    db = pscheduler.pg_connection(dsn)#012  File "/usr/lib/python2.6/site-packages/pscheduler/db.py", line 25, in pg_connection#012    dsn = string_from_file(dsn)#012  File "/usr/lib/python2.6/site-packages/pscheduler/filestring.py", line 22, in string_from_file#012    with open(string[1:], 'r') as content:#012IOError: [Errno 24] Too many open files: '/etc/pscheduler/database/database-dsn'

Diving into it, it looks like that process has 1024 file descriptors which was the default ulimit settings on that machine. After restarting the process, the file descriptors went down to around 10 or so but occasionally would rise coincident with this in the logs:

> Dec 12 15:42:13 ma-dev2.bldc.grnoc.iu.edu safe_run/scheduler ERROR    Exception: ConnectionError: ('Connection aborted.', error(101, 'Network is unreachable'))#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 453, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 409, in main_program#012    run_post(url, trynext, log)#012  File "/usr/libexec/pscheduler/daemons/scheduler", line 166, in run_post#012    r = requests.get(runtime_url, params=range_params, verify=False)#012  File "/usr/lib/python2.6/site-packages/requests/api.py", line 68, in get#012    return request('get', url, **kwargs)#012  File "/usr/lib/python2.6/site-packages/requests/api.py", line 50, in request#012    response = session.request(method=method, url=url, **kwargs)#012  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 464, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/usr/lib/python2.6/site-packages/requests/sessions.py", line 576, in send#012    r = adapter.send(request, **kwargs)#012  File "/usr/lib/python2.6/site-packages/requests/adapters.py", line 415, in send#012    raise ConnectionError(err, request=request)#012ConnectionError: ('Connection aborted.', error(101, 'Network is unreachable'))

It seems like there may be some error being trapped but is leaving a filehandle open uncleanly.

**Comment by mfeit-internet2** [comment]
All fixed.  The `Log` class wasn't undoing the logging setup when it was destroyed, leaving a socket open each time.
