### ISSUE TITLE
pScheduler stress testing fails

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#246]
I wrote a simple script to see when/where things fail (see below).

It got about 30 loops in before starting to give these errors:

Unable to determine the lead participant: Can't find pScheduler or BWCTL on None
Run on server was never populated.

#!/bin/bash
set -x
RCVHOST=antg-staging.es.net
for ((i=0; i < 100 ; i++))
do
    pscheduler task --slip PT60M throughput --dest $RCVHOST &
    sleep 1
    pscheduler task latency --dest $RCVHOST --packet-count 1000 --packet-interval .01 &
    sleep 1
    pscheduler task trace --dest  $RCVHOST &
    sleep 2
done

**Comment by mfeit-internet2** [comment]
Most of this can be attributed to the number of processes and threads in the web server in its default configuration.  The numbers have been increased for the time being pending observation of any impact it may have on smaller systems.
