### ISSUE TITLE
Notification mechanism for failing tests

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#248]
Add code that will do an HTTP(S) POST of data when a run or archiving fails.  This could leverage the `http_queue` table.

**Comment by igarny** [comment]
Hi Mark,

Previously (like a month ago) I had this in my logs:
`
Nov 22 16:46:50 psps-test2-mgmt runner DEBUG    2: Runs are ['https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/6433aa06-3708-4d85-8749-7562864fe637/runs/baccb5df-266c-40a4-a241-a66016c

Nov 22 16:53:43 psps-test2-mgmt archiver DEBUG    1: Failed: baccb5df-266c-40a4-a241-a66016c0fdbf to esmond: {"retry": "PT60S", "succeeded": false, "error": "401: Authentication credentials were not provided."}
`

Now I am not able to find the first event, which makes it very difficult/impossible to identify the exact task

Off topic:
I was not looking for anything fancy as code implementation with my inquiry on Slack. My question was if there is a way to activate these again.

**Comment by arlake228** [comment]
JQ transforms can handle this when done.
