### ISSUE TITLE
Remotely-Supervised Archiving

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#252]
This issue perfsonar/mesh-config#46 and the discussion in Slack before it reveal a possible problem with results recollection.
Problem is foreseen in the cases, where the measurement agent (M.Agent) is not the test lead. In these cases the test is performed from the remote host as source to the M.Agent.
The current concept for pS 4.0 requires:

1. the M.Agent submits MArchive connection details to the SOURCE host (test lead)
2. puts the responsibility on the SOURCE host = test LEAD to submit to the MArchive.

In the general case, where measurements are performed in the same organization it is acceptable and possible to defer the task of results submission to the remote system. But in the inter-domain use case there are many problems:

1. The defined scheme will not work in a environment, where the Esmond authorization is based on IP
2. The defined scheme presumes, that the MArchive of the initiating organization (the one of M.Agent) is available to the foreign organization of the SOURCE host = test LEAD. 
-- This in organizations with tight security is not valid
-- in organizations which apply virtualization is very likely not valid
-- requires needless sharing of MArchive credentials of initiator organization to a foreign orgnization

Proposal:
1. It is a fact that the pscheduler negotiation happens before and in order to perform a measurement
2. during the test negotiation process both test participants agree on their roles and thus it is clear, which participant is the test initiator M.Agent and which is the SOURCE host = test LEAD.
3. pS needs to have a process that makes sure, that after the end of the test the results are being collected/pushed at the test initiator M.Agent, which presumably has all the credentials and required connectivity to the MArchive of its organization. This can happen based on either push or pull mechanisms, preferably **push**.
-- PUSH: after the test finishes (with results or error) the outcome is submitted by the SOURCE host pscheduler archiver to the M.Agent pscheduler based on the connection details established during the test negotiation in phase 1
-- PULL: since the M.Agent host is aware of the test negotiation parameters, it is also aware of:
1. When the test results should be available. 
2. M.Agent also knows the test identifier, which is shared during the test negotiation.
Based on this information M.Agent would be able to retrieve the results (outcome of test) from the SOURCE host.

Benefits of the PULL mechanism:
1. it would require less traffic and less needless attempts
2. the results submission can be postponed based on SOURCE host availability / schedule

**Comment by mfeit-internet2** [comment]
(Random thoughts for when we start looking at this.)

This wouldn't be difficult.  On slack, I had suggested setting up proxies for archivers, which in retrospect is more difficult than it's worth.

The API is good enough that we could put together something that submits and supervises tasks on other systems and does the archiving after they complete.  It would work something like this:

1.  Originator strips all archiving info from the original task and submits the stripped version to the lead participant.
1.  Lead participant returns task identifier T.
1.  Originator looks for a run R to be scheduled for T, repeating the process periodically if none is found.
1.  Originator waits until R's completion time has passed.
1.  Originator polls the lead participant for a result, repeating periodically if none is found.
1.  Originator carries out the archiving as if it had been run locally using the archiving specifications and the result.

Supervision would be a standalone process, and we can put something in the API to submit a task to be supervised instead of the default behavior.

**Comment by igarny** [comment]
Another perspective:
Below is the negotiation and the communication in between 2 pS 4.0.rc kit instances over a trace test (single participant). Since it is run through CLI, it does not involve meshconfig.
In this example the test is initiated from the remote host to an interface on the local system.

The communication and the received results demonstrate, that there is already a mechanism to recollect the results of a single participant test with lead participant at the remote site at the destination host (M.Agent).
The only missing part in the whole picture is the service, that forwards the results on the initiator M.Agent side to a specified MA. Still I believe this function is fulfilled by the pscheduler archiver process.

IMHO utilizing already present functionality would simplify the solution. Of course it is possible, that I am missing functional dependencies or the complexity of the communication with meshconfig.

The example follows:

pscheduler task --debug trace --source perfsonar-lab-vm.ilab.umnet.umich.edu --ip-version 4 --dest psps-test2-mgmt.rrze.uni-erlangen.de
2017-01-11T16:30:25 Debug signal ignored; already not debugging
2017-01-11T16:30:25 Debug discontinued
2017-01-11T16:30:25 Assistance is from 127.0.0.1
2017-01-11T16:30:25 Using slip of PT5M
2017-01-11T16:30:25 Converting to spec via https://127.0.0.1/pscheduler/tests/trace/spec
Submitting task...
2017-01-11T16:30:28 Fetching participant list from https://127.0.0.1/pscheduler/tests/trace/participants
2017-01-11T16:30:28 {"dest": "psps-test2-mgmt.rrze.uni-erlangen.de", "source": "perfsonar-lab-vm.ilab.umnet.umich.edu", "ip-version": 4, "schema": 1}
2017-01-11T16:30:30 https://127.0.0.1/pscheduler/tests/trace/participants, status 200
2017-01-11T16:30:30 Got participants: {u'participants': [u'perfsonar-lab-vm.ilab.umnet.umich.edu']}
2017-01-11T16:30:30 Lead is perfsonar-lab-vm.ilab.umnet.umich.edu, null reason is No reason provided.  (Server is running old software.)
2017-01-11T16:30:30 Pinging perfsonar-lab-vm.ilab.umnet.umich.edu
2017-01-11T16:30:30 perfsonar-lab-vm.ilab.umnet.umich.edu is up
2017-01-11T16:30:30 Posting task to https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks
2017-01-11T16:30:30 Data is {"test": {"type": "trace", "spec": {"dest": "psps-test2-mgmt.rrze.uni-erlangen.de", "source": "perfsonar-lab-vm.ilab.umnet.umich.edu", "ip-version": 4, "schema": 1}}, "schedule": {"slip": "PT5M"}, "schema": 1}
Task URL:
https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19
2017-01-11T16:30:35 Posted https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19
Fetching first run...
2017-01-11T16:30:35 Fetching https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19/runs/first
2017-01-11T16:30:37 Handing off: pscheduler watch --format text/plain --debug https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19
2017-01-11T16:30:37 Debug signal ignored; already not debugging
2017-01-11T16:30:37 Debug discontinued
2017-01-11T16:30:37 Fetching https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19

Next run:
https://perfsonar-lab-vm.ilab.umnet.umich.edu/pscheduler/tasks/a3ec0c0e-74c7-466e-a4c2-70ac4fc50d19/runs/0e287ee9-cb7e-4ed0-846e-e21cb67a8509
Starts 2017-01-11T10:30:45-05:00 (~5 seconds)
Ends   2017-01-11T10:30:53-05:00 (~7 seconds)
Waiting for result...

1       198.111.226.1 AS237 2.2 ms
          MERIT-AS-14 - Merit Network Inc., US
2       198.111.225.56 AS237 0.2 ms
          MERIT-AS-14 - Merit Network Inc., US
3       198.111.225.4 AS237 0.3 ms
          MERIT-AS-14 - Merit Network Inc., US
4       v-pkt-arbl.r-bin-arb.umnet.umich.edu. (192.122.183.73) AS237 0.2 ms
          MERIT-AS-14 - Merit Network Inc., US
5       irbx93.glc-lan3.mich.net. (198.108.23.217) AS237 2.3 ms
          MERIT-AS-14 - Merit Network Inc., US
6       ae1x32.msu6.mich.net. (198.108.23.42) AS237 3 ms
          MERIT-AS-14 - Merit Network Inc., US
7       ae1x22.wsu5.mich.net. (198.108.23.51) AS237 10 ms
          MERIT-AS-14 - Merit Network Inc., US
8       ae1x22.sfld-cor-123net.mich.net. (198.108.23.50) AS237 3 ms
          MERIT-AS-14 - Merit Network Inc., US
9       v0x1004.rtr.wash.net.internet2.edu. (192.122.183.10) AS237 11.9 ms
          MERIT-AS-14 - Merit Network Inc., US
10      et-4-1-0.4072.rtsw.wash.net.internet2.edu. (198.71.45.5) AS11537 26.1 ms
          ABILENE - Internet2, US
11      internet2.mx1.lon.uk.geant.net. (62.40.124.44) AS20965 94.5 ms
          GEANT The GEANT IP Service, GB
12      ae0.mx1.ams.nl.geant.net. (62.40.98.81) AS20965 103.1 ms
          GEANT The GEANT IP Service, GB
13      ae1.mx1.ham.de.geant.net. (62.40.98.61) AS20965 109.5 ms
          GEANT The GEANT IP Service, GB
14      dfn-gw.mx1.ham.de.geant.net. (62.40.112.146) AS20965 118.9 ms
          GEANT The GEANT IP Service, GB
15      cr-erl2-be7.x-win.dfn.de. (188.1.146.209) AS680 127.7 ms
          DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE
16      kr-erl56-0.x-win.dfn.de. (188.1.234.230) AS680 128.7 ms
          DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE
17      131.188.20.253 AS680 127.5 ms
          DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE
18      reliant.gate.uni-erlangen.de. (131.188.20.202) AS680 138.1 ms
          DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE
19      psps-test2-mgmt.rrze.uni-erlangen.de. (131.188.81.85) AS680 127.4 ms
          DFN Verein zur Foerderung eines Deutschen Forschungsnetzes e.V., DE

No further runs scheduled.

**Comment by tonin** [comment]
@igarny do you know of existing mesh deployments that would break because of this issue?

**Comment by igarny** [comment]
I believe we have discussed this already. The only IP based authorization mesh I have access to the the pSmall project.
But if you are asking whether there are other IP based authorization meshes, then probably it would be a better idea to ask the perfsonar-user list: perfsonar-user-request@internet2.edu

Here is an example:
<h4>
From: perfsonar-user-request@internet2.edu [mailto:perfsonar-user-request@internet2.edu] On Behalf Of Andreas Demetriou <br>
Sent: Dienstag, 24. Januar 2017 13:07 <br>
To: perfsonar-user@internet2.edu <br>
Subject: [perfsonar-user] MA IP authentication <br>
</h4>

Still I have no idea about the pS organization of Andreas.

**Comment by igarny** [comment]
meshconfig related issue, hopefully deprecated by psconfig
