### ISSUE TITLE
powstream plugin: numerous events: "powstream exited with no errors ....."

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#259]
Hi Andy,

The issue might be related to this: https://github.com/perfsonar/mesh-config/issues/43
I am getting thousands of powstream errors per day since 16.Jan (the day the IPv6 misconfig was fixed)
"tool-powstream/run ERROR    powstream exited with no errors but should have kept running, will attempt restart"

[root@psps-test2-mgmt ~]# egrep "^Jan 17 .+ powstream exited with no errors but should have kept running, will attempt restart" /var/log/pscheduler/pscheduler.log -c
2056

Nevertheless the measurements appear to be continuous.
probably can be considered as an enhancement, if the event is changed from ERROR to WARN

Regards,
Ivan

**Comment by mfeit-internet2** [comment]
This seems to be a regular enough occurrence that it might be worth not logging.
