### ISSUE TITLE
BUG:  task: latency parameter: bucket-width

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#264]
Hi,
this report is from Hakan 

<h2>problem</h2>
hakan@Virtualhost:~$ pscheduler task latency --packet-count 10 --bucket-width 2 --dest 172.16.15.121 Submitting task...
Unable to post task: POST https://Virtualhost/pscheduler/tasks returned
500: Invalid test specification: Traceback (most recent call last):
   File
"/usr/lib/pscheduler/commands/../classes/test/latency/spec-is-valid",
line 17, in <module>
     valid, message = spec_is_valid(json)
   File "/usr/lib/pscheduler/classes/test/latency/validate.py", line 204, in spec_is_valid
     return json_validate(json, REQUEST_SCHEMA)
   File "/usr/lib/python2.7/dist-packages/pscheduler/jsonval.py", line 691, in json_validate
     '/' + ('/'.join([str(x) for x in ex.absolute_path])),
AttributeError: 'ValidationError' object has no attribute 'absolute_path'

<h2>Success</h2>
hakan@Virtualhost:~$ owping -c 10 -b 2 172.16.15.121 Approximately 4.1 seconds until results available

--- owping statistics from [172.16.15.120]:9097 to [172.16.15.121]:9049 ---
SID:    ac100f79dc2c5f933d8f0c77cb239c92
first:  2017-01-20T11:06:12.066
last:   2017-01-20T11:06:13.402
10 sent, 0 lost (0.000%), 0 duplicates
one-way delay min/median/max = 273/2e+03/273 ms, (unsync) one-way jitter = 0 ms (P95-P50) TTL not reported no reordering

--- owping statistics from [172.16.15.121]:9102 to [172.16.15.120]:9464 ---
SID:    ac100f78dc2c5f92f9259558b49b4c3f
first:  2017-01-20T11:06:12.126
last:   2017-01-20T11:06:12.949
10 sent, 0 lost (0.000%), 0 duplicates
one-way delay min/median/max = -272/-2e+03/-272 ms, (unsync) one-way jitter = 0 ms (P95-P50) TTL not reported no reordering

**Comment by mfeit-internet2** [comment]
See #262

**Comment by mfeit-internet2** [comment]
Closing.  Ivan confirmed that Hakan was running old software.
