### ISSUE TITLE
Update Debian package for pscheduler-bundle-full to match list in CentOS

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#267]
Currently there is some orange in the dashboard between 4.0 debian hosts and 3.5 hosts (coincidentally also debian, but could be to a CentOS 3.5 host as well). This is because pscheduler-bundle-full does not include pscheduler-tool-bwctliperf3 in its dependency list, which is needed for backward compatibility. Installing the package by hand gets rid of the orange. We should review the Debian package and make sure it is not missing anything else and update it accordingly.

**Comment by vvidic** [comment]
Depends list updated in debian/jessie and debian/wheezy branches and is in snapshot now.
