### ISSUE TITLE
Determine whether we can use stock python-dns instead of custom python-dnspython

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#271]
On ESnet our measurement hosts have python-dns already installed which conflicts with python-dnspython package built by pscheduler. It looks like both flavors of CentOS have python-dns though the CentOS 6 version is 0.11 compared to 0.12. Need to verify whether that matters or not.

**Comment by mfeit-internet2** [comment]
This may be a non-issue.

pScheduler depends on `python-dnspython`, which is a different package from `python-dns` and `python-dnspython`.  Further complicating things is that `python-dnspython` imports from `dns.*` and I think `python-dns` does, too.

`python-dnspython` isn't in the standard repos.

**Comment by arlake228** [comment]
They look to be the same package given that installing both creates file conflicts, they have similar/same version (depending on OS) and the URL given from `yum info python-dns` on both CentOS 6 and CentOS 7 point at http://www.dnspython.org/

**Comment by mfeit-internet2** [comment]
Oops, I think you're right.  I’ll check the versions on those packages and see if we can jettison the custom version.

We're going to have another Jinja2-style thing where the package we built will have to be removed.  I think it could be mitigated by making our package say it provides `python-dns`, change the dependency to that and then get rid of it before GA.  I'll do that.

**Comment by arlake228** [comment]
Sounds like a plan, thanks Mark.

**Comment by mfeit-internet2** [comment]
Updated as described.  This was another example of the Red Hat packagers not following their own naming conventions.

Holding open for 1.0 release prep.  For that:

 * Remove `python-dnspython` directory
 * Remove the package from `scripts/RPM-BUILD-ORDER.m4`
