### ISSUE TITLE
Limits: have a limit on the number of retries for a failing test

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#274]
My call here is related to #273 . I am observing the same excessive rate of failing tests.
This brings me to the feature request of having the ability to define the number of attempts for a test, which then will lead to the cancellation of the occurrence....meaning postpone for the next time slot in the future.
It would be nice if there if this comes as a limits feature and there are reasonable defaults.

**Comment by arlake228** [comment]
Not a good way to do this, less of a problem with excessive runs fixed,.
