### ISSUE TITLE
Runner not ignoring disabled tests

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#275]
I noticed on test-pt1.es.net that its continuing to run some tests that are no longer enabled. Example: https://test-pt1.es.net/pscheduler/tasks/a18413b8-9dee-43c1-8465-ece455d1a60f?detail=1 is running at the time of this issue creation. If I stop the pscheduler-runner the processes stop but when I start it again, the test fires up a new set of processes.

**Comment by mfeit-internet2** [comment]
Fixed.  Note that this does not actually stop anything but will prevent backgrounders from being restarted if the runner restarts.
