### ISSUE TITLE
Debian: dbconfig-common fills up /var/cache/dbconfig-common/backup/

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#279]
When doing a database schema update during installation of a new version of the pscheduler-server package, dbconfig-common automatically does a backup (dump) of the current DB to `/var/cache/dbconfig-common/backups/`  This is nice and useful.

However, the backups of pscheduler-server DB are around 1GB on a medium size mesh (the testing mesh) and then the backups are quickly filling up the disk space of the server. I'm not sure there is an automatism to remove the old and outdated backups, but we should do something otherwise the auto-upgrade fails when these backups are filling up the disk space.

**Comment by mfeit-internet2** [comment]
There's probably no need to back up the pScheduler database.  PostgreSQL is good about recovering from crashes, and odds are good that the database gets clobbered, the backups will, too.

The only other way to make the database smaller is to trim the retention time back from seven days.   (Can't do this from the outside at the moment.)

**Comment by tonin** [comment]
`dbconfig-common` is doing this automatically if the sysadmin agrees to it (or with unattended upgrades).  The message it displays is the following:

> According to the maintainer for this package, database upgrade operations need to be performed on pscheduler-server.  Typically, this is due to changes in how a new upstream version of the package needs to store its data. 
> 
> If you want to handle this process manually, you should refuse this option.  Otherwise, you should choose this option. During the upgrade, a backup of the database will be made in /var/cache/dbconfig-common/backups, from which the database can be restored in the case of problems.
>                                                                 
> Perform upgrade on database for pscheduler-server with dbconfig-common?

We have to look if there's a configuration option to disable those backups or add a script bit that removes the previous backups before upgrading.

**Comment by vvidic** [comment]
Pushed a change to remove all but last 3 database backups when new version is installed. We can adjust futher if this does not work out.
