### ISSUE TITLE
Check that TTL-Expired Archivings are Removed from Pool

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#282]
Verify that the periodic maintenance on the `archiving` table is turning on the `archived` bit when an archiving exceeds its TTL.

**Comment by arlake228** [comment]
I think I see what's going on. Looks like maybe we are "orphaning" archiving rows that have at least one attempt but their ttl has already expired before doing the final attempt. If you look inside the subselect of `archiving_next" you'll see its only grabbing jobs wth a TTL in the future:

```
 SELECT archiving.id FROM archiving
            WHERE
                NOT archived
                AND next_attempt IS NOT NULL
                AND next_attempt < now()
                AND (ttl_expires IS NULL OR ttl_expires > now())
            ORDER BY archiving.attempts, next_attempt
            LIMIT max_return
```

Likewise `archiving_maint_minute`, which cleans out the tasks, is only grabbing things with 0 attempts and a ttl in the past:
```
UPDATE archiving
    SET
        archived = TRUE,     -- Not really, but gets the attempt off the table.
        next_attempt = NULL,
        diags = diags || diag::JSONB
    WHERE
        NOT archived
	-- Note that this must be the same as the default in the table.
        AND next_attempt = '-infinity'
        AND attempts = 0
        AND ttl_expires < now();
```

Thus there is a gap where you have things that got attempted once but didn't hit their final attempt before their TTL expired. Good news is they are not causing any extra load, but they are inflating backlog numbers. 

Probably the thing to do is to just clean out anything with a ttl_expires that is in the past. That's what I assumed it was anyways and puts a firm ceiling on the lifespan of an archiving job.
