### ISSUE TITLE
powstream: "Unable to remove powstream temporary directory"

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#283]
Please review the case, where one powstream is trying to delete a folder, when there are other powstream processes using it.

grep "Unable to remove powstream temporary directory" /var/log/pscheduler/pscheduler.log
>>`Jan 30 17:29:38 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/a3bd5be9-950a-4dd2-93b4-cf1e08577be4: <type 'exceptions.OSError'>`
`Jan 30 17:29:38 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporar`
...
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/5e0fe407-a6d8-4820-88f0-9f20d02c2539: <type 'exceptions.OSError'>`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/5e0fe407-a6d8-4820-88f0-9f20d02c2539: <type 'exceptions.OSError'>`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**`: <type 'exceptions.OSError'>`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**`: <type 'exceptions.OSError'>`

grep **2bec50d3-9285-4dce-9ee1-a4cc7a561a2b** /var/log/pscheduler/pscheduler.log
>>`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9722]: open(/var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**`/15869965313380550681_15869965571120744792.owp.i): No such file or directory`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[9722]: open(/var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**`/15869965313380550681_15869965571120744792.owp.i): No such file or directory`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**: <type 'exceptions.OSError'>`
`Feb  2 09:52:22 psps-test2-mgmt tool-powstream/run WARNING  Unable to remove powstream temporary directory /var/lib/pscheduler/tool/powstream/**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**: <type 'exceptions.OSError'>`

ps ax | grep **2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**
>>`  664 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**` -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S ps-owdtst.rrze.uni-erlangen.de [ps-deb-2.es.net]:861`
` 1271 pts/1    S+     0:00 grep **2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**`
`24992 ?        S      0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**` -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S ps-owdtst.rrze.uni-erlangen.de [ps-deb-2.es.net]:861`
`32422 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/`**2bec50d3-9285-4dce-9ee1-a4cc7a561a2b**` -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S ps-owdtst.rrze.uni-erlangen.de [ps-deb-2.es.net]:861`

**Comment by arlake228** [comment]
Merging with #302
