### ISSUE TITLE
SQL exception for dbcursor.py? 

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#289]
Please note there is no doubt on the root cause of the problem. It is just that simple lack of connectivity leads to this error message.

```
Feb  5 04:13:41 psps-test2-mgmt pscheduler-api ERROR    Exception: InternalError: Unable to determine participants: Can't find pScheduler or BWCTL on ps-deb-2.es.net
CONTEXT:  SQL statement "WITH inserted_row AS (
        INSERT INTO task(json, limits_passed, participant, uuid, hints, enabled)
        VALUES (task_package, limits_passed, participant, task_uuid, hints, enabled)
        RETURNING *
    ) SELECT               * from inserted_row"
PL/pgSQL function api_task_post(jsonb,jsonb,json,integer,uuid,boolean) l
ine 11 at SQL statement#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query
InternalError: Unable to determine participants: Can't find pScheduler or BWCTL on ps-deb-2.es.net
CONTEXT:  SQL statement "WITH inserted_row AS (
        INSERT INTO task(json, limits_passed, participant, uuid, hints, enabled)
        VALUES (task_package, limits_passed, participant, task_uuid, hints, enabled)
        RETURNING *
    ) SELECT               * from inserted_row"

PL/pgSQL function api_task_post(jsonb,jsonb,json,integer,uuid,boolean) line 11 at SQL statement
```

**Comment by mfeit-internet2** [comment]
Determination of who the participants are is supposed to be based only on the contents of the test parameters, and pScheduler considers failure to do so an internal problem.

The BWCTL backward compatibility code that was grafted onto some of the tests violates this rule by attempting to determine whether the destination host is running pScheduler and/or BWCTL.  This means the ability to talk to the remote system becomes a factor in whether or not determining the participants succeeds.  It's a hack, everybody acknowledges that it's a hack and it will go away once we drop support for BWCTL.
