### ISSUE TITLE
Refactor Duration for Run/Post Time

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#29]
Currently, the duration includes all time required, including time to process the results.  Consider making the `duration` method return the actual time that the test will consume resources and how long afterward it will take to produce a result.  This will allow the scheduler to pack more runs into the timeline.

Sample output:

```
{
    "run": "PT5S",    // How long the run will consume resources
    "post": "PT2S"    // How much additional time to produce the result
}
```

**Should probably do this before the first release.**

**Comment by igarny** [comment]
If I can give another perspective:

"run": the time the tool is allowed on the wire
"post": the time before pscheduler timeouts the process/operation

"This will allow the scheduler to pack more runs into the timeline" and will allow pscheduler to maintain control over the processes and stability of the system.

**Comment by mfeit-internet2** [comment]
Kicking this into 1.1  To do:

 * Have tools declare these
 * Make the runner heed it.

**Comment by mfeit-internet2** [comment]
Two years after the first release, this doesn't appear to have been necessary.

Closing.
