### ISSUE TITLE
Task not found while disabling task: repetitions and message 

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#290]
For several days already pScheduler is trying to disable this task.
1) I assume there should have been a limit on the number of attempts to disable a certain task. Then cancel the operation with something of the sort: "giving up on attempts to disable task"
2) Also I find the message from Jan 31 more useful, than the new one from Feb 6.

Feb  6 14:41:04 psps-test2-mgmt pscheduler-api ERROR    Exception: InternalError: Task not found while disabling task db045f65-94eb-4da1-89e8-671ca9d433e9#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Task not found while disabling task db045f65-94eb-4da1-89e8-671ca9d433e9

**>> output from Jan 31:**
Jan 31 23:04:01 psps-test2-mgmt pscheduler-api ERROR    Exception: InternalError: Task not found while disabling task db045f65-94eb-4da1-89e8-671ca9d433e9#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Task not found while disabling task db045f65-94eb-4da1-89e8-671ca9d433e9
Jan 31 23:07:47 psps-test2-mgmt pscheduler-api ERROR    Exception: InternalError: Unable to determine participants: Can't find pScheduler or BWCTL on ps-deb-2.es.net#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, limits_passed, participant, uuid, hints, enabled)#012        VALUES (task_package, limits_passed, participant, task_uuid, hints, enabled)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,json,integer,uuid,boolean) line 11 at SQL statement#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Unable to determine participants: Can't find pScheduler or BWCTL on ps-deb-2.es.net#012#012CONTEXT:  SQL statement "WITH inserted_row AS (#012        INSERT INTO task(json, limits_passed, participant, uuid, hints, enabled)#012        VALUES (task_package, limits_passed, participant, task_uuid, hints, enabled)#012        RETURNING *#012    ) SELECT               * from inserted_row"#012PL/pgSQL function api_task_post(jsonb,jsonb,json,integer,uuid,boolean) line 11 at SQL statement

**Comment by mfeit-internet2** [comment]
This was fixed in 826548c2a37fd726bd6f465f84cee44d1e06c075.
