### ISSUE TITLE
iperf3: applies wrong participant address in UDP tests

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#291]
On a task with correct parameters:
https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/d6321c86-0918-4f1b-ba8c-beb6dbf825e7
{"reference": {"created-by": {"user-agent": "perfsonar-meshconfig", "uuid": "8B77ACAA-752A-11E6-992D-A7DF0A3704F4", "address": "antg-staging.es.net"}, "description": "UDP Test Between Testbeds"}, "schedule": {"start": "2017-02-05T18:23:31Z", "repeat": "PT7200S", "randslip": 0.25, "until": "2017-02-06T18:23:31Z", "slip": "PT7200S"}, "tool": "iperf3", "archives": [{"archiver": "esmond", "data": {"url": "https://perfsonar-testbed-ma.grnoc.iu.edu/esmond/perfsonar/archive/", "retry-policy": [{"attempts": 1, "wait": "PT60S"}, {"attempts": 1, "wait": "PT300S"}, {"attempts": 5, "wait": "PT3600S"}], "measurement-agent": "antg-staging.es.net"}, "ttl": "PT21600S"}], "test": {"type": "throughput", "spec": {"udp": true, "dest": "psps-test2-mgmt.rrze.uni-erlangen.de", "ip-version": 4, "source": "antg-staging.es.net", "bandwidth": 50000000, "duration": "PT10S", "parallel": 1, "schema": 1}}, "tools": ["bwctliperf3", "iperf3"], "schema": 1}

And with correct host resolving:
>> host "psps-test2-mgmt.rrze.uni-erlangen.de"
psps-test2-mgmt.rrze.uni-erlangen.de has address 131.188.81.85

In the below message from iperf3 for UDP tests I find strange references to my NATed interface. In my opinion the task specification, should be enough to define the iperf3 test parameters, so that this test succeeds.

https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/d6321c86-0918-4f1b-ba8c-beb6dbf825e7/runs/9404c3a9-c3ac-425f-a56e-74de9f5a1c5b
{"result-href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/d6321c86-0918-4f1b-ba8c-beb6dbf825e7/runs/9404c3a9-c3ac-425f-a56e-74de9f5a1c5b/result", "end-time": "2017-02-06T05:24:06+01:00", "participant": 1, "errors": null, "participant-data": {"server_port": 5201}, "result-merged": {"diag": "Participant 1:\n-----------------------------------------------------------\nServer listening on 5201\n-----------------------------------------------------------\nAccepted connection from 198.128.151.25, port 49239\n[  5] local 192.168.71.11 port 5201 connected to 198.128.151.25 port 38594\niperf3: error - unable to read from stream socket: No route to host\n\n\n", "succeeded": false, "error": "iperf3 returned an error: "}, "participant-data-full": [{}, {"server_port": 5201}], "state": "failed", "state-display": "Failed", "result-full": [{"succeeded": false, "error": "iperf3 returned an error: "}, {"diag": "-----------------------------------------------------------\nServer listening on 5201\n-----------------------------------------------------------\nAccepted connection from 198.128.151.25, port 49239\n[  5] local 192.168.71.11 port 5201 connected to 198.128.151.25 port 38594\niperf3: error - unable to read from stream socket: No route to host\n\n", "succeeded": true}], "participants": ["antg-staging.es.net", "psps-test2-mgmt.rrze.uni-erlangen.de"], "href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/d6321c86-0918-4f1b-ba8c-beb6dbf825e7/runs/9404c3a9-c3ac-425f-a56e-74de9f5a1c5b", "result": {"diag": "-----------------------------------------------------------\nServer listening on 5201\n-----------------------------------------------------------\nAccepted connection from 198.128.151.25, port 49239\n[  5] local 192.168.71.11 port 5201 connected to 198.128.151.25 port 38594\niperf3: error - unable to read from stream socket: No route to host\n\n", "succeeded": true}, "task-href": "https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/d6321c86-0918-4f1b-ba8c-beb6dbf825e7", "duration": "PT22S", "start-time": "2017-02-06T05:23:44+01:00"}

**Comment by daldoyle** [comment]
This was resolved by making iperf3 server always bind to address specified via -B. TCP mode appeared to work fine, but UDP mode wouldn't work in this case without it.
