### ISSUE TITLE
create non-overlapping set of ports for pscheduler and bwctl

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#296]
Currently there might be a iperf3 port collision if a host is part of both a 3.5 and 4.0 test mesh.

Reducing the bwctl port range should probably fix this?

This would need to be done in both the 3.5 and 4.0 repo.

putting this issue under pscheduler, as it spans multiple repos.

**Comment by bltierney** [comment]
tho this might cause test collisions, so perhaps a test failure it better than a test collision.

pushing this out.

**Comment by bltierney** [comment]
wrong button...

**Comment by arlake228** [comment]
Decided we should drop first port in range for throughput tool in BWCTL.

**Comment by schevali** [comment]
Need words for a NOTE in documentation that 'warns' about this happening (and push to upgrade all hosts to 4.0 for a happier, shinier world)
