### ISSUE TITLE
log what tools were run when, and with what arguements

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#299]
For easier debugging, it would be very helpful if pscheduler logging what tests it is running for all tests (not just those part of a central mesh).

Something like:

timestamp, running test: /path/to/tool arguments

perhaps this is there in Debug mode now?
I think it should be on by default.

perhaps this belongs in regularTesting instead/also?

For v3.5, we got logs like this, which were helpful:

regulartesting.log:2016/07/28 03:31:07 (10454) ERROR> CmdRunner.pm:148 perfSONAR_PS::RegularTesting::Utils::CmdRunner::run - Command exited, will restart in 300 seconds : /usr/bin/bwctl -s perfsonar.ipsl.upmc.fr -c llnl-pt1.es.net -T iperf3 -B llnl-pt1.es.net -I 21600 -R 25 -p -d /var/lib/perfsonar/regulartesting/bwctl_nyAFX -v -P 1 -t 10 -O 10 -w 67108864 -i 1 --parsable

But I'd like something like that when the test succeeds too.

**Comment by mfeit-internet2** [comment]
If you have the URL of the task, everything you need is available:

```
% pscheduler result https://dev7/pscheduler/tasks/c453a4e7-bbf1-47da-8c3f-e0802dd3a872/runs/73a17751-da52-4656-ad75-7f9a70636f15

2017-02-09T19:07:32-05:00 on dev7 and perfsonardev0.internet2.edu with simplestreamer:

simplestream --dest perfsonardev0.internet2.edu

Dawdled ......... P0D
Text Sent ....... Data sent at 2017-02-09 19:07:32.161998
Text Received ... Data sent at 2017-02-09 19:07:32.161998
Elapsed Time .... PT0.414643S


Diagnostics from dev7:

    Try 1 failed: [Errno 111] Connection refused
    Try 2 failed: [Errno 111] Connection refused
    Succeeded on try 3

Diagnostics from perfsonardev0.internet2.edu:

    Nothing to see at the receiving end.
```

There is one small change I need to make to the program that does that, but I'll take care of it shortly.

**Comment by mfeit-internet2** [comment]
The fixes will be out in the next build.  Have at it and close this if you're happy with it.

#251 is related.

**Comment by bltierney** [comment]
I'd really like to see the last 24 hrs of tests at a time, including all the command line args.

Lets discuss.

**Comment by mfeit-internet2** [comment]
Also added logging of each run that looks like this:

```
runner INFO     21: Running https://dev7/pscheduler/tasks/6cf02064-0374-43af-a42f-b6bad2895839/runs/5fbc3a95-fa15-41fe-98ba-e8ea65eec322
runner INFO     21: With iperf3: throughput --bandwidth 50000000 --dest perfsonardev0.internet2.edu
runner INFO     21: Run succeeded.
```
For background-multi, the logging looks like this:
```
runner INFO     33: Running https://dev7/pscheduler/tasks/8f1e4de4-c252-4b34-819c-edd0fc76c582/runs/a963f2a3-524e-466d-b87e-abbc6e551e0e
runner INFO     33: With powstream: latencybg --dest perfsonardev0.internet2.edu --duration PT5M
runner INFO     33: Posted result to https://dev7/pscheduler/tasks/8f1e4de4-c252-4b34-819c-edd0fc76c582/runs/e48cb880-3dbd-48f7-8ce3-311b380db07c
runner INFO     33: Posted result to https://dev7/pscheduler/tasks/8f1e4de4-c252-4b34-819c-edd0fc76c582/runs/c04cf5a6-457b-40e1-8d48-003c4b8e21e1
...
```

**Comment by mfeit-internet2** [comment]
Logging the command line is a tool-specific thing that lands in the diagnostics.  To see what's put there, use `pscheduler result --diags RUN-URL`.
