### ISSUE TITLE
missing powstream processes. which service has to manage the problem?

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#300]
The problem:
There is no responsible service to monitor and maintain powstream processes. Since powstream processes are mostly/exclusively defined and triggered through the meshconfig-agent configuration, I would have expected the meshconfig-agent on each of its reoccurring configuration checks to verify the powstream processes based on the configuration in -tasks.conf. BUT I would be happy to any reasonable solution.
(As agreed on the call yesterday I am opening this ticket with pscheduler)

Comments on the output:
Below you will see, that there are only powstream processes for the forward direction of measurements. Meaning my host as source.
After the restart of the meshconfig-agent service the powstream appears with additional streams on the forward direction (which looks like another problem) and has no reverse measurements opened.
Note at the very end of the report, that I am checking twice the status of the powstream processes. Please mind the process IDs. These are completely new processes on the same measurements.

> ps ax | grep pow | grep antg-staging.es.net
>>13935 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861

> service perfsonar-meshconfig-agent restart
>>/etc/init.d/perfsonar-meshconfig-agent stop: perfSONAR MeshConfig Agent stopped
waiting...
/usr/lib/perfsonar/bin/perfsonar_meshconfig_agent --config=/etc/perfsonar/meshconfig-agent.conf --pidfile=/var/run/perfsonar-meshconfig-agent.pid --logger=/etc/perfsonar/meshconfig-agent-logger.conf --user=perfsonar --group=perfsonar
/etc/init.d/perfsonar-meshconfig-agent start: perfSONAR MeshConfig Agent started

> tail -n 50 /var/log/perfsonar/meshconfig-agent.log
>>2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 08:47:35 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:48 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Task not found while disabling task 064b2b8e-8613-4dfe-8741-4fe721020024
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Task not found while disabling task fdc9b25f-5ddf-426a-82ba-2de58dfc368a
CONTEXT:  PL/pgSQL function api_task_disable(uuid,text) line 12 at RAISE
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Task not found while disabling task 32f140b9-17a8-49ee-aa9e-93d0df40d7f0
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Task not found while disabling task ce265310-2076-48a2-bec9-3011cd9eec53
CONTEXT:  PL/pgSQL function api_task_disable(uuid,text) line 12 at RAISE
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem determining which pscheduler to submit test to for creation, skipping test: 400 BAD REQUEST: Can't find pScheduler or BWCTL on ps-deb-2.es.net
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 422 UNPROCESSABLE ENTITY: Unable to complete request: Couldn't find a tool in common among the participants.
2017/02/10 09:47:49 (27585) INFO> perfsonar_meshconfig_agent:389 main:: - Added 1 new tasks, and deleted 0 old tasks

> ps ax | grep pow | grep antg-staging.es.net
>>16492 ?        S      0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861
22869 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861
24494 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861

> ps ax | grep pow | grep antg-staging.es.net
>>13792 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861
14821 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861
16492 ?        S      0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/e3da414c-792b-428d-a19c-b13fd71abd26 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S ps-owdtst.rrze.uni-erlangen.de [antg-staging.es.net]:861

**Comment by arlake228** [comment]
This seems like a fundamental misunderstanding of how things work. There is indeed something that monitors and maintains powstream process, its called pscheduler. mesh-config creates a pscheduler latencybg task. pscheduler starts this task and launches and maintains powstream. If powstream goes down before its supposed, it restarts it. None of the errors in the logs you share seem related to powstream whatsoever. Also the ps output is exactly what I'd expect if you restart the mesh-config with no changes to the test parameters of powstream. It should not have created any new powstream tasks. 

I think what you were actually trying to report was the fact you didn't have any reverse tests and got stuck in the weeds with how you think things work. There were some other hosts that saw similar issues about when you reported this but they seemed to have gone away with updates shortly thereafter.  I'm closing this for now and we can create a better issue if problems arise after the set of scheduling fixes that went in last night and this morning take effect.
