### ISSUE TITLE
more details in schedule command to help with debugging

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#303]
Currently when you run 'pscheduler schedule', you'll see something like this for tests initiated on a remote host: 

2017-02-13T08:59:46-08:00 - 2017-02-13T09:00:05-08:00  (Pending)
throughput --duration PT10S --ip-version 4 --dest test-pt1.es.net --parallel 1
  (Run with tool 'iperf3')
 
note: no 'source', and dest in this case is localhost.

It would be very helpful for debugging if someing filled in what the remote (ie: 'lead') host is.
Maybe just fill in --source?

**Comment by mfeit-internet2** [comment]
I'll make it spit out the participant list the same way the `result` command does:

```
2017-02-13T13:44:07-05:00 on dev7 with snooze:

idle --duration PT2S

Duration ... PT2S
```

It's a quick change.

There's some duplicated code between the two; one of the things I want to do for 1.1 is get all of that unified.

**Comment by mfeit-internet2** [comment]
This needs a little more work than I thought it would, so I'm going to push it into 1.0.

In the mean time, the host name in the URL for the run is in the lead participant.

**Comment by mfeit-internet2** [comment]
Closing; this doesn't really add a great deal of value.
