### ISSUE TITLE
Runs don't always start in sync.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#310]
(This is an "after-the-fact" ticket.)

Runs aren't always starting in sync.  This may be because the runner uses one database connection, and even though its individual cursors are thread-safe, they're probably getting serialized.

**Comment by mfeit-internet2** [comment]
@vvidic The changes made to the RPM spec in aee1c5a and 9b45cad need to be brought into Debian.

Summary:  Increase the maximum number of connections PostgreSQL will accept to 500 and restart the server.

**Comment by vvidic** [comment]
On Tue, Feb 14, 2017 at 01:52:32PM -0800, Mark Feit wrote:
> @vvidic The changes made to the RPM spec in aee1c5a and 9b45cad need to be brought into Debian.
> 
> Summary:  Increase the maximum number of connections PostgreSQL will accept to 500 and restart the server.

Not sure why the default of 100 connections is not enough and we need 500?
On the test server I see only 5 pscheduler connections and they are all idle.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
The single-connection architecture of the runner was causing the threads that handle each run to access the database sequentially and making some runs not start on time.

The code in the runner asks the server how many connections it has available and creates a pool with a maximum of half that number of connections.  The pool size becomes the limit on how many runs can happen concurrently.  Our target for a large mesh is 100x100, and that many simultaneous runs would consume 100 connections.  250 seems like a good margin.  The server limit is just a limit, the pool isn't going to grow beyond what it actually needs and PostgreSQL isn't going to allocate per-connect resources until those connections actually happen.

The memory footprints on my systems haven't grown any since I made this change.

**Comment by vvidic** [comment]
Debian package updated to 500 max connections.
