### ISSUE TITLE
pscheduler-* init scripts should have a dependency on the postgresql-9.5 service

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#312]
I believe it makes no sense to have pscheduler w/o the postrgesql service running

**Comment by mfeit-internet2** [comment]
Is there a situation where Pg isn't running when it should be?

Installation of the packages won't happen without Pg installed and running, and the services will do everything they can to thrive, including repeatedly trying to re-establish a connection with a downed server.

**Comment by igarny** [comment]
Yes. I have had this experience today (see logs below).
Please note I am not saying that pscheduler was running correctly without the DB. All I am saying is that the init-script should not restart gracefully without the DB being available.


--------------
Feb 16 12:38:20 psps-test2-mgmt safe_run/scheduler ERROR    Exception: OperationalError: could not connect to server: Connection r
efused#012#011Is the server running on host "127.0.0.1" and accepting#012#011TCP/IP connections on port 5432?#012#012Traceback (mo
st recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#0
12  File "/usr/libexec/pscheduler/daemons/scheduler", line 548, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012
  File "/usr/libexec/pscheduler/daemons/scheduler", line 445, in main_program#012    pg = pscheduler.pg_connection(dsn)#012  File
"/usr/lib/python2.6/site-packages/pscheduler/db.py", line 35, in pg_connection#012    pg = psycopg2.connect(dsn)#012  File "/usr/l
ib64/python2.6/site-packages/psycopg2/__init__.py", line 164, in connect#012    conn = _connect(dsn, connection_factory=connection
_factory, async=async)#012OperationalError: could not connect to server: Connection refused#012#011Is the server running on host "
127.0.0.1" and accepting#012#011TCP/IP connections on port 5432?
Feb 16 12:38:20 psps-test2-mgmt safe_run/scheduler ERROR    Waiting 2.25 seconds before restarting
```
Feb 16 12:38:21 psps-test2-mgmt pscheduler-api WARNING  Failed to connect to the database.
Feb 16 12:38:22 psps-test2-mgmt pscheduler-api WARNING  Failed to connect to the database.
Feb 16 12:38:22 psps-test2-mgmt pscheduler-api WARNING  Failed to connect to the database.
```
Feb 16 12:38:23 psps-test2-mgmt safe_run/scheduler ERROR    Restarting
Feb 16 12:38:23 psps-test2-mgmt safe_run/scheduler ERROR    Program threw an exception after 0:00:00.000303
Feb 16 12:38:23 psps-test2-mgmt safe_run/scheduler ERROR    Exception: OperationalError: could not connect to server: Connection r
efused#012#011Is the server running on host "127.0.0.1" and accepting#012#011TCP/IP connections on port 5432?#012#012Traceback (mo
st recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#0
12  File "/usr/libexec/pscheduler/daemons/scheduler", line 548, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012
  File "/usr/libexec/pscheduler/daemons/scheduler", line 445, in main_program#012    pg = pscheduler.pg_connection(dsn)#012  File
"/usr/lib/python2.6/site-packages/pscheduler/db.py", line 35, in pg_connection#012    pg = psycopg2.connect(dsn)#012  File "/usr/l
ib64/python2.6/site-packages/psycopg2/__init__.py", line 164, in connect#012    conn = _connect(dsn, connection_factory=connection
_factory, async=async)#012OperationalError: could not connect to server: Connection refused#012#011Is the server running on host "
127.0.0.1" and accepting#012#011TCP/IP connections on port 5432?

**Comment by mfeit-internet2** [comment]
That isn't the init scripts doing that.  The services are wrapped in a crash-proofing layer that will catch unrecoverable problems, log them and restart.

The init scripts can't and don't do anything to restart dead services.  If a service that depends on Pg dies because the Pg server went away or was restarted, it will have to be restarted manually.  Recovering automatically increases availability and reduces the support burden.

**Comment by arlake228** [comment]
Don't think there is anything to do here. daemons reconnect to postgresql properly if it goes down or is not yet started
