### ISSUE TITLE
postgresql 9.4 dependency impossible to meet (ubuntu)

### ISSUE THREAD

**Issue by dsturm-l** [perfsonar/pscheduler#320]
Hi, I have been trying out perfsonar 4.0, and I ran into this issue with downloading perfsonar-testpoint. It seems that pscheduler-server is dependent on postgresql-9.4, which isn't available in the Ubuntu 16.04 repositories. I have to download the program with aptitude, change the dependencies, and install it manually. If pscheduler-server were dependent on either postgresql-9.4 or 9.5, I would have no trouble installing from the repository. I would recommend changing this before the full release so Ubuntu users can install without issue.

```
root@igswmcmmas04:~# apt-get install pscheduler-server 
Reading package lists... Done 
Building dependency tree        
Reading state information... Done 
Some packages could not be installed. This may mean that you have 
requested an impossible situation or if you are using the unstable 
distribution that some required packages have not yet been created 
or been moved out of Incoming. 
The following information may help to resolve the situation: 

The following packages have unmet dependencies: 
pscheduler-server : Depends: postgresql-9.4 but it is not installable 
                    Depends: postgresql-plpython-9.4 but it is not installable 
                    Depends: postgresql-contrib-9.4 but it is not installable 
E: Unable to correct problems, you have held broken packages. 
root@igswmcmmas04:~#  
root@igswmcmmas04:~#  
root@igswmcmmas04:~# dpkg --get-selections | grep postgres 
postgresql-9.5                                  install 
postgresql-client-9.5                           install 
postgresql-client-common                        install 
postgresql-common                               install 
postgresql-contrib-9.5                          install 
postgresql-plpython-9.5                         install 
root@igswmcmmas04:~#
```

**Comment by tonin** [comment]
Thanks for this report.

Ubuntu 16 is not and will not be officially supported by perfSONAR 4.0, we officially support Ubuntu 12 & 14 and Debian 7 & 8.  Furthermore, there are some peculiarities about pscheduler on Debian/Ubuntu that we have decided to make it require postgresql 9.6 and we will provide a backport of that on our repositories.

Which repository are you using?  It might be that you have the RC2 packages which might still contain a wrong dependency to 9.4.  We should post RC3 packages soon that will have the correct dependency to 9.6.

**Comment by dsturm-l** [comment]
I think I'm downloading RC2 testpoint packages, but I have downloaded the Centos 7 RC3 ISO and installed it on a laptop for now. Is there a way to directly update to RC3? I have been using the guide on your site to try setting my mesh up, but significant portions are missing or are works in progress. I have not been able to find any documentation for perfSONAR 4.0rc3, or Maddash 2.0. Is there documentation I should know about for the most current release candidates? I'm willing to submit information, logs and data to improve support for ubuntu and arm64. I know that I would love to use the Odroid-C2 as a cheap, simple testpoint, and I'd be happy to submit any information to help make that possible.

**Comment by mfeit-internet2** [comment]
This needs a milestone; we need to decide which one or resolve it and close it.

**Comment by tonin** [comment]
The RC3 packages that are now present in http://downloads.perfsonar.net/debian/perfsonar-wheezy-4.0.list do depend on postgresql 9.6.  This version of postgres is available in the same repository.  But we have not tested perfsonar/pscheduler installation on Ubuntu 16, it is a distribution we don't support at this point.
