### ISSUE TITLE
faulty ping test specifications in my schedule

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#321]
Hi
Today I have found this in my schedule trying to debug a problem in the Ping dashboard with ps-deb-2 

https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/c1ee7827-3bfd-4b31-a2d4-680be3337d7b/runs/04f0d741-cc43-4360-b681-a17ae6eba79c

Please note, that the localhost is the initiator. It has spawned a test from the remote side to the local, but has failed because the binding parameter is for the remote host.

**Comment by mfeit-internet2** [comment]
Specifically, is this the problem?
```
{
    "diags": "ping -n -c 10 -i 1.0 -I 198.128.151.30 -s 1000 -W 1.0 131.188.81.85",
    "result": null,
    "succeeded": false,
    "error": "bind: Cannot assign requested address\n"
}
```
