### ISSUE TITLE
Add example pscheduler.limits file that points at R&E IP lists

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#324]
We have the script extract-limits-group that creates the necessary IP lists we need. Brian is working on uploading those. We should also create a sample limits file that points at these lists for easy copying over by people who want it.

**Comment by mfeit-internet2** [comment]
I have this available at Internet2 if you need it:

http://software.internet2.edu/data/pscheduler/limit-cidrs/

**Comment by mfeit-internet2** [comment]
I'll take this since I already have one in the works for #161.
