### ISSUE TITLE
Private archiver fields getting displayed in run info

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#325]
Basically as the title says, if you look at a run with an archiver containing a private field it is not getting hidden like when you display the task. Example, the archiver talking to the umich MA here: https://antg-dev.es.net/pscheduler/tasks/5eccc704-206a-4019-8141-6bc0c4d5546a/runs/59fe1aec-7d92-4de4-b1eb-3f9965bcf33d?pretty

**Comment by mfeit-internet2** [comment]
Fixed.

**Comment by mfeit-internet2** [comment]
Reopening for a better improvement.

**Comment by mfeit-internet2** [comment]
Decided to sanitize everything that comes out of the API instead of leaving it up to the individual parts.
