### ISSUE TITLE
Handle scheduling conflicts gracefully

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#327]
The scheduler doesn't behave well when something sneaks in and grabs a time slot during processing.

This shouldn't be treated as an internal problem; the API should spit back an error indicating that it was unable to schedule the run and the scheduler should try again.  Anything previously scheduled will need to be removed.

From the logs:
```
Feb 24 15:19:17 perfsonardev0 pscheduler-api ERROR    Exception: InternalError: Run would result in a scheduling conflict.
CONTEXT:  SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement

Traceback (most recent call last):
  File "./pschedulerapiserver/runs.py", line 395, in tasks_uuid_runs_run
  File "./pschedulerapiserver/dbcursor.py", line 107, in dbcursor_query
InternalError: Run would result in a scheduling conflict.
CONTEXT:  SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 29 at SQL statement

```

**Comment by bltierney** [comment]
also getting this in the logs, which I assume is related:?

Feb 26 09:29:10 antg-staging journal: pscheduler-api ERROR    Exception: InternalError: Invalid transition between states (5 to 8).#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/runs.py", line 478, in tasks_uuid_runs_run#012  File "./pschedulerapiserver/dbcursor.py", line 107, in dbcursor_query#012InternalError: Invalid transition between states (5 to 8).

**Comment by mfeit-internet2** [comment]
Not related to this.

**Comment by mfeit-internet2** [comment]
The API now returns a 409 if an attempt to post a run would result in a scheduling conflict.

The scheduler will try up to three times to schedule the run; after that it will post a non-starter with a suitable reason.
