### ISSUE TITLE
Debian upgrade throws database error

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#328]
Trying to updrade on Debian to the latest package throws the following error. This was on Debian 8.

```
error encountered processing /usr/share/dbconfig-common/data/pscheduler-server/upgrade/pgsql/1.0~24.rc3+20170224192205-1:
NOTICE: Table http_queue: Upgraded from version 1 to 2 ERROR: deadlock detected DETAIL: Process 5254 waits for AccessExclusiveLock on relation 16554 of database 16385; blocked by process 5263. Process 5263 waits for AccessShareLock on relation 16516 of database 16385; blocked by process 5254. HINT: See server log for query details.
```

This locked-up the auto-update process. I rebooted the host and did the update manually, at which point I got the same error, and then I retried and I *think* maybe it worked...or at least it proceeded with the update and pscheduler seems to function again.

**Comment by mfeit-internet2** [comment]
That might be an attempt to upgrade while one of the daemons or REST API is using the database.  The daemons should be shut down during upgrades; we might need to consider doing the same with httpd.

**Comment by vvidic** [comment]
On Sat, Feb 25, 2017 at 11:52:53AM -0800, Mark Feit wrote:
> That might be an attempt to upgrade while one of the daemons or REST API is
> using the database.  The daemons should be shut down during upgrades; we
> might need to consider doing the same with httpd.

The daemons are stopped already during upgrade, will try to do the same
for apache.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Replaced apache reload with restart on Debian 8. If there are still problems it would be good to check PIDs mentioned in the error message as they should point to the process using the database.
