### ISSUE TITLE
httpd locks up with "server reached MaxRequestWorkers setting" error

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#329]
On the Umich host today httpd was not responding. It had failed with:

> [mpm_prefork:error] [pid 53289] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting

Server was basically locked up and had to forcibly restart, then things seemed to bounce back. Need to keep our eyes open if this is just a one off, or becomes recurring issue. If don't see again in the next couple days, can maybe just close.

**Comment by arlake228** [comment]
I think I know the cause of this, more of a esmond(really cassandra) issue. Cassandra's rpm is stupid on el7 and doesn't track its pid file properly, so cassandra can get in a bad state. It did, which caused registrations to fail. Since umich uses a local MA, itself and everything in the testbed was getting hung-up by cassandra which pushed it over the max workers limit. I'll keep this open so i can verify, but really need an issue to compensate for the broken rpm that cassandra provides.

**Comment by mfeit-internet2** [comment]
Not pScheduler; see https://github.com/perfsonar/toolkit/issues/205.
