### ISSUE TITLE
Handle multiple IPs being involved in each end of a test

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#33]
Ivan suggested that for multi-homed systems, it would be a good idea to have a way to separate the address where we talk to pScheduler vs. where the test actually takes place.  (Current model is to have the BWCTL server listen on all interfaces.  That does simplify things.)

A [message from Barbaresco Pierrette on perfsonar-users](https://lists.internet2.edu/sympa/arc/perfsonar-user/2016-06/msg00049.html) adds the idea of being able to differentiate between private- and public-facing interfaces to handle situations where an interface is NATted.

Per-test parameters would have to go along these lines:

`dest-node` - Address of the pScheduler server, or possibly a base URL, e.g., `http://perfsonar.foo.org:12345`.

`dest` - IP of the test interface as seen from the `source` perspective (i.e., where it should send data).

`dest-bind` - IP where the test should bind when it runs.  This is the address of an interface on the local machine.  Defaults to the same value as `dest` if not provided.

This would work for true, 1:1-mapped NAT.  Need to consider this carefully because under resource management, PAT would be excruciatingly difficult because modeling ports would be near-impossible.  (Forwards would be okay as long as they're the same on the outside and inside.)  For interfaces, the resource model could hold the actual IP and where to reach in in public, and that in turn could be passed on in participant-specific data.

How far do we want to go in supporting this?

**Comment by igarny** [comment]
Just another point of view on the selection of parameters for this use case.
My kind suggestion is to keep "-dest" ("-src") parameter for the test interface on remote pS kit instance, and to use the extra parameter (dest-bind/src-bind) as a pointer to the pSched managed interface. I do not have a better naming proposal, but guess "*-bind" might be found misleading.

Thus we'll keep compliance with other tests and will only extend the syntax, wherever needed.

Regards,
Ivan

**Comment by igarny** [comment]
Hi Mark,

I am putting in a picture the obvious, but I would like to point out another problem:
https://docs.google.com/drawings/d/1pttzqIsOHSA3ddtGRCPC6AQugjmtwwzoFLDawW4codo/pub?w=960&h=720

1) How far do you want to go? Do you foresee a case, where pscheduler is contacted on a separate destination address and needs to open a test communication on another interface?
---- if not: (pscheduler operates on the same interface, where the measurement is performed) wouldn't it be simpler, if pscheduler just identifies the incoming interface to set it as a test interface for the task?
----wouldn't a local config for interface-to-address mapping be more reasonable to have on the host behind NAT. I mean how an external party is supposed to know what to write for the dest-bind parameter?

2) what about the reverse case, where the source is behind NAT? In fact I am going to generalize on this in another use case / issue

3) How far do you want to go? What about the use case, where both systems are behind a NAT?

**Comment by mfeit-internet2** [comment]
For latency, latencybg, rtt, simplestream, and throughput:  Added `source-node` and `dest-node` parameters.  For trace:  Added a `source-node` but not a `dest-node` because trace is a one-participant test.

The semantics for the `xxx` and `xxx-node` parameters are as follows:
* For determining participant:  If an `xxx-node` parameter is present, that value will be used, otherwise `xxx` if present; otherwise the default
* For determining the interface used in the test:  `xxx`

Still need to do #234 to make everything fully-bindable.
