### ISSUE TITLE
Bump user process limit on CentOS 6

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#331]
CentOS 6 has a default per user process limit of 1024 which means around 200 powstream tests you start getting errors. We should bump this to 4096 which matches what CentOS 7 does. Shoudl conf tag this so people can edit if they need to.

**Comment by mfeit-internet2** [comment]
Do we want to do this in pScheduler or as part of one of the toolkit RPMs?  (I'm inclined not to do it in pScheduler.)

**Comment by arlake228** [comment]
Thinking on this some I agree that we should throw it in the perfsonar toolkit/bundle packages. Commits incoming to fix this.
