### ISSUE TITLE
 Invalid transition between states ERROR

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#333]
currently seeing lots of these in the logs:

Mar  2 13:43:20 antg-staging journal: pscheduler-api ERROR    Exception: InternalError: Invalid transition between states (5 to 8).#012#012Traceback (most recent call last):#012  File "./pschedulerapiserver/runs.py", line 505, in tasks_uuid_runs_run#012  File "./pschedulerapiserver/dbcursor.py", line 107, in dbcursor_query#012InternalError: Invalid transition between states (5 to 8).

**Comment by schevali** [comment]
Working with Michael on tracking down the issue I'm seeing with a formerly stable host; 149.165.239.235

Seeing the same type of error when digging into /var/log/messages. Manual runs present with several failure conditions:
“Unable to post task”
“Unable to divine CLI from spec: …” 
“Unable to complete request: Couldn’t find a tool in common”
“Run on server was never populated”
And occasionally complete.

All boxes updated on Friday and again today to catch the weekend pushes to staging.

So posting the above here to see if this is related and if so what the short-term fix could be.

**Comment by mfeit-internet2** [comment]
A note about this:  Whatever is causing it isn't disturbing the existing data, so runs that finished successfully aren't being corrupted into failures.

**Comment by mfeit-internet2** [comment]
Looks like this is a conflict between [what happens in the trigger for run updates](https://github.com/perfsonar/pscheduler/blob/master/pscheduler-server/pscheduler-server/database/run.sql#L346) and when [a run is updated with the full result](https://github.com/perfsonar/pscheduler/blob/master/pscheduler-server/pscheduler-server/api-server/pschedulerapiserver/runs.py#L492).

It looks like this happens on multi-participant tests when the local participant succeeded and one of the others failed, resulting in a state change when `result_full` is brought in.

This might be a good opportunity to use the unused `cleanup` state  in the run state list.

**Comment by mfeit-internet2** [comment]
In the interest of not disturbing the code too much, I'm going to make `finished` -> `failed` a valid state transition.

Kicking this into 1.1 for further consideration.
