### ISSUE TITLE
BWCTL tool 'sum' Exceptions

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#335]
Seeing a few of these in the logs on perfsonardev0:
```
Mar  4 12:07:02 perfsonardev0 tool-bwctl/run ERROR    Exception 'sum'
```

From a quick grep through the sources, it looks like this is the `run` method in `pscheduler-tool-bwctliperf2/bwctliperf2` or `pscheduler-tool-bwctliperf2/bwctliperf3`, both of which register themselves as `tool-bwctl`.  (All of the methods in those tools do that; this should probably be fixed, too.)

The `Logger` class has a method called `exception()` that will send a full accounting of the last-thrown exception.  This is worth calling anytime you catch an exception you can't otherwise handle.

**Comment by arlake228** [comment]
I see the line where this specific error is coming, but looking at this, appears the parsing function generally needs to handle missing keys in the iperf3 JSON better as its vulnerable to lots of errors of this type. Will do so as part of this change.
