### ISSUE TITLE
Latencybg runs getting marked as 'Missed'

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#338]
On sacr-pt1.es.net, a busy measurement host in ESnet's network, latencybg tasks are frequently having their first runs marked as 'Missed'. This in turn prevents latencybg from running. The way latencybg works, it probably doesn't make sense to mark them as Missed ever since really the tool just periodically creates new runs. I think the fix is a pretty minor update to the WHERE clauses in run_handle_stragglers to ignore backgroundmulti tasks.

**Comment by mfeit-internet2** [comment]
Please hold off on making changes to this until we've had a chance to talk about it.

**Comment by arlake228** [comment]
We decided that the right solution is to only mark backgroundmulti as missed if it is past the end time of the task.
