### ISSUE TITLE
bug: attempts to archive measurements to an unathorized remote location

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#339]
Could be a meshconfig-agent issue

Mar  7 09:46:48 psps-test2-mgmt archiver WARNING  2175121: Failed to archive https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/138cbe59-0277-4333-aaa3-36b73f4b056f/runs/fe5a05
c7-aaab-4ca7-9da7-e5ea3aeaf082 to esmond: 
Unable to post metadata to http://perfsonar-lab-vm.ilab.umnet.umich.edu/esmond/perfsonar/archive/: ('Connection aborted.', error(111, 'Connection
 refused'))

**Comment by mfeit-internet2** [comment]
Not a bug in pScheduler.
