### ISSUE TITLE
Integrate testing for Python library.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#347]
(Please leave this in the 1.0 milestone.  --Mark)

Code is in the `unittests-cleanup` branch.

From @montegoode in Slack:

Hey Mark,

My initial pass is basically done.

I've set up a suite of unit tests, mostly cobbled together from the code in the the various `__main__` blocks, and formulated a few of my own. I have written documentation for all of that and I'll attach a PDF version of it for your perusal/see if that suffices.

Have also taken a very light "linting" pass which is just reformatting pep8 style violations. Not real nitty gritty pylint stuff. More on linting in a moment.

I have also modified `setup.py` so that the third party dependencies will also automatically be installed. It's just good practice, but it's also in service of being able to set up a self-contained development installation/testing situation. That's also covered in the documentation I wrote.

Next steps:

For starters, it would be good if you can look in the new tests directory in my branch here:
```
pscheduler/python-pscheduler/pscheduler/tests
```
And grep for the string XXX. I left some comments in the tests I set up where I needed clarification. They are basically all situations where I am not sure what "stable" testing values can be used. By way of example: a DNS test condition might fail if they change the IP address of a host. There were a couple of places I could use clarity on what a stable test condition might be. Given that feedback, I could tighten those tests up.

I can flesh the test documentation out as well if you need me to.

And...what else?

OK, so there is linting to be done. It would not be the first time I've done a detailed linting pass on python code to get it all tidied up. However, the code base seems to be in so much flux right now that I would be spending the bulk of my time fighting with merge conflicts trying to keep pace with all the activity in the master branch. So that might not be the best course of action at the moment. It might be better to do that after the release when things calm down a bit.

Wanted to get a handle on the scope of the rest of it. We had originally kind of just left it at "some unit tests and linting" and that's kind of happened. And Jon is wanting some time estimates from me.

I don't need an immediate answer on those test conditions and etc. I'm going to be on a call for a while right now, and a good chunk of my day tomorrow (Wednesday) will be taken up by a workstation tear down/set up maneuver. So if you can't drop everything right now and give me an answer, don't worry about it. :slightly_smiling_face:

Also attached this doc:  [README.md.pdf](https://github.com/perfsonar/pscheduler/files/826104/README.md.pdf)

**Comment by mfeit-internet2** [comment]
Assigning to @vvidic for an optional adjustment to the Debian build:

The RPM spec has been changed from using `python setup.py build` to just `make` for the build step, with the Makefile taking care of running the unit tests.

If you want the Debian builds to run the tests (probably a good idea), make that change.

Close this when you're done.

**Comment by mfeit-internet2** [comment]
CentOS 6 doesn't run the tests correctly:
```
opying pscheduler/limitprocessor/pscheduler-limits-validate.json -> build/lib/pscheduler/limitprocessor
nosetests ./tests
.....E.....E....EE...E...EE....
======================================================================
ERROR: Filestring tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/filestring_test.py", line 23, in test_filestring
    self.assertGreaterEqual(fstab.find('/etc/fstab'), 0)
AttributeError: 'TestFilestring' object has no attribute 'assertGreaterEqual'
======================================================================
ERROR: iso dt conversion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/iso8601_test.py", line 39, in test_iso
    with self.assertRaises(ValueError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
======================================================================
ERROR: Bulk resolve test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/psas_test.py", line 33, in test_bulk_resolve
    self.assertIsNone(ret.get('this-is-not-valid'))
AttributeError: 'TestPsas' object has no attribute 'assertIsNone'
======================================================================
ERROR: Bulk resolve test.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/psdns_test.py", line 48, in test_bulk_resolve
    self.assertIsNone(ret.get('does-not-exist.internet2.edu'))
AttributeError: 'TestPsdns' object has no attribute 'assertIsNone'
======================================================================
ERROR: Test loading
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/psjson_test.py", line 51, in test_load
    with self.assertRaises(ValueError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
======================================================================
ERROR: SI as number test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/sinumber_test.py", line 37, in test_si_as_number
    with self.assertRaises(ValueError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
======================================================================
ERROR: SI range test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pscheduler-dev/python-pscheduler/rpmbuild/BUILD/pscheduler-1.3.0.2/tests/sinumber_test.py", line 79, in test_si_range
    with self.assertRaises(ValueError):
TypeError: failUnlessRaises() takes at least 3 arguments (2 given)
----------------------------------------------------------------------
Ran 31 tests in 1.120s
FAILED (errors=7)
```

**Comment by vvidic** [comment]
Debian build runs the test automatically via ``dh_auto_test`` but had to disable this due to following errors:

```
======================================================================
ERROR: pscheduler.limitprocessor.limit.test.test_data_is_valid
Check to see if data is valid for this class.  Returns a tuple of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_data_is_valid() takes exactly 1 argument (0 given)

======================================================================
ERROR: pscheduler.limitprocessor.limit.testtype.testtype_data_is_valid
Check to see if data is valid for this class.  Returns a tuple of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: testtype_data_is_valid() takes exactly 1 argument (0 given)

======================================================================
FAIL: test_filestring (filestring_test.TestFilestring)
Filestring tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-pscheduler-1.0.0.2+20170524051353/tests/filestring_test.py", line 23, in test_filestring
    self.assertGreaterEqual(fstab.find('/etc/fstab'), 0)
AssertionError: -1 not greater than or equal to 0

----------------------------------------------------------------------
Ran 33 tests in 0.823s

FAILED (failures=1, errors=2)
E: pybuild pybuild:256: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 --dir . returned exit code 13
```

**Comment by mfeit-internet2** [comment]
Looks like this is a completely different set of errors than we get on CentOS 6.  Joyous.

**Comment by arlake228** [comment]
The tests should run on CentOS 6 and CentOS 7 now per commit that references this issue. I just went ahead and cleaned them up while working on adding some functions to test IP limits since I wanted to be able to use the unit tests and turned out to be a pretty quick fix.

**Comment by mfeit-internet2** [comment]
Tests are re-enabled on CentOS.

@vvidic Please check that Debian is good and close this ticket if so.

**Comment by vvidic** [comment]
I think it still has the same problems, this is on Debian 8/jessie:

```
======================================================================
ERROR: pscheduler.limitprocessor.limit.test.test_data_is_valid
Check to see if data is valid for this class.  Returns a tuple of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_data_is_valid() takes exactly 1 argument (0 given)

======================================================================
ERROR: pscheduler.limitprocessor.limit.testtype.testtype_data_is_valid
Check to see if data is valid for this class.  Returns a tuple of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: testtype_data_is_valid() takes exactly 1 argument (0 given)

======================================================================
FAIL: test_filestring (filestring_test.TestFilestring)
Filestring tests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-pscheduler-1.3.0.4.1+20170719032220/tests/filestring_test.py", line 23, in test_filestring
    assert(fstab.find('/etc/fstab') >= 0)
AssertionError

----------------------------------------------------------------------
Ran 37 tests in 0.869s

FAILED (failures=1, errors=2)
E: pybuild pybuild:256: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 --dir . returned exit code 13
```

**Comment by vvidic** [comment]
On Debian 7/wheezy it fails to find requests module installed on the system:

```
======================================================================
ERROR: Failure: ImportError (No module named requests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.6/dist-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.6/dist-packages/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/buildd/python-pscheduler-1.3.0.4.1+20170719032237/tests/threadsafe_test.py", line 9, in <module>
    from pscheduler.threadsafe import ThreadSafeDictionary
  File "/tmp/buildd/python-pscheduler-1.3.0.4.1+20170719032237/pscheduler/__init__.py", line 5, in <module>
    from .api import *
  File "/tmp/buildd/python-pscheduler-1.3.0.4.1+20170719032237/pscheduler/api.py", line 17, in <module>
    from .psurl import *
  File "/tmp/buildd/python-pscheduler-1.3.0.4.1+20170719032237/pscheduler/psurl.py", line 8, in <module>
    import requests
ImportError: No module named requests

----------------------------------------------------------------------
Ran 24 tests in 0.121s

FAILED (errors=22)
E: pybuild pybuild:256: test: plugin distutils failed with: exit code=1: python2.6 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.6 2.7 --dir . returned exit code 13
```

**Comment by apertome** [comment]
Setting to 4.1, since it's not ready for 4.0.1 and it sounds like there is more work to be done on the Debian side to make this work.

**Comment by vvidic** [comment]
@mfeit-internet2 Can we move ``python-pscheduler/tests`` to ``python-pscheduler/pscheduler/tests`` because than it seems to work correctly?

```
$ nosetests tests
...................................
----------------------------------------------------------------------
Ran 35 tests in 0.982s

OK
```

**Comment by mfeit-internet2** [comment]
@vvidic I think I put them where they are to match what had already been done.  I do agree that the right place would be one level down with the sources.

On a related note:  There's been some on-and-off discussion about whether we want to continue running the tests separately as they are now or as part of the build process.  I think that if we're going to fold the tests in with the source, we should make it part of the build process, but I'd also like a way to use the environment to bypass it so it doesn't slow down the builds I do during development.

**Comment by vvidic** [comment]
There already exists ``python-pscheduler/pscheduler/tests`` but there is only one file in there. Is this used for something?

**Comment by vvidic** [comment]
The Debian build does not see anything below ``python-pscheduler/pscheduler`` so if you could move the ``tests`` directory there we can run the unit tests during the build.

**Comment by mfeit-internet2** [comment]
I'll do that today or early next week as part of this ticket.

**Comment by vvidic** [comment]
@mfeit-internet2 can you check this directory issue?

**Comment by mfeit-internet2** [comment]
@vvidic This has been done; the usual `make` will do tests as part of the process.

**Comment by vvidic** [comment]
Tests activated on the Debian side to run during package build.
