### ISSUE TITLE
Non-Lead Escape Hatch for Archivers

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#356]
@igarny would like a way to archive data about all runs, including those for non-lead participants, out of pScheduler for assessing node usage.

Consider adding a boolean `non-lead` field to the archive spec that would enable archiving when the node isn't the lead.

This should probably be honored only for archivers configured globally (in `/etc/pscheduler/default-archives`) to prevent outside hosts from imposing extra work.

**Comment by arlake228** [comment]
Replaced by #252
