### ISSUE TITLE
HTTP archiver retry policy not properly applied

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#359]
The retry policy code in the HTTP archiver will only be run if the op is invalid.  That needs to happen when either the `POST` or `PUT` operations fails.

**Comment by epcjr** [comment]
Fixed in 9ecf3995ed6979271dbffd2af494e833de12c229

**Comment by mfeit-internet2** [comment]
Code looks okay.  Closing.
