### ISSUE TITLE
HTTP Response Time Test/Tool

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#361]
Title says it all.

**Comment by mfeit-internet2** [comment]
Comment from Dale Carder, who wants this, too:

The one usecase I had in mind was to integrate echoping, particularly to
monitor http responsiveness.  I used that at $job-1 (sparingly) for
monitoring some critical 3rd party services.  

For example, I'd wish these were together and also had a traceroute
test, so it would seem to me to be much more straightforward to use the
perfsonar framework.
https://stats.net.wisc.edu/smokeping/smokeping.fcgi?target=kaltura.kaltura-http
https://stats.net.wisc.edu/smokeping/smokeping.fcgi?target=kaltura.kaltura-icmp

Another detailed example for wisconsin public radio:
https://stats.net.wisc.edu/smokeping/smokeping.fcgi?target=External.wpr-icecast

Dale

**Comment by arlake228** [comment]
I believe this is done, can we close?

**Comment by mfeit-internet2** [comment]
Yup.  Closing.
