### ISSUE TITLE
Alternate Backward Compatibility Proposal

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#365]
# Skip this.  The scheduler would try to coordinate with pScheduler at the other end, which would not necessarily exist.

This ticket proposes an alternative method for BWCTL backward compatibility that stays truer to the architecture and requires fewer code changes over time.

**This is worth considering _now_ because #364 would entail a change to the JSON fed the the `participants` method in test plugins.**

The model is supposed to be that `participants` derives a participant list using only what's in the test specification.  What we're doing for BWCTL backward compatibility gives tests indirect knowledge of tools that they really shouldn't have.  I don't care for it but am willing to tolerate it temporarily for the sake of a smooth transition.

A better approach to this might be:
 * Let `participants` work as intended.
 * Have the `can-run` methods for the `bwctl*` tools recuse themselves from tests where there's pScheduler but no BWCTL on the other end.
 * Give the `bwctl*` tools a higher preference so they'll be selected for tasks with only BWCTL at other end.  (And, by extension, they will self-deselect when pScheduler is present.)

In practice:
 * A `throughput` task is submitted to pScheduler node A with the destination being BWCTL-only node B.
 * The `participants` method says the participants are A and B.
 * The task is shopped around to tools `iperf2`, `iperf3`, `nuttcp`, `bwctliperf2` and `bwctliperf3`.
 * All tools say they can do the test, but the `bwctl*` tools do the BWCTL-only check before saying yes.
 * The `bwctliperf3` tool is selected because it has a higher preference than the pScheduler-only tools and `bwctliperf2`.

Pros:
 * `lead-bind`, which was only ever intended to be applied to pScheduler-to-pScheduler communication, is no longer a factor.  Because BWCTL doesn't allow splitting of control and test traffic, the `can-run` method can bind against the `source` parameter if there is one.
 * Building a system without backward compatibility will just mean not installing `pscheduler-tool-bwctl*`.
 * Similarly, removing it from an existing system is a matter of removing packages and not changing any code.

Cons:
 * When we remove support for BWCTL and stop distributing `pscheduler-tool-bwctl*`, the old packages will remain on existing systems during upgrades.  We can remedy that by publishing one final upgrade to those packages that renders them inert (e.g., they don't claim they can run any tests).
 * Some of the timeout-related ugliness is still present, but I can live with that.  I'd much rather have it shifted to `can-run` than `participants` and the problem goes completely away on systems where the backward compatibility packages are never installed because `can-run` is no longer reaching out and touching other things.

Other comment:  I have no idea why I didn't think of this sooner.

**Comment by arlake228** [comment]
We would have already done it this way, but the problem is reverse tests. If you want to go from B->A and B only has BWCTL you can't treat that as a lead and submit things to it and ask it to run things like can-run. Are you proposing the client or assist server does the can-run as well because that seems problematic as well ?

**Comment by mfeit-internet2** [comment]
While working a different issue, I noticed something that makes this infeasible:  With two participants, the scheduler would try to talk to a pScheduler at the far end that doesn't exist.

Closing.
