### ISSUE TITLE
Check that pscheduler-server RPM spec halts httpd.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#366]
Need to make sure that HTTPD is shut down while the database is being upgraded.

This could be kicked into 1.0 since it doesn't seem to be much of a problem.  @vvidic noticed it on Debian, and they're already fixing it.

**Comment by vvidic** [comment]
Debian part already being handled in #328.

**Comment by mfeit-internet2** [comment]
We're good.  No changes needed.
