### ISSUE TITLE
strange error in 'pscheduler result' output

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#374]
I noticed a Non-Starter on antg-dev, and when looking at the result, I see this:

pscheduler result https://antg-dev.es.net/pscheduler/tasks/3c6684fb-403d-4fe0-ad53-636ca1da8108/runs/e62a91fa-90d3-49f0-9ea9-f09bedb21cc1

Run never started: Failed to post/put runs to all participants: function api_run_post(unknown, timestamp with time zone, unknown) does not exist
LINE 1: SELECT * FROM api_run_post('3c6684fb-403d-4fe0-ad53-636ca1da...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by arlake228** [comment]
For reference the task was indeed created at 2017-03-16T08:26:10-07:00 (i.e. the day before the time on the problematic run). We don't currently track when the run was added, see #375, but given what we know about how the scheduler works, that run should have been added around the same time. Given all the issues we had going that day and the fact that I was using test-pt1 as grounds to test fixes to some of those, I am pretty sure that is what caused.

...in fact I think I may even know the specific cause: I was adding and deleting api_run_post in postgres yesterday fixing a bug in it.I think this is about that time so probably got caused when I was monkeying with that.

Also, running the test by hand seems to work just fine now.

**Comment by mfeit-internet2** [comment]
If you were dropping and then recreating the function, then there would have been a period where it didn't exist, so that explanation would make sense.  I use the `CREATE OR REPLACE` so the whole thing happens in one transaction.

I'm going to assign this to you; close it if you think we have no issue here.

**Comment by bltierney** [comment]
I'm seeing something similar, but slightly different still on several hosts. For example:

pscheduler result https://ps-deb-2.es.net/pscheduler/tasks/1a3ae765-a55d-4ed4-a930-5e7d8a152c70/runs/c38bcfef-7309-40ba-99f2-f358852bc1d0
Run never started: Failed to post lead run: Unable to get participant data: Process took too long to run.
CONTEXT:  PL/pgSQL function run_alter() line 121 at RAISE
SQL statement "WITH inserted_row AS (
        INSERT INTO run (uuid, task, times, state, errors)
        VALUES (run_uuid, task.id, time_range, initial_state, nonstart_reason)
        RETURNING *
    ) SELECT               uuid FROM inserted_row"
PL/pgSQL function api_run_post(uuid,timestamp with time zone,uuid,text) line 37 at SQL statement

**Comment by mfeit-internet2** [comment]
That was corrected in 187dbb5, committed on Thursday.   How old is the code on that host?

**Comment by bltierney** [comment]
I'm seeing it on several hosts, most I could confirm got last nights update.

**Comment by mfeit-internet2** [comment]
Just reread the error message.   I'll fix that in the morning.

**Comment by arlake228** [comment]
Pretty sure this is related to my last comment in #370.

**Comment by mfeit-internet2** [comment]
I can't find anything in any of the `participant-data` methods that would cause them to run long.

I do notice that on that machine and many of the others, there are fairly regular periods where WIO gets spiky, up to 10%.  Is there a chance that there's a maintenance period when I/O becomes bad enough that the VMs see too much time pass?

**Comment by mfeit-internet2** [comment]
I can't tie this to anything unusual on either of the systems involved:  [ps-deb-2](http://perfsonar-testbed-ma.grnoc.iu.edu/ganglia/?c=Testbed&h=ps-deb-2.es.net&m=load_one&r=custom&s=by%20name&hc=4&mc=2&cs=03%2F19%2F2017%2009%3A12&ce=03%2F19%2F2017%2009%3A32),  [perfsonardev0](http://perfsonar-testbed-ma.grnoc.iu.edu/ganglia/?c=Testbed&h=perfsonardev0.internet2.edu&m=load_one&r=custom&s=by%20name&hc=4&mc=2&cs=03%2F19%2F2017%2009%3A12&ce=03%2F19%2F2017%2009%3A32).  The scheduling was attempted at about 09:22Z, and these charts show ten minutes on either side of that.

**Comment by mfeit-internet2** [comment]
As an experiment:  Add some code to `run_program()` to verify that the elapsed time is actually what we think it should be, i.e., that the time taken actually merits a timeout having occurred.

Kicking into 1.0 since we're in the realm of experimentation.
