### ISSUE TITLE
pscheduler returning "Unknown command" error 

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#376]
This is from ps-deb-2.es.net:

2017-03-18T06:42:42-07:00 - 2017-03-19T06:42:42-07:00  (Non-Starter)
latencybg --dest perfsonar-dev5.grnoc.iu.edu --packet-padding 0 --source ps-
  deb-2.es.net --ip-version 4 --packet-interval 0.1 --duration PT86400S --packet-
  count 600 (Run with tool 'powstream')
--
https://ps-deb-2.es.net/pscheduler/tasks/9e852a14-6cb7-468d-a142-f97d63cffe4d/runs/f2c00016-c33f-4410-a8cd-3fb15f18ac89

checking the results:

pscheduler results https://ps-deb-2.es.net/pscheduler/tasks/9e852a14-6cb7-468d-a142-f97d63cffe4d/runs/f2c00016-c33f-4410-a8cd-3fb15f18ac89
**results: Unknown command.  Use --help for help.**

**Comment by mfeit-internet2** [comment]
`result`.  No `s`.
