### ISSUE TITLE
remedies on the future "non-starter" runs in the schedule

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#381]
It is a fact, that based on casual circumstances, pscheduler may not be able to setup a future run(s) of a task  or more. Since pscheduler is operating on the future task run coordination it would be of great benefit to have a solution to deal with "non-starter" run cases.

1) have solution for manual intervention. effective in cases the sys admin identifies a problem with pscheduler, which prevented the daemon to operate properly and task runs are being set to fail.
I would see this solution as an option to: `pscheduler schedule` command. Possibly will reiterate all the non-starter runs and try to remedy the situation without impacting the current schedule.
I would not see this as a solution for the near 2-3h in the future.

2) It would be nice, if pscheduler daemon would automatically revise its own schedule for the distant horizon in between the 22-24h period and internally tries to remedy the non-starter cases. Perhaps, this can happen every 2h without a cron job.

**Comment by mfeit-internet2** [comment]
Closing per reference from other ticket.
