### ISSUE TITLE
Update tests to limit all parameters

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#390]
In reviewing @igarny's difficulties limiting throughput tests to having a source on a certain interface, I looked into  throughput's `limit-passes` and found that it only processes limits on the parameters that were limited by BWCTL.

Some of the other tests (at least the ones that I wrote that were intended for production use) can limit on every parameter.

Need to review all tests (including `simplestream`, which is now for production) and bring them up to snuff on that front.

**Comment by igarny** [comment]
Here is the initial request for this enhancement:
https://github.com/perfsonar/bwctl/issues/30

**Comment by igarny** [comment]
Hi guys my concerns with FW workaround / mitigation to the problem:

1. pSched will schedule tests, even if these are not allowed on the FW. Supposedly these would fail, but pSched will schedule retries. My understanding is that this can lead to a disaster for the pscheduler timeline, depending on the frequency and the retry policy of the pschedulers (leader side)
2. In a case where the FW is configured only on the ingress side this can lead to successful disruptive tests.

**Comment by daldoyle** [comment]
Dan Doyle
GlobalNOC Software Developer
1-812-856-3892
daldoyle@globalnoc.iu.edu

> On Mar 31, 2017, at 10:56 AM, Ivan Garnizov <notifications@github.com> wrote:
> 
> Hi guys my concerns with FW workaround / mitigation to the problem:
> 
> pSched will schedule tests, even if these are not allowed on the FW. Supposedly these would fail, but pSched will schedule retries. My understanding is that this can lead to a disaster for the pscheduler timeline, depending on the frequency and the retry policy of the pschedulers (leader side)

There is no retry for tests, only for archiving results. This will have no impact on the scheduling timeline. You will just have a bunch of failed tests if it is misconfigured to the wrong interface, at which point you can correct the configuration and then everything will work fine.

> In a case where the FW is configured only on the ingress side this can lead to successful disruptive tests.
> —
> 

Yep, this is why we're going to work on fixing it. That being said, the impact of this is relatively low in most cases - occasionally you might see some loss in a few owamp tests if the the interface is being saturated.

**Comment by arlake228** [comment]
May need to split out, but main issue is some tests don't limit on source and dest. Probably need to write some library calls and update tools.

**Comment by igarny** [comment]
Hi guys,
Thanks for looking into this.
WRT the initial communication it seems to me we are missing a configuration definition for each tool for allowed interfaces to run/bind. Here I am referring to the `/etc/pscheduler/tool/*.conf`
Please consider also support for Namespaces in the syntax.
I would suggest Namespaces to go along with network interfaces description. Examples for allowed interfaces on measurement:
- local network interface: eth0
- namespace: LNN:eth0
- IP address: (I believe is superficial)
