### ISSUE TITLE
add support for new iperf flags, --fq-rate in particular

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#394]
iperf 2.0.9 adds some useful output info via a new '-e' command line flag.

We should consider adding support for this to v1.1.

eg:
./iperf -e -c antg-staging -i1
------------------------------------------------------------
Client connecting to antg-staging, TCP port 5001 with pid 22911
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  3] local 131.243.24.11 port 48084 connected with 198.128.151.25 port 5001
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 0.00-1.00 sec   102 MBytes   858 Mbits/sec  818/0        299     1090K/10000 us
[  3] 1.00-2.00 sec   111 MBytes   933 Mbits/sec  890/0          0     1186K/10000 us
[  3] 2.00-3.00 sec   110 MBytes   927 Mbits/sec  884/0          0     1220K/9875 us
[  3] 3.00-4.00 sec   111 MBytes   934 Mbits/sec  891/0          0     1221K/9875 us
[  3] 4.00-5.00 sec   112 MBytes   937 Mbits/sec  894/0          0     1223K/9875 us
[  3] 5.00-6.00 sec   114 MBytes   952 Mbits/sec  908/0          0     1230K/10000 us
[  3] 6.00-7.00 sec   111 MBytes   933 Mbits/sec  890/0          0     1238K/10750 us
[  3] 7.00-8.00 sec   113 MBytes   949 Mbits/sec  905/0          0     1271K/9875 us
[  3] 8.00-9.00 sec   112 MBytes   936 Mbits/sec  893/0          0     1271K/9875 us
[  3] 9.00-10.00 sec   112 MBytes   937 Mbits/sec  894/0          0     1271K/9875 us
[  3] 0.00-10.00 sec  1.08 GBytes   929 Mbits/sec  8867/0        299     1271K/9875 us

**Comment by bltierney** [comment]
re-requesting this, as I'd really l to see the iperf2 '-e' results, due to this iperf3 bug: 
https://github.com/esnet/iperf/issues/382

It would also be nice to include support for the new iperf2.0.13 flag --fq-rate

**Comment by mfeit-internet2** [comment]
Comparison of without and with `-e`:

```
$ iperf -c localhost
------------------------------------------------------------
Client connecting to localhost, TCP port 5001
TCP window size: 2.50 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 54552 connected with 127.0.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  50.5 GBytes  43.3 Gbits/sec

$ iperf -c localhost -e
------------------------------------------------------------
Client connecting to localhost, TCP port 5001 with pid 104773
Write buffer size:  128 KByte
TCP window size: 2.50 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 52858 connected with 127.0.0.1 port 5001
[ ID] Interval        Transfer    Bandwidth       Write/Err  Rtry    Cwnd/RTT
[  3] 0.00-10.00 sec  50.6 GBytes 43.4 Gbits/sec  414184/0   0       3005K/44 us
```

Comments/questions:

 * `Write` - Number of writes?
 * `Err` - Write errors?
 * `Rtry` - Same as retransmits?
 * `Cwnd` - No idea what this is.
 * `RTT` - Not something we usually report.

**Comment by bltierney** [comment]
from the iperf2 man page (hidden near the bottom): https://iperf2.sourceforge.io/iperf-manpage.html

Write/Err: Total number of successful socket writes. Total number of non-fatal socket write errors
Rtry: Total number of TCP retries
Cwnd/RTT: TCP congestion window and round trip time (sampled where NA indicates no value)
 
so to map to iperf3 output:
[ ID] Interval           Transfer     Bitrate                       Retr  Cwnd
[  5]   0.00-1.00   sec  4.00 MBytes  33.5 Mbits/sec    0    575 KBytes
[  5]   1.00-2.00   sec  29.9 MBytes   251 Mbits/sec    0   4.55 MBytes

Rtry = Retr
Cwnd = Cwnd

**Comment by mfeit-internet2** [comment]
Upgrading iperf2 to the latest.  To do:

- [ ] Build for Debuntu
- [ ] Adjust RPM spec to require new version
- [ ] Adjust plugin run method to report additional results

**Comment by mfeit-internet2** [comment]
Still having difficulties with the random-ish order of lines produced by iperf2 around the final summary.
