### ISSUE TITLE
Port drop-in package to Debian

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#404]
We should port and add the `drop-in` package to our repository.  For Debian, we don't need it for the pscheduler, but it is also used by the toolkit from the `configure_esmond` script.

**Comment by mfeit-internet2** [comment]
FYI, at some point in the future, I want to get all of the third-party stuff (which includes `drop-in`; I maintain and distribute it separately from perfSONAR) into a separate repository.

**Comment by tonin** [comment]
Are you referring to a separate RPM/Debian repo or a git repo?  Because we already have some other places for this kind of things:
 1. a distinct git repo for third party stuff that are not available in the official distro repos at https://github.com/perfsonar/minor-packages/ packages built from there end up in the main perfsonar RPM/Debian repositories so to satisfy the dependencies (as the other 3rd party packages in the pscheduler git repo)
 1. separate RPM and Debian repos ready at http://downloads.perfsonar.net/redhat/branches/extras/ and http://downloads.perfsonar.net/debian/dists/perfsonar-jessie-extras/ to host 3rd party packages coming from outside of the project

Do we need yet another repo?

IMHO `drop-in` would fit in 1.

**Comment by vvidic** [comment]
On Tue, Apr 11, 2017 at 10:00:33AM -0700, Antoine Delvaux wrote:
> Are you referring to a separate RPM/Debian repo or a git repo?  Because we already have some other places for this kind of things:
>  1. a distinct git repo for third party stuff that are not available in the official distro repos at https://github.com/perfsonar/minor-packages/ packages built from there end up in the main perfsonar RPM/Debian repositories so to satisfy the dependencies (as the other 3rd party packages in the pscheduler git repo)
>  1. separate RPM and Debian repos ready at http://downloads.perfsonar.net/redhat/branches/extras/ and http://downloads.perfsonar.net/debian/dists/perfsonar-jessie-extras/ to host 3rd party packages coming from outside of the project

configure_esmond is already patched on our side, so we don't need it
immediately, but we can package it after the release so we have it
ready.

Just let me know if it stays in pscheduler repo or we move it somewhere
else.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
FYI, the original sources for drop-in are at https://github.com/markfeit/drop-in.  License is Apache 2.0, just like perfSONAR.

**Comment by vvidic** [comment]
On Mon, May 08, 2017 at 08:10:11AM -0700, Mark Feit wrote:
> FYI, the original sources for drop-in are at
> https://github.com/markfeit/drop-in.  License is Apache 2.0, just like
> perfSONAR.

Ok, guess we can take v1.4 from there and package that.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
drop-in v1.4 is packaged now in the pscheduler repo.
