### ISSUE TITLE
Systemd isn't daemonizing daemons

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#414]
On CentOS 7, the [template used for systemd](https://github.com/perfsonar/pscheduler/blob/master/pscheduler-server/pscheduler-server/daemons/service-template.raw) doesn't use the `--daemon` switch when starting the daemons.  This results in the crash-proofing code in the daemons not being enabled and the process bombing out if it encounters a failure (PostgreSQL not being up in the observed case.)

To Do:

- [x] Add `--daemon` to `ExecStart`
- [x] Set up proper dependencies so Pg is started first.  (Optional; program will flail until it does.)

**Comment by vvidic** [comment]
Created pull request #418

**Comment by mfeit-internet2** [comment]
Fixed with vvidic's commits.  Closing.
