### ISSUE TITLE
confirm that iperf3 retransmit info is captured correctly

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#417]
I'm seeing many plots like this where retransmits went away after the upgrade:

http://ps-dashboard.es.net/perfsonar-graphs/?url=http://hous-pt1.es.net:8085/esmond/perfsonar/archive&source=192.12.137.251&dest=198.129.254.50&url=http://hous-pt1.es.net:8085/esmond/perfsonar/archive&source=192.12.137.251&dest=198.129.254.66&#start=1490365406&end=1493043806&summaryWindow=3600&timeframe=1m

This might be due to some fix in CentOS 6.9, or might be due to a bug. Need to confirm all is working as expected.

**Comment by arlake228** [comment]
Confirmed this was a problem with archiver and fixed in latest update that is in yum repo.
