### ISSUE TITLE
retransmits not getting archived to esmond

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#421]
Looking at the archiver code and some esmond results, it looks like retransmits are not getting archived at all. Not sure how this ever worked, should be fixed later today.

**Comment by bltierney** [comment]
While you are in that code: Are we archiving 1 second samples for any of the TCP_info stuff?

For the X-Swap project, it would be useful to have the interval results for retransmits, rrt_max, and maybe others.
