### ISSUE TITLE
pscheduler tool iperf2 lacks a config file

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#425]
many other tools in pscheduler have their configuration controlled by a config file in the /etc/pscheduler/tool folder
example: CONFIG_FILE 
https://github.com/perfsonar/pscheduler/blob/81ce7f5cd76315340239f1eb1ac0df71c1490c44/pscheduler-tool-iperf3/iperf3/iperf3_defaults.py

iperf2 though misses such config file.

**Comment by daldoyle** [comment]
Done in dd546a0b18da6e7eb5dcec8f53b2d5441cd616dc
