### ISSUE TITLE
ping tool does not properly detect IPv6 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#431]
If you try to do an IPv6 ping using two hostnames that only have AAAA records, you get the following:

`Unable to resolve destination 'lbl-pt1-v6.es.net'`

I also note that if you don't explicitly specify `ip-version` it will use ping instead of ping6. It should likely use the `pscheduler.ip_normalize_version` library call to fix both of these problems.

**Comment by vvidic** [comment]
Seems that `dns_bulk_resolve` is by default using IPv4/A. Can you try the following change:

```
 if dest_ip_addr is None:
-    dest_ip_map = pscheduler.dns_bulk_resolve([dest])
+    dest_ip_map = pscheduler.dns_bulk_resolve([dest], ip_version=ipversion)
     dest_ip_addr = dest_ip_map[dest]
```

**Comment by arlake228** [comment]
The proposed patch is only part of the fix. Also need do the correct thing when ipversion is not specified, including pick ping6 of ping. Working on full fix now.
