### ISSUE TITLE
test iperf 3.2

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#444]
Bruce wrote an email saying that he thinks he has a version of iperf3.2 that is worth testing (currently at master branch in git).  From the note....

1.  We fixed a bunch of (mostly minor) statistics and reporting bugs.
Mostly these affected the human-readable output, but one change that
affects the JSON is that at least for TCP tests, the statistics for each
end of the test should be consistent and correct across both the client
and server.  (We still have this problem for UDP, in that we sometimes
use a mishmash of sender-side and receiver-side numbers to compute some
things, and it's not necessarily easy to fix.  In theory this shouldn't
be a huge difference in the reported values.)

2.  It should be possible to connect from iperf 3.1 to iperf 3.2 and
vice versa (I already fixed one bug in this area).

3.  I imported a recent cJSON, mostly for bugfixes (they've been doing a
lot of work the past 6 months or so).  In my testing so far this works
about the same as what we had before and I hope that the rest of
perfSONAR sees it the same way.

4.  The new authentication feature requires openssl (it's auto-detected
at compile-time).  I haven't decided whether to adjust the RPM spec file
to now make openssl a dependency for iperf3 or not.  Right now I'm kind
of +0 on this.  Mostly because it's likely the build machine will have
openssl on it for other reasons, so if we auto-detect, the binary RPM
package will pick it the dependency anyway.  Your input would be
appreciated.

**Comment by mfeit-internet2** [comment]
Re. 4:  I'd require it for build and installation.  That way there's no chance that a compiled binary will fail to work on a system that didn't otherwise have OpenSSL on it.

**Comment by daldoyle** [comment]
Tested this and it seems to work fine on EL7 but there are issues on EL6, including message I sent to Bruce below...

[daldoyle@daldoyle-dev-6 iperf]$ rpm -qa iperf3
iperf3-3.1.6-1.el6.x86_64

[daldoyle@daldoyle-dev-6 iperf]$ bwctl -T iperf3 -c perfsonar-dev5.grnoc.iu.edu
bwctl: Using tool: iperf3
<results as normal>


<yum upgrade from built source>

[daldoyle@daldoyle-dev-6 iperf]$ rpm -qa iperf3
iperf3-3.2.0-1.el6.x86_64

[daldoyle@daldoyle-dev-6 iperf]$ bwctl -T iperf3 -c perfsonar-dev5.grnoc.iu.edu
bwctl: Requested tools supporting the requested options not available by both servers. See the '-T' option
bwctl: Available tools that support the requested options: iperf nuttcp

**Comment by daldoyle** [comment]
This was all resolved and release. The el6 vs el7 was a red herring, turns out bwctl only checks for available tools on startup and it just happened that I only restarted it on el6. Had to adjust bwctl to allow for "iperf-3.2" as an acceptable string and otherwise things seem good to go, did the release last week.
