### ISSUE TITLE
Diagnostics for when MTU issue are affecting pscheduler HTTP traffic

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#449]
Jason Z and I ran into an issue today where path MTU discovery was not working which was causing pscheduler control traffic to hang. On the surface it looked like a firewall issue as connections to 443 would just hang, but in fact it had nothing to do with the port and was just because of the message size. 

It might be nice to add a diagnostic utility (or as part of a larger diagnostic utility) to send pings of a few different sizes and capture the results. This type of thing will likely be common for our uses cases since we have a mix of standard and jumbo frames out in the wild. This is not generally the first thing you'll look for, so might be nice to have a tool that will point you in the right direction if this is the case.

**Comment by mfeit-internet2** [comment]
This would be a nice addition to #405.

**Comment by mfeit-internet2** [comment]
Might be more useful to just have a MTU test/tool pair that figures this out

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added MTU diagnostics to the troubleshooter.
