### ISSUE TITLE
Reducing the dependencies of pscheduler-core

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#450]
Reported by Brian Candler.

**pscheduler-core** has a hard dependency on gnuplot that attracts a lot of unneeded dependencies.  See the discussion on [the perfsonar-user list](https://lists.internet2.edu/sympa/arc/perfsonar-user/2017-05/msg00063.html).  If we can lower that dependency to `gnuplot5-nox` that could remove a few of these.

Further improvement to reduce the list of dependencies is to install the perfsonar bundle packages with the apt option `--no-install-recommends`.  We should document this possibility in the installation instructions.

This is for Debian (7|8), but the same is probably true for CentOS that also has a gnuplot dependency.

**Comment by vvidic** [comment]
On Thu, May 18, 2017 at 09:12:30AM -0700, Antoine Delvaux wrote:
> **pscheduler-core** has a hard dependency on gnuplot that attracts a lot of unneeded dependencies.  See the discussion on [the perfsonar-user list](https://lists.internet2.edu/sympa/arc/perfsonar-user/2017-05/msg00063.html).  If we can lower that dependency to `gnuplot5-nox` that could remove a few of these.
> 
> Further improvement to reduce the list of dependencies is to install the perfsonar bundle packages with the apt option `--no-install-recommends`.  We should document this possibility in the installation instructions.
> 
> This is for Debian (7|8), but the same is probably true for CentOS that also has a gnuplot dependency.

Today I already changed that to:

  Recommends: gnuplot-nox | gnuplot

Unfortunately gnuplot-nox also pulls in X11 libraries so the
installation is not that smaller than gnuplot-qt :)  But like
you mentioned people can at least skip installing recommended
packages.

Don't think we can do the same on the RPM side because it only
has the hard Requires dependency.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by tonin** [comment]
>  Recommends: gnuplot-nox | gnuplot

Can it be a `Recommends: ` instead of a `Depends: ` as it is needed by the plotting part of pscheduler?

Maybe we should look at moving the pscheduler code related to plotting into its own package and don't make it part of the perfsonar-testpoint bundle?

**Comment by mfeit-internet2** [comment]
I just checked and discovered that CentOS 6 and 7 have a `gnuplot-minimal` that can do the PNG output I need:
 
```
================================================================================
 Package                Arch          Version                 Repository   Size
================================================================================
Installing:
 gnuplot-minimal        x86_64        4.6.2-3.el7             base        629 k
Installing for dependencies:
 gd                     x86_64        2.0.35-26.el7           base        146 k
 gnuplot-common         x86_64        4.6.2-3.el7             base        595 k

Transaction Summary
================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 1.3 M
Installed size: 3.4 M
```

The package needs the DajaVu-Sans font (in `dejavu-sans-fonts`) or it will flop back to something not scalable.  The RPM doesn't have this dependency, so it will be need to be manually added to `pscheduler-core`'s spec.

**Comment by vvidic** [comment]
On Thu, May 18, 2017 at 09:29:29AM -0700, Antoine Delvaux wrote:
> Can it be a `Recommends: ` instead of a `Depends: ` as it is needed by the plotting part of pscheduler?
> 
> Maybe we should look at moving the pscheduler code related to plotting into its own package and don't make it part of the perfsonar-testpoint bundle?

Since plotting is not the main purpose of pscheduler I guess we
can recommend it, but not force it :)  Default installations will
get gnuplot and user can override that if needed.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by bltierney** [comment]
using gnuplot-minimal sounds like a good option to me.

Perhaps we should also generate a package called pscheduler-minimal, that leaves out things like gnuplot entirely?

I also noticed this pscheduler dependency, which will also bloat the image:

python-py-radix/python-py-radix.spec:BuildRequires:     gcc

What is that used by? Does it really need gcc?

**Comment by vvidic** [comment]
On Thu, May 18, 2017 at 10:11:53AM -0700, Brian Tierney wrote:
> using gnuplot-minimal sounds like a good option to me.
> 
> Perhaps we should also generate a package called pscheduler-minimal, that leaves out things like gnuplot entirely?
> 
> I also noticed this pscheduler dependency, which will also bloat the image:
> 
> python-py-radix/python-py-radix.spec:BuildRequires:     gcc
> 
> What is that used by? Does it really need gcc?

Package probably has some C code, so gcc is needed during build
time.  But that should not matter during package installation.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
I'll make the change to the CentOS version after this ticket has been pushed through the  workflow.

> Perhaps we should also generate a package called pscheduler-minimal, that leaves out things like gnuplot entirely?

I don't think there's a need for that.  pScheduler's packaging is already as finely-grained as I can make it without going overboard.  I think the comment I made to Brian Candler in email may have made the absolute number less of an issue.

 > python-py-radix/python-py-radix.spec:BuildRequires: gcc

As Valentin pointed out, `BuildRequires` dependencies don't carry into installation of the finished product.

**Comment by tonin** [comment]
Everything's ready on the Debian side, including documentation.  So I'll assign this to you @mfeit-internet2
