### ISSUE TITLE
API replacing authentication-related values with 'null'

### ISSUE THREAD

**Issue by akarahman** [perfsonar/pscheduler#451]
When the API pulls JSON out, it replaces any name that has "_" as a prefix with null. As a result, all values with such names that are being taken from the command line and converted to the JSON spec will be changed to null and will not conform to the type associated with that value. 
Example output from pscheduler:
```javascript
$ pscheduler task --export snmp --version 2c --community demopublic --op walk --dest test.net-snmp.org
{
    "schema": 1,
    "test": {
        "spec": {
            "_community": null,
            "dest": "test.net-snmp.org",
            "op": "walk",
            "schema": 1,
            "version": "2c"
        },
        "type": "snmp"
    }
}

**Comment by mfeit-internet2** [comment]
Summary of the problem:
 * The `tests_name_spec()` function in the API's `tests.py` calls `ok_json()` with its result.
 * `ok_json()` calls `response_json_dump()` to produce a sanitized version of the JSON, which is stripping out the underscored value.

Add a `sanitze` argument to `response_json_dump()` that defaults to `True` pass that through the other functions to allow a function responding to a request to bypass sanitization.
