### ISSUE TITLE
Remove default apache welcome page

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#457]
A default install of pscheduler, without the toolkit package, displays the apache standard welcome page at the root URL.  This is both for CentOS and Debian installs.

Following recommendations from the security report, we should probably remove this page or put a redirect to some other place.

**Comment by mfeit-internet2** [comment]
That's a system configuration problem.  pScheduler doesn't presume to make changes to the system that don't involve itself.

**Comment by tonin** [comment]
Shouldn't we, as we add the apache dependency, also take care of that part of the system configuration?  In pscheduler packages or in the bundle packages maybe?

**Comment by tonin** [comment]
Issue moved to [perfsonar/toolkit #253](https://github.com/perfsonar/toolkit/issues/253) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tonin** [comment]
After discussion we decided it is better to put this in the toolkit-security package if anywhere.
