### ISSUE TITLE
'streaming' mode for archiver plugins

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#466]
This is an issue to track adding the option for an archiver to plugin to run in streaming mode. In this mode, pscheduler will launch the the archiver once and pipe input to it. This will save on python initialization overhead that seems to be the primary source of CPU utilization on hosts that do a lot of archiving. Consideration will need to be made about how we want to handle launching multiple archivers of the same type so we are not forced to serialize all requests of the same type.

**Comment by mfeit-internet2** [comment]
Other known to-dos:

- [ ] Bump python-pscheduler version number
- [ ] Make sure all archivers and pscheduler-server depend on that version.

**Comment by mfeit-internet2** [comment]
** Release Notes:**

Changed the interface to archivers to use a streaming I/O instead of invoking each one per result.
