### ISSUE TITLE
Empty error message from iperf3 failing test

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#474]
I think pscheduler should say something more specific in this error then just an empty line

[geantadmin@ps-small ~]$ pscheduler task throughput --destination psmp-gn-owd-01.gen.ch.geant.net
Submitting task...
Task URL:
https://ps-small.dev.ja.net/pscheduler/tasks/b0f94bd2-864e-4926-a571-9a630b91c9f3
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://ps-small.dev.ja.net/pscheduler/tasks/b0f94bd2-864e-4926-a571-9a630b91c9f3/runs/395d9e73-0f4c-4154-afe6-5f8b82548ae1
Starts 2017-06-09T16:34:16+02:00 (~35 seconds)
Ends   2017-06-09T16:34:35+02:00 (~18 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By ps-small.dev.ja.net:
    iperf3 returned an error:

By psmp-gn-owd-01.gen.ch.geant.net:
    iperf3 returned an error:

No runs scheduled for this task.
[geantadmin@ps-small ~]$ bwctl -c psmp-gn-owd-01.gen.ch.geant.net
bwctl: Unable to connect to psmp-gn-owd-01.gen.ch.geant.net
[geantadmin@ps-small ~]$ bwctl -T iperf3 -c psmp-gn-owd-01.gen.ch.geant.net
bwctl: Unable to connect to psmp-gn-owd-01.gen.ch.geant.net
[geantadmin@ps-small ~]$

**Comment by daldoyle** [comment]
Should be addressed by this:
https://github.com/perfsonar/pscheduler/commit/810c231914fdd7870db21b6673422bbcd5e6a031
iperf3 tool will now report stdout and stderr instead of the "error" field if the error field is empty
