### ISSUE TITLE
Preempt Future Runs for High-Priority Local Tasks

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#479]
Have a way to tell `task` that you want to preempt runs on the local system 

Consider add a `permissions` section to the limits file that would allow giving permission to do this to classifiers.

Complication:  If a run is canceled locally, this doesn't guarantee that the other participants will be willing to do the same on their schedules to accommodate it.  May need to schedule based on what would be canceled and actually do the cancellation when it's about to be set in stone.

**Comment by igarny** [comment]
Hi Mark,
Your concern on the complications is a very much valid one. 
In our pS 4.0 organization of throughout tests we use a single port for iperf3. IMHO this means that, if the remote party misses the info about the preemption or ignores it, it will then obsolete the measurement with the higher priority by running a test during the reserved period.
