### ISSUE TITLE
Context Changer Plugins

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#480]
Develop a new type of plug-in for changing run execution contexts.

See https://github.com/perfsonar/pscheduler/wiki/Contexts for overview.

**Comment by mfeit-internet2** [comment]
Finished version will need some checkout by @igarny; will discuss a few things with him in email.

**Comment by mfeit-internet2** [comment]
- [ ] Once `post-4.0.1` is pulled into `master`, the additional packages will have to be added to Debian.

**Comment by vvidic** [comment]
I think the context plugins are tracked in #540 now, so we can close this one?

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added plugins and task configuration for changing execution context (notably Linux network namespace) before running a task's tool.
