### ISSUE TITLE
API call to validate contexts

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#484]
The pSConfig project will need an API call to validate the definition of a context. Should take context JSON as input and output whether its valid. If invalid, it should include a message describing why it failed.

**Comment by mfeit-internet2** [comment]
Added a complete `/contexts` subtree to the API that mimics `/archivers`.  Will merge into the master when issue-480 is pulled.

Examples you'll care about:
```
curl -k 'https://localhost/pscheduler/contexts/linuxnns/data-is-valid?data=%7B%20%22namespace%22%3A%20%22floop%22%20%7D'
curl -k 'https://localhost/pscheduler/contexts/linuxnns/data-is-valid?data=%7B%7D'
```

**Comment by mfeit-internet2** [comment]
Going to re-open this until checked out.
