### ISSUE TITLE
API call to validate test spec

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#485]
The pSConfig project will need an API call to validate the definition of a test spec. Should take test spec JSON as input and output whether its valid. If invalid, it should include a message describing why it failed.

**Comment by mfeit-internet2** [comment]
@arlake228 Need a clarification:  Do you want to validate entire tasks or just the test spec?

**Comment by arlake228** [comment]
It just needs to be the test spec. My brain was thinking task for some reason when I wrote this, but definitely just needs to be the test spec. I am going to change the title to be clearer.

**Comment by mfeit-internet2** [comment]
Done.  Examples:
```
% curl -s -k 'https://localhost/pscheduler/tests/idle/spec/is-valid?pretty'
No test spec provided

% curl -s -k 'https://localhost/pscheduler/tests/idle/spec/is-valid?pretty&spec=%7B%22duration%22%3A%20%22PT2S%22%2C%20%22schema%22%3A%201%7D'
{
    "valid": true
}

% curl -s -k 'https://localhost/pscheduler/tests/idle/spec/is-valid?pretty&spec=%7B%22badkey%22%3A%20%22PT2S%22%2C%20%22schema%22%3A%201%7D'
{
    "error": "Additional properties are not allowed (u'badkey' was unexpected)",
    "valid": false
}
```
