### ISSUE TITLE
Add option to show details if 'expanded' set when listing tasks in API

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#487]
This is the pscheduler portion of perfsonar/mesh-config#58. The /tasks call currently supports setting the GET option `expanded=1` but the meshconfig also need the ability to set `details=1` and see the detail so if it knows whether a task is still running or has been cancelled. A note from the referenced issue made by @mfeit-internet2 :

> Note to self: Need to pull the code that generates the details from /tasks/get/xxx into a function and call it from /tasks/get when details and expanded are set.

**Comment by mfeit-internet2** [comment]
This is done on the `api-task-overhaul` branch.

`GET /pscheduler/tasks` supports `expanded` as it always did and now `details` if `expanded` is in effect.

`GET /pscheduler/tasks/<uuid>` supports `details` as it always has.

@arlake228 Please test (just need to build a fresh `pscheduler-server`), let me know how it goes and I'll merge it into the master.

**Comment by arlake228** [comment]
Looks like it works to me. Should be ok to merge.
