### ISSUE TITLE
Trace test result JSON schema uses host instead of hostname

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#490]
In pscheduler-test-trace/trace/validate.py the result_is_valid method indicates a hop object may contain a "host" key. It appears that all the trace plugins (traceroute, tracepath and paris-traceroute) actually fill this in as "hostname" instead of "host". I think the right thing to do here is update the schema since we already have lots of results using hostname. 

As far as I can tell nothing actually uses the "host" key name anywhere, but assigning to Mark to verify I am not missing anything. Assuming that's all it is, just just be a matter of changing "host"->"hostname" at https://github.com/perfsonar/pscheduler/blob/master/pscheduler-test-trace/trace/validate.py#L54

**Comment by mfeit-internet2** [comment]
Yup, that was an oversight.  Fixed.
