### ISSUE TITLE
pscheduler - iperf3 failure: Exception [Errno 101] Network is unreachable

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#491]
Hi guys,

As reported by email and in the comment following the initial opening. There is a failure / exception reported on the local sender side in a iperf3 test.

```
Jun 22 11:12:55 psmp-lhc-mgmt-01-gen-ch tool-iperf3/run DEBUG    ['Traceback (most recent call last):', '  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/run", line 373, in <module>\
n    results = run_client()', '  File "/usr/libexec/pscheduler/commands/../classes/tool/iperf3/run", line 222, in run_client\n    affinity = pscheduler.source_affinity(normalized_dest, ip_version=i
p_version)', '  File "/usr/lib/python2.6/site-packages/pscheduler/interface.py", line 20, in source_affinity\n    (address, intf) = source_interface(addr, ip_version=ip_version)', '  File "/usr/lib
/python2.6/site-packages/pscheduler/interface.py", line 38, in source_interface\n    s.connect((addr,port))', '  File "<string>", line 1, in connect', 'error: [Errno 101] Network is unreachable']
Jun 22 11:12:55 psmp-lhc-mgmt-01-gen-ch tool-iperf3/run ERROR    Exception [Errno 101] Network is unreachable
```

This server participates in a mesh with 4 other servers and the only failures I have are with this server as a source participant on IPv6 test.

Please hint me on the tool to use to reproduce this failure on a CLI.

**Comment by igarny** [comment]
psmp-lhc-mgmt-01-gen-ch ~]$ pscheduler task --debug --lead-bind psmp-lhc-bind-01-gen-ch.geant.net throughput --omit PT5S --duration PT30S --source-node psmp-lhc-bw-01-gen-ch-v6.geant.net --source psmp-lhc-bw-01-gen-ch-v6.geant.net --ip-version 6 --dest-node psmp-lhc-bw-01-fra-de-v6.geant.net --dest psmp-lhc-bw-01-fra-de-v6.geant.net --parallel 1
<result as below>
psmp-lhc-mgmt-01-gen-ch ~]$ pscheduler task --debug --lead-bind psmp-lhc-bind-01-gen-ch.geant.net throughput --omit PT5S --duration PT30S --source psmp-lhc-bw-01-gen-ch-v6.geant.net --ip-version 6 --dest psmp-lhc-bw-01-fra-de-v6.geant.net --parallel 1
2017-06-21T15:39:35 Debug signal ignored; already not debugging
2017-06-21T15:39:35 Debug discontinued
2017-06-21T15:39:35 Assistance is from localhost
2017-06-21T15:39:35 Forcing default slip of PT5M
2017-06-21T15:39:35 Converting to spec via https://localhost/pscheduler/tests/throughput/spec
Submitting task...
2017-06-21T15:39:35 Fetching participant list
2017-06-21T15:39:35 Spec is: {"source": "psmp-lhc-bw-01-gen-ch-v6.geant.net", "ip-version": 6, "dest": "psmp-lhc-bw-01-fra-de-v6.geant.net", "duration": "PT30S", "omit": "PT5S", "parallel": 1, "schema": 1}
2017-06-21T15:39:36 Got participants: {u'participants': [u'psmp-lhc-bw-01-gen-ch-v6.geant.net', u'psmp-lhc-bw-01-fra-de-v6.geant.net']}
2017-06-21T15:39:36 Lead is psmp-lhc-bw-01-gen-ch-v6.geant.net
2017-06-21T15:39:36 Pinging https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/
2017-06-21T15:39:36 psmp-lhc-bw-01-gen-ch-v6.geant.net is up
2017-06-21T15:39:36 Posting task to https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks
2017-06-21T15:39:36 Data is {"test": {"type": "throughput", "spec": {"source": "psmp-lhc-bw-01-gen-ch-v6.geant.net", "ip-version": 6, "dest": "psmp-lhc-bw-01-fra-de-v6.geant.net", "duration": "PT30S", "omit": "PT5S", "parallel": 1, "schema": 1}}, "schedule": {"slip": "PT5M"}, "lead-bind": "psmp-lhc-bind-01-gen-ch.geant.net", "schema": 1}
Task URL:
https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390
2017-06-21T15:39:44 Posted https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390
Running with tool 'iperf3'
Fetching first run...
2017-06-21T15:39:44 Fetching https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390/runs/first
2017-06-21T15:39:46 Handing off: pscheduler watch --format text/plain --debug https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390
2017-06-21T15:39:46 Debug signal ignored; already not debugging
2017-06-21T15:39:46 Debug discontinued
2017-06-21T15:39:46 Fetching https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390

Next scheduled run:
https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390/runs/f58b5f55-4e23-4584-9ecc-e8160fc36bcb
Starts 2017-06-21T15:39:54Z (~7 seconds)
Ends   2017-06-21T15:40:38Z (~43 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By psmp-lhc-bw-01-gen-ch-v6.geant.net:
      (No error reported)

By psmp-lhc-bw-01-fra-de-v6.geant.net:
    iperf3 returned an error:

No further runs scheduled.




psmp-lhc-mgmt-01-fra-de ~]$ grep 94325 /var/log/pscheduler/pscheduler.log
Jun 21 15:51:29 psmp-lhc-mgmt-01-fra-de runner DEBUG    Run 94325, starts at 2017-06-21 15:51:35+00:00
Jun 21 15:51:29 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Thread running
Jun 21 15:51:29 psmp-lhc-mgmt-01-fra-de runner DEBUG    Putting runs on deck: [94325L]
Jun 21 15:51:29 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Lead bind for this run is psmp-lhc-bind-01-gen-ch.geant.net
Jun 21 15:51:29 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Sleeping 0:00:05.951996 until test start
Jun 21 15:51:35 psmp-lhc-mgmt-01-fra-de runner INFO     94325: Running https://psmp-lhc-mgmt-01-fra-de.geant.net/pscheduler/tasks/ee97ac6b-1922-4239-9bb3-c19ad8aacfaf/runs/201593f7-b83a-47e2-85fd-f1a47da39c4c
Jun 21 15:51:35 psmp-lhc-mgmt-01-fra-de runner INFO     94325: With iperf3: throughput --omit PT5S --duration PT30S --source psmp-lhc-bw-01-gen-ch-v6.geant.net --ip-version 6 --dest psmp-lhc-bw-01-fra-de-v6.geant.net --parallel 1
Jun 21 15:51:35 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Tool input: {"task-uuid": "ee97ac6b-1922-4239-9bb3-c19ad8aacfaf", "participant": 1, "schedule": {"duration": "PT44S", "start": "2017-06-21T15:51:35Z"}, "participant-data": [{}, {"server_port": 5201}], "test": {"type": "throughput", "spec": {"dest": "psmp-lhc-bw-01-fra-de-v6.geant.net", "omit": "PT5S", "source": "psmp-lhc-bw-01-gen-ch-v6.geant.net", "ip-version": 6, "duration": "PT30S", "parallel": 1, "schema": 1}}, "limits-passed": [[{"duration": {"range": {"upper": "PT60S", "lower": "PT5S"}}, "udp": {"match": false}}]], "schema": 1}
Jun 21 15:51:35 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Start time difference is 0:00:00.016685
Jun 21 15:52:17 psmp-lhc-mgmt-01-fra-de runner INFO     94325: Run succeeded.
Jun 21 15:52:17 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Run returned {"succeeded": false, "error": "iperf3 returned an error: "}
Jun 21 15:52:17 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Stored local result
Jun 21 15:52:17 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Run complete
Jun 21 15:52:17 psmp-lhc-mgmt-01-fra-de runner DEBUG    94325: Thread finished


psmp-lhc-mgmt-01-gen-ch ~]$ grep 94560 -A 2 /var/log/pscheduler/pscheduler.log
Jun 21 15:39:54 psmp-lhc-mgmt-01-gen-ch runner INFO     94560: Running https://psmp-lhc-mgmt-01-gen-ch.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390/runs/f58b5f55-4e23-4584-9ecc-e8160fc36bcb
Jun 21 15:39:54 psmp-lhc-mgmt-01-gen-ch runner INFO     94560: With iperf3: throughput --omit PT5S --duration PT30S --source psmp-lhc-bw-01-gen-ch-v6.geant.net --ip-version 6 --dest psmp-lhc-bw-01-fra-de-v6.geant.net --parallel 1
Jun 21 15:39:57 psmp-lhc-mgmt-01-gen-ch tool-iperf3/run ERROR    Exception [Errno 101] Network is unreachable
Jun 21 15:39:57 psmp-lhc-mgmt-01-gen-ch runner INFO     94560: Run succeeded.
Jun 21 15:40:01 psmp-lhc-mgmt-01-gen-ch runner INFO     82541: Posted result to https://psmp-lhc-owd-01-gen-ch-v4.geant.net/pscheduler/tasks/593b453c-7eaa-4c9f-8e8f-487fb1d6de75/runs/c8e3a524-0121-405a-af2a-53dc5b478cff
Jun 21 15:40:03 psmp-lhc-mgmt-01-gen-ch runner INFO     89705: Posted result to https://psmp-lhc-owd-01-gen-ch-v6.geant.net/pscheduler/tasks/e214e744-1b20-44db-9034-c5a33dc14262/runs/eddad2e2-bd07-4e39-9c81-451194024816




psmp-lhc-mgmt-01-gen-ch ~]$ sudo traceroute6 -s psmp-lhc-bind-01-gen-ch.geant.net psmp-lhc-bw-01-fra-de-v6.geant.net
traceroute to psmp-lhc-bw-01-fra-de-v6.geant.net (2001:798:111:1::5a), 30 hops max, 80 byte packets
1  2001:798:111:1::65 (2001:798:111:1::65)  0.335 ms  0.498 ms  0.491 ms
2  2001:798:111:1::5d (2001:798:111:1::5d)  8.972 ms  8.962 ms  8.936 ms
3  psmp-lhc-bw-01-fra-de-v6.geant.net (2001:798:111:1::5a)  8.526 ms  8.714 ms  8.701 ms

psmp-lhc-mgmt-01-gen-ch ~]$ iperf3 -c psmp-lhc-bw-01-fra-de-v6.geant.net -B psmp-lhc-bw-01-gen-ch-v6.geant.net -6 -p 5201
Connecting to host psmp-lhc-bw-01-fra-de-v6.geant.net, port 5201
[  4] local 2001:798:111:1::66 port 38049 connected to 2001:798:111:1::5a port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   838 MBytes  7.03 Gbits/sec    0   12.7 MBytes
[  4]   1.00-2.00   sec  1.14 GBytes  9.78 Gbits/sec    0   12.8 MBytes
[  4]   2.00-3.00   sec  1.15 GBytes  9.88 Gbits/sec    0   12.8 MBytes
[  4]   3.00-4.00   sec  1.15 GBytes  9.88 Gbits/sec    0   12.8 MBytes
[  4]   4.00-5.00   sec  1.15 GBytes  9.88 Gbits/sec    0   12.8 MBytes
[  4]   5.00-6.00   sec  1.15 GBytes  9.88 Gbits/sec    0   12.8 MBytes
[  4]   6.00-7.00   sec  1.15 GBytes  9.88 Gbits/sec    0   12.8 MBytes
^C[  4]   7.00-7.85   sec   998 MBytes  9.88 Gbits/sec    0   12.8 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-7.85   sec  8.68 GBytes  9.50 Gbits/sec    0             sender
[  4]   0.00-7.85   sec  0.00 Bytes  0.00 bits/sec                  receiver
iperf3: interrupt - the client has terminated

**Comment by mfeit-internet2** [comment]
At least one problem in play here is that `pscheduler.source_interface()` should be catching `socket.error` and not `socket.gaierror`.

**Comment by mfeit-internet2** [comment]
Can you run this program on `psmp-lhc-mgmt-01-gen-ch` and `psmp-lhc-bw-01-gen-ch-v6.geant.net` and paste in the output?
```
#!/usr/bin/python

import pscheduler
import socket

for host in [
        ("source", "psmp-lhc-bw-01-gen-ch-v6.geant.net"),
        ("source-node", "psmp-lhc-bw-01-gen-ch-v6.geant.net"),
        ("dest", "psmp-lhc-bw-01-fra-de-v6.geant.net"),
        ("dest-node", "psmp-lhc-bw-01-fra-de-v6.geant.net"),
        ("lead-bind", "psmp-lhc-bind-01-gen-ch.geant.net")
        ]:
    key, fqdn = host
    try:
        interface = pscheduler.source_interface(fqdn, ip_version=6)
    except Exception as ex:
        interface = str(ex)

    print key, "-", fqdn
    print "   IP       ", pscheduler.dns_resolve(fqdn, ip_version=6)
    print "   Interface", interface
    print

```

**Comment by igarny** [comment]
in fact in my version of the file, I do not have this exception handling. The script makes straight assignments. The version on my side is:
python-pscheduler-1.3.0.2-1.el6.noarch

below is the output of the script:
```
[dfn.garnizov@psmp-lhc-mgmt-01-gen-ch ~]$ ./test.py
source - psmp-lhc-bw-01-gen-ch-v6.geant.net
   IP        2001:798:111:1::66
   Interface ('2001:798:111:1::66', 'p2p1')

source-node - psmp-lhc-bw-01-gen-ch-v6.geant.net
   IP        2001:798:111:1::66
   Interface ('2001:798:111:1::66', 'p2p1')

dest - psmp-lhc-bw-01-fra-de-v6.geant.net
   IP        2001:798:111:1::5a
   Interface [Errno 101] Network is unreachable

dest-node - psmp-lhc-bw-01-fra-de-v6.geant.net
   IP        2001:798:111:1::5a
   Interface [Errno 101] Network is unreachable

lead-bind - psmp-lhc-bind-01-gen-ch.geant.net
   IP        2001:798:111:1::66
   Interface ('2001:798:111:1::66', 'p2p1')

```

**Comment by igarny** [comment]
psmp-lhc-mgmt-01-gen-ch ~]$ nc -vv -s psmp-lhc-bw-01-gen-ch-v6.geant.net psmp-lhc-bw-01-fra-de-v6.geant.net 443
Connection to psmp-lhc-bw-01-fra-de-v6.geant.net 443 port [tcp/https] succeeded!

**Comment by igarny** [comment]
psmp-lhc-mgmt-01-gen-ch ~]$ curl --interface psmp-lhc-bw-01-gen-ch-v6.geant.net -k https://psmp-lhc-bw-01-fra-de-v6.geant.net/pscheduler
"This is the pScheduler API server on psmp-lhc-bw-01-fra-de-v6.geant.net (psmp-lhc-mgmt-01-fra-de.geant.net)."

**Comment by igarny** [comment]
most likely this is what is happening:

psmp-lhc-mgmt-01-gen-ch ~]$ curl -k https://psmp-lhc-bw-01-fra-de-v6.geant.net/pscheduler                                         curl: (7) Failed to connect to 2001:798:111:1::5a: Network is unreachable

**Comment by igarny** [comment]
So here is the difference in the servers:
server with failures:
```
psmp-lhc-mgmt-01-gen-ch ~]$ curl -vv -k https://psmp-lhc-bw-01-fra-de-v6.geant.net/pscheduler                                     * About to connect() to psmp-lhc-bw-01-fra-de-v6.geant.net port 443 (#0)
*   Trying 2001:798:111:1::5a... Failed to connect to 2001:798:111:1::5a: Network is unreachable
* Success
* couldn't connect to host
* Closing connection #0
curl: (7) Failed to connect to 2001:798:111:1::5a: Network is unreachable
```

server without failures:
```
psmp-lhc-mgmt-01-ams-nl ~]$ curl -vv -k https://psmp-lhc-bw-01-fra-de-v6.geant.net/pscheduler             
* About to connect() to psmp-lhc-bw-01-fra-de-v6.geant.net port 443 (#0)
*   Trying 2001:798:111:1::5a... Connection timed out
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
```

It appears, that in the first case, the error leads to an exception, where in the second case, the lack of connectivity is just ignored. I could be wrong, since I have the assumption, that the `/usr/lib/python2.6/site-packages/pscheduler/interface.py` is missing the binding option on the connectivity verification and ignores the status from the socket opening.

This is the only difference I could find in the behavior of a running and a failing system.

**Comment by mfeit-internet2** [comment]
Based on your observations:

 * psmp-lhc-mgmt-01-gen-ch has nothing in its routing table that knows where to send packets bound for 2001:798:111:1::5a.  This suggests that the system is misconfigured.  Ping6 should confirm that.
 * psmp-lhc-mgmt-01-ams-nl has a route, but packets aren't making it to the other end.  This suggests a network problem.

Dan's code looks fine.  The socket used in the call to `connect()` is a datagram socket, so there's no packets sent.  cURL is using TCP, which does send packets.  Binding is not an issue here, because no matter which interface you bind with, the outgoing packets get sent based on what's in the routing table.

Close this if you think we're done; I don't see a pScheduler problem here.

**Comment by igarny** [comment]
A fix in the routing of the server is applied to operate as the rest of the servers.
Now I am getting the same "Connetction timed out" response, which does not break the script.
