### ISSUE TITLE
pscheduler - iperf3 report is misleading

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#492]
this issue is related to the #491 
There I see in the pscheduler output: 
```
Next scheduled run:
https://psmp-lhc-bw-01-gen-ch-v6.geant.net/pscheduler/tasks/32cea5cc-f00e-4c48-a1db-cc01a439e390/runs/f58b5f55-4e23-4584-9ecc-e8160fc36bcb
Starts 2017-06-21T15:39:54Z (~7 seconds)
Ends   2017-06-21T15:40:38Z (~43 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By psmp-lhc-bw-01-gen-ch-v6.geant.net:
      (No error reported)

By psmp-lhc-bw-01-fra-de-v6.geant.net:
    iperf3 returned an error:

No further runs scheduled.
```

when the real problem is with the exception on the local side as reported in #491 opening message

**Comment by daldoyle** [comment]
I believe this was already addressed in another ticket. If the error text is empty it will grab all of stderr and display that instead which should prevent the "empty error" problem indicated here.
