### ISSUE TITLE
Iperf3 report: minor inconvenience on the task/run diagnostic description 

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#494]
This host updates from nightly repo.

On this url 
https://psps-test2-mgmt.rrze.uni-erlangen.de/pscheduler/tasks/b5892cdc-c9ea-45e7-abee-fc981676115f/runs/d24d5681-cad5-4189-9b5c-e4db645fdda2?pretty

you will find messages with incorrectly parsed newline symbols:
"diags": "/usr/bin/iperf3 -s -1 --json -p 5201 -B test-pt1.es.net -4\n\n",
"diags": "Participant 1:\n/usr/bin/iperf3 -s -1 --json -p 5201 -B test-pt1.es.net -4\n\n\n",

**Comment by mfeit-internet2** [comment]
JSON doesn't permit raw newlines inside strings.  Any confirming parser will understand this and produce strings with proper newlines.

**Comment by mfeit-internet2** [comment]
...conforming...
