### ISSUE TITLE
command to reset the auth token for tasks already scheduled in the future

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#495]
Hi Mark,

It would be a nice feature to have the ability to update the auth token for a given archive destination/url based on a command.
This of course should require manual intervention and sudo privileges.

Thanks

**Comment by mfeit-internet2** [comment]
This seems like something that pSConfig would take care of nicely:  change the token in the config and the nodes will pick it up and replace existing tasks with new ones.

Please close this if that's satisfactory.

**Comment by mfeit-internet2** [comment]
Another (better) way to approach this would be rolling token replacement.

First iteration:

 * Add token 1 to the MA
 * Set mesh config to tasks that archive with token 1

Subsequent iterations:

 * Add token _n_ to the MA
 * Set mesh config to run tasks that archive with token _n_
 * Wait a reasonable amount of time for tasks with token _n - 1_ to have expired
 * Drop token _n - 1_ from the MA

I think given those two options, this can be closed.
