### ISSUE TITLE
Set no/long expiration when creating pscheduler account

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#503]
From [this comment](https://lists.internet2.edu/sympa/arc/perfsonar-user/2017-07/msg00007.html) in perfsonar-users.

- [x] See to it that the account never expires.
- [x] Use `chage` to force the password expiration off or very long.

**Comment by mfeit-internet2** [comment]
@vvidic Please propagate these changes into Debian and then close.

**Comment by vvidic** [comment]
``chage`` added to Debian ``postinst``.
