### ISSUE TITLE
Ability to control the schedule horizon through LIMITS or is there another prioritization method

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#504]
Hi Mark,
I believe it would be very beneficial to be able to control the schedule horizon for pS nodes of special interest to the owning organization.
There are pS nodes out there of high interest to the public, which may be overtaken by "random" requests for measurements, and thus become unavailable to measurements of the hosting organization.
In the past there was a promise for some sort of a prioritization solution, but I believe it would be sufficient to just allow certain parties to be able to schedule measurements further in the schedule horizon than others.

I have no idea to what further complications this may lead wrt implementation/development of pSconfig/mesh-config

**Comment by mfeit-internet2** [comment]
I think this would be better handled with priorities.  See #479.
