### ISSUE TITLE
Add internal for starting/stopping services

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#505]
It would be nice to have an internal called `service` that will do the right thing on the current platform to start, stop or restart services.

This would enable a `restart` command and also allow `internal db-change-password` to restart the services when run manually.  (Right now the latter just prints a reminder to do so.)

**Comment by mfeit-internet2** [comment]
Please check for issues with Debian (assuming systemd is used there as well).  I would recommend using the internal while it's installed to start, stop and restart things, but it probably isn't mandatory.

Close when finished.

**Comment by vvidic** [comment]
I can check the Debian side, but would need to have this change in the master branch if possible?

**Comment by mfeit-internet2** [comment]
Under the new branching scheme, this won't make it into master until the 4.1.5 branch has been released.  Being able to participate in that is another good reason to bring Debian into the development mainstream.

**Comment by vvidic** [comment]
Ok, need to check with Antoine how we are going to handle this on the Debian side than.

**Comment by mfeit-internet2** [comment]
Debian changes look good and have been pulled in.

**Comment by mfeit-internet2** [comment]
Re-opening.  Andy found a spot where the internal is used on upgrading systems before it's installed.

Need to do a full evaluation of all uses of the internal vs. systemctl.

**Comment by mfeit-internet2** [comment]
Checked everything over.  I think we're good.
