### ISSUE TITLE
Limits file troubleshooter

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#519]
This ticket is to track the progress of a script I wrote for Ivan for troubleshooting limits files.

It's peripherally-related to #139.

**Comment by mfeit-internet2** [comment]
Changes in the spec file will need to be merged into Debian build.

**Comment by mfeit-internet2** [comment]
I've been using this enough for other things that I'm happy with it.  Close after downstream work is done.

**Comment by vvidic** [comment]
``limit-diags`` command is visible now on the Debian side.
