### ISSUE TITLE
Use POST for test results.

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#52]
While implementing parallel flows for the iperf tools, it looks like I have run into a URI limit while sending back the test output. It's quite a lot of output.

Looking through the apache logs and talking with Mark quickly, it sounds like we are using "PUT" requests here, which have a URI limit of ~8k characters. We should convert this to using "POST" since the limit there is significantly higher and arguably is more correct in the REST model.

In particular this was the results coming out of "run" I think, but it might be worth checking out any other places we may expect there to be large-ish arbitrary data coming out of things.

**Comment by mfeit-internet2** [comment]
Current code (runner) does a PUT to `/pscheduler/tasks/T/runs/R`.

Rearrange the REST API such that:

* `/pscheduler/tasks/T/runs/R/result/n` is the resource for a partial result where `n` is the participant number.  
* `/pscheduler/tasks/T/runs/R/result` is the full result.

Will also need to change `watch` and possibly do something triggered where the full result is generated once all of the participants have posted their results.

**Comment by mfeit-internet2** [comment]
Turned out this could be done with a `PUT` since that operation supports having a body.  Converted everything to use that.
