### ISSUE TITLE
JQ Indentifier and Limit

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#527]
Add a `jq` limit type that passes the entire task specification through a JQ script that returns `true` if the limit passes or `false` if it doesn't.

**Comment by mfeit-internet2** [comment]
Also did an identifier that operates on the hints.

**Comment by mfeit-internet2** [comment]
For downstream:  This change includes a new version of the tarball containing the code and a minor change the the build procedure (runs `cython` before `setup.py` as directed by the upstream author).

**Comment by mfeit-internet2** [comment]
Put back to In Progress; want to get rid of the `transform` item in the `data` and have the transform parameters at the top level.

**Comment by vvidic** [comment]
``python-pyjq`` with patches packaged on the Debian side.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added an identifier to the limit system which makes yes/no decisions based on the requester and server IPs using a JQ script.

Added a limit which makes pass/fail decisions using a JQ script.
