### ISSUE TITLE
JQ standard function library

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#528]
Build a package that contains importable functions that will be useful in the limit processor.

**Comment by mfeit-internet2** [comment]
Downstream:  This adds a package called `pscheduler-jq-library` and adds a dependency on it from `python-pscheduler`.

**Comment by vvidic** [comment]
``python-pscheduler`` depends on ``pscheduler-jq-library`` now.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added a small library of JQ functions useful in transforms.
