### ISSUE TITLE
Add pyjq package for Debian

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#538]
We will need to package pyjq for Debian.

**Comment by mfeit-internet2** [comment]
Hold off on this until #529 is finished.  I forked out a copy of the code to make some improvements, because it doesn't throw exceptions when the script produces an error.  Might get that done today.

**Comment by mfeit-internet2** [comment]
Patches are done; just apply the three that are there after unpacking and prior to building.

Also bumped the version number to reflect that our version is different than the developer's.

**Comment by vvidic** [comment]
On Fri, Aug 18, 2017 at 06:37:48AM -0700, Mark Feit wrote:
> Patches are done; just apply the three that are there after unpacking and prior to building.
> 
> Also bumped the version number to reflect that our version is different than the developer's.

Right, except we can't change the version from inside the package.
It needs to be the same number that the tar.gz has.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
Make it the tarball version then and I'll adjust the spec.

**Comment by vvidic** [comment]
jq packages should be functional now on the Debian side.
