### ISSUE TITLE
Add Debian packaging to new snmp and contexts plugins

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#540]
The new SNMP plugins developed by UMich and the new context developments need to be packaged for Debian.  This is:
- pscheduler-archiver-snmptrap
- pscheduler-context-changefail
- pscheduler-context-changenothing
- pscheduler-context-linuxnns
- pscheduler-test-snmpget
- pscheduler-test-snmpgetbgm
- pscheduler-test-snmpset
- pscheduler-tool-net-snmp
- pscheduler-tool-net-snmp-set
- pscheduler-tool-pysnmp

We also then need to add those new plugins to the pscheduler build matrix in Jenkins.

**Comment by vvidic** [comment]
Context plugins packaged and tested.

**Comment by vvidic** [comment]
SNMP plugins are packaged but I have problems testing them. Do we want to keep this open until they work properly?

**Comment by vvidic** [comment]
And do we include all these plugins in pscheduler-bundle-full?

**Comment by tonin** [comment]
> And do we include all these plugins in pscheduler-bundle-full?

This is probably a question for @mfeit-internet2

**Comment by mfeit-internet2** [comment]
> SNMP plugins are packaged but I have problems testing them. Do we want to keep this open until they work properly?

I'd say that if you're happy with how they package up for Debian, go ahead and close it.  UMich is going to be dogfooding all of it over the next month.  Any problems they find in the code will be corrected upstream, and I don't anticipate any packaging-related changes.

 > And do we include all these plugins in pscheduler-bundle-full?

Anything in the output of `scripts/build-order` should be in the full bundle.

**Comment by epcjr** [comment]
THank you!

-Ed

**Comment by vvidic** [comment]
Added context and snmp plugins to pscheduler-bundle-full and it installs without errors.

I'll close this now and we can add tests for snmp stuff in a month or so.
