### ISSUE TITLE
Exclude pscheduler-test-snmpset and pscheduler-tool-net-snmp-set from pscheduler-bundle-all

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#551]
We should exclude pscheduler-test-snmpset and  pscheduler-tool-net-snmp-set from the default pscheduler installation. The tools purpose is to write to SNMP which is higher risk than other stuff we do, and the test/tool itself has very niche use cases currently. Its great we have it so those that need it can install it, but probably better if it is not included by default.

**Comment by epcjr** [comment]
I assume the risk is a security concern?  perfSONAR will only be able to set SNMP variables that it has passwords/community strings for.  I'm OK with it either way.

**Comment by arlake228** [comment]
Correct. Example: as soon as it goes thrown on a network where the passwords haven't been changed from the default the device ships with and someone uses perfSONAR as the vector in, we get a black mark (whether its right or wrong). Probably not worth the risk of including by default and let someone make an explicit decision on whether to install it or not.

**Comment by epcjr** [comment]
I thought of the same scenario.  Sucks but I agree.

**Comment by mfeit-internet2** [comment]
This is done.  `pscheduler-bundle-full` no longer includes these packages.  The build process now produces `pscheduler-bundle-extras`, which does.

Downstream:  If this has any implications for Debian, please take care of them, otherwise just close the ticket.

**Comment by vvidic** [comment]
On Wed, Sep 27, 2017 at 04:34:53PM +0000, Mark Feit wrote:
> This is done.  `pscheduler-bundle-full` no longer includes these
> packages.  The build process now produces `pscheduler-bundle-extras`,
> which does.
> 
> Downstream:  If this has any implications for Debian, please take care
> of them, otherwise just close the ticket.

Ok, will create the pscheduler-bundle-extras package linking those
two plugins.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
``pscheduler-bundle-extras`` package available on the Debian side, closing.
