### ISSUE TITLE
Error installing pscheduler Debian package from nightly

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#563]
When I try to do a clean install of pscheduler on a Debian 8 host, I get the following:

```
Setting up pscheduler-server (1.0.2~1.b1+20171105194437-1) ...
Trying automatic postgresql upgrade...
Ver Cluster Port Status Owner Data directory Log file
dpkg: error processing package pscheduler-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-blinker (1.3.dfsg2-1) ...
Processing triggers for python-support (1.0.15) ...
Errors were encountered while processing:
 pscheduler-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This is a new install with a fresh postgresql install.

**Comment by tonin** [comment]
I cannot recreate this with the current packages from snapshot.  It could be a number of different things:
 - The last merge of master into the debian/jessie branch solved a problem
 - Would it be an install in a container?  I know that postgresql installation fails in Docker
 - Which version of postgresql got installed with pscheduler-server?  It needs to be 9.6 coming from our own repo.  Did you had postgresql previously installed?
 - Did you receive the dbconfig-common dialog messages to configure postgresql?
 - Are you installing pscheduler-server alone or a pS bundle?

Can you maybe try to do a new install with the current packages?

**Comment by vvidic** [comment]
It seems to me the postgresql was not running for some reason as there was no output from ``pg_lscluster`` command. We can fix the postinst error but the installation will fail later on when it tries to connect to the database.

**Comment by arlake228** [comment]
This was temporary, fixed by new build, closing.
