### ISSUE TITLE
pscheduler task import always ask for a test-type

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#564]
I have a test definition saved in a JSON file, including the test-type.  However, whenever I import the test, pscheduler ask for a test-type, only to disregard it.

```
gts@ftk:~/demo$ pscheduler task --import vlan12-rtt.json 
Usage: task [options] test-type [test-options]

gts@ftk:~/demo$ pscheduler task --import vlan12-rtt.json trace
Submitting task...
Task URL:
https://ftk/pscheduler/tasks/81c54796-89da-4b94-ac45-8632fe189aee
Running with tool 'ping'
Fetching first run...

gts@ftk:~/demo$ pscheduler task --import vlan12-rtt.json ghgjh
Submitting task...
Task URL:
https://ftk/pscheduler/tasks/e14d467c-98ff-46e4-9dd2-4f7572917f90
Running with tool 'ping'
Fetching first run...
```

The saved JSON file contains:
```
{
    "contexts": {
        "contexts": [
            [
                {
                    "context": "linuxnns",
                    "data": {
                        "namespace": "vlan12"
                    }
                }
            ]
        ],
        "schema": 1
    },
    "schema": 2,
    "test": {
        "spec": {
            "dest": "10.10.12.3",
            "schema": 1
        },
        "type": "rtt"
    }
}
```

**Comment by mfeit-internet2** [comment]
The type argument exists as an ignored placeholder so you can do on-the-fly editing of what was imported:
```
pscheduler task --import vlan12-rtt.json xxx --length 1234
```

There has to be a non-switch argument to separate the task switches from the test switches.  However, it wouldn't be unreasonable to  adjust it so that if there was an import, zero arguments after the task switches would be accepted.  Maybe I'll have it complain if the imported task doesn't have a `type` in it.

**Comment by tonin** [comment]
Thanks for the explanations.

> However, it wouldn't be unreasonable to adjust it so that if there was an import, zero arguments after the task switches would be accepted. Maybe I'll have it complain if the imported task doesn't have a type in it.

I think that would be a nice addition and would avoid confusion when using `--import`.

**Comment by mfeit-internet2** [comment]
Done.  See `pscheduler task --help` for explanation of new behavior, which is slightly better than discussed.
