### ISSUE TITLE
bash_completion support

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#573]
Had a random thought this morning while doing some pScheduler work - some sort of bash_completion (or equiv for other shells?) would be a nice quality of life thing for users. 

There's a wide range of scope. At the very least adding the stock commands like "task" and "schedule" would be neat, going further into details of those commands would be gravy.

**Comment by vvidic** [comment]
I have something in the works here, will send a PR next week...

**Comment by vvidic** [comment]
The PR adds basic completion support. We can add more later, but that will probably require pscheduler to export some database info (task, run, dest) perhaps using some new pscheduler internal commands.

**Comment by vvidic** [comment]
Initial bash support now merged, so closing.
