### ISSUE TITLE
pscheduler overlapping exclusive tests

### ISSUE THREAD

**Issue by daldoyle** [perfsonar/pscheduler#575]
We recently upgraded I2's internal pS instance that it uses to measure its backbone connections. Most of the time everything looks good, but periodically (about once a day) we have a rolling failure across the board where throughput test results get poor. After about 1 poor result, things recover until the next day.

Doing some digging, I found an example in the output of one host. Below is the "schedule" output trimmed to the two offending tests. Note the overlapping timeframes. As expected, test 1 performance starts off high and gets bad at the end, and test 2 starts off bad and gets high at the end, ie both are bad only during the overlap period.

This is a pretty aggressive mesh. We are doing throughput tests every hour and each host is involved in a lot of tests. I only mention this because it may be an edge case in the scheduler when things are close together. It also seems to line up roughly with when meshconfig adds the next set of tests, but I can't confirm that 100%.

Andy suggested that this may be a function of randomized slip being incorrectly calculated/applied. I am trying a few workarounds from him and will update the ticket if it seems to have a good effect.

> 2017-12-19T12:05:34Z - 2017-12-19T12:06:03Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 10.13.0.169 --dest 10.13.0.170 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/cdbb9dd2-2a2f-41c0-9710-abcd465a1b8e/runs/e3acb563-5c7c-4ffa-bc31-c8d1d34ce925
> 
> 
> 2017-12-19T12:05:48Z - 2017-12-19T12:06:16Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 10.13.2.22 --dest 10.13.2.21 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/934e18df-8891-48cf-8f0a-86d02b0efd07/runs/ca4e8f8e-38af-4bc8-9f88-f5eefe9204b8

**Comment by daldoyle** [comment]
It appears like disabling randslip actually makes this more pronounced. I confirmed new tasks were created with "randslip: false", but now observed blocks of tests with perfectly overlapping timeframes, but they're not consistently sized. One had 6, the one above it only had 3. My dev spidey sense says "race condition" or lack of / wrong use of a transaction.

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:48Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.46.50 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/2f9ab9ea-4d44-4921-8470-edb3facebb7c/runs/035d1233-5bb4-433a-bdf9-958580d09996

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:49Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.46.58 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/26cc478e-a090-4413-a37b-84c097d2ad41/runs/933b1f8b-7ce8-46bd-af59-9ab979281dec

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:49Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.46.62 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/ba943bb1-7ff2-4837-850e-4e061d5b28ae/runs/c9e1e89b-31c0-41ec-a30c-7cc36819b723

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:49Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.46.64 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/85d81406-d9b0-487b-a1eb-a14631c09683/runs/6709f627-ee92-4194-82df-86ce2db4976c

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:49Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.46.56 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/d6d5f04e-13e8-46e2-b6e7-288060fd91a7/runs/afe519cd-cb72-4df1-88b2-2d31191dd4f7

> 2017-12-21T14:22:20Z - 2017-12-21T14:22:49Z  (Finished)
> throughput --omit PT5S --duration PT20S --source 198.71.46.46 --dest 198.71.45.175 --window-size 96000000 --parallel 1 (Run with tool 'iperf3')
> https://localhost/pscheduler/tasks/b32bed61-1e97-40fa-8f3a-c20b81ffab1d/runs/cb4bf182-a644-4aff-9f25-842bdcda59a3

**Comment by mfeit-internet2** [comment]
> It appears like disabling randslip actually makes this more pronounced. 

That would make a lot of sense since things scheduled for some even time interval are more likely to collide.

Your theory that this is transaction-related is probably correct; I'll be looking at that this morning.

**Comment by mfeit-internet2** [comment]
What I saw in the test bed (with much less frequency) gave me a hunch that I ran with until I had enough access to PAS-SEAT to do debugging and retrieve the logs.  Once I got that access, here's what I found:

There were a number of collisions on PAS-SEAT, but here's one that happened between a pair of runs for tasks `12098` (SEAT to KANS) and `12059` (KANS to CLEV): 
```
A run   | 544732
A task  | 12098
B run   | 544733
B task  | 12059
A times | ["2018-01-06 16:43:01+00","2018-01-06 16:43:35+00")
B times | ["2018-01-06 16:42:55+00","2018-01-06 16:43:29+00")
A added | 2018-01-05 17:41:48.888732+00
B added | 2018-01-05 17:41:48.969732+00
```
Observe that:
  * The scheduled times overlap by 28 seconds
  * The runs were added 81 ms apart.

The debug output shows the following for the scheduling of that run (altered for clarity):

```
21:41:42 12098: 2 participants in this task
21:41:42 12098: Fetching proposals from https://SEAT/pscheduler/tasks/743e6aa4-2437-4ebd-9ed3-4ac663027701/runtimes
21:41:42 12098: Ranges: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 20:52:33+00:00),
                         R(2018-01-06 20:53:07+00:00..2018-01-06 21:41:05+00:00)]
21:41:42 12098: Fetching proposals from https://KANS/pscheduler/tasks/743e6aa4-2437-4ebd-9ed3-4ac663027701/runtimes
21:41:42 12098: Ranges: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 20:42:14+00:00),
                         R(2018-01-06 20:42:48+00:00..2018-01-06 21:11:49+00:00),
                         R(2018-01-06 21:12:23+00:00..2018-01-06 21:24:40+00:00),
                         R(2018-01-06 21:25:14+00:00..2018-01-06 21:27:23+00:00),
                         R(2018-01-06 21:27:57+00:00..2018-01-06 21:36:08+00:00),
                         R(2018-01-06 21:36:42+00:00..2018-01-06 21:41:05+00:00)
                ]
21:41:42 12098: Done fetching time ranges
21:41:42 12098: Ranges in common: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 20:42:14+00:00),
                         R(2018-01-06 20:42:48+00:00..2018-01-06 20:52:33+00:00),
                         R(2018-01-06 20:53:07+00:00..2018-01-06 21:11:49+00:00),
                         R(2018-01-06 21:12:23+00:00..2018-01-06 21:24:40+00:00),
                         R(2018-01-06 21:25:14+00:00..2018-01-06 21:27:23+00:00),
                         R(2018-01-06 21:27:57+00:00..2018-01-06 21:36:08+00:00),
                         R(2018-01-06 21:36:42+00:00..2018-01-06 21:41:05+00:00)
                ]
21:41:42 12098: Selected range
                         R(2018-01-06 21:36:42+00:00..2018-01-06 21:41:05+00:00)
```

```
21:41:42 12059: 2 participants in this task
21:41:42 12059: Fetching proposals from https://SEAT/pscheduler/tasks/9f1f715d-9296-4208-9f2c-8f656a8fa5b4/runtimes
21:41:42 12059: Ranges: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 20:52:33+00:00),
                         R(2018-01-06 20:53:07+00:00..2018-01-06 21:41:05+00:00)
                        ]
21:41:42 12059: Fetching proposals from https://CLEV/pscheduler/tasks/9f1f715d-9296-4208-9f2c-8f656a8fa5b4/runtimes
21:41:42 12059: Ranges: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 21:22:51+00:00),
                         R(2018-01-06 21:23:25+00:00..2018-01-06 21:41:05+00:00)]
21:41:42 12059: Done fetching time ranges
21:41:42 12059: Ranges in common: [
                         R(2018-01-06 20:41:05+00:00..2018-01-06 20:52:33+00:00),
                         R(2018-01-06 20:53:07+00:00..2018-01-06 21:22:51+00:00),
                         R(2018-01-06 21:23:25+00:00..2018-01-06 21:41:05+00:00)]

21:41:42 12059: Selected range
                         R(2018-01-06 21:23:25+00:00..2018-01-06 21:41:05+00:00)
```

Both tasks are offered exactly the same ranges of times by SEAT, which is okay because they're available.  The scheduler's threads simultaneously ask for overlapping runs for both and, because those transactions are isolated, both look okay and don't trigger a failure. What should be happening is one task is scheduled and then the other attempts but is rejected because of the overlap, in which case the scheduler will throw it back in the pool and try again.

This can't be fixed with the `SERIALIZABLE` transaction isolation level  ([Useful info on how that works](http://shiroyasha.io/transaction-isolation-levels-in-postgresql.html)) because there would be errors in one transaction when the other touches a table it's using.  We just want one or the other to neatly say "no thanks."

The solution is to serialize access to the `run` table with an explicit lock inside `api_run_post()` for the entire period between the conflict check and the insertion of the new row.  This is a fairly short process and shouldn't cause undue delays for anything else using the table.  Because the scheduling process is distributed, the scheduler cannot lock the entire schedules of all participants for the duration.  Instead it does a primitive rollback, backoff and retry if one of the participants develops a conflict.

**Comment by mfeit-internet2** [comment]
**Release notes:**

Adjusted scheduler to avoid conflicts under heavy loads.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Improved schedule handling under very heavy loads.
