### ISSUE TITLE
Make pScheduler Logs Readable

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#577]
The `/var/log/pscheduler` directory is readable by the `pscheduler` group, but the contents are owned by `root` and not readable by anyone else.

Find a way to fix it so the `pscheduler` group can read it.

**Comment by mfeit-internet2** [comment]
Not quite so easy:  Rsyslogd supports specifying permissions on the files it creates but applies the current umask.  There's a configuration option for setting the umask, but it's global and doing something friendly toward making the file readable will make all logs readable.  Not what we want.

**Comment by mfeit-internet2** [comment]
This isn't pressing and may not even be necessary.  Iceboxing.

**Comment by mfeit-internet2** [comment]
Add a `pscheduler log` command to `pscheduler-server` that uses `sudo` to dump out the most recent log file.

There should be an `--all` switch that gathers all logs and dumps them out in the right order.

**Comment by mfeit-internet2** [comment]
**Downstream:**

This adds a new command (`log`) and adds to sudoers.  Close when finished.

**Release Notes:**

Added a `log` command to retrieve the pScheduler logs

**Comment by tonin** [comment]
Tested and working on Debian.
