### ISSUE TITLE
Throughput test to show sender and receiver information

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#582]
With bwctl in pS 3.5 we had a summary line like this at the end of a throughput test:

```
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[ 16]   0.00-10.02  sec   607 MBytes   508 Mbits/sec  128             sender
[ 16]   0.00-10.02  sec   607 MBytes   508 Mbits/sec                  receiver

```

With pscheduler, we now have:
```
Summary
Interval       Throughput     Retransmits    
0.0 - 20.0     186.49 Mbps    0
```

Which I'm not sure if it's the sender or receiver summary.

@daldoyle commented on [Tue Sep 19 2017](https://github.com/perfsonar/project/issues/1180)

Originally from #396

Allow an option to specify displaying both sender and receiver output. This is analogous to the -x flag in bwctl.

**Comment by vvidic** [comment]
I guess we need to modify some tools first to report both sender and receiver info?

**Comment by tonin** [comment]
No, the underlying iperf/iperf3 output already has this information, unless it is not present in the JSON output.

```
[geantadmin@pssmall ~]$ iperf3 -c ps-4-0.qalab.geant.net 
Connecting to host ps-4-0.qalab.geant.net, port 5201
[  5] local 130.225.192.109 port 46206 connected to 150.254.208.65 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  49.3 MBytes   414 Mbits/sec    0   3.75 MBytes       
[  5]   1.00-2.00   sec  70.0 MBytes   587 Mbits/sec   11   1.11 MBytes       
[  5]   2.00-3.00   sec  50.0 MBytes   419 Mbits/sec    0   1.17 MBytes       
[  5]   3.00-4.00   sec  55.0 MBytes   461 Mbits/sec    0   1.29 MBytes       
[  5]   4.00-5.00   sec  62.5 MBytes   524 Mbits/sec    0   1.54 MBytes       
[  5]   5.00-6.00   sec  76.2 MBytes   639 Mbits/sec    0   1.93 MBytes       
[  5]   6.00-7.00   sec  95.0 MBytes   798 Mbits/sec    0   2.44 MBytes       
[  5]   7.00-8.00   sec   110 MBytes   921 Mbits/sec    0   3.04 MBytes       
[  5]   8.00-9.00   sec   110 MBytes   923 Mbits/sec    0   3.58 MBytes       
[  5]   9.00-10.00  sec   110 MBytes   925 Mbits/sec    0   4.20 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   788 MBytes   661 Mbits/sec   11             sender
[  5]   0.00-10.05  sec   786 MBytes   656 Mbits/sec                  receiver

iperf Done.
```

And the JSON contains this bit (`iperf3 -J`:
```
"end":	{
		"streams":	[{
				"sender":	{
					"socket":	5,
					"start":	0,
					"end":	10.000189065933228,
					"seconds":	10.000189065933228,
					"bytes":	703390480,
					"bits_per_second":	562701745.226941,
					"retransmits":	69,
					"max_snd_cwnd":	3640272,
					"max_rtt":	37000,
					"min_rtt":	22875,
					"mean_rtt":	26187
				},
				"receiver":	{
					"socket":	5,
					"start":	0,
					"end":	10.040550947189331,
					"seconds":	10.000189065933228,
					"bytes":	698000920,
					"bits_per_second":	556145513.26619589
				}
			}],
		"sum_sent":	{
			"start":	0,
			"end":	10.000189065933228,
			"seconds":	10.000189065933228,
			"bytes":	703390480,
			"bits_per_second":	562701745.226941,
			"retransmits":	69
		},
		"sum_received":	{
			"start":	0,
			"end":	10.040550947189331,
			"seconds":	10.040550947189331,
			"bytes":	698000920,
			"bits_per_second":	556145513.26619589
		},
		"cpu_utilization_percent":	{
			"host_total":	18.872219738690525,
			"host_user":	0.27518055406478126,
			"host_system":	18.70228129751229,
			"remote_total":	7.5817787356045372,
			"remote_user":	0.76968221745446852,
			"remote_system":	6.8068771106129562
		},
		"sender_tcp_congestion":	"htcp",
		"receiver_tcp_congestion":	"htcp"
	}
```
I'm not sure which of the `sum_sent` or `sum_received` is actually reported by pscheduler.

**Comment by vvidic** [comment]
On Tue, Feb 06, 2018 at 03:47:53PM +0000, Antoine Delvaux wrote:
> And the JSON contains this bit (`iperf3 -J`:
> ```
> "end":	{
> 		"streams":	[{
> 				"sender":	{
> 					"socket":	5,
> 					"start":	0,
> 					"end":	10.000189065933228,
> 					"seconds":	10.000189065933228,
> 					"bytes":	703390480,
> 					"bits_per_second":	562701745.226941,
> 					"retransmits":	69,
> 					"max_snd_cwnd":	3640272,
> 					"max_rtt":	37000,
> 					"min_rtt":	22875,
> 					"mean_rtt":	26187
> 				},
> 				"receiver":	{
> 					"socket":	5,
> 					"start":	0,
> 					"end":	10.040550947189331,
> 					"seconds":	10.000189065933228,
> 					"bytes":	698000920,
> 					"bits_per_second":	556145513.26619589
> 				}
> 			}],
> 		"sum_sent":	{
> 			"start":	0,
> 			"end":	10.000189065933228,
> 			"seconds":	10.000189065933228,
> 			"bytes":	703390480,
> 			"bits_per_second":	562701745.226941,
> 			"retransmits":	69
> 		},
> 		"sum_received":	{
> 			"start":	0,
> 			"end":	10.040550947189331,
> 			"seconds":	10.040550947189331,
> 			"bytes":	698000920,
> 			"bits_per_second":	556145513.26619589
> 		},
> 		"cpu_utilization_percent":	{
> 			"host_total":	18.872219738690525,
> 			"host_user":	0.27518055406478126,
> 			"host_system":	18.70228129751229,
> 			"remote_total":	7.5817787356045372,
> 			"remote_user":	0.76968221745446852,
> 			"remote_system":	6.8068771106129562
> 		},
> 		"sender_tcp_congestion":	"htcp",
> 		"receiver_tcp_congestion":	"htcp"
> 	}
> ```
> I'm not sure which of the `sum_sent` or `sum_received` is actually reported by pscheduler.

From what I can tell the sum_sent and sender parts are used
while sum_received and receiver are just dropped. So we would
need to include those in the tool results now?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
I managed to add a ``receiver-throughput-bits`` value to the summary results so the ``iperf3`` output now looks like this:

```
* Stream ID 5
Interval       Throughput     Retransmits    Current Window 
0.0 - 1.0      111.24 Mbps    0              812.59 KBytes  
1.0 - 2.0      102.81 Mbps    0              1.62 MBytes    
2.0 - 3.0      94.35 Mbps     0              2.45 MBytes    
3.0 - 4.0      94.13 Mbps     0              2.61 MBytes    
4.0 - 5.0      93.77 Mbps     0              2.70 MBytes    
5.0 - 6.0      94.15 Mbps     0              2.85 MBytes    
6.0 - 7.0      83.83 Mbps     0              3.04 MBytes    
7.0 - 8.0      73.31 Mbps     2              2.18 MBytes    
8.0 - 9.0      114.83 Mbps    0              2.37 MBytes    
9.0 - 10.0     93.77 Mbps     0              2.55 MBytes    

Summary
Interval       Throughput     Retransmits    Receiver Throughput 
0.0 - 10.0     95.62 Mbps     2              93.04 Mbps
```
Let me know if this is ok?

**Comment by mfeit-internet2** [comment]
That looks fine to me.   That format is for human consumption, so if it breaks any scrapers, that's tough cookies.

**Comment by vvidic** [comment]
On Wed, Feb 07, 2018 at 05:21:16PM +0000, Mark Feit wrote:
> That looks fine to me.   That format is for human consumption, so if
> it breaks any scrapers, that's tough cookies.

Great, thanks for checking.  I will create a PR tomorrow for review.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
PR merged, closing.
