### ISSUE TITLE
Simple prioritization of tasks based on multiple horizons

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#583]
Hi guys,

An ability of pSc to operate with different horizons would allow us to define a sort of different prioritization levels on tasks.
It would allow the admin to setup the higher priority tasks in a long pSc schedule horizon, where the schedule is generally free/ not populated. While for lower priority tasks like external projects and/or public requests the admin would be able to limit their view/access to the pSc horizon and thus make sure these do not block his priority tasks on the schedule.

I would see this feature implemented as a pSc Limits feature, so that the admin has the flexibility to configure different sets of horizons say 8h, 12h, 18h, 24h.
I guess it does not make sense to have a pSc horizon for more than 48h

A kind suggestion to have that proposal evaluated along with other prioritization approaches in terms of feasibility, completeness, difficulties and effort and eventually make this request an epic in order to follow on the dependencies it has.

**Comment by mfeit-internet2** [comment]
This would leverage the first-scheduled-first-run model that BWCTL had.  I think this is better served by #479.  Closing.
