### ISSUE TITLE
New install, web services not showing

### ISSUE THREAD

**Issue by LastEagle** [perfsonar/pscheduler#594]
Running perfSonar 4.02.  I used the full iso to build a new server, however on installing the iso, perfSonar did not appear to be installed.  I ran all the commands as needed to get the software working.  Now on the webpage localhost/toolkit after being logged in as admin.  I'm unable to view the Services. I am also unable to see and test results or scheduled tests.  On the CLI i'm able to see the scheduled tasks.  I'm also able to see the json schedule and results.  

It appears the web services did not fulling install.  Any help would be appreciated.

**Comment by mfeit-internet2** [comment]
This isn't really an issue with pScheduler.  Please send requests for general help to the [perfsonar-users mailing list](https://lists.internet2.edu/sympa/subscribe/perfsonar-user).
