### ISSUE TITLE
Automagically restart daemons if they're dead.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#597]
Need a cron job in pscheduler-server that checks to see if all of the daemons are running and restarts those that aren't.  This will allow recovery if a process is killed off externally or because it OOMs.

Mildly related to #295 and #505.

**Comment by vvidic** [comment]
On Tue, Mar 13, 2018 at 11:10:19AM -0700, Mark Feit wrote:
> Need a cron job in pscheduler-server that checks to see if all of the
> daemons are running and restarts those that aren't.  This will allow
> recovery if a process is killed off externally or because it OOMs.

You can also investigate Restart=on-failure and related systemd options.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by igarny** [comment]
IMHO it is even more important to have a report about the state of the services, that have been found dead along with the magic.
Please note there are already automation procedures taking care of this. Thus IMHO it would mostly be of benefit to people without central management. Still the reporting is equally important in all cases.

**Comment by vvidic** [comment]
I have a failing service after boot today, so some kind of retry would be good there:

```
Jul  9 10:53:57 pstest systemd[1]: Started pScheduler server - archiver.
Jul  9 10:55:33 pstest systemd[1]: Starting pScheduler server - archiver...
Jul  9 10:55:33 pstest systemd[1]: Started pScheduler server - archiver.
Jul  9 10:55:40 pstest archiver[320]: Traceback (most recent call last):
Jul  9 10:55:40 pstest archiver[320]: File "/usr/lib/pscheduler/daemons/archiver", line 880, in <module>
Jul  9 10:55:40 pstest archiver[320]: main_program()
Jul  9 10:55:40 pstest archiver[320]: File "/usr/lib/pscheduler/daemons/archiver", line 764, in main_program
Jul  9 10:55:40 pstest archiver[320]: db = pscheduler.PgConnection(dsn)
Jul  9 10:55:40 pstest archiver[320]: File "/usr/lib/python2.7/dist-packages/pscheduler/db.py", line 105, in __init__
Jul  9 10:55:40 pstest archiver[320]: self.pg = pg_connection(dsn, autocommit=autocommit, name=name)
Jul  9 10:55:40 pstest archiver[320]: File "/usr/lib/python2.7/dist-packages/pscheduler/db.py", line 37, in pg_connec
Jul  9 10:55:40 pstest archiver[320]: pg = psycopg2.connect(dsn)
Jul  9 10:55:40 pstest archiver[320]: File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in conn
Jul  9 10:55:40 pstest archiver[320]: conn = _connect(dsn, connection_factory=connection_factory, async=async)
Jul  9 10:55:40 pstest archiver[320]: psycopg2.OperationalError: FATAL:  the database system is starting up
Jul  9 10:55:40 pstest archiver[320]: FATAL:  the database system is starting up
Jul  9 10:55:40 pstest systemd[1]: pscheduler-archiver.service: main process exited, code=exited, status=1/FAILURE
Jul  9 10:55:40 pstest systemd[1]: Unit pscheduler-archiver.service entered failed state.
```

**Comment by mfeit-internet2** [comment]
@vvidic The four daemons have built-in crash protection with automatic restart and a backoff in the time between attempts.  I prefer the backoff to what systemd can do, which is restart at a fixed interval.  The only things that will make the daemon die are a signal that terminates the process or a failure in Python that causes a non-program-directed exit.

The hitch is that if the `--daemon` switch is not in effect, the crash protection isn't, either.  This was because we had to daemonize for EL6 and the non-daemonized mode was for development.  With 6 going away, I can re-think that behavior if Debian prefers processes that don't daemonize.  (EL7's Systemd doesn't care either way; it's a one-line change.)

How about if I separate daemonizing from crash protection and do the latter only if the program is being run interactively?

**Comment by vvidic** [comment]
Current pscheduler services have the preferred `Type=simple`:

```
[Service]
Type=simple
User=pscheduler
Group=pscheduler
PermissionsStartOnly=true
ExecStart=/usr/lib/pscheduler/daemons/runner --dsn @/etc/pscheduler/database/database-dsn
ExecStartPost=/bin/sh -c "echo $MAINPID > /run/pscheduler-runner.pid"
ExecStopPost=/bin/rm -f /run/pscheduler-runner.pid
```

so there is no `--daemon` parameter and it would be good to have the protection as default or additional parameter.

**Comment by vvidic** [comment]
Systemd protection could be a second level that would restart the service every N minutes instead of that cron job:

```
Note that service restart is subject to unit start rate limiting configured with StartLimitIntervalSec=
and StartLimitBurst=, see systemd.unit(5) for details. A restarted service enters the failed state only
after the start limits are reached.

Setting this to on-failure is the recommended choice for long-running services, in order to increase
reliability by attempting automatic recovery from errors. For services that shall be able to terminate
on their own choice (and avoid immediate restarting), on-abnormal is an alternative choice.
```

**Comment by mfeit-internet2** [comment]
This is (partially) what's being done on CentOS 7, where we are using `--daemon`:
```
...
[Service]
Type=simple
User=pscheduler
Group=pscheduler
PermissionsStartOnly=true
PIDFile=/run/pscheduler-ticker.pid
LimitNOFILE=4096
LimitNPROC=4096
...
# Generate options file
ExecStartPre=-/bin/sh -c "if [ -r /etc/pscheduler/daemons/ticker.conf ]; then opts=$(sed -e 's/#.*$//' /etc/pscheduler/daemons/ticker.conf); echo OPTIONS=$opts > /run/pscheduler-ticker.options; chown pscheduler:pscheduler /run/pscheduler-ticker.options; fi"

# Start service
ExecStart=/usr/libexec/pscheduler/daemons/ticker --daemon --pid-file /run/pscheduler-ticker.pid --dsn @/etc/pscheduler/database/database-dsn $OPTIONS
...
[Install]
WantedBy=multi-user.target
```

I think I'm probably just going to make the protected mode the default behavior and be done with it.

**Comment by mfeit-internet2** [comment]
@vvidic It turns out that all of the daemons except the archiver were running protected in non-daemon mode.  That inconsistency has been fixed.  I'll adjust the CentOS systemd files to correct that separately.

**Comment by vvidic** [comment]
Service files for Debian are now synced with CentOS so they should behave the same.

**Comment by mfeit-internet2** [comment]
Adjusted service file template to recover after a hard failure.
