### ISSUE TITLE
Adjust python-psycopg2 requirements.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#605]
From Slack.  Need to make sure we're getting a version of psycopg2 where this functions correctly.

Looks like Marian had 2.5.1; he installed 2.6.1 and the problem went away.  My dev systems are getting 2.7.4 from PGDG.

-----
Marian Babik [8:32 AM]
hey, just finished debugging a centos7 toolkit instance that had this error:
safe_run/scheduler ERROR    Exception: ProgrammingError: syntax error at or near ")"
                                                            LINE 2: ...    FROM schedule_runs_to_schedule WHERE task in () LIMIT 50
turned out the system was using yum priorities and python-psycopg2 came from centos-base instead of internet2
this of course has messed up the entire installation, perhaps adding something on the expected priority of internet2 repo to the docs would help

Mark Feit [8:37 AM]
The maintainers strongly discourage use of priorities.  If anything, it's probably the RPM depending on python-psycopg2 and without specifying a version.

Marian Babik [8:37 AM]
so I understand pscheduler depends on python-psycopg2, right ?
let me look up the exact versions

Mark Feit [8:38 AM]
It does, yes.  The RPM that needs it requires >= 2.2.0.

Marian Babik [8:38 AM]
I had python-psycopg2-2.5.1-3.el7.x86_64 instead of python-psycopg2-2.6.1-1.rhel7.x86_64
after installing 2.6.1 and re-installing pscheduler the error went away
anyway, in case priorities are discouraged I would just add it to the docs (so people don't expect this to work) ....

Mark Feit [8:40 AM]
I'll check the versions of everything and adjust the RPM specs accordingly.

**Comment by mfeit-internet2** [comment]
The problem going away after the upgrade turns out to have been a coincidence.

The [code constructing that part of the query](https://github.com/perfsonar/pscheduler/blob/9ba8ddcfa80f60ddfa4244416711c6f8037eb9a4/pscheduler-server/pscheduler-server/daemons/scheduler#L758) needs to hold a lock on the worker list during both the length check and the dump of the keys.  In Marian's case, the key list went empty between those two operations and that result into an invalid query.

The code has been switched to use a regular dictionary and an explicit lock.

**Comment by marian-babik** [comment]
Thanks for debugging and fixing this. 

I would still consider adding a note in the docs about priorities of yum repos as at least within WLCG using yum priorities is very common and since the installation finishes fine while having Internet2 repo at lowest priority, all sorts of unexpected issues can arise from this.

**Comment by mfeit-internet2** [comment]
@marian-babik Closing this issue.  See https://github.com/perfsonar/docs/issues/124 for continuation.
