### ISSUE TITLE
a latency non-starter task?

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#609]
I have attached a latency task created by pS 4.0.2 meshconfig service, which eventually ended up as a non-starter:

[non-starter-task.txt](https://github.com/perfsonar/pscheduler/files/1938816/non-starter-task.txt)
```
// 20180423165722
// https://psbrix.rrze.uni-erlangen.de/pscheduler/tasks/ca24823d-ebb9-447f-911c-c7a69f55998a

{
  "reference": {
    "created-by": {
      "address": "psbrix.rrze.uni-erlangen.de",
      "uuid": "daf8537d-3858-4cbc-ae5d-9cd3f95845c0",
      "user-agent": "perfsonar-meshconfig"
    },
    "description": "pSmall IPv6 loss"
  },
  "schedule": {
    "start": "2018-04-23T01:50:10Z",
    "until": "2018-04-24T01:50:10Z"
  },
  "tool": "powstream",
  "archives": [
    {
      "data": {
        "url": "http://ps-sn-central.qalab.geant.net/esmond/perfsonar/archive/",
        "retry-policy": [
          {
            "attempts": 1,
            "wait": "PT60S"
          }
        ],
        "measurement-agent": "psbrix.rrze.uni-erlangen.de"
      },
      "archiver": "esmond",
      "ttl": "PT180S"
    }
  ],
  "test": {
    "type": "latencybg",
    "spec": {
      "source": "psmp-gn-owd-01-mad-es-v6.geant.net",
      "dest": "psbrix.rrze.uni-erlangen.de",
      "packet-padding": 0,
      "flip": true,
      "data-ports": {
        "upper": 9960,
        "lower": 8760
      },
      "ip-version": 6,
      "packet-interval": 0.10000000000000001,
      "duration": "PT86400S",
      "packet-count": 600,
      "schema": 1
    }
  },
  "schema": 1
}
```
[non-starter-run.txt](https://github.com/perfsonar/pscheduler/files/1938817/non-starter-run.txt)
```
// 20180423165640
// https://psbrix.rrze.uni-erlangen.de/pscheduler/tasks/ca24823d-ebb9-447f-911c-c7a69f55998a/runs/36dd7836-229d-488e-91e0-57bd24bd1e07

{
  "result-href": "https://psbrix.rrze.uni-erlangen.de/pscheduler/tasks/ca24823d-ebb9-447f-911c-c7a69f55998a/runs/36dd7836-229d-488e-91e0-57bd24bd1e07/result",
  "end-time": "2018-04-24T03:50:10+02:00",
  "participant": 0,
  "participant-data": {
    
  },
  "result-merged": null,
  "participant-data-full": null,
  "participants": [
    "psbrix.rrze.uni-erlangen.de"
  ],
  "state-display": "Non-Starter",
  "result-full": null,
  "state": "nonstart",
  "errors": "Failed to get run data from all participants",
  "href": "https://psbrix.rrze.uni-erlangen.de/pscheduler/tasks/ca24823d-ebb9-447f-911c-c7a69f55998a/runs/36dd7836-229d-488e-91e0-57bd24bd1e07",
  "task-href": "https://psbrix.rrze.uni-erlangen.de/pscheduler/tasks/ca24823d-ebb9-447f-911c-c7a69f55998a",
  "duration": "P1D",
  "start-time": "2018-04-23T03:50:10+02:00",
  "added": "2018-04-22T21:38:39+02:00",
  "result": null
}
```

IMHO this is related to this issue:
perfsonar/mesh-config/issues/113

**Comment by mfeit-internet2** [comment]
After some poking around in the software, this gets interesting:

Non-start indicates a failure in scheduling where it was able to find a slot on the timeline for the run but one of the preparatory steps between that and having everything needed before starting failed.  The assumption from a scheduling standpoint is that we tried and failed and that's the end of it.

If we don't treat these runs as failed (i.e., we ignore that they ever existed), the scheduler will continue trying to schedule another one at the same time and won't stop until it either succeeds or the run's start time passes.  Then it will move on to the next one and the process will repeat, leaving the database littered with non-starters.

The runner will restart runs of bg-multi tasks that should be running but aren't, which provides a safety net for reboots and other instances where the runner is restarted.  That doesn't cover non-starters because by definition, they never got to a point where they could be run in the first place.

I don't think this can be handled neatly in pScheduler because we'd have to make all sorts of assumptions about task duration and truncating it based on a start time we'd have to make up.  pSConfig, on the other hand, could look at tasks that it thinks should be running but don't have a valid run scheduled, cancel the duds and reschedule new ones.

**Comment by vvidic** [comment]
Here is some info I got for non-stater tasks:

```May 11 07:49:46 ps-bionic scheduler WARNING  2891: Failed to get run data (400): Request timed out
May 11 07:49:46 ps-bionic scheduler INFO     2891: Posting non-starting run at 2018-05-12T07:49:07+02:00 for task b6e6fdf5-b5d6-4df0-9fb5-a711afbdee77: Failed to get run data from all participants
May 11 07:49:46 ps-bionic scheduler WARNING  2887: Failed to get run data (400): Request timed out
May 11 07:49:46 ps-bionic scheduler INFO     2887: Posting non-starting run at 2018-05-12T07:49:07+02:00 for task 18df068e-1fd8-41c5-a6d6-33d2ecb1f70b: Failed to get run data from all participants
May 11 07:49:46 ps-bionic scheduler WARNING  2890: Failed to get run data (400): Request timed out
May 11 07:49:46 ps-bionic scheduler INFO     2890: Posting non-starting run at 2018-05-12T07:49:07+02:00 for task e1986a3c-56a4-4897-ac57-adb12572f1ec: Failed to get run data from all participants
May 11 07:49:46 ps-bionic scheduler WARNING  2893: Failed to get run data (400): Request timed out
May 11 07:49:46 ps-bionic scheduler INFO     2893: Posting non-starting run at 2018-05-12T07:49:07+02:00 for task 300ed69f-ddee-4542-bf26-9246d6dc3951: Failed to get run data from all participants
```
Looks like a timeout in some request?

**Comment by mfeit-internet2** [comment]
@vvidic Probably.  I think maybe the scheduler should hold onto the error message(s) so they can be part of the diagnostic.

**Comment by igarny** [comment]
So is there a way (available switch or something) to further increase the output details for pscheduler wrt these errors?
From the report it is obvious, that it is the scheduler service, that is seeing the difficulties. I see these errors for trace tests as well. In these cases there is no negotiation with the remote party except for the case, where the test is requested from the remote participant.

In the GEANT production I have only forward requests. The only timeout I can think of is the postgreSQL queries. 
It would be much more helpful, if the message clarifies this.
If this is the case, then obviously we cannot apply the same config for powerful, overloaded, small-node and isolated/non-busy pS nodes.

**Comment by ajragusa** [comment]
Just an FYI that we have seen this happen at least 3 times, I did not think to gather logs to figure out why it happened.  Next time I'll make sure to grab them and put them in.

**Comment by mfeit-internet2** [comment]
@ajragusa If this is happening on PAS systems, let me know which ones.  I have enough access to snoop around.

**Comment by igarny** [comment]
Here is an example of the issue presumably https://perfsonar.r2.brudie.belnet.net/pscheduler/tasks/d4cdf664-e7c3-408c-811b-136b9038afd2/runs/3e22cd5b-7208-42c3-9dee-6a675e80fc48

Toolkit version: 4.1.1-1.el7

**Comment by mfeit-internet2** [comment]
Closed per Ivan.
