### ISSUE TITLE
pscheduler archiver option fails with throughput

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#611]
Here is the archiver json
```
{
    "archiver": "esmond",
    "data": {
        "measurement-agent": "1.1.1.1",
        "url": "https://prod-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/",
        "_auth-token": "----------------------------------------",
        "retry-policy": [
            { "attempts": 1,  "wait": "PT60S"   },
            { "attempts": 2,  "wait": "PT600S"  },
            { "attempts": 11, "wait": "PT3600S" }
        ]
    }
}
```

**Fails with throughput:**
https://psmp-gn-mgmt-01-pra-cz.geant.net/pscheduler/tasks/393d2f05-75c6-44a2-94c9-a684c9c6b012/runs/38bd17c1-4b3b-4913-9b25-49cfface2962?pretty
[archthroughput.txt](https://github.com/perfsonar/pscheduler/files/1979605/archthroughput.txt)

**succeeds with traceroute:**
[archtrace.txt](https://github.com/perfsonar/pscheduler/files/1979604/archtrace.txt)
https://psmp-gn-bw-01-lon-uk.geant.net/pscheduler/tasks/5d45ba9a-26b1-41d4-9e15-da72f9641945/runs/a221e9fd-b16e-4ff0-ae34-25fbef33b260?pretty

**Comment by mfeit-internet2** [comment]
What Andy said.  I might suggest being a bit more aggressive in the early stages or archiving, especially with measurements like throughput that don't happen as frequently.

Closing; this doesn't appear to be a problem with pScheduler.
