### ISSUE TITLE
pSc MA submission: stderr = Time to live expired

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#614]
As suggested by Mark on the pS Dev mailing list:
curl -k https://test1.rrze/pscheduler/tasks/fc4800d2-90ee-4e40-953f-f354583e09f3/runs/3690b010-4ab6-41ab-b02c-0de200cf78d6?pretty

I guess this is in fact a standard outcome, with only 2 attempts prescribed in the mesh-configuration for the staging MA

{
    "added": "2018-05-07T13:59:36Z",
    "archivings": [
        {
            "archived": true,
            "archiver": {
                "description": "Send results to Esmond",
                "maintainer": {
                    "email": "perfsonar-developer@internet2.edu",
                    "href": "http://www.perfsonar.net",
                    "name": "perfSONAR Development Team"
                },
                "name": "esmond",
                "schema": 1,
                "version": "1.0"
            },
            "archiver_data": {
                "measurement-agent": "sophia-bg.rrze.uni-erlangen.de",
                "retry-policy": [
                    {
                        "attempts": 1,
                        "wait": "PT60S"
                    },
                    {
                        "attempts": 1,
                        "wait": "PT300S"
                    }
                ],
                "url": "https://perfsonar-stage-ma.grnoc.iu.edu/esmond/perfsonar/archive/"
            },
            "diags": [
                {
                    "return-code": 1,
                    "stderr": "Time to live expired",
                    "stdout": "",
                    "time": "2018-05-07T14:30:01Z"
                }
            ],
            "last_attempt": null
        }
    ],
    "duration": "PT6S",
    "end-time": "2018-05-07T13:59:57Z",
    "errors": null,
    "href": "https://test1.rrze/pscheduler/tasks/fc4800d2-90ee-4e40-953f-f354583e09f3/runs/3690b010-4ab6-41ab-b02c-0de200cf78d6",
    "participant": 0,
    "participant-data": {},
    "participant-data-full": [
        {}
    ],

**Comment by mfeit-internet2** [comment]
I can't see the original task but have to assume the TTL was short enough that the archiving was dumped.  The TTL was originally used only when the archiving wasn't acted on at all; Andy suggested that we just make it absolute (e.g., if not archived after _x_ time, drop it) and it was rewritten that way.

Other than that, is there a bug or enhancement here that needs to be worked on?

**Comment by mfeit-internet2** [comment]
This turned out to be a dead archiver process on Ivan's system.  Closing.
