### ISSUE TITLE
"Non-Start" trace tasks unclear

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#619]
On this server I am having difficulties with operating pscheduler and the service is regularly having huge delays in responses.
I found these re-occurring failures
What could be the reason for these repeated messages?

@psmp-gn-bw-01-gen-ch ~]$ grep c354885a-27ca-4886-bd2c-cd46e120584c pscheduler.log | head -n 5
```
May 11 12:10:52 psmp-gn-bw-01-gen-ch scheduler INFO     163639: Posting non-starting run at 2018-05-11T18:50:09Z for task c354885a-27ca-4886-bd2c-cd46e120584c: Error fetching task: Resource Not found.
May 11 12:10:53 psmp-gn-bw-01-gen-ch scheduler INFO     163639: Posting non-starting run at 2018-05-11T19:00:09Z for task c354885a-27ca-4886-bd2c-cd46e120584c: Error fetching task: Resource Not found.
May 11 12:10:53 psmp-gn-bw-01-gen-ch scheduler INFO     163639: Posting non-starting run at 2018-05-11T19:10:09Z for task c354885a-27ca-4886-bd2c-cd46e120584c: Error fetching task: Resource Not found.
May 11 12:10:53 psmp-gn-bw-01-gen-ch scheduler INFO     163639: Posting non-starting run at 2018-05-11T19:20:09Z for task c354885a-27ca-4886-bd2c-cd46e120584c: Error fetching task: Resource Not found.
May 11 12:10:54 psmp-gn-bw-01-gen-ch scheduler INFO     163639: Posting non-starting run at 2018-05-11T19:30:09Z for task c354885a-27ca-4886-bd2c-cd46e120584c: Error fetching task: Resource Not found.
```
@psmp-gn-bw-01-gen-ch ~]$ grep -c c354885a-27ca-4886-bd2c-cd46e120584c pscheduler.log
138

@psmp-gn-bw-01-gen-ch ~]$ grep  ": Posting non-starting run at " pscheduler.log | grep -c "Error fetching task: Resource Not found."
**3309**

@psmp-gn-bw-01-gen-ch ~]$ grep  ": Posting non-starting run at " pscheduler.log | grep "Error fetching task: Resource Not found." | grep -c "^May 11"
496

**Comment by mfeit-internet2** [comment]
> the service is regularly having huge delays in responses.

Sluggishness is usually a sign the system is overloaded.  Have you ruled that out?

**Comment by mfeit-internet2** [comment]
> psbrix.rrze.uni-erlangen.de

If this machine or any of the others involved is a Gigabyte BRIX, replace it with something more reliable and powerful enough to handle the workload.  @schevali reports that those machines get bogged down when part of a mesh that's any bigger than 7x7 and were also the ones he had to reinstall most frequently.

The error shown in your non-starters says the task that's being scheduled no longer exists when it clearly does.  I'm not inclined to believe this is a software problem or we'd be seeing it elsewhere.

**Comment by marian-babik** [comment]
Following Ivan's request, here is info from http://perfsonar02-iep-grid.saske.sk/toolkit/

[root@perfsonar02-iep-grid ~]# grep -c ": Posting non-starting run at " /var/log/pscheduler/pscheduler.log*
/var/log/pscheduler/pscheduler.log:5509

pscheduler schedule -PT10H > sched10
[root@perfsonar02-iep-grid ~]# ls -lh sched10
-rw-r--r-- 1 root root 19M May 17 11:35 sched10
[root@perfsonar02-iep-grid ~]# grep -1 Non-Starter sched10 | grep -c trace
642
[root@perfsonar02-iep-grid ~]# grep -1 Non-Starter sched10 | grep -c rtt
0
[root@perfsonar02-iep-grid ~]# grep -1 Non-Starter sched10 | grep -c latencybg
1
[root@perfsonar02-iep-grid ~]# grep -1 Non-Starter sched10 | grep -c throughput
0

Node is not very busy, mostly idle (50-80%), it's supposed to run 81 uni-directional latency tests (+ traces).

**Comment by igarny** [comment]
Also what I add as a comment to this https://github.com/perfsonar/pscheduler/issues/619#issuecomment-389627644 this comment  https://github.com/perfsonar/mesh-config/issues/113#issuecomment-379758781 from Andy about an ESnet host.

Also I would like to remind you about our discussion on the Dev call..."it might be an issue of the rate at which the mesh-config service is generating the tasks"

**Comment by igarny** [comment]
Some conclusions from a call with Antoine:
There are different cases
- non-starters from initial task coordination reported here: https://github.com/perfsonar/pscheduler/issues/619#issue-322356093 . The host is with pSc 1.0.2.3-1.el6, there might be other cases.
- non-starters at run time multiple cases with pSc 1.0.2.6-1.el6
- non-starters are kind of missing in the pS Dev staging mesh. These are on radar

Since we see non-starters in the first two cases of (1) then it might be an issue with mesh-config

**Comment by igarny** [comment]
Changed the title, since there is no clear indication, but just a presumption on the utilization of the system

**Comment by mfeit-internet2** [comment]
(Wrote these notes yesterday but forgot to add them to the ticket.)

The non-starts on your system are being triggered by the scheduler asking the local API for information about the task and the API -- for whatever reason -- being unable to find it and returning a 404.  The task information is clearly in the database because posting the integrity constraints in the database would prevent posting a run to a task that doesn't exist.  There's no scenario where the scheduler could get hold of a task that didn't exist.

So the next question is why the API is returning a 404.  We should be able to determine at least some of that by looking at the logs on the system where you're having problems.

One thing I did discover is that there's no cap on the number of scheduling threads the scheduler will run, which could be causing problems during periods of high scheduling activity.  That's something that was done in the other daemons and is easy to fix here.  Capping the threads may not solve the problem, as the system already self-regulates itself by only trying to schedule a run for one task at a time.

**Comment by igarny** [comment]
Hello Mark
Actually my monitor have not been seeing these "non-starters" for over a month. I guess these have been resolved by an upgrade or a reduction of the number of tests.

perhaps it is safe to just close this.

**Comment by mfeit-internet2** [comment]
Closed per Ivan.
