### ISSUE TITLE
Do RTT measurements with TWAMP as an alternative to ping

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#625]
TWAMP (twping) can report RTT as well as one-way delay.  We currently have a pscheduler tool called `twping` that makes one-way latency measurements.  We could add another tool (or re-use the same?) to make RTT measurements.

It would be useful to be able to run something like:
```
pscheduler task --tool twping rtt --dest some.device.in.the.world
```

**Comment by mfeit-internet2** [comment]
(To fill in something we discussed on Slack)

I would suggest adding a `protocol` field to the RTT test so the test spec, rather than selection of a specific tool, guides what tool is used.  If not provided, tools like TWAMP that use uncommon protocols should remove themselves from consideration.

**Comment by vvidic** [comment]
Please review the rtt changes to twping plugin. For the ``protocol`` think I guess the ``rtt`` test would need to be modified?

**Comment by mfeit-internet2** [comment]
Correct.  I would suggest the following changes:

To the `rtt` test:
 - [ ] Add `protocol` field.  This should be optional, with the value as an enumerated string that's either `icmp` or `twamp`.   The behavior for tasks without this field should be to assume `icmp`.
 - [ ] Bump the schema version to `2` and do the changes required to handle it.  (Should be similar to the last round where you did it.)

To the `ping` tool:
 - [ ] Make `can-run` decline if the `protocol` is present and not `icmp`.

To the `twping` tool:
 - [ ] Make `can-run` decline if the `protocol` is not present or something other than `icmp`.

**Comment by vvidic** [comment]
On Wed, May 30, 2018 at 04:25:27PM +0000, Mark Feit wrote:
> Correct.  I would suggest the following changes:

Ok, I get the idea, will give it a try...

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
On Wed, May 30, 2018 at 04:25:27PM +0000, Mark Feit wrote:
> Correct.  I would suggest the following changes:
> 
> To the `rtt` test:
>  - [ ] Add `protocol` field.  This should be optional, with the value as an enumerated string that's either `icmp` or `twamp`.   The behavior for tasks without this field should be to assume `icmp`.
>  - [ ] Bump the schema version to `2` and do the changes required to handle it.  (Should be similar to the last round where you did it.)
> 
> To the `ping` tool:
>  - [ ] Make `can-run` decline if the `protocol` is present and not `icmp`.
> 
> To the `twping` tool:
>  - [ ] Make `can-run` decline if the `protocol` is not present or something other than `icmp`. 

Adding the protocol option breaks the tool selection:

$ pscheduler task --tool=twping rtt --dest=pstest.geant.carnet.hr 
Submitting task...
Unable to post task: Unable to complete request: Couldn't find a tool in common among the participants.
The 'pscheduler troubleshoot' command may be of use in problem diagnosis. 'pscheduler troubleshoot --help' for more information.

Protocol option is now required to get the twping tool working again:

$ pscheduler task --tool=twping rtt --dest=pstest.geant.carnet.hr --protocol=twamp
Submitting task...
Task URL:
https://pstest2.geant.carnet.hr/pscheduler/tasks/07b1186d-2222-46b1-9162-a6261d3be814
Running with tool 'twping'
Fetching first run...

Let me know if this is acceptable or we should allow twping when
protocol is not set?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
That's fine.  If the `can-run` methods for the `ping` and `twping` are correct, you shouldn't have to explicitly select a tool:

 - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=icmp` should make `ping` select itself and `twamp` bow out.  (Behavior should be the same without the `--protocol` switch.)

 - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=twamp` should make `ping` bow out and `twamp` select itself.

**Comment by vvidic** [comment]
On Thu, Jun 07, 2018 at 06:41:21AM -0700, Mark Feit wrote:
> That's fine.  If the `can-run` methods for the `ping` and `twping` are correct, you shouldn't have to explicitly select a tool:
> 
>  - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=icmp` should make `ping` select itself and `twamp` bow out.  (Behavior should be the same without the `--protocol` switch.)
> 
>  - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=twamp` should make `ping` bow out and `twamp` select itself.

Yes, this works as described.

I'm just saying tool selection is now broken with this option so this
gives a strange error:

  pscheduler task --tool=twping rtt --dest=pstest.geant.carnet.hr

while this runs fine:

  pscheduler task --tool=ping rtt --dest=pstest.geant.carnet.hr

so a bit confusing for the users maybe?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
On Thu, Jun 07, 2018 at 06:41:21AM -0700, Mark Feit wrote:
> That's fine.  If the `can-run` methods for the `ping` and `twping` are correct, you shouldn't have to explicitly select a tool:
> 
>  - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=icmp` should make `ping` select itself and `twamp` bow out.  (Behavior should be the same without the `--protocol` switch.)
> 
>  - `pscheduler task rtt --dest=pstest.geant.carnet.hr --protocol=twamp` should make `ping` bow out and `twamp` select itself.

Is there some other way we can prefer ping over twping when protocol
is not set?  Maybe the tool priority thing could help here?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
The `trace` test's `probe-type` already assumes ICMP unless told otherwise, and we have tools that can and can't handle the others.

ICMP-as-default behavior should be fine if we make a note in the docs about it.  The only way `twping` should ever put itself in the running is when the protocol is explicitly set to `twamp`.

**Comment by vvidic** [comment]
On Thu, Jun 07, 2018 at 08:53:27AM -0700, Mark Feit wrote:
> The `trace` test's `probe-type` already assumes ICMP unless told
> otherwise, and we have tools that can and can't handle the others.
> 
> ICMP-as-default behavior should be fine if we make a note in the docs
> about it.  The only way `twping` should ever put itself in the running
> is when the protocol is explicitly set to `twamp`.

Ok, will update the PR with this change as is.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
Please review this last change adding ``--protocol`` option to rtt tests.

**Comment by vvidic** [comment]
Changes merged, closing the issue.
