### ISSUE TITLE
Result version mismatch when running reverse throughput

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#639]
On a production system:

```
[root@farm-host ~]# pscheduler task throughput --dest perfsonardev0.internet2.edu --reverse
Submitting task...
Task URL:
https://a1.ps.dev.internet2.edu/pscheduler/tasks/815093ab-0103-4dd0-b3ac-43a7bab3f7fb
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://a1.ps.dev.internet2.edu/pscheduler/tasks/815093ab-0103-4dd0-b3ac-43a7bab3f7fb/runs/e8d7ccff-fe75-4ba3-a4b1-2449bb20b6b7
Starts 2018-06-27T21:09:49-04:00 (~8 seconds)
Ends   2018-06-27T21:10:08-04:00 (~18 seconds)
Waiting for result...
Unable to retrieve formatted result: Failed to format result: At /summary/summary: Additional properties are not allowed (u'receiver-throughput-bits' was unexpected)

[root@farm-host ~]# rpm -q pscheduler-test-throughput pscheduler-tool-iperf3
pscheduler-test-throughput-1.0.2.6-1.el7.centos.noarch
pscheduler-tool-iperf3-1.0.2.6-1.el7.centos.noarch
```
At the other end (nightly):
```
[mfeit@perfsonardev0 ~]$ rpm -q pscheduler-test-throughput pscheduler-tool-iperf3
pscheduler-test-throughput-1.1-0.1.b1.el6.2103.a91094cda37134f752cc09ebf145ad502911a35e.noarch
pscheduler-tool-iperf3-1.1-0.1.b1.el6.2103.a91094cda37134f752cc09ebf145ad502911a35e.noarch
```

We may have to eliminate the extra field in the result until we figure out how to deal with old leads testing to second participants with newer firmware.  I'm thinking we may have to have the far end look at the schema version in the test spec and not burp out results with newer fields.

**Comment by mfeit-internet2** [comment]
This is what's happening:

 - The second participant (running 4.1b) runs the test and produces a final JSON-formatted test result with the additional field that gets passed back as part of the intermediate result.
 - The lead participant (4.0):
   - Retrieves the later version's JSON during the result merge and plugs it in as the full result.
   - During a query for a formatted result, the formatter attempts to validate the result beforehand and fails because of the additional field.

Givens:
 - The `reverse` switch has to work.
 - We cannot retroactively upgrade the 4.0 systems to understand the new result format.
 - We cannot change the intermediate result format because older systems won't understand it.
 - Second participants are not currently passing back any information about what version they are as part of the intermediate results.

The better thing to do would have been to take the raw data from iperf3 and return that as intermediate data and let the lead participant parse it to format the result.  We could potentially still do that by picking the JSON out of the diagnostics, but that seems very hacky.

Even with the `-R` switch in effect, it looks like the lead can get the exact same raw iperf3 data from the client side and produce a result in the local format without having to care what the other end's JSON looks like.  I'm not 100% positive yet, but I think we should be able to make an orderly transition to that by having the lead side of 4.1's tool disregard the second participant's intermediate result.  For compatibility with 4.0, it can still generate a first-version result.  Once we EOL 4.0, that can be removed.

I'm going to experiment with this further and implement a solution if it works.

**Comment by mfeit-internet2** [comment]
The `receiver-throughput-bits` code put in by #582 has been removed for the time being while we come up with a better way to keep 4.0 hosts from breaking.  When it comes time to put it back, the original commit was 538b93eb23efde6cbe8369b315adbdf2d7bd8371.

Some side discussions with @mattzekauskas lead me to think that we need to get a better handle on what we're pulling out of iperf3 and what we're reporting.  We should probably also talk to Bruce Mah and find out whether we can, in future versions, get the data out of both ends from just the client side, which would probably be useful.

Tabling this ticket until we get 4.1 out the door.

**Comment by tonin** [comment]
Just for the record, one participant at the ASTRON workshop last week asked why retransmits information was only shown for one direction and not for reverse.  It seems it is something people are missing.

**Comment by mfeit-internet2** [comment]
On further review, the better thing to do here would be for each end to pass in the raw JSON from iperf3 as its intermediate results and let the lead participant do the conversion.

**Comment by mfeit-internet2** [comment]
This is a good reason to have bonus material, so the tools could just produce a second measurement in the reverse direction that looks like the first.
