### ISSUE TITLE
Integrate with Existing Toolkit

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#64]
Known issues:

**PostgreSQL.**  Old toolkit runs 9.4, pScheduler needs 9.5.  The upgrade shouldn't break anything for other applications.

**mod_wsgi.**  Old toolkit installs `python27-mod-wsgi`, which has conflicts with files in the `mod_wsgi` RPM.

**Comment by mfeit-internet2** [comment]
Assigning this to Andy since he's doing (has done?) the work.

**Comment by arlake228** [comment]
closing, any specific issues should be created separately
