### ISSUE TITLE
Fix log propagation and other anomalies

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#644]
During #597, I found some odd behaviors in how the `Log` class would change the environment variable that would pass state through for debugging child processes.

This was cleaned up and tagged for that issue, but we can wait for 4.1.1 or 4.2 to release the change.

The issue branch will be renamed to match this ticket; keep it open until we start development on 4.1.x and merge it into that branch.

Edit:  Renamed branch to [issue-644](https://github.com/perfsonar/pscheduler/tree/issue-644).

**Comment by mfeit-internet2** [comment]
**Release notes:**

Improved propagation of debug and logging state between processes.

**Comment by arlake228** [comment]
Merged into 4.1. Closing.
