### ISSUE TITLE
Integrate PyJQ 2.2.0

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#648]
Improvements to PyJQ developed in #529 were contributed to the main source in https://github.com/doloopwhile/pyjq/pull/12 and became part of the 2.2.0 release.

Remove the patches from the `python-pyjq` RPM and upgrade it to 2.2.0.

No rush on this since the code is identical.

**Comment by mfeit-internet2** [comment]
Awaiting merge into next version branch.

Downstream:  Two of the patches that used to be made to this package are no longer necessary.

**Comment by vvidic** [comment]
Has this change been merged somewhere?

**Comment by mfeit-internet2** [comment]
Not yet.  I'm holding it and a couple of other things in branches until we're ready to start the new branching scheme.

**Comment by mfeit-internet2** [comment]
This has been merged into the `4.2.0` branch.

Close when handled downstream.

**Comment by mfeit-internet2** [comment]
This change broke the import search path; see #691.

**Comment by mfeit-internet2** [comment]
This is was fixed in #691 .  Please adjust Debian so it applies the new patch and makes the same change as the RPM spec, then close.

**Comment by vvidic** [comment]
Should be ready on the Debian side too.
