### ISSUE TITLE
Missing NUMA dependencies

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#651]
John Hicks bumped into a situation where iperf3 and nuttcp wouldn't run on Debian:
```
OSError: [Errno 2] No such file or directory: ‘numactl’
```

In the CentOS version, both tool plugins use `numactl` but neither depends on it.  It happens to work there because the test plugin depends on it but doesn't use it.

John's system also wound up with no `pscheduler-tool-iperf3` after installing `perfsonar-testpoint`, which it should have.

To do:

- [x] Fix on CenOS
- [ ] Fix on Debian

**Comment by tonin** [comment]
Looks to be working.  I'll include that in pscheduler 1.1 (pS 4.1).  It is currently only published in the snapshot/nightly repo (and `apt-get dist-upgrade` is needed to get them).
