### ISSUE TITLE
Add -d and --destination options to clock task

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/pscheduler#657]
It would be good to add the two other destination options smimilarly to other task types:

[geantadmin@psmall-poz3 ~]$ pscheduler task clock -d psmall-poz1.man.poznan.pl
localhost: no such option: -d
[geantadmin@psmall-poz3 ~]$ pscheduler task clock --destination psmall-poz1.man.                                                 poznan.pl
localhost: no such option: --destination
[geantadmin@psmall-poz3 ~]$ pscheduler task clock --dest psmall-poz1.man.poznan.                                                 pl
Submitting task...

**Comment by mfeit-internet2** [comment]
The convention for command line switches is that the long-form switch matches the name of the pair in the JSON test specification (e.g., `--length` sets `length`).  The short versions (e.g., `-u` for `--udp`) were put in place as  [comfort food](https://en.wikipedia.org/wiki/Comfort_food) for BWCTL users.

The `--destination` switch in the `throughput` test should never have been there in the first place.  We could remove it in a future release or just say we goofed if anyone asks why that's there.  But we shouldn't be using it in examples or documentation.

**Comment by szymontrocha** [comment]
clear now. anyway it's inconsistent between tasks. Users will not know it's because json, they would rather go opposite way (as me) - if one task supports it one will use it for other assumint it's still the same pscheduler. but it's up to you of course.

**Comment by mfeit-internet2** [comment]
I don't want something we put into existing tests as an aid in transitioning to the new system to propagate into new ones, so I think I'm going to leave this as-is.
