### ISSUE TITLE
Port GridFTP plugins to Debian

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#660]
We need to look how it is possible to port the 3 new plugins to Debian:
 - pscheduler-test-disk-to-disk
 - pscheduler-tool-ftp
 - pscheduler-tool-globus

The last one will have a dependency on some Globus tools (i.e.: `globus-url-copy`) which seems to be available in Debian in the [globus-gass-copy-progs](https://packages.debian.org/stretch/globus-gass-copy-progs) package.

Some documentation about the setup of those test and tools is available at https://github.com/nathanShepherd/pScheduler-GridFTP-Documentation

**Comment by vvidic** [comment]
On Mon, Aug 20, 2018 at 08:00:21AM -0700, Antoine Delvaux wrote:
> We need to look how it is possible to port the 3 new plugins to Debian:
>  - pscheduler-test-disk-to-disk
>  - pscheduler-tool-ftp
>  - pscheduler-tool-globus
> 
> The last one will probably be the most difficult as it requires some Globus tools (`globus-url-copy`).

There is some Globus packaging in Debian but we need to check
if it is usable:

  globus-gass-copy-progs: /usr/bin/globus-url-copy

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by vvidic** [comment]
I think this was released in 4.1.6, so closing.
