### ISSUE TITLE
Verify that plot-schedule works

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#669]
Plot-schedule seems to leave empty gaps where there should be schedule data.

Also doesn't seem to show non-starters where there probably should be some.

**Comment by igarny** [comment]
Hi Szymon, @szymontrocha 
Where did you read about the "Background-multi column"?
Or how do you know about this one?

**Comment by szymontrocha** [comment]
There are 5 types in classification http://docs.perfsonar.net/pscheduler_client_schedule.html but only 4 columns in the plot  :-)

**Comment by szymontrocha** [comment]
So you are saying you have no plans to separate it? It's confusing. If yes, that has to be explained in the documentation as users are bit surprised. Is there a problem with separating it?

**Comment by szymontrocha** [comment]
I created enhancement issue for plot modification #676

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Made schedule plotter handle time zones in a uniform and correct way.
