### ISSUE TITLE
treat `pscheduler troubleshoot localhost` the same as `pscheduler troubleshoot`

### ISSUE THREAD

**Issue by epcjr** [perfsonar/pscheduler#670]
Could we please treat `pscheduler troubleshoot localhost` the same as `pscheduler troubleshoot`?

**Comment by mfeit-internet2** [comment]
I'll see what I can do with that.  Localhost is just a name, and in theory I shouldn't care what the name is or how it resolves.  Maybe I'll have it burp out a note when you do that but still proceed.
