### ISSUE TITLE
Add RTT parameter for disabling fragmentation

### ISSUE THREAD

**Issue by apertome** [perfsonar/pscheduler#673]
The RTT test (and/or `ping` tool, I'm not sure which) allows you to set the packet size for a test with `--size`, but there is no way to disallow packet fragmentation. Because of this, the test results show the test succeeding, even if the MTU is higher than will actually work. There's no indication that fragmentation is taking place:

```
$ pscheduler task rtt --length 8000 --dest 74.114.98.19 --source psmp-gn-owd-01.fra.de.geant.net
Submitting task...
Task URL:
https://psmp-gn-owd-01.fra.de.geant.net/pscheduler/tasks/940cf879-1e33-44a3-a5bb-b3e199a5cf15
Running with tool 'ping'
Fetching first run...

Next scheduled run:
https://psmp-gn-owd-01.fra.de.geant.net/pscheduler/tasks/940cf879-1e33-44a3-a5bb-b3e199a5cf15/runs/050e4c20-304f-410d-94a6-aa873dcf9356
Starts 2018-09-10T15:05:28Z (~6 seconds)
Ends   2018-09-10T15:05:39Z (~10 seconds)
Waiting for result...

1       74.114.98.19  8008 Bytes  TTL 55  RTT 106.0000 ms
2       74.114.98.19  8008 Bytes  TTL 55  RTT 106.0000 ms
3       74.114.98.19  8008 Bytes  TTL 55  RTT 106.0000 ms
4       74.114.98.19  8008 Bytes  TTL 55  RTT 106.0000 ms
5       74.114.98.19  8008 Bytes  TTL 55  RTT 106.0000 ms

0% Packet Loss  RTT Min/Mean/Max/StdDev = 106.594000/106.602000/106.613000/0.413000 ms

No further runs scheduled.
```

The `ping` flag to prevent fragmentation is: 
`-M do`

For example:
```
$ ping -s 8000 -M do psmp-gn-owd-01.fra.de.geant.net
PING psmp-gn-owd-01.fra.de.geant.net (62.40.106.137) 8000(8028) bytes of data.
ping: local error: Message too long, mtu=1500
ping: local error: Message too long, mtu=1500
^C
--- psmp-gn-owd-01.fra.de.geant.net ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1662ms
```

It might be good to also mention that fragmentation may be taking place if `--size` is set, but the `--fragment 0` parameter (or whatever you want to call it) is not set. Annoyingly, ping doesn't seem to indicate this in any way when you run it without `-M do`.

The `trace` test does allow you to specify `--fragment 0` or `--fragment 1`, I believe, already, although I'm not 100% sure that is the syntax it's using.

**Comment by mfeit-internet2** [comment]
Did the following, please check that this is what you're after and I'll pull it:

Added a `fragment` Boolean to the test (and corresponding `--fragment` and `--no-fragment` to the CLI).

Tool `bwctlping` was left alone since it is being deprecated and will reject schema-3 tests.  It doesn't support fragmentation anyway.

Tool `ping` was changed so that it will add `-M want` to the command line if `fragment` is `true`  or `-M do` if it is `false.`  (Tested, works properly.)

Tool `twping` rejects `fragment` since it's not supported.

**Comment by apertome** [comment]
This looks great, thanks, Mark!

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added parameters to the RTT test to allow fragmentation control.
