### ISSUE TITLE
pscheduler task/run archiving

### ISSUE THREAD

**Issue by apertome** [perfsonar/pscheduler#683]
It would be very useful if pscheduler would archive its own task/run data. This would make it easier to analyze pscheduler's behavior as well as verifying that tasks/runs are being created as expected, and other possible use cases. 

To be clear, I'm talking about the records like:

/pscheduler/tasks/<taskid>

and

/pscheduler/tasks/<taskid>/runs/<runid>

**Comment by mfeit-internet2** [comment]
Ideas:

Make the archiver operate on all runs, even failures.

Add an optional `include-failures` field in the archive spec that processes failures if `true`.  The existing behavior is maintained if `false`.

Add to what the archivers get handed:

```
{
  // Existing fields

  "id": "2d288552-88c9-4870-8f34-30b28d29a086",
  "reference": null,
  "test": {  ... },
  "tool": { ... },
  "participants": [ "localhost" ],
  "schedule": { ... },
  "result": null,

  // New fields, taken from the run.

  "state": "failed"
  "errors": "Unable to activate kafooble: no veeblefetzer found."
}
```

**Comment by mfeit-internet2** [comment]
This is useful, but not pressing so I'm going to icebox it.

**Comment by apertome** [comment]
@mfeit-internet2  Hmm, based on your response, I'm not sure I explained this well. We want the *entire* `task`/`run` data structures.

We have a use case where we want to do this in production. Let's talk about it more on the dev call tomorrow perhaps.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added the ability to send failed runs to archivers.
