### ISSUE TITLE
Create users and groups as system instead of regular

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#694]
All creation of users and groups should be done with the `-r` switch to make them system instead of normal.

Check to see if there are any implications of pScheduler not having a home directory (there shouldn't be).

**Comment by candlerb** [comment]
In addition to pscheduler uid/gid, there are also these gids:

```
esmond:x:1001:
perfsonar:x:1002:
pssudo:x:1003: 
```

(the `esmond` and `perfsonar` users already have system uids, and `pssudo` is a group only)

**Comment by mfeit-internet2** [comment]
`pssudo` will be covered in this ticket; if you'd like to open one in the `toolkit` project for the others, one of us will take care of it.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

The pScheduler account is created as a system user (new installs only), login is disabled and the home directory is pointed at a temporary directory.

**Comment by mfeit-internet2** [comment]
Need to hold for creation of 4.1.5.

**Comment by vvidic** [comment]
On the Debian side it is already created with system UID and GID so it should be good:
```
uid=110(pscheduler) gid=115(pscheduler) groups=115(pscheduler)
```

**Comment by vvidic** [comment]
Same goes for the other accounts mentioned:
```
uid=113(esmond) gid=118(esmond) groups=118(esmond)
pssudo:x:123:
```
