### ISSUE TITLE
Archive failure debugging

### ISSUE THREAD

**Issue by apertome** [perfsonar/pscheduler#701]
When archiving is failing, it's difficult to track down the cause. There are a few issues that contribute to this. By the way, these issues all were experienced with the esmond archiver, but I suspect some/all of them are applicable to archiving in general.

- [ ] 1. Archive failures do not always follow the retry options; in the situation we saw today, failed archivings were retried again and again, causing a long backlog. It did not appear it was going to clear. It's also not clear to me whether these would have expired at some point, but we had a backlog of >1000, interfering with other tests.
- [ ] 2. Archive errors (`diags`) are not populated until the archiver gives up on that archiving
- [ ] 3. Running tests with the `--debug` flag does nothing to increase verbosity when archiving

Number 1 and 2 above are especially problematic in that you *never* get the `diags` field populated.

Here's an example of something being retried again and again:
```
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
Oct 16 19:31:54 pas-tst.elpa.net.internet2.edu journal: archiver WARNING  289428: Failed to archive https://localhost/pscheduler/tasks/ec7bd639-c04a-4fef-b2d1-dc15c7223721/runs/80b6666d-3460-4ae3-b1cd-52595
2dcda3b to esmond: Archiver error: Program exited 1: Traceback (most recent call last):
```

from that same task:
```
               "retry-policy": [
                    {
                        "attempts": 1,
                        "wait": "PT60S"
                    },
                    {
                        "attempts": 1,
                        "wait": "PT120S"
                    }
```

I would expect this to archive, retry once after 60s, and again after 120s, but instead it retries dozens of times at once, repeating over and over, with `last_attempt` and `diags` never getting set.

**Comment by apertome** [comment]
Here's a log showing more details about the bizarre archive failure behavior.

You'll notice there are ~46 simultaneous failure messages, then it waits 30-120s and retries again, once again dozens at a time. This continues for over an hour (in fact, it's still happening, this started around 90 minutes ago). once again, `last_attempt` and `diags` never get set so these just keep retrying over and over again.

[task-80b6666d-3460-4ae3-b1cd-525952dcda3b.log](https://github.com/perfsonar/pscheduler/files/2484688/task-80b6666d-3460-4ae3-b1cd-525952dcda3b.log)

**Comment by apertome** [comment]
Related to #698 which has more context

**Comment by mfeit-internet2** [comment]
Some quick comments:

 > 1. Archive failures do not always follow the retry options; in the situation we saw today, failed archivings were retried again and again, causing a long backlog. It did not appear it was going to clear. It's also not clear to me whether these would have expired at some point, but we had a backlog of >1000, interfering with other tests.

This looks like a plugin failure being treated as immediate retry, which is a bug in the archiver daemon and should be easy to fix.  I'll try to look at this tonight or tomorrow during downtime.  I think we should treat that as a permanent failure.

 > 2. Archive errors (diags) are not populated until the archiver gives up on that archiving

The diags in the database should be updated after each attempt since the daemon doesn't keep tabs on any of it while it's waiting between attempts.  I'm pretty sure `pscheduler result` will show partial results; again, will check.

 > 3. Running tests with the --debug flag does nothing to increase verbosity when archiving

The `--debug` switch is for debugging the `task` command.  You can do a `pscheduler debug on archiver` to have the archiver spew more log messages.

**Comment by mfeit-internet2** [comment]
The changes for this will be committed shortly, but here's how things fell out:

The `StreamingJSONProgram` class, which runs archiver plugins' `archive` methods, will attempt to restart the method multiple times (3 by default) as it always has.  A situation where the failure is cured by restarting the method (e.g., ran out of a resource) will result in success the next attempt and all will be well.  If the program repeatedly exits with a non-zero status or otherwise misbehaves when handed the same input (as happened in #698), the attempt to write/read a blob of JSON to/from it will be declared a _bad failure_.

The archiver daemon will treat bad failures as permanent and abandon the archiving.

Archiver plugins that want to tell the daemon to retry even in the face of these kinds of failures should wrap whatever they're doing in a try/catch so exceptions can be caught, the retry policy can be applied and sane output is produced for the daemon to consume.  After that, the program can exit with a regular EOF and the class that runs the method will start a fresh one next time it's asked.

I had added code to the database to apply a 24-hour TTL to archivings that don't specify one.  I'm going to remove it, because I think treating bad failures as permanent will solve one end of the problem and the keep time for runs will have the same effects because deletions will cascade into archivings.

**Comment by mfeit-internet2** [comment]
Going to call this one done.

**Comment by apertome** [comment]
This worked in my testing, too. thanks!
