### ISSUE TITLE
Disk-to-disk test looks for non-existent "host-node" in participants

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#710]
The disk-to-disk test looks for a field called `host-node` in participants, but this field cannot be set at the CLI and is not in the JSON request schema. It would be nice to have such a field for third-party tests, but currently there is no way to pass it through.

**Comment by epcjr** [comment]
Added Nate

**Comment by nathanShepherd** [comment]
This issue has been resolved in a recent commit. Users can now specify a host-node at the command line interface.
