### ISSUE TITLE
pscheduler task idle returns 5S for 4S or less as argument

### ISSUE THREAD

**Issue by mattzekauskas** [perfsonar/pscheduler#713]
found during a tutorial at SC with a slew o' VMs.

[workshop@workshop18 ~]$ pscheduler task idle --duration PT4S
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/345170f3-4e0c-40d0-b453-1bf5b5ae622a
Running with tool 'snooze'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/345170f3-4e0c-40d0-b453-1bf5b5ae622a/runs/aa10e163-3f2a-4b04-959f-d2d65713fc92
Starts 2018-11-13T21:09:42Z (~7 seconds)
Ends   2018-11-13T21:09:47Z (~4 seconds)
Waiting for result...

Duration ... PT5S

No further runs scheduled.

-=-=-=-
[workshop@workshop18 ~]$ pscheduler task idle --duration PT2S
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/41a57825-e2d6-4965-969e-39fd4f2f5dd7
Running with tool 'snooze'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/41a57825-e2d6-4965-969e-39fd4f2f5dd7/runs/99e14b91-6ab8-4a85-a607-00b408714c10
Starts 2018-11-13T21:13:01Z (~7 seconds)
Ends   2018-11-13T21:13:06Z (~4 seconds)
Waiting for result...

Duration ... PT5S

No further runs scheduled.
-=-=-=--
10S worked as expected.

**Comment by mfeit-internet2** [comment]
Figured this out:

The standard limit configuration has a bit of rewriter script that increases the duration of some tasks to a minimum value as a "if you're going to bother us, at least make it worth our while" measure.  The VM for that system was still up, so I pulled the diagnostics for that run and confirmed it:

```
Limit system diagnostics:
...
  Rewriter made changes:
    Bumped duration to 5-second minimum
...
```
