### ISSUE TITLE
error handling if accidentally use URL for a source or destination

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#724]
If you cut/paste a hostname that includes "http://", such as:

pscheduler task throughput --dest http://perfsonar2.mi.infn.it --source lhcmon.bnl.gov

You get this error:

Submitting task...
Unable to determine the lead participant: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/test/throughput/participants", line 41, in <module>
    has = pscheduler.api_has_services([source, destination], timeout=3)
  File "/usr/lib/python2.7/site-packages/pscheduler/api.py", line 351, in api_has_services
    for host, service, state in pool.imap(check_one, args, chunksize=1):
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
ValueError: invalid literal for int() with base 10: ''

----

can it just return 'invalid hostname' instead?

**Comment by mfeit-internet2** [comment]
There is (was) some inconsistent validation of the incoming test spec among the tests' `participants` methods.  All have been brought up to snuff.
