### ISSUE TITLE
API Server Debugging Doesn't Work

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#753]
The change made in #113 failed to take into account the fact that more-recent versions of systemd give services their own temporary space, and the way things worked out the processes in the API server didn't see what each other was writing.

**Comment by mfeit-internet2** [comment]
Downstream (@vvidic or @tonin):  The commits in 77b2a2f make a change to the RPM spec that needs to be carried into Debian.  Please adjust and close when finished.

**Comment by mfeit-internet2** [comment]
**Release Notes:**
Improved debugging in the API service

**Comment by vvidic** [comment]
Not sure if creating `RUN_SPACE=/run/pscheduler-server` in the package will work because `/run` gets wiped on reboot?

For systemd we would need to used tmpfiles.d to create this dir and for init scripts run the mkdir manually.

**Comment by mfeit-internet2** [comment]
Good point.  I'll square that away when I get back to work tomorrow.

**Comment by mfeit-internet2** [comment]
This has been fixed in c124a8e69daf8ef7367e748bba7fbd20038265ce, which also moves all of the PID and options files into the same private directory.

**Comment by vvidic** [comment]
Yes, I think this should work now except these commands are in /bin on Debian and Ubuntu:

```
ExecStartPre=-/usr/bin/mkdir -p __RUNDIR__
ExecStartPre=-/usr/bin/chown __PSUSER__:__PSUSER__ __RUNDIR__
ExecStartPre=-/usr/bin/chmod 700 __RUNDIR__
```

**Comment by mfeit-internet2** [comment]
Well, that's just dandy.  CentOS has copies in both places.

If systemd will let us get away without using the path, go that route, otherwise change them to /bin.

**Comment by vvidic** [comment]
Yes, /bin is symlinked in CentOS, but Debian does not have that yet.

We have adjusted for this already in other commands so we can do the same here.

```
# Generate the PID file in an atomic way
ExecStartPre=-/bin/rm -f __RUNDIR__/pscheduler-__PROG__.pid.build
ExecStartPre=-/usr/bin/touch -f __RUNDIR__/pscheduler-__PROG__.pid.build
```

**Comment by mfeit-internet2** [comment]
That's fine by me.

**Comment by vvidic** [comment]
Ok, pushed the change to 4.2.0 branch.

**Comment by vvidic** [comment]
/var/run/pscheduler-server/ created on the Debian as expected, so closing.
