### ISSUE TITLE
HTTP Archiver needs Content-Type

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#756]
The HTTP archiver doesn't provide a `Content-Type` header when posting a result.  That angers ElasticSearch, which expects `application/json`.

Add an optional `content-type` field to the archive spec that will be used for the operation if provided.

If there is no `content-type`, these should be the rules:

 * With a transform in raw mode, `text/plain`.
 * With a transform not in raw mode:
    * If what comes back can be converted to a JSON type, `application/json`.
    * Otherwise, `text/plain` with a string representation.
 * With no transform, `application/json`.

**Comment by apertome** [comment]
Please add this info to the docs, too.

**Comment by mfeit-internet2** [comment]
This is done and pulled into 4.1.6, as are the docs.  Check there for details.  This version will pick up that the data is `application/json` without doing anything special, but you can still change or remove the `Content-Type` header if you need to.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Gave the HTTP archiver the ability to provide headers to the server with automatic determination of `Content-Type` and `Content-Length` that can be overridden manually.
