### ISSUE TITLE
Add congestion control selection to throughput test

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#78]
This should be added to the test spec and CLI even if the tools don't support it yet so we don't have to change the JSON later.

Here's a good list to start with:  http://sgros.blogspot.com/2012/12/controlling-which-congestion-control.html

**Comment by daldoyle** [comment]
Initial list done by:
https://github.com/perfsonar/pscheduler/commit/3c7d25d5f698b9f68bb44ea2fc249fe1af2d2151

At the moment these are still passed straight through to the underlying tool, may need to change that behavior later if another tool comes along and uses different nomenclature.
