### ISSUE TITLE
No latencybg results when running from CLI

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#784]
@tonin reports that running `latencybg` from the command line results in a run with no additional runs produced other than the dummy "master" run.

The CLI doesn't show that the run has completed:
```
pscheduler task latencybg --dest dev2 --duration PT20S
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/7f0dca4d-8ee1-4f01-be71-69067f1790fd
Running with tool 'powstream'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/7f0dca4d-8ee1-4f01-be71-69067f1790fd/runs/7ceab9c8-e0ab-4b07-a776-8e3c0891c8e0
Starts 2019-03-13T11:56:34-04 (~2 seconds)
Ends   2019-03-13T11:56:54-04 (~19 seconds)
Waiting for result...

Run has not completed.

No further runs scheduled.
```

Fetching the master run shows it to be in the `cleanup` state.

Debug shows that the tool is run but no results are produced:
```
Mar 13 11:56:34 dev1 journal: tool-powstream/run DEBUG    Debug started
Mar 13 11:56:34 dev1 journal: tool-powstream/run DEBUG    Powstream run ends at 2019-03-13 11:56:54-04:00
Mar 13 11:56:34 dev1 journal: tool-powstream/run DEBUG    Powstream run ends at 2019-03-13 11:56:54-04:00
Mar 13 11:56:37 dev1 journal: tool-powstream/run DEBUG    Parent pid is 31139
Mar 13 11:56:37 dev1 journal: tool-powstream/run DEBUG    Parent pid is 31139
Mar 13 11:56:37 dev1 journal: tool-powstream/run DEBUG    Running command: /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/7f0dca4d-8ee1-4f01-be71-69067f1790fd-2019Mar13T155634184013 -c 600 -i 0.1 -t [dev2]:861
Mar 13 11:56:37 dev1 journal: tool-powstream/run DEBUG    Running command: /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/7f0dca4d-8ee1-4f01-be71-69067f1790fd-2019Mar13T155634184013 -c 600 -i 0.1 -t [dev2]:861
Mar 13 11:56:54 dev1 journal: tool-powstream/run DEBUG    powstream returned status None
Mar 13 11:56:54 dev1 journal: tool-powstream/run DEBUG    powstream returned status None
Mar 13 11:56:54 dev1 journal: tool-powstream/run DEBUG    Terminated powstream process 4371
Mar 13 11:56:54 dev1 journal: tool-powstream/run DEBUG    Terminated powstream process 4371
```

This is probably related to the plugin, because `idlebgm` behaves correctly.

**Comment by arlake228** [comment]
@mfeit-internet2 I may need to discuss with you what needs to be done here since from what I recall this is a limitation of the CLI as it relates to all continuous tasks (not just latencybg). IIRC it is due to the way they report results vs. how the CLI fetches them. Has something changed, are there other continuous tasks that for which this works?

**Comment by mfeit-internet2** [comment]
@arlake228 I need to look further into it. In theory, there should be no difference between the CLI and anything else since the task ends up a a blob of JSON, but the former does have the extra `cli-to-spec` step.

This is on the short list when I get done with pShooter.

**Comment by mfeit-internet2** [comment]
For Antoine's diagnostic use case (i.e., making sure results are being produced), it's better to use the `result` command with the task URL:
```
pscheduler result https://localhost/pscheduler/tasks/3760d10e-eb81-45d8-b864-c510a2865262
```
This will run a dump of all runs for a task from the beginning until the present and then exit.

-----

Making the CLI keep up with background-multi runs the way it does with non-multi poses some logistical problems.

Regular (non-multi) runs are synchronous.  They're scheduled in advance, so the CLI can ask the system when the next one is scheduled to wrap up, sleep until then and then go ask the server for the result.  By that time, the next run (if there is one) will already have been scheduled and the process can repeat indefinitely without chewing up a lot of resources.

Multi runs are asynchronous.  The "master" (first) run endures for the entire time the task is scheduled to run and the tool's `run` method provides a stream of results that are turned into runs as they're produced.  They look like regular runs, but the only way to detect that one has happened is to poll the API and find out.  Setting an interval for that would be guesswork because when new runs are produced would be dependent on the tool producing them and possibly the task parameters.  The development and resource consumption for this seem excessive for what is, essentially, a rarely-used case.

The CLI doesn't behave well for multis, and that will be fixed as part of this ticket.  I think what I'm going to do is have the watcher check to see if the task is multi (already available from the API), recommend using `result` to check on progress and then exit.  That seems like a good solution without the downsides.
