### ISSUE TITLE
Upgrade jq to 1.6

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#785]
Jq 1.6 was released in November.

Need to apply a patch for the problem in #717, which looks like a jq bug.

**Comment by mfeit-internet2** [comment]
This has been done and includes a semi-final fix to `python-pyjq` for #717 since both had to be worked at the same time.

Debian will need to adjust its builds for both packages and then this ticket can be closed.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Upgraded the jq scripting language to version 1.6.  (Release notes for that are at https://github.com/stedolan/jq/releases/tag/jq-1.6.)

**Comment by vvidic** [comment]
Updated Debian packaging in branch ``issue-785``, so you can merge if you wish.

**Comment by mfeit-internet2** [comment]
Merged, fixed, never closed it.
