### ISSUE TITLE
Upgrade python-jsonschema to 3.0.1

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#789]
pShooter needs a feature in draft 7.  This needs to be re-added to the RPM builds because it was removed.

**Comment by mfeit-internet2** [comment]
This required the addition of a newer version of setuptools and the addition of Pyrsistent.

**Comment by mfeit-internet2** [comment]
Debian will need to build or simply install this and prerequisites.

Close when finished.

**Comment by vvidic** [comment]
I assume python-pscheduler requires this new version of jsonschema?

**Comment by vvidic** [comment]
Merged the Debian changes into the 4.2.0 branch.
