### ISSUE TITLE
Requesting a duration past the scheduling time horizon causes scheduler to go nuts

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#80]
I requested a background task with a duration past the 24 hour scheduling time horizon while debug was on and got the following constantly in the logs until i killed psheduler:

> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Trying to schedule 8b5257dc-bb17-466f-be62-98bb135b848d for 2016-08-18 09:51:19.408807-04:00 at https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    URL is https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Posting https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d at 2016-08-18 09:51:19.408807-04:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Participant list is [None]
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Participant task URL is https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Range parameters are {'start': '2016-08-18T09:51:19-04:00', 'end': '2066-08-06T09:51:19-04:00'}
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Unable: No mutually-agreeable time to run this task.[[(datetime.datetime(2016, 8, 18, 9, 51, 19, tzinfo=<FixedOffset u'-04:00'>), datetime.datetime(2016, 8, 19, 9, 51, 9, tzinfo=<FixedOffset u'-04:00'>))]] 18250 days, 0:00:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    BACKGROUND TASK 8b5257dc-bb17-466f-be62-98bb135b848d, 0 runs, try 2016-08-18 09:51:09-04:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Trying to schedule 8b5257dc-bb17-466f-be62-98bb135b848d for 2016-08-18 09:51:19.431840-04:00 at https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    URL is https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Posting https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d at 2016-08-18 09:51:19.431840-04:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Participant list is [None]
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Participant task URL is https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Range parameters are {'start': '2016-08-18T09:51:19-04:00', 'end': '2066-08-06T09:51:19-04:00'}
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Unable: No mutually-agreeable time to run this task.[[(datetime.datetime(2016, 8, 18, 9, 51, 19, tzinfo=<FixedOffset u'-04:00'>), datetime.datetime(2016, 8, 19, 9, 51, 9, tzinfo=<FixedOffset u'-04:00'>))]] 18250 days, 0:00:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    BACKGROUND TASK 8b5257dc-bb17-466f-be62-98bb135b848d, 0 runs, try 2016-08-18 09:51:09-04:00
> Aug 18 09:51:09 psched-dev2 scheduler DEBUG    Trying to schedule 8b5257dc-bb17-466f-be62-98bb135b848d for 2016-08-18 09:51:19.455818-04:00 at https://psched-dev2/pscheduler/tasks/8b5257dc-bb17-466f-be62-98bb135b848d

**Comment by mfeit-internet2** [comment]
The scheduling rules aren't exempting background tests from the scheduling horizon and should be.

Restrictions on duration will still be possible through the limit system.

**Comment by mfeit-internet2** [comment]
Fixed in dccce756eed8ea2048bbe5184f738825037fd4de.
