### ISSUE TITLE
Improvement: stop parsing pSc Limits rules, once a pass assessment is reached.

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#802]
I would like to refer to #800 . There you'll notice, that even though the Limits have been satisfied already in the first rule, pscheduler continues to process the Limits rules. Despite the fact they fail, the task is accepted. Meaning it makes little to no sense for these to be processed.
One can imagine with complex psc Limits rules, it is not very much practical.

Perhaps we could have a flag similar to **"stop-on-failure"**, although I would say this would not fit with the logic, still it is not my call.

**Comment by mfeit-internet2** [comment]
The rest of the limits are processed to support the "infinite limit" case, where throughput had to be capped to a certain bandwidth even if none was specified.  This was originally done with code in the tool's `run` method that would see what limits were passed (even if they didn't affect the pass/fail status) and use the appropriate value.

The rewriter now takes care of this, and everything else put in to support it will go away in 4.3.

**Comment by mfeit-internet2** [comment]
Given that the feature requiring this is going to go away, this will be a self-solving issue.  Closing.
