### ISSUE TITLE
SSL: certificate subject name (stretch) does not match target host name 'localhost'

### ISSUE THREAD

**Issue by vvidic** [perfsonar/pscheduler#817]
Not sure if this is related to pycurl change but I thought we don't check SSL certificates?

```
# pscheduler troubleshoot
Performing basic troubleshooting of localhost.

localhost:

  Measuring MTU... Failed.
SSL: certificate subject name (stretch) does not match target host name 'localhost'
```

**Comment by vvidic** [comment]
Also not sure if we still need python-requests installed with pycurl?

```
[Wed Apr 17 11:09:36.113941 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556] mod_wsgi (pid=8177): Target WSGI script '/usr/share/pscheduler/api-server/pscheduler-api-server.wsgi' cannot be loaded as Python module.
[Wed Apr 17 11:09:36.113958 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556] mod_wsgi (pid=8177): Exception occurred processing WSGI script '/usr/share/pscheduler/api-server/pscheduler-api-server.wsgi'.
[Wed Apr 17 11:09:36.113974 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556] Traceback (most recent call last):
[Wed Apr 17 11:09:36.113989 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]   File "/usr/share/pscheduler/api-server/pscheduler-api-server.wsgi", line 10, in <module>
[Wed Apr 17 11:09:36.114012 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]     from pschedulerapiserver import application
[Wed Apr 17 11:09:36.114021 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]   File "/usr/share/pscheduler/api-server/pschedulerapiserver/__init__.py", line 17, in <module>
[Wed Apr 17 11:09:36.114036 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]     from .response import *
[Wed Apr 17 11:09:36.114044 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]   File "/usr/share/pscheduler/api-server/pschedulerapiserver/response.py", line 6, in <module>
[Wed Apr 17 11:09:36.114057 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556]     import requests
[Wed Apr 17 11:09:36.114072 2019] [wsgi:error] [pid 8177:tid 140360336254720] [remote 127.0.0.1:54556] ImportError: No module named requests
```

**Comment by vvidic** [comment]
Maybe this is just a leftover import of requests we need to remove?

**Comment by mfeit-internet2** [comment]
I'm not seeing the cert problem in the production or dev code on EL7.

The import of requests in the API should not have been there;  it slipped in during an April, 2016 change in which I broke the monolithic server module into pieces and remained.   I've removed the import in 4.2.0 and got rid of the dependencies in the RPM spec.

I'll keep this open until the cert problem is resolved.

**Comment by vvidic** [comment]
On Thu, Apr 18, 2019 at 07:17:39PM +0000, Mark Feit wrote:
> I'm not seeing the cert problem in the production or dev code on EL7.
> 
> The import of requests in the API should not have been there;  it
> slipped in during an April, 2016 change in which I broke the
> monolithic server module into pieces and remained.   I've removed the
> import in 4.2.0 and got rid of the dependencies in the RPM spec.
> 
> I'll keep this open until the cert problem is resolved.

Thanks for the check.  Maybe we are missing some piece on the Debian
side or have a different version of pycurl.  I'll try to dig a bit more...

-- 
Valentin

**Comment by mfeit-internet2** [comment]
Valentin's fix was pulled.  Closing.
