### ISSUE TITLE
"Invalid transition between states" error when adding multiple long-running tests

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#82]
On antg-dev, while adding multiple long-running latencybg tests I eventually get something like the following in the logs: 

> Aug 19 11:07:04 antg-dev runner ERROR    Exception: InternalError: Invalid transition between states (7 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (7 to 3).
> Aug 19 11:07:05 antg-dev runner ERROR    Exception: InternalError: Invalid transition between states (7 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (7 to 3).
> Aug 19 11:07:12 antg-dev safe_run/runner ERROR    Exception: InternalError: Invalid transition between states (7 to 2).#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 608, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 565, in main_program#012    """, (tuple(run_ids),))#012InternalError: Invalid transition between states (7 to 2).
> Aug 19 11:07:12 antg-dev safe_run/runner ERROR    Waiting 0.75 seconds before restarting
> Aug 19 11:07:14 antg-dev runner ERROR    Exception: InternalError: Invalid transition between states (7 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (7 to 3).
> Aug 19 11:07:19 antg-dev runner ERROR    Exception: InternalError: Invalid transition between states (7 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (7 to 3).
> Aug 19 11:07:19 antg-dev archiver-esmond/archive INFO     Started
> Aug 19 11:07:19 antg-dev archiver-esmond/archive INFO     Started
> Aug 19 11:07:19 antg-dev archiver-esmond/archive INFO     Started
> Aug 19 11:07:21 antg-dev test-latencybg/spec-is-valid INFO     Started
> Aug 19 11:07:21 antg-dev safe_run/runner ERROR    Program threw an exception after 0:00:08.393592
> Aug 19 11:07:21 antg-dev safe_run/runner ERROR    Exception: InternalError: Invalid transition between states (7 to 2).#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/pscheduler/saferun.py", line 41, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 608, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 565, in main_program#012    """, (tuple(run_ids),))#012InternalError: Invalid transition between states (7 to 2).
> Aug 19 11:07:21 antg-dev safe_run/runner ERROR    Waiting 1.0 seconds before restarting
> Aug 19 11:07:22 antg-dev safe_run/runner ERROR    Restarting
> Aug 19 11:07:24 antg-dev runner ERROR    Exception: InternalError: Invalid transition between states (7 to 3).#012#012Traceback (most recent call last):#012  File "/usr/libexec/pscheduler/daemons/runner", line 232, in run#012    self.__run()#012  File "/usr/libexec/pscheduler/daemons/runner", line 261, in __run#012    """, [self.id])#012InternalError: Invalid transition between states (7 to 3).

I ran into it multiple times and once it hits, it seems to prevent any new tasks from getting added. Starting from a clean schedule, I encountered it upon entering the 7th task the first time, cleared the DB (make fresh) and then hit it on the 9th task the second time. Not sure if the number of tasks is actually significant or not. Maybe some sort of race condition? Looks like maybe a run is getting marked as missed and then something else comes along and wants to mark it on on-deck or running.

**Comment by mfeit-internet2** [comment]
Andy says "OK"
