### ISSUE TITLE
NUMA library complains that value is invalid

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#834]
Boaz Raz observed the following:

```
$ pscheduler task throughput --bandwidth 1M --dest $ip
Submitting task...
Task URL:
https://localhost/pscheduler/tasks/75622bc4-c08d-4e61-8ea0-4edf099093d0
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://localhost/pscheduler/tasks/75622bc4-c08d-4e61-8ea0-4edf099093d0/runs/69eafb25-8a50-49a3-877c-d8fd3a26cf4f
Starts 2019-05-03T14:14:10Z (~6 seconds)
Ends   2019-05-03T14:14:29Z (~18 seconds)
Waiting for result...

Run did not complete: Failed


Diagnostics from localhost:
  No diagnostics.

Error from localhost:
  iperf3 returned an error: <0> is invalid

  libnuma: Warning: node argument 0 is out of range

  usage: numactl [--all | -a] [--interleave= | -i <nodes>] [--preferred= | -p <node>]
                 [--physcpubind= | -C <cpus>] [--cpunodebind= | -N <nodes>]
                 [--membind= | -m <nodes>] [--localalloc | -l] command args ...
         numactl [--show | -s]
         numactl [--hardware | -H]
         numactl [--length | -l <length>] [--offset | -o <offset>] [--shmmode | -M <shmmode>]
                 [--strict | -t]
                 [--shmid | -I <id>] --shm | -S <shmkeyfile>
                 [--shmid | -I <id>] --file | -f <tmpfsfile>
                 [--huge | -u] [--touch | -T]
                 memory policy | --dump | -d | --dump-nodes | -D

  memory policy is --interleave | -i, --preferred | -p, --membind | -m, --localalloc | -l
  <nodes> is a comma delimited list of node numbers or A-B ranges or all.
  Instead of a number a node can also be:
    netdev:DEV the node connected to network device DEV
    file:PATH  the node the block device of path is connected to
    ip:HOST    the node of the network device host routes through
    block:PATH the node of block device path
    pci:[seg:]bus:dev[:func] The node of a PCI device
  <cpus> is a comma delimited list of cpu numbers or A-B ranges or all
  all ranges can be inverted with !
  all numbers and ranges can be made cpuset-relative with +
  the old --cpubind argument is deprecated.
  use --cpunodebind or --physcpubind instead
  <length> can have g (GB), m (MB) or k (KB) suffixes


Diagnostics from $IP:
  No diagnostics.

Error from $IP:
  iperf3 returned an error:
  Process took too long to run.

No further runs scheduled.


$  numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6
node 0 size: 0 MB
node 0 free: 0 MB
node 1 cpus: 1 3 5 7
node 1 size: 8114 MB
node 1 free: 4744 MB
node distances:
node   0   1
  0:  10  20
  1:  20  10

$ numastat
                           node0           node1
numa_hit                       0         9992950
numa_miss                      0               0
numa_foreign                   0               0
interleave_hit                 0           15419
local_node                     0         5085119
other_node                     0         4907831```
```

**Comment by mfeit-internet2** [comment]
More from Slack:

Mark Feit [10:18 AM]
One last question:  What was the IP you were testing to?  (Need to see what interface was being selected.)

Boaz Raz [9:07 AM]
oh sorry, i was out yesterday
198.71.46.67
https://pas.net.internet2.edu/maddash-webui/details.cgi?uri=/maddash/grids/AL3S+Throughput/198.71.46.219/198.71.46.67/Throughput

Mark Feit [9:11 AM]
No sweat.  I'm just trying to re-create the same conditions.

Boaz Raz [9:11 AM]
sure

Mark Feit [9:11 AM]
It's weird, though...  I can't find a reason for it to have happened.

Boaz Raz [9:12 AM]
I did Disable NUMA
and after that it just worked

Mark Feit [9:13 AM]
There is code in the plugin that asks the system for affinity for the outbound interface and uses the result.

Boaz Raz [9:13 AM]
as I know this server used to have 16GB RAM, I don't know if the issue starts at the same time the memory failed
I can enable NUMA if you want and reboot the server
if you want to test and re-create the error

Mark Feit [9:14 AM]
Ah, the plot thickens.  Was the faulty memory replaced?

Boaz Raz [9:14 AM]
the faulty memory was not replaced

Mark Feit [9:17 AM]
So this could be a hardware-induced problem.  But if you want to re-enable NUMA and re-boot, I'm game to try it out in that state.

Boaz Raz [9:18 AM]
sure, give me few min please. I'l let you know when its done

Mark Feit [9:18 AM]
Take your time; I have other things to tend to.

Boaz Raz [10:07 AM]
I enabled `NUMA` on pas-tst.start
```$  numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6
node 0 size: 0 MB
node 0 free: 0 MB
node 1 cpus: 1 3 5 7
node 1 size: 8114 MB
node 1 free: 4648 MB
node distances:
node   0   1
  0:  10  20
  1:  20  10```
this is the test I was trying `pscheduler task throughput  --dest 198.71.46.67`
and it is failing now

**Comment by mfeit-internet2** [comment]
This appears to be a system-specific problem.  The host enumerates a node 0 (as shown above) but libnuma fails to allow its use, even for operations outside of pScheduler:
```
[mfeit@pas-tst ~]$ numactl -N 0 hostname
libnuma: Warning: node argument 0 is out of range

<0> is invalid

[mfeit@pas-tst ~]$ numactl -N 1 hostname
pas-tst.star.net.internet2.edu
[mfeit@pas-tst ~]$ 

[mfeit@pas-tst ~]$ rpm -qa | fgrep numa
numactl-2.0.9-7.el7.x86_64
numactl-libs-2.0.9-7.el7.x86_64
```

I ran the same test on CHIC, NEWY32AOA, LOSA and SEAT.  All have the same libnuma and all function correctly.

Given that the problem system is known to have bad RAM, I'm inclined to chalk this up to a hardware problem.

**Comment by apertome** [comment]
Reopening to discuss further at dev meeting tomorrow

**Comment by mfeit-internet2** [comment]
`numactl` has a `--preferred=N` switch that will allocate memory on node N if it can or fall back to other nodes if it can't.

The down side is that if there's a memory failure like the one seen here, the program would fall back silently and there could be a difference in the measurement results.

**Comment by mfeit-internet2** [comment]
**Release notes:**

Adjusted behavior of the iperf3 tool to not use NUMA if the selected node cannot run a program.
