### ISSUE TITLE
Secure iperf3 server against non-pScheduler clients

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#836]
When running iperf3, the server will accept a connection from any client, which could potentially mean that a third party could get use of it.

Have the `participant-data` method generate random credentials for each test that the client and server ends will use to prevent this.

Will probably need to set up the API server so:
 * Non-leads will only show the participant data to the lead
 * Non-leads will only accept changes to the participant data from the lead (ALREADY COVERED)
 * Lead doesn't show participant data at all.  Nothing needs to see it.

**Comment by mfeit-internet2** [comment]
Bruce is planning to release this change in 3.7, but since it's only a behavior change, the feature can be implemented in pScheduler at any time.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added authentication to the iperf3 tool to prevent the server from being used outside of a task.

**Comment by tonin** [comment]
The Python `secrets` module is from Python 3.6 … and both Debian 9 and Ubuntu 16 are still using Python 3.5.  We'll need to build our own `python3-secrets` package for those OS if we want to support that feature.

**Comment by tonin** [comment]
A few pointers to build that python-secrets package:
- source: https://pypi.org/project/python-secrets/
- packaging python module for Debian: https://www.debian.org/doc/packaging-manuals/python-policy/module_packages.html
- general Debian Python policy: https://www.debian.org/doc/packaging-manuals/python-policy/
- the python-ntplib package we provide might serve as an example.

**Comment by mfeit-internet2** [comment]
Closing since D9 and U16 are no longer supported.
