### ISSUE TITLE
Make a snmp test/tool bundle

### ISSUE THREAD

**Issue by epcjr** [perfsonar/pscheduler#842]
Make a snmp test/tool bundle

**Comment by epcjr** [comment]
Also add this to Ansible automations

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Split the `extras` bundle into one for the SNMP tests, tools and archiver (called `snmp`) and one for obsolete packages (called `obsolete`).

**Comment by mfeit-internet2** [comment]
@tonin Please check the Debian bundles in this branch and make sure they're good.

**Comment by tonin** [comment]
@mfeit-internet2 all good by me, ready to be merged, see #871
