### ISSUE TITLE
Throughput test needs limits.

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#86]
Title says it all.

**Comment by mfeit-internet2** [comment]
Something to consider for this:

Throughput without `--bandwidth` is effectively infinite.  This means the limit processor will have to treat that situation as being beyond any limit (if there is one).  The cure would be one of:

* Require that a bandwidth-limited task have an explicit `--bandwidth` that's within the limit.  This would at least require the submitter to understand exactly how much bandwidth he's asking for.
* Find a way for the runner to pass all of the applied limits to the `run` method and let it decide how to limit itself.

**Comment by igarny** [comment]
Hi Mark,

Generally my assumption would be, that the initiator of bandwidth test is part of an organization maintaining any of the 2 hosts. In this case it should not be a problem for her to define the max or less of the line speed of the local interface.

In another case, where pro-s are investigating a path, I would expect them to check (get informed) about the properties of the toolkit instances they would like to use. So these guys would know the expected limits.

In the case, where somebody decided, just for fun, to run a test between 2 remote points. I would guess pSched would give them minimum. For example: Imagine someone starts a test with no duration? Currently bwctl starts a 10sec test, right? 

Most importantly pSched should announce something in the sort (like bwctl does): the task was run with these limits applied ......./ But you already have this in the task description.
I would hope to see the undefined parameters commented with (defaults)(automatic)(unspecified)(...) in the task description.

**Comment by daldoyle** [comment]
Current plan after talking about it internally -

Make limits apply to UDP tests only since these require a bandwidth requirement. This is functionally the same as the bwctl based system so we don't lose anything or expose anyone to more "risk".

Longer term, Mark is going to look into adding a mechanism that would allow limit processors to modify the test spec ultimately passed down into "run". (Or another option he deems more appropriate)

**Comment by daldoyle** [comment]
Basic limits have been implemented that parallel what BWCTL did. Waiting on longer term limit processor enhancements before tackling the rest since they won't be terribly effective otherwise.

**Comment by mfeit-internet2** [comment]
Kicking into RC2, holding on the resolution of the infinite limits problem.

**Comment by mfeit-internet2** [comment]
Needs polishing.

**Comment by arlake228** [comment]
To close this issue, need to update throughput tests to limit parameters it does not currently look at, in particular source and dest

**Comment by daldoyle** [comment]
I think this is done. throughput tests now allow limits on "source", "dest", and "endpoint. 

"source", "dest" are limits of their respective fields - the limit-passes function will figure out which one it is and then apply the limits accordingly.

"endpoint" just ensures that one of the addresses is in the allowed limit.
