### ISSUE TITLE
Couldn't format pSConfig

### ISSUE THREAD

**Issue by lbsou** [perfsonar/pscheduler#869]
I did a bit of testing with two perfsonar server (same LAN) for the last 3 days and I came across a problem

I frequently get an error when I save the test in the web-ui : Error - Couldn't format pSConfig template file

I'm running Chrome 75.0.3770.100 (64 bits)
Installed from : pS-Toolkit-4.1.6-CentOS7-FullInstall-x86_64-2019Feb20.iso on barebone servers.
I disabled all firewall and IPV6.
All service are in running state.

Any ideas?

**Comment by mfeit-internet2** [comment]
This is not a pScheduler issue.

If you have support questions, please join the perfsonar-user mailing list and ask there.
