### ISSUE TITLE
Implement task cancels

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#90]
Right now the task resource's HTTP DELETE returns not implemented. We need to implement this by RC1 so the meshconfig can properly clear out tests no longer in the mesh.

**Comment by mfeit-internet2** [comment]
First commit just does it on the local host.  Second will take care of it on other participants.

**Comment by mfeit-internet2** [comment]
Tasks can now be canceled with a HTTP `DELETE` and also with `psc cancel task-url`.

The task isn't actually deleted and will remain in the system until purged due to old age.
