### ISSUE TITLE
Update archiver to call result-format

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#912]
After talking with Mark, our conclusion was the best way to get the results formatted the way we want is to add a `format` option to the archiver specification that, if set, calls the `result-format` function of the test before passing it to the archiver. This has number of advantages such as leaving the door open for future formats and not requiring any changes to archivers like rabbitmq, http, or syslog. A few more detailed notes:

- We will add a `format` option to the archiver spec. The value will indicate the format you want passed to the archive. We need to come up with a name for the format we want for stuff going into elastic. Mark is going to look at the MIME types since that is what they are currently. If this option is not set, the raw JSON will get passed (i.e. exactly what happens today)

- The formatting happens BEFORE any JQ transformations. This means that If the format is not JSON then any JQ transformations will fail. 

- The archiver will temporarily cache transformations for a given result so the same transformation does not need to happen multiple times if multiple archivers were specified. 

Examples of what we want the new format to look like are below: 

https://gist.github.com/arlake228/b6b468b1fb5d9c0fc341f3d8ef47c14c
https://gist.github.com/arlake228/32f7f95a0c5b96157eec1de8daee307b
https://gist.github.com/arlake228/81f7ea71a92064c5072aa58aef22b03b
https://gist.github.com/arlake228/c1cc6bc025399a3e6711b8850e5c7d3e

**Comment by mfeit-internet2** [comment]
**Design Notes:**

New format is called _pScheduler JSON Simplified_ or PJS.

Test Plugins:

* `result-format` needs to support a new type, `application/x-pscheduler-json-simplified`.  This produces only the test-specific part of the PJS

New `formatter` plugin type:

 * Does wholesale conversion of results to other formats.
 * Input is the JSON the archiver would have pre-transform.
 * Output is JSON described below.
 * First target type will be `pjs`.  This will call the test plugin's `result-format` and request `application/x-pscheduler-json-simplified`.

Formatter output JSON:
```
On success:
{
    "succeeded": true,
    "result": ... Any JSON ...
}

On failure:
{
    "succeeded": false,
    "error": "...Error Message..."
}

```

Archiver:

 * New spec schema to add `format` parameter that names which formatter plugin will be used.  (See below.)
 * On first attempt, do the formatting and store it in the database so it doesn't have to be re-generated each time.
 * Transform, if applied, happens _after_ formatting.
 * The user is responsible for applying transforms to JSON only; failure to parse means the archiving fails permanently.

**Comment by mfeit-internet2** [comment]
Has what we ended up doing in 5.0 obsoleted this?  Can we close it?

**Comment by mfeit-internet2** [comment]
OBE.
