### ISSUE TITLE
Iperf2 has timeout problems

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#924]
Iperf2 seems to be having problems with the remote end dying with "process took to long to run."

**Comment by mfeit-internet2** [comment]
We'd iceboxed this because nobody had complained about it and just this morning, someone did.

Probably need to adjust the destination-side estimate of run time.

**Comment by mfeit-internet2** [comment]
This may have the same problem iperf3 did with calculating bad times.

See https://github.com/perfsonar/pscheduler/commit/417df72271cc27202628a3fa649897323c9593a2#diff-90b79b4771dbe6b8496e750992a37ee9

That was a slightly different problem, but the approach in fixing this should be the same.

**Comment by stanier** [comment]
Any update on this?  I have a deployment that heavily relies on `iperf` for throughput testing and this is really slowing us down.

**Comment by mfeit-internet2** [comment]
Sorry, this one slipped through the cracks.  We'd tagged it for 4.3 well before it had been decided there would be a 4.2.4 release.

4.2.4 is at the tail end of the release pipeline (and will probably be announced today or tomorrow), so it's unlikely I can get the fix into that.  However, I can make the adjustments and follow it up with a 4.2.5 in a few days.

**Comment by mfeit-internet2** [comment]
I have a fix for that that we'll try and get out in the next few days.

TODO:
- [ ] Need to merge this fix with 4.3.0

**Comment by mfeit-internet2** [comment]
This will be out in the next bugfix release.

**Comment by stanier** [comment]
Awesome, thank you!
