### ISSUE TITLE
HTTP test archiver problem, when archiving non "200 OK" responses

### ISSUE THREAD

**Issue by TS0TNE** [perfsonar/pscheduler#931]
When receiving the non "200 OK" response code from the web server, the archiver is not able to archive the result.
The command below recives  "403 forbidden" from the web server and thus the archiver not sending the data to the elasticsearch.

pscheduler task --archive @archive_logstash.json  http --url https://cert.ge/

In case of "200 OK" response code, everything works good and I'm getting the data in elasticsearch.

**Comment by mfeit-internet2** [comment]
The HTTP test was originally designed to measure the response time for successful retrieval of a URL and treats any status not in the 200 family as a failure in making the measurement.  Those failures don't get archived, although #866 requests that failures be archived.  (We do intend to do that in a future release.)

In the shorter term, we can look at expanding the test so it can be told to accept non-2xx statuses as successful measurements.  That won't be difficult and is worth doing.

**Comment by TS0TNE** [comment]
Thank you. It would be good if non 200 status codes would be archived as well. Then, based on status codes, I will be able to recognize failures

**Comment by mfeit-internet2** [comment]
Restarting this from a merge with the 4.3.0 branch.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added test parameters to `http` for treating non-2xx responses as successes and capturing the result and all or part of the content returned.
