### ISSUE TITLE
The json GET param does not look at the "detail" field

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#95]
When using the "json" GET parameter to query a list of tasks, it does not appear to filter on the detail field. A use case for this would be to query all "enabled" tasks so you don't have to sift through disabled tasks. The enabled field is currently found in detail. 

This is not high priority and is not blocking anything, but may be nice to add at some point.

**Comment by mfeit-internet2** [comment]
Implementation note:

Have the database generate full JSON, including the details and store that in a column, then do queries based on the column.

This may be easy enough to get into 1.0, so putting it in for RC2 and will kick it further out as needed.

**Comment by mfeit-internet2** [comment]
Should make sure this gets brought into the database's `schedule.sql` at line 17.

**Comment by mfeit-internet2** [comment]
Done; will be committed shortly.

Note that any fields named `*-href` cannot be searched, but all others can.

```
curl -s -k https://localhost/pscheduler/tasks?detail&expanded&json=%7B%20%22detail%22%3A%20%7B%20%22enabled%22%3A%20true%20%7D%20%7D'
```

**Comment by mfeit-internet2** [comment]
** Release Notes:**

API added the ability to filter on server-added details when querying tasks.
