### ISSUE TITLE
Amazon S3 performance benchmarking plugin

### ISSUE THREAD

**Issue by epcjr** [perfsonar/pscheduler#950]
https://github.com/dvassallo/s3-benchmark

https://github.com/wasabi-tech/s3-benchmark

**Comment by mfeit-internet2** [comment]
This will need packaging for Debian.  Before closing, move this to Downstream.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added a `s3throughput` test and a corresponding tool for measuring throughput of S3-compatible object storage services.
