### ISSUE TITLE
support for throughput test  --bidir

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#951]
please add support for the bidirectional throughput testing:

  iperf3 --bidir / iperf2 --dualtest

**Comment by mfeit-internet2** [comment]
This will require a significant change to the result format and would be a good opportunity to tackle the problem of handing having a mix of older and newer versions of the plugins.

**Comment by bltierney** [comment]
So I take it this is still on the list, but wont happen for a while? :)

**Comment by mfeit-internet2** [comment]
Might be a 4.4 thing.  Right now our next goal is to get 4.3, the Python 3 upgrade, out without changing too many variables.

**Comment by mfeit-internet2** [comment]
I'm going to hold this for when we do bonus material.

**Comment by bltierney** [comment]
I no longer think this is worth the effort, so closing
