### ISSUE TITLE
Installation of the toolkit package on Centos  httpd-wsgi-socket-1.0 /post installation failure

### ISSUE THREAD

**Issue by LucRoadRunner** [perfsonar/pscheduler#952]
Installing : httpd-wsgi-socket-1.0-1.el7.centos.noarch                                                                                                         136/565 
Job for httpd.service invalid.
warning: %post(httpd-wsgi-socket-1.0-1.el7.centos.noarch) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package httpd-wsgi-socket-1.0-1.el7.centos.noarch

**Comment by mfeit-internet2** [comment]
The problem only cropped up during installation, when Apache wasn't running yet and the package tried to do a reload. 

All packages using `systemctl reload` or `restart` have been switched to use `reload-or-try-restart` so there will be no complaint if the service isn't running.

**Comment by LucRoadRunner** [comment]
Thank you for this, Mark.
Have a nice day.

Luc

Le mar. 14 janv. 2020 à 02:24, Mark Feit <notifications@github.com> a
écrit :
