### ISSUE TITLE
Consider using PycURL over requests

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#96]
In anything that imports `requests`, consider PycURL (http://pycurl.io) instead as a way to speed things up.

**Comment by mfeit-internet2** [comment]
Probably not necessary.  Closing.

**Comment by mfeit-internet2** [comment]
Reconsidering.  Reopening.

**Comment by mfeit-internet2** [comment]
Debian:  The RPM spec files have bumped `python-pscheduler` to version 1.3.7.1 and the modules that use it (changed in 97fad06) need to have the Debian packaging updated to match.

**Comment by vvidic** [comment]
Updated dependencies on the Debian side.

**Comment by vvidic** [comment]
Debian side should be ready, closing.
