### ISSUE TITLE
python-pyjq-2.3 causes issues to pscheduler

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#961]
@LucRoadRunner commented on [Tue Jan 28 2020](https://github.com/perfsonar/project/issues/1277)

Hello

The current packages of perfsonar uses the python-pyjq-2.3 version in the perfSONAR repository.
This version causes issues to pscheduler (problem to import _pyjq module) and pscheduler is not functional anymore.

Had to switch back to version python-pyjq-2.1 to fix the pscheduler issue.

**Comment by mfeit-internet2** [comment]
Just built a VM to test this out.  The error is:
```
ImportError: /usr/lib64/python2.7/site-packages/_pyjq.so: undefined symbol: jv_is_integer_large
```

`jv_is_integer_large` is part of a patch done to jq in #717 and #785 that fixes a joint jq-PyJQ bug.  (See the tickets for details.)  The jq developers haven't resolved it on their own yet.

EPEL upgraded to 1.6 and hosts are selecting that over ours.  I'll find a way to make our fixed version take precendence.

**Comment by mfeit-internet2** [comment]
This was taken care of and a fix announced here:  https://lists.internet2.edu/sympa/arc/perfsonar-announce/2020-01/msg00001.html

**Comment by LucRoadRunner** [comment]
python-pyjq 2.1 is available in perfSONAR 4.1.6 repoitority. From 4.2.0, i
t is not included anymore.in the perfosnar repository.

Le ven. 31 janv. 2020 à 00:02, Mark Feit <notifications@github.com> a
écrit :

**Comment by mfeit-internet2** [comment]
The current repositories for CentOS and Debian on x86_64 show the current versions; see  http://software.internet2.edu/rpms/el7/x86_64/latest/packages and http://downloads.perfsonar.net/debian/#perfsonar-4.2.

Several systems in our test bed rebuild from scratch every night and have had no problems after the patch.

Could you provide more specifics about what where you're trying to build (platform and distribution) and provide a dump of the installation output?

**Comment by LucRoadRunner** [comment]
The confusion is on my side by keeping in my local repository different
versions of perfSONAR. Scratching my local repo and restarting with 4.2.1
was indeed OK. Please feel free to close it definitely. Sorry for the
inconvenience.
