### ISSUE TITLE
Adjust package version numbers

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#97]
Most packages have a version number of 0.0 in their RPM specs.  Adjust them to 1.0.

**Comment by arlake228** [comment]
As an FYI you may want to look at https://github.com/perfsonar/project/wiki/Versioning for how we do pre-release versions. Basically you'll make the RPM version 4.0 and make the release 0.X.rc1 where X is the number we bump when we want a new RPM in the staging repo.

**Comment by mfeit-internet2** [comment]
Seen that.  I thought we'd decided against lock-stepping pSc's version numbers with pS since it's pretty much a standalone package.  This would be a one-time thing, as I don't think the version numbers on packages should change if the code in them doesn't.  Sounds like a good topic for a Thursday discussion.

**Comment by arlake228** [comment]
Ugh sorry, I meant to type 1.0. I must have 4.0 on the brain. I was really trying to highlight how we do the pre-release relnum.
