### ISSUE TITLE
pre-emption failure

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#973]
Hi Mark,
I have prepared a special configuration to verify the operation of Priorities feature.
I have prepared 2 tasks, one with high priority and another with low.
I have run these twice and based on priority these follow as:
1. high 2. low 3. low 4. high
Each pair of tasks create a scheduling conflict.

https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/f14fce88-7918-4008-9f27-3d113954cefe
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/5bf437e2-1f4c-443e-b234-eb47b47ab9fd
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/37ab5093-cc64-4702-b421-6570c03f76e6
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/98cd80e9-cfb7-4210-9417-9bb1078a320d

Please note the specification of the tasks is the same with only difference in the requester.
The result is:
1. succeeds 2. non-starter 3. succeeds 4. non-starter

Where I would expect: 3. pre-empted 4. succeeds.
I'll be happy to replay all that, if needed

**Comment by igarny** [comment]
Hi Mark,
as we spoke today about the pre-emption issue on the call. Here I ran the test again:
I see the same behavior
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/31274cf5-ade4-408c-925d-5f04508d331c"
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/aedb6947-99d7-4efe-a9cb-b97d180aa9e4"
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/4ba5cada-27b6-44ea-bfdb-07845ae38d6f"
https://t2-psdev.rrze.uni-erlangen.de/pscheduler/tasks/fe78158b-2937-4863-8f86-1842e10d3c2d"

**Comment by mfeit-internet2** [comment]
This should solve the priority problems.  Please check them out during the beta and close this ticket (and any others that are related) if things look good.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Fixed buggy implementation of priorities and preemption to make the feature work as originally intended.

**Comment by mfeit-internet2** [comment]
@igarny seems satisfied with this.
